---
title: "W14 Global Life Expectancy"
author: "Sung Inkyung"
date: '2020 8 17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(countrycode)
library(viridis)
library(showtext)

font_add_google("Bebas Neue")
font_add_google("Poppins")

showtext_opts(dpi = 320)
showtext_auto()
```


```{r}
life_expectancy <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-07-03/week14_global_life_expectancy.csv")

df <- life_expectancy %>% 
  mutate(continent = countrycode(sourcevar = country,
                                 origin = "country.name",
                                 destination = "continent")) %>% 
  filter(!is.na(continent))
```

```{r}
plot_life <- df %>% 
  filter(year > 1950) %>% 
  ggplot(aes(code, year, fill = life_expectancy)) +
  geom_tile() +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(1950, 2015, 10),
                     expand = c(0, 0)) +
  scale_fill_viridis(option = "viridis") +
  facet_wrap(~ continent,
             ncol = 1, 
             scales = "free") +
  guides(fill = guide_colorbar(title = "Years",
                               title.position = "top")) +
  labs(x = "",
       y = "",
       title = "Global Life Expectancy 1950 - 2015",
       caption = "Source: oneworldindata.org | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key.width = unit(3.5, "line"),
        legend.key.height = unit(.7, "line"),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 11),
        plot.title = element_text(family = "Bebas Neue",
                                  size = 35,
                                  face = "bold",
                                  hjust = 0.5,
                                  margin = margin(b = 15)),
        plot.caption  = element_text(family = "Poppins",
                                     size = 12,
                                     color = "gray45",
                                     margin = margin(t = 10)),
        axis.text.x = element_text(family = "Poppins",
                                   angle = 90, 
                                   vjust = .5, 
                                   size = 9),
        axis.text.y = element_text(family = "Poppins",
                                   size = 9),
        axis.ticks = element_line(color = "gray60"),
        strip.text.x = element_text(family = "Bebas Neue",
                                    size = 17, 
                                    hjust = 0, 
                                    face = "bold"))
  
  ggsave("W14_GlobalLifeExpectancy.png", width = 35, height = 30, units = "cm")
```

