---
title: "W48_DoctorWho_IMDBRating"
author: "Sung Inkyung"
date: '2021 11 29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by Z3tt] (https://github.com/Z3tt/TidyTuesday/blob/master/R/2020_12_TheOffice.Rmd)
```{r}
library(tidyverse)
library(paletteer)
library(cowplot)
theme_set(theme_minimal())

theme_update(plot.background = element_rect(fill = "#fafaf5",
                                            color = "#fafaf5"),
             panel.background = element_rect(fill = NA, 
                                             color = NA),
             panel.border = element_rect(fill = NA, 
                                         color = NA),
             panel.grid.major.x = element_blank(),
             panel.grid.minor.x = element_blank(),
             axis.text.x = element_blank(),
             axis.text.y = element_text(size = 15),
             axis.ticks = element_blank(),
             axis.title.y = element_text(size = 17, 
                                         margin = margin(r = 10)),
             legend.title = element_text(size = 15),
             plot.caption = element_text(size = 15,
                                         color = "grey60",
                                         face = "bold",
                                         hjust = .5,
                                         margin = margin(5, 0, 20, 0)),
             plot.margin = margin(10, 25, 10, 25))
```


```{r}
episodes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-11-23/episodes.csv')

```


```{r}
df <- episodes %>% 
  filter(season_number <= 12) %>% 
  arrange(season_number, episode_number) %>% 
  filter(!is.na(season_number),
         !is.na(episode_number)) %>% 
  mutate(season = factor(season_number),
         n = row_number()) %>% 
  group_by(season) %>% 
  mutate(avg_rating = mean(rating),
         start = min(n),
         end = max(n),
         median = median(n)) %>% 
  ungroup()


df_lines <- df %>% 
  group_by(season) %>% 
  summarise(start = mean(start),
            end = mean(end),
            s_avg = unique(avg_rating)) %>% 
  mutate(lag_n = lead(start, default = max(end)),
         lag_rating = lead(s_avg, default = max(s_avg)))
```


```{r}
plot_waterfall <- df %>% 
  ggplot(aes(n, rating)) +
  geom_hline(data = tibble(y = 70:100),
             aes(yintercept = y),
             color = "#d3d3d3") +
  geom_segment(aes(y = avg_rating,
                   yend = avg_rating,
                   x = start,
                   xend = end,
                   color = season),
               lwd = 2.5) +
  geom_segment(aes(y = rating, 
                   yend = avg_rating,
                   x = n, 
                   xend = n,
                   color = season)) +
  geom_segment(data = df_lines,
               aes(x = end,
                   xend = lag_n,
                   y = s_avg,
                   yend = lag_rating,
                   color = season)) +
  geom_point(aes(size = uk_viewers,
                 color = season)) +
  geom_label(aes(label = glue::glue('Season {season}'),
                 x = median,
                 y = 101,
                 color = season), 
             fontface = "bold",
             label.padding = unit(.3, "lines"),
             label.r = unit(.25, "lines"),
             size = 6) +
  scale_x_continuous(expand = c(.005, .005)) +
  scale_y_continuous(breaks = seq(70, 100, by = 5),
                     limits = c(70, 101.5),
                     sec.axis = dup_axis(name = NULL)) +
  scale_color_paletteer_d("miscpalettes::brightPastel") +
  scale_size_binned(name = "UK Viewers per Episode",
                    range = c(.3, 3)) +
  guides(size = guide_bins(show.limits = T,
                           direction = "horizontal",
                           title.position = "top",
                           title.hjust = .5),
         color = FALSE) +
  labs(x = "",
       y = "IMDB rating",
       caption = "Source: datardis Pkg | Graphic: Sung Inkyung") +
  theme(legend.position = c(.5, .085),
        legend.key.width = unit(2, "lines"))

logo <- png::readPNG(here::here("2021", "week48", "doctor-who-logo.png"))

ggdraw(plot_waterfall) +
  draw_image(logo, x = -.35, y = -.31, scale = .12)

ggsave(here::here("2021", "week48", "W48_DoctorWho_IMDBRating.png"), width = 26, height = 11) 
```
##scale_color_paletteer_d("palettetown::roselia")


