---
title: "W10 NHL Seasons Goals"
author: "Sung Inkyung"
date: '2020 3 8'
output: html_document
---
```{r}
library(tidyverse)
library(ggbeeswarm)
library(showtext)

font_add_google("Teko")
font_add_google("Advent Pro")

showtext_opts(dpi = 320)
showtext_auto()
```


```{r}
season_goals <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-03/season_goals.csv') 


  season_goals %>% 
    count(yr_start, sort = TRUE) %>% 
    arrange(desc(n))
```


```{r}
season <- season_goals %>% 
  filter(yr_start >= 1960, league == "NHL") %>% 
  select(player, season, age, goals) %>% 
  group_by(player, age, season) %>% 
  summarise(total = sum(goals)) %>% 
  mutate(cum = cumsum(total),
         id = row_number(),
         age_class = case_when(
            age <= 19 ~ "10-19",
            age <= 29 ~ "20-29",
            age <= 39 ~ "30-39",
            age <= 49 ~ "40-49",
           TRUE ~ ">50"
         )) %>% 
  filter(id >= 1, id <= 15) %>% 
  ungroup() 

season %>% 
  count(age, sort = TRUE) %>% 
  arrange(desc(age))

season %>% 
  count(cum, sort = TRUE) %>% 
  arrange(desc(cum))

```

```{r}
season %>% 
  ggplot(aes(age_class, cum)) +
  geom_quasirandom(alpha = 0.3, width = 0.3,
                   color = "#6f263d") + #Colorado Avalanche Primary Colors
  stat_summary(fun.y = "median",
               geom = "point",
               size = 2,
               color = "#236192") +
  stat_summary(fun.y = "median", geom = "line",
               aes(group = 1),
               size = 0.7,
               color ="#236192") +
  scale_y_continuous(limits = c(0, 120),
                     expand = c(0, 0)) +
  labs(x = "age",
       y = "total goals",
       title = "How age affects total goals in NHL",
       subtitle = " Most goals are achieved by players between the age of 20 agnd 29 in the NHL since 1960",
       caption = "Data: HockeyReference.com | Graphic:Sung Inkyung") +
  theme_minimal() +
  theme(plot.margin = unit(rep(1.2, 4), "cm"),
        plot.title = element_text(family = "Teko",
                                  size = 22,
                                  face = "bold",
                                  margin = margin(b = 8)),
        plot.subtitle = element_text(family = "Advent Pro",
                                     size = 14, 
                                     lineheight = 1.1,
                                     margin = margin(b = 45)),
        plot.caption = element_text(family = "Advent Pro",
                                     size = 9,
                                     margin = margin(t = 30)),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text = element_text(size = 11),
        axis.text.x = element_text(margin = margin(t = 5)),
        axis.text.y = element_text(margin = margin(r = 5)),
        axis.title = element_text(size = 14),
        axis.title.y = element_text(family = "Advent Pro",
                                    margin = margin(r = 10),
                                hjust = 1),
        axis.ticks = element_line(),
        axis.title.x = element_text(family = "Advent Pro",
                                    margin = margin(t = 10),
                                hjust = 1),
        axis.line = element_line())
  
ggsave("W10_NHLSeasonsGoals.png", width = 24, height = 18, units = "cm")
```


