---
title: "Week8 World Freedom Index"
author: "Sung Inkyung"
date: '2022 3 2'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scico)
library(showtext)

font_add_google("EB Garamond")
font_add_google("Poppins")
showtext_opts(dpi = 300)
showtext_auto()

```

```{r}
freedom <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-22/freedom.csv') %>% 
  janitor::clean_names() %>% 
  rename(civil_liberties = cl,
         political_rights = pr)

df <- freedom %>% 
  filter(region_name == "Asia") %>% 
  pivot_longer(cols = c(civil_liberties, political_rights)) %>% 
  mutate(name = case_when(name == "civil_liberties" ~ "Civil Liberties",
                          name == "political_rights" ~ "Political Rights"))

f1 <- "EB Garamond"
f2 <- "Poppins"
```

```{r}
plot <- df %>% 
  ggplot() +
  geom_bar(aes(x = year,  fill = as.factor(value), position = "fill", width = 0.85)) +
  scale_x_continuous(breaks = seq(1995, 2020, 5)) +
  scale_fill_scico_d(palette = "davos", direction = -1) +
  facet_wrap(~name, ) +
  guides(fill = guide_legend(nrow = 1, label.position = "bottom",
                             title = "")) +
  coord_cartesian(expand = FALSE) +
  labs(title = "Freedom Index Distribution of Asia 1995-2020",
       subtitle = "Evolution of political rights and civil liberties ratings\n1 is the highest rating out of 7",
       caption = "Source: UN and Freedom House | Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "top",
        legend.text = element_text(family = f2, 
                                   size = 9,
                                   color = "white"),
        panel.spacing = unit(2, "lines"),
        plot.background = element_rect(fill = "#2C194C", color = NA),
        strip.text = element_text(family = f2, 
                                  size = 21,
                                  face = "bold", 
                                  color = "#DFDFAB",
                                  margin = margin(t = 10, b = 10)),
        plot.title = element_text(family = f1,
                                  size = 36,
                                  face = "bold",
                                  hjust = 0.5,
                                  color = "white",
                                  margin = margin(b = 9)),
        plot.subtitle = element_text(family = f2,
                                  size = 25,
                                  hjust = 0.5,
                                  color = "white",
                                  margin = margin(b = 15)),
        plot.caption = element_text(family = f2,
                                  size = 13,
                                  hjust = 0.5,
                                  color = "#AEBDA5",
                                  margin = margin(t = 20)),
        axis.text.x = element_text(family = f2,
                                   size = 13, 
                                   color = "#7C9BB4"),
        plot.margin = margin(20, 20, 20, 20))

ggsave("W8_WoldFreedomIndex.png", width = 40, height = 30, units = "cm")

#scico(7, palette = "davos")
  
```

