---
title: "ACS Census Data(2015)"
author: "Sung Inkyung"
date: '2020 8 20 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
library(showtext)

font_add_google("Roboto Condensed", "Roboto Condensed")
showtext_auto()

extrafont::loadfonts(device = "win")
```


```{r}
census <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-04-30/week5_acs2015_county_data.csv")
```


```{r}
df <- census %>% 
  ggplot() +
  geom_density_ridges(aes(IncomePerCap, State),
                      scale = 2,
                      alpha = .9,
                      size = .3,
                      color = "#033f40",
                      fill = "#006766") +
  scale_x_continuous(labels = scales::dollar,
                     n.breaks = 7,
                     expand = c(0, 0)) +
  labs(x = "",
       y = "",
       title = "US Census 2015",
       subtitle = "Income per Capita by State",
       caption = "Source: cnesus.gov, Kaggle | Graphic: Sung Inkyung") +
  theme_minimal(base_family = "Roboto Condensed") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.background = element_rect(fill = "#ebe6d9",
                                       color = NA),
        plot.title = element_text(hjust = .5),
        plot.subtitle = element_text (hjust = .5),
        plot.margin = margin(10, 10, 10, 10))

ggsave(here::here("2018", "week_05", "W5_ACS Census Data 2015.png"), width = 16, height = 20, units = "cm")
```

