---
title: "W28 CoffeeRatings"
author: "Sung Inkyung"
date: '2020 7 11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggthemes)
library(ggdist)
library(ggtext)
library(ragg)
library(grid)
library(paletteer)
library(showtext)

font_add_google("Prata")
font_add_google("Fira Sans Condensed")
font_add_google("Graduate")


showtext_opts(dpi = 320)
showtext_auto()

theme_set(theme_minimal())
```


```{r}
coffee <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv')

coffee %>% 
  count(country_of_origin, sort = T)
```

```{r}
coffee_metrics <- coffee %>%
  select(total_cup_points, variety,
         country_of_origin,
         aroma:moisture) %>%
  mutate(
    country_of_origin = case_when(country_of_origin == "Tanzania, United Republic Of" ~ "Tanzania",
                                  str_detect(country_of_origin, "United States") ~ "United States",
                                  TRUE ~ country_of_origin)) %>% 
  pivot_longer(aroma:uniformity, names_to = "metric", values_to = "value") %>% 
  filter(!is.na(variety))
```


```{r}
plot <- coffee_metrics %>% 
  filter(country_of_origin %in% c("Ethiopia", "Kenya", "Colombia", "Uganda", "Costa Rica", 
                                  "El Salvador", "United States", "Indonesia", "Guatemala", "Brazil", 
                                  "Tanzania", "Taiwan", "Hondura", "Mexico", "Nicaragua", "Vietnam")) %>% 
  ggplot(aes(factor(metric), value, group = 1)) + 
  geom_polygon(aes(fill = value), color = NA) +
  coord_polar() + 
  facet_wrap(~ country_of_origin, ncol = 5) +
  scale_fill_paletteer_c("gameofthrones::martell") +
  scale_y_continuous(limits = c(0, 10),
                     breaks = seq(0, 10, 2.5)) +
  expand_limits(y=0) +
  guides(fill = guide_colorbar(barheight = unit(3, units = "mm"),  
                                 barwidth = unit(60, units = "mm"),
                                 direction = "horizontal",
                                 ticks.colour = "#e8d8c3",
                                 title.position = "top",
                                 title.hjust = 0.5)) +
  labs(x = "",
       y = "",
       title = "Coffee Ratings by Country",
       subtitle = "Countries of origin with 20 or more tested beans are shown.\nThe coffee bean from Guatemala got the lowest rating(59.8).\nCoffee beans with minimum rating above 80 are from Ethiopia,\nUganda and Tanzania. The best coffee bean is from Ethiopia,\nthe only bean above median 85 with minimum rating 80.3",
       caption = "Source: James LeDoux & Coffee Quality Database | Graphic: Sung Inkyung") +
  theme(legend.position = "bottom",
        strip.background = element_rect(fill = "#63270d", color = NA),
        strip.text = element_text(color = "white",
                                  family = "Graduate"),
        plot.title = element_text(family = "Prata",
                                  size = 20,
                                  face = "bold",
                                  hjust = 0.5,
                                  margin = margin(t = 20,
                                                  b = 10)),
        plot.subtitle = element_text(family = "Fira Sans Condensed",
                                     size = 13,
                                     hjust = 0.5,
                                     margin = margin(b = 20)),
        plot.caption = element_text(color = "gray45",
                                    family = "Fira Sans Condensed",
                                    size = 9,
                                    hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_text(family = "Fira Sans Condensed",
                                   size = 4.5,
                                   margin = margin(5, 5, 5, 5)),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "#f3ebe0", color = NA),
        panel.spacing = unit(.5, "lines"))

ggsave("W28_CoffeeRatingsRadar.png", width = 20, height = 20, units = "cm")
```

### Source[tidytuesday by Z3tt] (https://github.com/Z3tt/TidyTuesday/blob/master/R/2020_28_CoffeeRatings.Rmd)
```{r}
df <- coffee %>% 
  filter(total_cup_points != 0) %>% 
  group_by(species, owner, country_of_origin, farm_name, mill, ico_number, harvest_year, grading_date) %>% 
  summarize(total_cup_points = mean(total_cup_points, na.rm = T)) %>% 
  group_by(country_of_origin) %>%
  filter(n() >= 20) %>%
  mutate(#
    med = median(total_cup_points),
    min = min(total_cup_points),
    n = n()) %>% 
  ungroup() %>% 
  mutate(
    country_of_origin = case_when(country_of_origin == "Tanzania, United Republic Of" ~ "Tanzania",
                                  str_detect(country_of_origin, "United States") ~ "United States",
                                  TRUE ~ country_of_origin)) %>% 
  mutate(
    country = fct_reorder(country_of_origin, med),
    y = as.numeric(country) - .3)

df_country <- df %>% 
  group_by(country) %>% 
  slice(1)
  
plot <- ggplot(df, aes(total_cup_points, y = y)) +
  ## labels countries
  geom_text(data = df_country, 
            aes(x = min, y = y,
                label = country, 
                size = n),
            color = "#207878",
            family = "Graduate",
            fontface = "bold",
            vjust = 0, 
            hjust = -0.01) +
  ## stripe
  stat_interval(aes(y = y - 0.05),
                orientation = "horizontal",
                .width = c(.35, .15, .95, 1),
                stroke = 0,
                size = 1.4) +
  ## indicator median
  geom_point(data = df_country,
             aes(x = med, 
                 y = y - .22),
             shape = 17,
             color = "gray30",
             size = 2.5) +
  geom_text(data = df_country,
            aes(x = med + .16,
                y = y - .11,
                label = glue::glue("{round(med, 1)}")),
            color = "gray20",
            family = "Fira Sans Condensed",
            size = 3, 
            vjust = 1, 
            hjust = 0) +
  ##indicator minimum
  geom_point(data = df_country,
             aes(x = min + .1,
                 y = y - .22),
             shape = 2,
             color = "firebrick3",
             size = 2.5) +
  geom_text(data = df_country,
            aes(x = min + .25,
                y = y - .11,
                label = glue::glue("{round(min, 1)}")),
            color = "firebrick3",
            family = "Fira Sans Condensed",
            size = 3,
            vjust = 1, 
            hjust = 0) +
  ## dots
  stat_dots(quantile = NA,
            orientation = "horizontal",
            normalize = "none",
            scale = .87,
            color = "#4d2d18",
            fill = "#4d2d18") +
  scale_color_manual(values = c("grey85", "#baab86", "#ba722f", "#63270d"),
                     guide = F) +
  scale_size(range = c(8.75, 15.5),
             guide = F) +
  labs(x = "",
       y = "",
       title = "Coffee Rating by Country",
       subtitle = "Countries of origin with 20 or more tested beans are shown. The red triangle marks the minimum rating,\nthe solid black triangle indicates meidan scale.",
       caption = "Source: Coffee Quality Institute | Graphic: Sung Inkyung") +
  theme(plot.background = element_rect(fill = "#fff7eb", 
                                       color = NA),
        plot.title = element_text(family = "Prata",
                                  size = 28,
                                  face = "bold",
                                  margin = margin(t = 20,
                                                  b = 7)),
        plot.subtitle = element_text(family = "Fira Sans Condensed",
                                     size = 17),
        plot.caption = element_text(color = "gray45",
                                    family = "Fira Sans Condensed",
                                    size =11,
                                    hjust = 0.95),
        axis.title = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.margin = margin(10, 10, 10, 10))

ggsave("W28_CoffeeRatings.png", width = 30, height = 32, units = "cm")
```

