---
title: "W23 Marble Races"
author: "Sung Inkyung"
date: '2020 6 5'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(showtext)

font_add_google("Comfortaa")
font_add_google("Poppins")

showtext_opts(dpi = 320)
showtext_auto()

```


```{r}
marbles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-02/marbles.csv')
```


```{r}
cumsum_marbles <- marbles %>% 
  distinct(team_name, date, points, race) %>% 
  filter(!is.na(points)) %>% 
  group_by(team_name) %>% 
  mutate(date = dmy(date),
         cum_points = cumsum(points),
         highlight = case_when(
           team_name == "Savage Speeders"~ "SVG",
           team_name == "Hazers" ~ "HAZ", 
           team_name == "O'rangers" ~ "ORG",
           TRUE ~ "n" )
         ) %>% 
  arrange(-cum_points) %>% 
  ungroup()

cumsum_marbles %>% 
  count(team_name, cum_points, sort = T) %>% 
  arrange(-cum_points) %>% 
  slice(1:10)
```

```{r}
plot <- cumsum_marbles %>% 
  ggplot(aes(date, cum_points, group = team_name, color = highlight)) +
  geom_line(size = 1, show.legend = F) +
  geom_text(data = subset(cumsum_marbles, highlight != "n" & date == max(date)),
            aes(label = team_name), 
            family = "Poppins",
            size = 3.5, fontface = "bold",
            hjust = 1.1, vjust = -0.2, show.legend = F) +
  scale_color_manual(values = c("SVG" = "#8a0606", 
                                "HAZ" = "#9232b8", 
                                "ORG" = "#ff4500", 
                                "n" = "#e5e5e5")) +
  scale_y_continuous(breaks = seq(0, 100, 20)) +
  scale_x_date(breaks = "1 week",
               date_labels = "%b-%d",
               expand = c(0.01, 0)) +
  labs(x = "",
       y = "Cumulative points",
       title = "Top Mables Racing Teams by Jelle's Marble Runs in 2020",
       subtitle = "Jelle's Marble Runs is a YouTube channel based in the Netherlands, run by Jelle and Dion Bakker\nbased around the game of marbles, marble runs, and marble races.",
       caption = "Source: Jelle's Marble Runs | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(plot.title = element_text(family = "Comfortaa",
                                  size = 16, face = "bold",
                                  margin = margin(b = 7)),
        plot.subtitle = element_text(family = "Poppins",
                                         size = 10,
                                         lineheight = 1.1,
                                         margin = margin(b = 15)),
        plot.caption = element_text(color = "azure4",
                                    family = "Poppins",
                                size = 7,
                                hjust = 1,
                                margin = margin(t = 20, b = 10)),
        panel.grid.major = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size = .03,
                                          color = "gray60"),
        panel.grid.minor = element_blank(),
        plot.margin = margin(2, 2, 2, 2, "mm"))

ggsave("W23_MarbleRaces.png", width = 22, height = 16, units = "cm")
```

