---
title: "W40 NYC Pizza Rating"
date: '2019 10 9'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggbeeswarm)
library(scales)
library(glue)
library(cowplot)
library(showtext)

font_add_google("Lora")
font_add_google("Jost")

showtext_opts(dpi = 320)
showtext_auto()
```
### source [Tidy Tuesday screecast: analyzing pizza ratings by david robinson] (https://youtu.be/Mkac8DHScps)
```{r}
pizza_jared <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_jared.csv") %>% 
  mutate(time = as.POSIXct(time, origin = "1970-01-01"),
         date = as.Date(time))

pizza_barstool <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_barstool.csv") 
```

```{r different scale!}
answer_levels =  c("Never Again", "Poor", "Average", "Good", "Excellent")

jared <- pizza_jared %>% 
  mutate(answer = fct_relevel(answer, answer_levels),
         answer_num = as.numeric(answer)) %>% 
  group_by(place, answer) %>% 
  summarise(votes = sum(votes)) %>% 
  mutate(answer_num = as.numeric(answer),
         total = sum(votes),
         percent = votes / total,
         jared_avg = sum(answer_num * percent),
         jared_avg = round(jared_avg, 2)) %>% 
  ungroup()
```


```{r NYOSPM vs Barstool Sports}
barstool <- pizza_barstool %>% 
  select(place = name,
         city,
         price_level,
         contains("review")) %>% 
  rename_all(~str_remove(., "review_stats_")) %>% 
  select(-contains("provider")) %>% 
  filter(place %in% jared$place,
        !city %in% c("Brooklyn", "Miami", "Santa Monica"))

jb <- jared %>% 
  select(place, answer, answer_num, votes, total, jared_avg) %>% 
  left_join(barstool, by = "place") %>%  
  mutate(scale_jared = unlist(as.list(scale(jared_avg))), 
         scale_barstool= unlist(as.list(scale(all_average_score)))) %>% 
  unnest() %>% 
  mutate(price_level = factor(price_level,
                              labels = c("Very cheep", "Cheep", "Expensive"))) %>% 
  filter(!is.na(price_level))

pizza_combo <- jb %>% 
  distinct(place, answer, answer_num, price_level, scale_jared, scale_barstool) %>% 
  pivot_longer(cols = c("scale_jared", "scale_barstool"),
               names_to = "reviewer",
               values_to = "scale",
               values_drop_na = TRUE) %>% 
  mutate(average = round(scale, 2))
```

```{r}
pizza_place <- pizza_combo %>% 
  ggplot() +
  geom_density(aes(scale,  fill = reviewer), 
               alpha = 0.5,
               show.legend = FALSE) +
  scale_fill_manual(values = c("#bbbc1d", "#003363"),
                    labels = c("New York Open\nData Science Meetup",
                               "Barstool Sports")) +
  labs(x = "", 
       y = " ",
       title = "Pizza place ratings from two groups",
       subtitle = "NYODSM members stand slightly \nstronger on rating pizza places \nin New York city than Barstool \nsports reviewers") +
  theme_minimal() +
  theme(legend.position = "none",
        panel.background = element_blank(),
        plot.title = element_text(family = "Lora", size = 16, margin = margin(b = 7)),
        plot.subtitle = element_text(family = "Jost", size = 14, margin = margin(b = 10)))
  


pizza_price <- pizza_combo %>% 
  ggplot()+
  geom_density(aes(scale,  fill = reviewer), 
               alpha = 0.5) +
  scale_fill_manual(values = c("#bbbc1d", "#003363"),
                    labels = c("New York Open\nData Science Meetup",
                               "Barstool Sports")) +
  facet_wrap(~price_level) + 
  labs(x = " ",
       y = " ",
       title = "Pizza price ratings from two groups",
       subtitle = "NYODSM members takes on rating pizza price \nmore aggressively in New York City than \nBarstool sports reviewers.") +
  theme(legend.position = "top",
        panel.background = element_blank(),
        plot.title = element_text(family = "Lora", size = 16, margin = margin(b = 7)),
        plot.subtitle = element_text(family = "Jost", size = 14,  margin = margin(b = 10)))
```
### http://rpubs.com/thewiremonkey/534934
### http://docs.statwing.com/interpreting-residual-plots-to-improve-your-regression/ 
```{r}
jb_aov <- aov(scale_barstool ~scale_jared, jb)
jb_stdres <- rstandard(jb_aov)
order(abs(jb_stdres), decreasing = TRUE)[1:6]
```

```{r}
labels <- jb[order(abs(jb_stdres), decreasing = TRUE)[1:30], ]

aov_plot <- jb %>% 
  ggplot(aes(scale_jared, scale_barstool)) +
  geom_point(aes(color = "#tomato",
                 size = abs(jb_stdres))) +
  geom_abline(slope = 1, color = "#7daba1",
              size = 1) +
  geom_smooth(method = "lm",
              size = 0.7,
              color = "#b30417") +
  scale_x_continuous(limits = c(-2, 2)) +
  scale_y_continuous(limits = c(-2, 2)) +
  geom_text(data = labels,
            aes(scale_jared, scale_barstool,
                label = place),
            family = "Jost",
            size = 3.5,
            nudge_y = 0.35) +
  labs(title = "Pizza places with the highest variance in rating", 
       subtitle = "Corresponding pizza places with distinguishable rating difference by NYODSM and \nthe average Barstool Sports reviewer # of size is absolute value of the standardized residuals",
       x = "New York Open Data Science Meetup", 
       y = "Barstool Sports Reviewers",
       caption="Source: Jared Lander / Barstool Sports | Graphic: Sung Inkyung") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(family = "Lora", size = 16, margin = margin(b = 7)),
        plot.subtitle = element_text(family = "Jost", size = 14, margin = margin(b = 10)),
        plot.caption = element_text(family = "Jost", size = 10, margin = margin(t = 15))) 


ggdraw() +
  draw_plot(pizza_place, x = 0, y = 0.5, width = .5, height = .5) +
  draw_plot(pizza_price, x = 0.5, y = 0.5, width = .5, height = .5) +
  draw_plot(aov_plot, x = 0, y = 0, width = 1, height = 0.5) +
  draw_plot_label(label = c("A", "B", "C"), 
                  size = 14, 
                  x = c(0, 0.5, 0),
                  y = c(1, 1, 0.5))

ggsave("W40_NYC-PizzaPlaceRatings.png", width = 28, height = 24, units = "cm")
```