---
title: "Waffle plots"
author: "Sung Inkyung"
date: '2019 11 23 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###source[tidy tuesday by Edgar-Zamora] (https://github.com/Edgar-Zamora/My-Work/blob/master/%23TidyTuesday/NZ%20Bird%20of%20the%20Year/NZ_bird_of_year.R)
### Finally I can get on a waffle plot. With 0.7version, it doesn't allow me to work on this plot under Window environment. Thanks to Edgar_Zamor's comment on his corresponding github page, I downloaded waffle package 1.0 version as noted. Now I explored a couple of waffle plots from TidyTuesday data.
```{r}
library(tidyverse)
library(DT)
library(ggthemes)
library(paletteer)
library(waffle)
library(lubridate)
library(here)
```

```{r bird-waffle}
nz_bird <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-11-19/nz_bird.csv")
```

```{r new zealand birds waffle}
top5_votes <- nz_bird %>% 
  filter(!is.na(vote_rank) & !is.na(bird_breed)) %>% 
  count(bird_breed) %>% 
  arrange(desc(n)) %>% 
  top_n(5) %>% 
  rename(total = n)

top5_names <- top5_votes$bird_breed

top5_breakdown <- nz_bird %>% 
  count(bird_breed, vote_rank) %>% 
  filter(bird_breed %in% top5_names) %>% 
  left_join(top5_votes, by = "bird_breed") %>% 
  group_by(bird_breed) %>% 
  mutate(n = n/25,
         vote_rank = as.factor(vote_rank)) %>% 
  select(c(-total))

top5_breakdown %>% 
  ggplot(aes(fill = fct_rev(vote_rank), values = rev(n))) +
  geom_waffle(color = "white",
              size = .25, 
              n_rows = 10,
              flip = TRUE) +
  facet_wrap(~rev(bird_breed),
             nrow = 1, 
             strip.position = "bottom",
             labeller = label_wrap_gen(width = 10)) + 
  scale_x_discrete() +
  scale_y_continuous(labels = function(x) x * 25,
                     expand = c(0, 0),
                     limits = c(0, 50),
                     breaks = seq(0, 50, by = 5)) +
  scale_fill_tableau(name = "One square = 25 votes",
                     labels = c("Vote 1", "Vote 2", "Vote 3", 
                                "Vote 4", "Vote 5")) +
  coord_equal() +
  labs(x = "Bird breed",
       y = "Total votes",
       title = "Vote rank breakdown among the top5 bird breeds of the year 2019 in New Zealand",
       subtitle = "Yellow-eyed penguin is set in sky of New Zealand as a bird of the year 2019",
       caption = "New Zealand Fores and Bird Org") +
  theme_minimal()+
  theme(legend.title = element_text(size = 9),
        legend.key.size = unit(1, 'line'),
        panel.grid = element_blank(),
        plot.title = element_text(size = 16, hjust = .2),
        plot.subtitle = element_text(size = 11, hjust = .4,
                                     margin = margin(b = 20)),
        plot.caption = element_text(margin = margin(t = 20),
                                    size = 9,
                                    color = "#848484",
                                    hjust = 1),
        strip.text.x = element_text(size = 9),
        axis.ticks = element_blank(),
        axis.title = element_text(size = 9),
        axis.text = element_text(size = 7),
        panel.background = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(size = 9))
  
```

```{r commute waffle}
commute <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-11-05/commute.csv")

```

```{r}
city_mode <- commute %>% 
  group_by(city, mode) %>% 
  summarise(total = sum(n)) %>% 
  ungroup() %>% 
  mutate(total = round(total / 1000)) %>% 
  arrange(desc(total)) %>% 
  top_n(10)

top10_names <- city_mode$city
```

```{r}
top10_breakdown <- commute %>% 
  count(city, mode) %>% 
  filter(city %in% top10_names) %>% 
  left_join(city_mode, by = "city") %>% 
  mutate(city = str_remove(city, " city")) 
  

city_mode_plot <- top10_breakdown %>% 
  ggplot(aes(fill = mode.x, values = total)) +
  geom_waffle(n_rows = 10, size = 0.25, color = "white",
              flip = TRUE) +
  coord_equal() +
  scale_x_discrete() +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_manual(values = c("#80bbc5", "#e14b76"), #Bike:#ffcc99
                    labels = c("Bike", "Walk")) +
  facet_wrap(facets = ~fct_reorder(city, total, .desc = TRUE),
             nrow = 1, 
             strip.position = "bottom") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(x = "",
       y = "",
       title = "Distribution across top 10 city (in thousands)",
       caption = "Source : ACS Survey") +
  theme_minimal()
  
```

```{r}
state_mode <- commute %>% 
  select(-c(city_size, moe, state_abb, state)) %>% 
  group_by(state_region, mode) %>% 
  summarize(total = sum(n)) %>% 
  ungroup() %>% 
  mutate(total = round(total / 1000)) %>% 
  filter(!is.na(state_region))
  
  
state_mode_plot <- state_mode %>% 
  ggplot(aes(fill = mode, values = total)) +
  geom_waffle(n_rows = 10, size = 0.25, color = "white",
              flip = TRUE) +
  coord_equal() +
  scale_x_discrete() +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_manual(values = c("#80bbc5", "#e14b76"),
                    labels = c("Bike", "Walk")) +
  facet_wrap(facets = ~fct_reorder(state_region, desc(total)),
             nrow = 1, 
             strip.position = "bottom") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(x = "",
       y = "",
       title = "Distribution across state regions (in thousands)",
       caption = "Source : ACS Survey") +
  theme_minimal() +
  theme(legend.title = element_text(size = 9),
        legend.key.size = unit(1, 'line'),
        panel.grid = element_blank(),
        plot.title = element_text(size = 16, hjust = .2,
                                  margin = margin(b = 20)),
        plot.caption = element_text(margin = margin(t = 20),
                                    size = 9,
                                    color = "#848484",
                                    hjust = 1),
        strip.text.x = element_text(size = 9),
        axis.ticks = element_blank(),
        axis.text = element_text(size = 7),
        panel.background = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(size = 9))
  
  

```

```{r horror movie waffle plot}
horror_movies <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-22/horror_movies.csv")
```

```{r}
horror_cleaned <- horror_movies %>% 
  select(-c(movie_rating, plot, cast, filming_locations)) %>% 
  mutate(release_date = dmy(release_date),
         release_country = as.factor(release_country),
         year = year(release_date))

# top 5 countries by year
top5_countries <- horror_cleaned %>% 
  count(year, release_country) %>% 
  drop_na() %>% 
  arrange(year, -n) %>% 
  group_by(year) %>% 
  top_n(5) %>% 
  ungroup()


US2017 <- top5_countries %>% 
  filter(year == 2017, release_country == "USA") %>% 
  tally(n) %>% 
  pull(n)


release_country_plot <- top5_countries %>% 
  ggplot(aes(fill = release_country, values = n)) +
  geom_waffle(color = "white", size = .25, n_rows = 10, flip = TRUE) +
  facet_wrap(~year, nrow = 1, strip.position = "bottom") +
  scale_x_discrete() +
  scale_y_continuous(labels = function(x) x*10,
                     expand = c(0, 0)) +
  scale_fill_paletteer_d(ggsci, lanonc_lancet, name = NULL) +
  coord_equal() +
  theme_minimal() +
  labs(title = "Top 5 countries of releasing horror movies between 2012 and 2017",
       caption = "Source | IMDB") 
```

```{r my github plot}
horror_cleaned %>% 
  filter(!is.na(review_rating),
         !is.na(year)) %>% 
  count(review_rating, year,sort = TRUE) %>% 
  ggplot(aes(review_rating, n)) +
  geom_col() +
  facet_wrap(~ year, ncol = 2)

#review rating average = 5.4
# max review rating = 9.8

review_rating_breakdown <- horror_cleaned %>% 
  filter(!is.na(review_rating),
         !is.na(year)) %>% 
  drop_na() %>% 
  mutate(
    rating = case_when(
      review_rating < 5.5 ~ "Below average",
      review_rating < 7.5 ~ "Higher than 5.4",
      review_rating < 10 ~ "Higher than 7.5",
      TRUE ~ as.character(review_rating)
    )
  )

plot <- review_rating_breakdown %>% 
  count(year, rating) %>% 
  ggplot(aes(fill = rating, values = n)) +
  geom_waffle(color = "white", size = .25, n_rows = 10, flip = TRUE) +
  facet_wrap(~ year, nrow = 1, strip.position = "bottom") +
  scale_x_discrete() +
  scale_y_continuous(labels = function(x) x*10,
                     expand = c(0, 0)) +
  scale_fill_paletteer_d(wesanderson, GrandBudapest1, 
                         name = "Review Rating\nBreakdown") +
  coord_equal() +
  labs(title = "Review ratings trend of horror movies (2012 - 2017)",
       subtitle = "\nTrends of horror movies quality have shifted over time in a promising way.\nAverage of rating is 5.4.",
       caption = "Source | IMDB") +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme_minimal() +
  theme(legend.title = element_text(size = 9),
        legend.key.size = unit(1, 'line'),
        panel.grid = element_blank(),
        plot.title = element_text(size = 16),
        plot.subtitle = element_text(size = 11,
                                     margin = margin(b = 20)),
        plot.caption = element_text(margin = margin(t = 20),
                                    size = 9,
                                    color = "#848484",
                                    hjust = 1),
        strip.text.x = element_text(size = 9),
        axis.ticks = element_blank(),
        axis.title = element_text(size = 9),
        axis.text = element_text(size = 7),
        panel.background = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(size = 9))

ggsave(here("figures", "TrendofHorrorMovies.png"), width = 11, height = 7, units = "in")
```
