---
title: "W7 Wealth & Income"
author: "Sung Inkyung"
date: '2021 12 27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(scales)
```


```{r}
lifetime_earn <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/lifetime_earn.csv')
```


```{r}
df_gender <- lifetime_earn %>% 
  group_by(race, gender, lifetime_earn) %>% 
  pivot_wider(names_from = gender, values_from = lifetime_earn) %>% 
  ungroup() %>% 
  mutate(id = 1)

plot <- df_gender %>% 
  ggplot(aes(factor(id))) +
  geom_bar(aes(y = `Men`, fill = 'Men'), 
           stat = 'identity', width = .8) +
  geom_bar(aes(y = `Women`, fill = 'Women'), 
           stat = 'identity', width = .5) +
  geom_text(aes(y = Men, 
                label = dollar(Men)),
            size = 3.5,
            hjust = 0.5,
            vjust = 2.1,
            color = "White") +
  geom_text(aes(y = Women, 
                label = dollar(Women)),
            color = "white",
            hjust = 0.5,
            vjust = 2.1,
            size = 3.5) +
  scale_fill_manual("",
                    values = c("gray50", "gray65")) +
  scale_y_continuous(expand = expansion(c(0, .05))) +
  facet_wrap(~ fct_rev(race), 
             strip.position = 'bottom') +
  expand_limits(y = 0) +
  labs(x = "",
       y = "",
       title = "Lifetime Earning in USA",
       subtitle = "<span style = 'color:gray50'>**MEN**</span> <span style = 'color:gray65'>**WOMEN**</span>",
       caption = "Source: Urban Institute & US Census | Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "none",
        strip.text = element_text(size = 13, 
                                  margin = margin(t=5)),
        plot.title = element_text(size = 24,
                                  hjust = 0.5),
        plot.subtitle = element_markdown(size = 18,
                                         hjust = 0.5),
        plot.caption = element_text(size = 11,
                                    hjust = 0.5,
                                    color = "gray45",
                                    margin = margin(t = 25)),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        plot.margin = margin(10, 10, 10, 10))

ggsave(here::here("2021", "week7", "W7_WealthIncome.png"), width = 18, height = 21, units = "cm")
```

