---
title: "W19 AnimalCrossing"
author: "Sung Inkyung"
date: '2020 5 20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(showtext)

font_add_google("Fredoka One")
font_add_google("Poppins")
font_add_google("Pacifico")

showtext_opts(dpi = 320)
showtext_auto()
```
### Source[color combo by DESIGN WIZARD] (https://www.designwizard.com/blog/design-trends/colour-combination)

```{r}
villagers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv') %>% 
  mutate(gender = str_to_title(gender),
         species = str_to_title(species),
         personality = str_to_title(personality))

animals <- villagers %>% 
  group_by(gender, species) %>% 
  count(personality, sort = T) %>% 
  ungroup()

```


```{r}
pal <- c("#00539cff", "#76528bff", "#2bae66ff", "#f95700ff", "#fcf951ff", "#ffa177ff", "#4b878bff", "#df6589ff")

plot <- animals %>% 
  mutate(species = fct_rev(species),
         gender = fct_rev(gender)) %>% 
  ggplot(aes(personality, species, 
             size = n, color = personality)) +
  geom_point(show.legend = F) +
  scale_color_manual(values = pal) +
  facet_wrap(~gender, scales = "free_x") +
  labs(x = "Personality",
       y = "",
       title = "Personality of Animals in Animal Crossing: New Horizons by Nitendo",
       subtitle = "The animals that most often match their personalities in the life simulation<br>video games in 2020 are **the peppy rabbit** and **the lazy dog**",
       caption = "Source: Villager DB | Graphic: Sung Inkyung") +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "#1c1c1bff", 
                                        color = "#1c1c1bff"),
        plot.background = element_rect(fill = "#1c1c1bff", 
                                       color = "#1c1c1bff"),
        plot.title = element_text(color = "gray95",
                                  family = "Fredoka One",
                                  face = "bold",
                                  size = 22,
                                  hjust = 0.5,
                                  margin = margin(b = 10)),
        plot.subtitle = element_markdown(color = "gray95",
                                         family = "Poppins",
                                         size = 18,
                                         hjust = 0.5,
                                         margin = margin(b = 15)),
        plot.caption = element_text(color = "gray65",
                                    family = "Poppins",
                                    size = 12,
                                    hjust = 0.95,
                                    margin = margin(t = 25)),
        strip.text = element_text(color = "#ffd662",
                                  family = "Fredoka One",
                                  face = "bold",
                                  size = 15),
        strip.background = element_rect(fill = "gray25"),
        axis.text.x = element_text(color = "white",
                                   family = "Poppins",
                                   size = 11),
        axis.text.y = element_text(color = "white",
                                   family = "Pacifico",
                                   size = 12),
        axis.title.x = element_text(color = "white",
                                    family = "Poppins",
                                    size = 10,
                                    margin = margin(t = 15)),
        panel.grid.major = element_line(color = "gray25", 
                                        size = rel(0.5)),
        panel.grid.minor = element_line(color = "gray25", 
                                        size = rel(0.25)),
        plot.margin = margin(10, 10, 10, 10, "mm"))
  
  ggsave("W19_AnimalCrossing.png", width = 32, height = 30, units = "cm")
```

