---
title: "Art Collections"
author: "Sung Inkyung"
date: '2021 1 16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggnewscale)
library(pals)
```


```{r}
artwork <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-12/artwork.csv')

artists <- readr::read_csv("https://github.com/tategallery/collection/raw/master/artist_data.csv")

```


```{r}
artwork_artist <- artwork %>% 
  left_join(artists,by = c("artistId" = "id")) %>% 
  select(artist,acquisitionYear, gender) %>% 
  mutate(gender = case_when(str_detect(artist, "British") ~ "Other",
                            str_detect(artist, "Art & Language") ~ "Male",
                            TRUE ~ gender),
         artist = case_when(str_detect(artist, "British") ~ "British School",
                            TRUE ~ artist)) %>% 
  filter(!is.na(gender)) %>% 
  group_by(artist, acquisitionYear, gender) %>% 
  summarise(total = n()) %>% 
  filter(gender != "Other") %>% 
  filter(artist != "Turner, Joseph Mallord William") %>% 
  ungroup() %>% 
  filter(total > 180)


artwork_artist$fraction <-  artwork_artist$total / sum(artwork_artist$total)

artwork_artist$ymax <-  cumsum(artwork_artist$fraction)

artwork_artist$ymin <- c(0, head(artwork_artist$ymax, n = -1))
```


```{r}
plot_artwork <- artwork_artist %>% 
  ggplot() + 
  geom_rect(aes(fill = factor(acquisitionYear), 
                ymax = ymax, 
                ymin = ymin, 
                xmax = 5, 
                xmin = 4), 
            color="white", 
            size=.5, 
            alpha=0.7) +
  scale_fill_manual(values = as.vector(watlington(8)),
                    guide=guide_legend(title="Acquisition Year",
                                       order=3)) +
  new_scale_fill() +
  geom_rect(aes(fill = artist, 
                ymax = ymax, 
                ymin = ymin, 
                xmax = 4, 
                xmin = 3), 
            color = "white", 
            size = .5, 
            alpha = 0.75) +
  scale_fill_manual(values = as.vector(kelly(8)),
                    guide=guide_legend(title="Artist", 
                                       order = 2)) +
  new_scale_fill() +
  geom_rect(aes(fill = gender, 
                ymax = ymax, 
                ymin = ymin, 
                xmax = 3, 
                xmin = 2), 
            color = "white", 
            size = .5, 
            alpha = 0.8) +
  scale_fill_manual(values = c("#222233"), #bb0077
                    guide=guide_legend(title = "Gender",
                                       order = 1)) +
  xlim(c(0, 5)) + 
  labs(title="Artist Artworks in Tate Musuem by Aquisition Year",
       subtitle = "(Excluding Turner, Joseph Mallord William)",
       caption ="Source: Tate collection | Graphic: Sung Inkyung") +
  coord_polar(theta = "y") +
  theme(aspect.ratio = 1,
        legend.position = "bottom",
        legend.direction = "vertical",
        panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size = 11),
        plot.title = element_text(face = "bold",
                                  hjust = .5),
        plot.subtitle = element_text(hjust = .5),
        plot.caption = element_text(hjust = .5,
                                    size = 9,
                                    margin = margin(t = 15)))

ggsave(here::here("2021", "week3", "W3_ArtCollections.png"), width = 19, height = 17, units = "cm")
  
```

