---
title: "The Office"
author: "Sung Inkyung"
date: '2021 1 3'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(widyr)
library(tidygraph)
library(ggraph)
library(igraph)
library(ggtext)
```


```{r}
office <- schrute::theoffice

office %>% 
  count(character, sort = T)

office %>% 
  count(season, sort = T)
```


```{r}
office_similarity <- office %>% 
  group_by(character) %>% 
  filter(n() > 500) %>% 
  ungroup() %>% 
  select(season, episode, character, text) %>% 
  mutate(name = glue::glue("S{season}|{episode}"),
         id = row_number()) %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words) %>% 
  count(character, word) %>% 
  add_count(word, wt = n, name = "word_total") %>% 
  filter(word_total > 50) %>% 
  pairwise_similarity(character, word, n, upper = F, sort = T)


graph_tbl <- office_similarity %>% 
  as_tbl_graph()
```


```{r}
plot <-
  ggraph(graph_tbl, layout = "star") +
  geom_edge_link(aes(edge_colour = similarity)) +
  scale_edge_colour_gradientn( colors = scico::scico(100, palette = "turku"),
       name = NULL,
       limits = c(0, 1.01)) +
  coord_fixed(clip = "off") +
  labs(title = "Bonding Characters in **THE OFFICE**",
       subtitle = "The illustrated below shows the similarity between characters\nin The OFFICE over 9 seasons and their corresponding episdoe.\nSteve Carell(Michael) and John Krasinski(Jim) are my all-time favorite\nactors showing the highest similarity among characters.",
       caption = "**Source**: schrute | **Graphic**: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "top",
        legend.key.height = unit(.6, "lines"),
        legend.key.width = unit(3, "lines"),
        legend.title = element_text(size = 12,
                                    color = "#334455", ),
        legend.text = element_text(size = 9,
                                   color = "#334455"),
        plot.background = element_rect(fill = "#556677",
                                       color = "#556677"),
        plot.title = element_markdown(size = 16,
                                      color = "#bbccdd",
                                      face = "bold",
                                      hjust = .5,
                                      margin = margin(t = 5, b = 10)),
        plot.subtitle = element_text(size = 12,
                                      color = "#bbccdd",
                                      hjust = .5,
                                     lineheight = 1.1,
                                      margin = margin(b = 20)),
        plot.caption = element_markdown(size = 9,
                                        color = "#bbccdd", 
                                       margin = margin(t = 25)),
        plot.title.position = "plot",
        plot.margin = margin(20, 20, 20, 20)) 
         
ggsave(here::here("2020", "W12_TheOffice_Characters.png"), width = 20, height = 20, units = "cm")
```

