---
title: "W34 Extinct Plants"
author: "Sung Inkyung"
date: '2020 11 14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(showtext)

font_add_google("Righteous")
font_add_google("Graduate")
font_add_google("Saira Condensed")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)

```


```{r}
threats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv')

```


```{r}
top_threats <- threats %>% 
  filter(threatened != 0,
         threat_type != "Unknown") %>% 
  group_by(continent) %>% 
  count(threat_type, name = "count_type", sort = T) %>% 
  mutate(rank = row_number(),
         threat_type = str_replace_all(threat_type, " ", "\n"),
         continent = str_replace(continent, " ", "\n"),
         total = sum(count_type)) %>% 
  ungroup() %>% 
  group_by(threat_type) %>% 
  mutate(total_type = sum(count_type)) %>% 
  ungroup()
  

plot_continent <- top_threats %>% 
  ggplot(aes(rank, 5)) +
  geom_point(aes(size = total_type), 
             color = "#8a9d79", 
             alpha = 0.6) +
  geom_text(aes(y = 3.5, 
                label = threat_type),
            color = "#D198C5",
            family = "Saira Condensed",
            size = 3.5,) + 
  scale_y_continuous(limits = c(3, 6)) +
  scale_size_continuous(range = c(6, 13),
                        name = "Extinct plant types") +
  facet_wrap(~ continent, 
             ncol = 1, 
             strip.position = "left") +
  labs(x = "",
       title = "Threaten Plant Types Across Continents upto 2020",
       caption = "**Source**: IUCN Red List | **Graphic**: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "top",
        legend.title = element_text(color = "gray65",
                                    family = "Saira Condensed",
                                    size = 12),
        legend.text = element_text(color = "gray65",
                                   family = "Saira Condensed",
                                   size = 13),
        plot.background = element_rect(fill = "black"),
        strip.text.y = element_text(color = "#ADEFD1",
                                    size = 16,
                                    family = "Graduate",
                                    face = "bold",hjust = .5,
                                    vjust = .5,
                                    margin = margin(l = 10)),
        plot.title = element_text(color = "#E0C568FF",
                                  family = "Righteous",
                                  size = 28,
                                  face = "bold",
                                  hjust = .5,
                                  margin = margin(b = 20)),
        plot.caption = element_markdown(color = "#CBCE91",
                                        family = "Saria Condensed",
                                        size = 11, hjust = .5,
                                        margin = margin(t = 20)),
        plot.margin = margin(20, 20, 20, 20))

ggsave("W34_ExtinctPlants.png", width = 30, height = 35, units = "cm")
```
