---
title: "W36 Moore's Law"
author: "Sung Inkyung"
date: '2019 9 4'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### source[tidytuesday by jkaupp](https://github.com/jkaupp/tidytuesdays/blob/master/2019/week36/R/analysis.R)
          [tidytuesday by Z3tt](https://github.com/Z3tt/TidyTuesday/blob/master/R/2019_35_SimpsonsGuests_black.Rmd)
```{r}
library(tidyverse)
library(gganimate)
library(nord)
library(cowplot)
library(patchwork)
library(showtext)

font_add_google("Oswald")
font_add_google("Karla")

showtext_opts(dpi = 320)
showtext_auto()
```

```{r}
cpu <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-03/cpu.csv")

gpu <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-03/gpu.csv")

ram <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-03/ram.csv")
```

```{r purrr::imap_dfr}
cgr <- list(cpu = cpu, gpu = gpu, ram = ram) %>% 
  imap_dfr(~select(.x, date_of_introduction, transistor_count, area, process) %>% 
             mutate(type = .y)) %>% 
  group_by(date_of_introduction, type) %>% 
  summarize_at(vars(transistor_count, area, process), mean, na.rm = TRUE) %>% 
  arrange(date_of_introduction, type)

```

```{r}
p <- cgr %>%  
  ggplot(aes(date_of_introduction, transistor_count)) +
  geom_text(aes(label = toupper(type), 
                x = 2003, y = 700), 
            color = "grey90", family = "Oswald", size = 30, fontface = "bold") +
  geom_smooth(method = "loess", 
              formula = y ~ log10(x), 
              se = FALSE, 
              na.rm = TRUE,
              size = 0.5,  
              color = "#d2bf4c") +
  geom_hline(aes(yintercept = 10^10), 
             linetype = "dotted", 
             color = "#ff326f") +
  geom_point(aes(color = log10(process)), 
             size = 3,
             na.rm = TRUE,
             show.legend = FALSE) +
  scale_color_nord(discrete = FALSE,
                   palette = "lumina") +
  scale_x_continuous(breaks = seq(1963, 2019, by = 8)) +
  scale_y_log10(breaks = c(1, 10^3, 10^6, 10^9, 10^12),
                labels = scales::comma) +
  facet_wrap(~ type) +
  labs(x = NULL, 
       y = "Number of Transistors") +
  theme(strip.text = element_blank(),
        strip.background = element_blank(),
        panel.spacing.x = unit,
        axis.text = element_text(size = 9),
        axis.title.y = element_text("plain",
                                    size = 11)) +
  theme_half_open() +
  panel_border() 
```

```{r}
plot <- p + plot_annotation(title = "MOORE'S LAW",
                     caption = "Source: Wikipedia | Graphic: Sung Inkyung") &
  theme(plot.title = element_text(family = "Oswald", size = 36, color = "#0b4f6c", hjust = 0.5),
        plot.caption = element_text(family = "Karla", size = 11, color = "grey45"))

ggsave("W36_MooreLaw.png", width = 35, height = 13, units = "cm")
```

