---
title: "W42 Car Fuel Economy"
author: "Sung Inkyung"
date: '2019 10 18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### source[data in detail](https://www.fueleconomy.gov/feg/ws/index.shtml#fuelType1)
```{r}
library(tidyverse)
library(gghighlight)
library(ggalt)
library(ggrepel)
library(ggtext)
library(janitor)
library(scales)
library(showtext)

font_add_google("Teko")
font_add_google("Oxygen")

showtext_opts(dpi = 320)
showtext_auto()
```

```{r}
big_epa_cars <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-15/big_epa_cars.csv")
```


```{r}
top_make <- big_epa_cars %>%
  clean_names() %>% 
  count(make, year) %>% 
  count(make) %>% 
  filter(n == max(n))
```

```{r}
top_save <- big_epa_cars %>% 
  clean_names() %>% 
  select(make, year, save = you_save_spend) %>% 
  semi_join(top_make) %>% 
  group_by(year, make) %>% 
  summarise(total_save = mean(save)) %>% 
  group_by(year) %>% 
  mutate(rank = min_rank(desc(total_save))) %>% 
  ungroup()

tol22rainbow= c("#771155", "#AA4488", "#CC99BB", "#114477", "#4477AA", "#77AADD", 
                "#117777", "#44AAAA", "#77CCCC", "#117744", "#008000", "#88CCAA", 
                "#777711", "#AAAA44", "#244C96", "#774411", "#AA7744", "#FFA500", 
                "#771122", "#AA4455", "#DD7788", "#525252")

top_save_plot <- top_save %>%
  sample_frac(1) %>% 
  ggplot() +
  geom_line(aes(year, rank, color = make),
            show.legend = FALSE) +
  gghighlight(unhighlighted_colour = alpha("#b8b8b8"),
              use_direct_label = FALSE) +
  facet_wrap(~make) +
  scale_y_continuous(trans = "reverse", breaks = NULL) +
  scale_color_manual(values = tol22rainbow) +
  expand_limits(x = 2020) +
  labs(x = "",
       y = "",
       title = "Fuel economy journey of major automakers",
       subtitle = "Incessant efforts to advance, downturn, and revitalize in cost savings are observed among automakers <br>since 1984. However, <span style='color:#008000'>**Jaguar**</span>, <span style = 'color:#244C96'>**Mercedez-Benz**</span> and <span style='color:#FFA500'>**Porsche**</span> don't seem to traget improving fuel economy.",
       caption = "Source: fueleconomy.gov | Graphic: Sung Inkyung") +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "aliceblue"),
        panel.grid.major = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text = element_text(color = "#1c1c39"),
        axis.ticks = element_blank(),
        plot.title = element_markdown(color = "#1c1c39",
                                      family = "Teko",
                                      size = 28,
                                      margin = margin(b = 5)),
        plot.subtitle = element_markdown(color = "#1c1c39",
                                         family = "Oxygen",
                                         size = 15,
                                         margin = margin(b = 15)),
        plot.caption = element_text(color = "#132048",
                                    family = "Teko",
                                    size = 12,
                                    hjust = 1),
        strip.text = element_text(color = "#132048",
                                  family = "Teko",
                                  size = 13),
        strip.background = element_rect(fill = "#c4e2f3", color = NA),
        panel.spacing.x = unit(10, "pt"),
        panel.spacing.y = unit(10, "pt"),
        plot.margin = margin(10, 10, 10, 10))

ggsave("W42_TopSavingCarJourney.png", width = 28, height = 21.5, units = "cm")
```
### source[tidy tuesday by jake kaupp](https://github.com/jkaupp/tidytuesdays/blob/master/2019/week42/R/analysis.R)
```{r}
colors <- set_names(grey.colors(22), pull(top_make, make))
colors[["Dodge"]] <- "#390071"
colors[["Porsche"]] <- "#a95292"
colors[["BMW"]] <- "#ea3b52"
colors[["Mazda"]] <- "#39ff14"
colors[["Honda"]] <- "#98f898"
colors[["Volkswagen"]] <- "#c7ea46"
colors[["Ford"]] <- "#ffdb00"
colors[["Lincoln"]] <- "#79f6fc"

rank_plot <-  
  ggplot(top_save, aes(year, rank, color = make)) +
  geom_segment(aes(x =1983,
                   xend = 2021,
                   y = rank, yend = rank),
               color = "#cccccc", alpha = 0.5, size = 0.1) +
  geom_xspline(aes(color = make),
               show.legend = FALSE)+
  geom_point(aes(fill = make), 
             shape = 21, 
             color = "#b9bbb6",
             show.legend = FALSE) +
  geom_richtext(data = filter(top_save, year == 2020), 
                aes(label = make, 
                    x = 2021, color = make), 
                family = "Teko",
                hjust = 0, size = 4, 
                show.legend = FALSE,  
                fill = NA, 
                label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt")) +
  geom_text(data = filter(top_save, year == 1984),
            aes(label = rank, x = 1983),
            family = "Teko",
            hjust = 1,
            size = 3) +
  scale_color_manual(values = colors) +
  scale_fill_manual(values = colors) +
  scale_size_identity() +
  scale_x_continuous(limits = c(1984, 2022),
                     breaks = seq(1985, 2020, by = 5)) +
  scale_y_continuous(trans = "reverse", breaks = NULL) +
  expand_limits(x = 2025)+
  labs(x = "",
       y = "",
       title = "Fuel cost savings journey of major automakers since 1984",
       subtitle = "It appears to be hard to set a default value for the pereference or purpose of car buyers despite of cost saving advantage \nsince it is a challenging task to pull off a desired result.",
       caption = "Source: fueleconomy.gov | Graphic: Sung Inkyung") +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "#b9bbb6"),
        panel.grid = element_blank(),
        plot.title = element_text(color = "#1c1c39",
                                  family = "Teko",
                                  size = 28,
                                  margin = margin(b = 5)),
        plot.subtitle = element_text(color = "#1c1c39",
                                     family = "Oxygen",
                                     size = 15,
                                     margin = margin(b = 15)),
        plot.caption = element_text(color = "#132048",
                                    family = "Teko",
                                    size = 12,
                                    hjust = 1),
        axis.text = element_text(color = "#1c1c39"),
        plot.margin = margin(10, 10, 10, 10))

ggsave("W42_TopSavingCarRank.png", width = 35, height = 24.5, units = "cm")
```
