---
title: "US-Tuition"
author: "Sung Inkyung"
date: '2020 8 17 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(ggrepel)
```


```{r}
avg_tuition <- read_excel("2018/week_01/us_avg_tuition.xlsx")

avg_tuition %>% 
  count(State, sort = T)

avg_tuition_tidy <- avg_tuition %>% 
  pivot_longer(cols = 2:13, 
               names_to = "period",
               values_to = "tuition")

top_tuition <- avg_tuition_tidy %>% 
  filter(period == c("2004-05", "2015-16")) %>% 
  group_by(State) %>% 
  mutate(tuition_lag = lag(tuition),
         diff = (tuition / tuition_lag - 1) * 100) %>% 
  ungroup() %>% 
  top_n(7, diff) %>% 
  select(State)

top_state <- avg_tuition_tidy %>% 
  filter(State %in% top_tuition$State)

plot <- avg_tuition_tidy %>% 
  ggplot() +
  geom_line(aes(period, tuition, group = State),
            color = "#806b76",
            size = .5) +
  geom_line(data = top_state,
            aes(period, tuition, group = State),
            color = "#235090",
            size = 1) +
  geom_text_repel(data = top_state %>% 
                    filter(period == "2015-16"),
                  aes(period, tuition, 
                      label = State),
                  color = "#235090",
                  nudge_x = .5,
                  size = 3.5) +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(x = "",
       y = "",
       title = "Average US State Tuition Costs 2004 - 2015",
       subtitle = "Highligted states show the highest increase in tuition out of 50 US states over 12 years",
       caption = "Source: onlinembapage.com |Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(size = 25,
                                  face = "bold",
                                  color = "#151b25"),
        plot.subtitle = element_text(size = 15, ,
                                     color = "#151b25",
                                     margin = margin(t =5, b= 10)),
        plot.caption = element_text(size = 9,
                                    color = "#151b25",
                                    margin = margin(t = 10)),
        panel.grid.major.x = element_line(linetype = 8),
        panel.grid.major.y = element_line(linetype = 8),
        panel.grid.minor = element_blank(),
        plot.margin = margin(10, 10, 10, 10))

ggsave(here::here("2018", "week_01", "W1_US-AverageTuition.png"), width = 36, height = 30, units = "cm")
```

