---
title: "Passwords"
author: "Sung Inkyung"
date: '2020 1 14 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)
library(tidytext)
library(janitor)
library(showtext)

font_add_google("Oswald")
font_add_google("Oxygen")

showtext_opts(dpi = 320)
showtext_auto()
```
### Source[Lander Analytics:Ten Tremendous Tricks in the Tidyverse by David Robinson] (https://youtu.be/NDHSBUN_rVU)
```{r}
tuesdata <- tidytuesdayR::tt_load('2020-01-14') 
passwords <- tuesdata$passwords %>% 
  remove_empty("rows") %>% 
  arrange(category, password)
```

```{r}
plot <- passwords %>%
  na.omit() %>% 
  add_count(category) %>% 
  filter(n > 20) %>%
  filter(str_detect(password, "[A-Za-z]")) %>% 
  bind_tf_idf(category, password, n) %>% 
  arrange(desc(tf_idf)) %>% 
  mutate(password = factor(password, levels = rev(unique(password)))) %>% 
  group_by(category) %>% 
  slice(1:10) %>% 
  ungroup() %>%
  mutate(password = fct_reorder(password, tf_idf)) %>% 
  mutate(colour = case_when(
    category == "name" ~ "#1B9E77",
    category == "cool-macho" ~ "#666666",
    category == "simple-alphanumeric" ~ "#66A61E",
    category == "fluffy" ~ "#7570B3",
    category == "sport" ~ "#A6761D",
    category == "nerdy-pop" ~ "#D95F02",
    category == "animal" ~ "#E6AB02",
    TRUE ~ "#808080")) %>%
  ggplot(aes(x = 0,
             y = fct_rev(factor(category)),
             xend = password,
             yend = 1, 
             colour= colour,
             alpha = (colour != "grey60"))) +
  geom_curve(aes(colour = colour), 
             curvature = -0.5, 
             arrow = arrow(length = unit(0.005, "npc")), 
             show.legend = F) +
  scale_x_discrete() +
  scale_y_discrete() +
  scale_color_identity() +
  scale_size_identity() +
  scale_alpha_manual(values = c(0.7, 0.9), guide = F) +
  labs(y = " ",
       x = " ",
       title = "Top 10 TF-IDF Passwords by Cateogries",
       caption = "Source: Information is Beautiful") +
  theme_minimal () +
  theme(legend.position = "none",
        plot.title = element_text(family = "Oswald",
                                  size = 14, margin = margin(b = 15)), 
        plot.caption = element_text(family = "Oxygen", size = 7),
        panel.grid = element_blank(),
        axis.text.x = element_text(family = "Oxygen",
                                   angle = 60, size = 4.5, hjust = 1,
                                   margin=margin(t = -25, b = 10)))

ggsave("W3_Passwords.png", width = 18, height = 13, units = "cm")

```
