---
title: "AlcoholConsumption"
author: "Sung Inkyung"
date: '2020 8 20 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
alcohols <- read.csv(here::here("2018/week_13/AlcoholConsumption.csv"))
```


```{r}
df <- alcohols %>% 
  pivot_longer(names_to = "alcohol", values_to = "value",
               -country) %>% 
  group_by(alcohol) %>% 
  slice_max(order_by = value, n = 100) %>% 
  mutate(axis_x = rep(1:10, length = n()),
         axis_y = rep(20:1, each = 10, length = n()),
         label = str_c(country, value, sep = "\n"))

```


```{r}
plot_beer <- df %>% 
  filter(alcohol == "beer_servings") %>% 
  ggplot(aes(axis_x, axis_y)) +
  geom_point(aes(size = value)) +
  scale_size(range = c(0, 17)) +
  geom_text(aes(label = label),
            size = 2.5, 
            nudge_y = -0.4) +
  labs(x = "",
       y = "",
       title = "Beer Consumption by Country",
       subtitle = "Top 100 countries with highest servings consumed per person, 2010",
       caption = "Source: FiveThirtyEight package | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        plot.title = element_text(size = 25, 
                                  face = "bold",
                                  hjust = .5),
        plot.subtitle = element_text(size = 13,
                                     hjust = .5),
        plot.caption = element_text(size = 9),
        axis.text = element_blank(),
        plot.margin = margin(20, 10, 10, 10))

ggsave(here::here("2018", "week_13", "W13_BeerConsumtion.png"),  width = 22, height = 30, units = "cm", dpi = 300)
```

```{r}
plot_wine <- df %>% 
  filter(alcohol == "wine_servings") %>% 
  ggplot(aes(axis_x, axis_y)) +
  geom_point(aes(size = value)) +
  scale_size(range = c(0, 17)) +
  geom_text(aes(label = label),
            size = 2.5, 
            nudge_y = -0.5) +
  labs(x = "",
       y = "",
       title = "Wine Consumption by Country",
       subtitle = "Top 100 countries with highest servings consumed per person, 2010",
       caption = "Source: FiveThirtyEight package | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        plot.title = element_text(size = 25, 
                                  face = "bold",
                                  hjust = .5),
        plot.subtitle = element_text(size = 13,
                                     hjust = .5),
        plot.caption = element_text(size = 9),
        axis.text = element_blank(),
        plot.margin = margin(20, 10, 10, 10))

ggsave(here::here("2018", "week_13", "W13_WineConsumtion.png"),  width = 22, height = 30, units = "cm", dpi = 300)
```

```{r}
plot_spirit <- df %>% 
  filter(alcohol == "spirit_servings") %>% 
  ggplot(aes(axis_x, axis_y)) +
  geom_point(aes(size = value)) +
  scale_size(range = c(0, 17)) +
  geom_text(aes(label = label),
            size = 2.5, 
            nudge_y = -0.4) +
  labs(x = "",
       y = "",
       title = "Spirit Consumption by Country",
       subtitle = "Top 100 countries with highest servings consumed per person, 2010",
       caption = "Source: FiveThirtyEight package | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        plot.title = element_text(size = 25, 
                                  face = "bold",
                                  hjust = .5),
        plot.subtitle = element_text(size = 13,
                                     hjust = .5),
        plot.caption = element_text(size = 9),
        axis.text = element_blank(),
        plot.margin = margin(20, 10, 10, 10))

ggsave(here::here("2018", "week_13", "W13_SpiritConsumtion.png"),  width = 22, height = 30, units = "cm", dpi = 300)
```

