---
title: "CollegeTuition"
author: "Sung Inkyung"
date: '2020 3 15 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(janitor)
library(here)
```


```{r}
tuition_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv') %>% 
  clean_names()

salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv') %>% 
  clean_names()

```


```{r}
skimr::skim(tuition_cost)
skimr::skim(salary_potential)

```


```{r}
tuition_cost %>% 
  filter(! degree_length == "Other") %>% 
  ggplot(aes(type, in_state_tuition, fill = degree_length)) +
  geom_boxplot(alpha = 0.8) +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(x = "",
       y = "In-State Tuition", fill = "Degree-Length") +
  theme_minimal()
```


```{r}
data <- salary_potential %>% 
  left_join(tuition_cost) %>% 
  group_by(state_name, type) %>% 
  summarise(early_med_pay = median(early_career_pay),
            mid_med_pay = median(mid_career_pay)) %>% 
  ungroup() %>% 
  mutate(state_name = as.factor(state_name),
         state_name = fct_reorder(state_name, early_med_pay)) 

data %>% 
  group_by(type) %>% 
  filter(type %in% c("Public", "Private")) %>% 
  top_n(7)

  
  
```


```{r}
type <- data %>% 
  pivot_longer(cols = -c(state_name, type), 
               names_to = "phase",
               values_to = "payment") %>% 
  arrange(desc(phase, payment)) %>% 
  filter(!is.na(type),
         !is.na(state_name),
         !is.na(payment),
         phase != "change_med_pay",
         type != "For Profit")


type_plot <- type %>% 
  ggplot(aes(y = state_name)) +
  geom_line(aes(x = payment)) +
  geom_point(aes(x = payment, fill = phase), 
             size = 2, 
             pch = 21,
             show.legend = FALSE) +
  facet_wrap(~type) +
  scale_x_continuous(labels = scales::dollar_format()) +
  scale_fill_manual(values = c("#e5ee8e", "#6abff8")) +
  labs(x = "Salary",
       y = "",
       title = "Discrepancy of salary between<span style = 'color:#e5ee8e'> **early** </span>and<span style = 'color:#6abff8'> **middle**</span> phase of career by state",
       subtitle = "Both private and public colleges start higher in New York, California and Massachusetts comparatively.",
       caption = "Data: Tuitiontracker.org | Graphic: Sung Inkyung") +
  theme(legend.position = "none",
        plot.title = element_markdown(size = 16,
                                      margin = margin(b = 10)),
        plot.subtitle = element_markdown(size = 12,
                                         margin = margin(b = 20)),
        panel.background = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_line(size = 0.4,
                                          color = "gray80")) 

ggsave(here("2020", "W11_TuitionTracker.png"), width = 29, height = 25, units = "cm")
```

