---
title: "BeerProduction"
author: "Sung Inkyung"
date: '2020 4 5 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```


```{r}
brewing_materials <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewing_materials.csv')

```


```{r}
brewing_materials %>% 
  count(material_type, sort = T)

brewing_materials %>% 
  count(type, sort = T)
```


```{r}
type <- brewing_materials %>% 
  filter(str_detect(type, "Barley") |
           str_detect(type, "Corn") |
           str_detect(type, "Hops") |
           str_detect(type, "Malt") |
           str_detect(type, "Rice") |
           str_detect(type, "Sugar") |
           str_detect(type, "Wheat")) %>% 
  mutate(ym = make_datetime(year, month)) %>% 
  mutate(diff_ytd = (ytd_current - ytd_prior_year) / 1000) %>% 
  na.omit()

#Accident Art
accidentRt <- type %>% 
  ggplot(aes(x = ym, y = diff_ytd, fill = type)) +
  geom_density(color = NA,
               stat = "identity",
               position = "fill",
               na.rm = T) +
  scale_fill_brewer(palette = "PuOr") +
  labs(caption = "Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position ='none',
        legend.text = element_text(size=5)) 
  

```


```{r}
plot <- type %>% 
  ggplot(aes(x = ym, y = diff_ytd, color = type)) +
  geom_point(show.legend = F,
             na.rm = T) +
  geom_path(show.legend = F,
            na.rm = T) + 
  labs(x = "",
       y = "Difference in number of barrels",
       title = "Yearly Beer Ingredients Usage in USA between 2008 and 2014",
       subtitle = "Difference between the number of barrels in current year and one year prior",
       caption = "Source: TTB | Graphic: Sung Inkyung") +
  facet_wrap(~type, nrow = 2) +
  scale_color_brewer(palette = "PuOr") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(size = 16,
                                  color = "#814d30"),
        plot.subtitle = element_text(size = 13,
                                     color = "#f28e1c"))
                              
```
```{r}
type_plot <- type %>% 
  ggplot(aes(x = ym, y = ytd_current, fill = type)) +
  geom_density(color = NA,
               stat = "identity",
               position = "fill") +
  scale_fill_brewer(palette = "PuOr") +
  labs(x = "",
       y = "Number of barrels in current year",
       title = "Yearly Beer Ingredients Usage in USA between 2008 and 2014",
       subtitle = "Plot below shows that malt is an essential ingredient when it comes to beer type",
       caption = "Source: TTB | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(plot.title = element_text(size = 16,
                                  color = "#814d30"),
        plot.subtitle = element_text(size = 13,
                                     color = "#f28e1c"))
```

