---
title: "GDPR Violation"
author: "Sung Inkyung"
date: '2020 4 26 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(here)

```


```{r}
gdpr_violations <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_violations.tsv') %>% 
  mutate(date = as.Date(date, "%m/%d/%Y")) %>% 
  filter(date >= "2019-01-01")

gdpr_violations %>% 
  count(date, sort = T)

range(gdpr_violations$date)

gdpr_violations %>% 
  count(name, type, sort = T)

company <- gdpr_violations %>% 
  group_by(controller) %>% 
  summarise(fine = sum(price)) %>% 
  arrange(-fine) %>% 
  filter(fine >= 1000000) %>% 
  ungroup()  %>% 
  ggplot(aes(x = fine, y = reorder(controller, fine))) +
  geom_col(fill = "#9478ab") +
  scale_x_continuous(labels = dollar_format(suffix = "€", prefix = ""), 
                     limits = c(0, 60000000),
                     breaks = seq(0, 60000000, 10000000)) +
  labs(x = "Fines",
       y = "",
       title = "Total Fines of General Data Protection Regulation(GDPR) Violations by Company") +
  theme_minimal()
```


```{r}
country <- gdpr_violations %>% 
  count(name, sort = T) %>% 
  ungroup() %>% 
  ggplot(aes(x = n, y = reorder(name, n))) +
  geom_col(fill = "#9478ab") +
  geom_label(aes(label = n),
             color = "#ffa751",
             nudge_x = 1) +
  scale_x_continuous(expand = expansion(c(0,0))) +
  labs(x = "",
       y = "",
       title = "Frequency of General Data Protection Regulation(GDPR) Violations by Country") +
  theme_minimal()
  

```


```{r}
df <- gdpr_violations %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(year, name) %>% 
  summarise(fine = sum(price)) %>% 
  ungroup() %>% 
  filter(fine >= 1000000) %>% 
  mutate(name = reorder(name, fine)) %>% 
  ggplot(aes(x = fine, y = name, fill = as.factor(year))) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = c("#1626ac", "#ffa751")) +
  scale_x_continuous(labels = dollar_format(suffix = "€", prefix = ""), 
                     limits = c(0, 60000000),
                     breaks = seq(0, 60000000, 10000000)) +
  labs(x = "",
       y = "",
       title = "General Data Protection Regulation(GDPR) Violations in 2019 and 2020") +
  theme_minimal() +
  theme(legend.title = element_blank())
  
```

```{r}

gdpr <- gdpr_violations %>% 
  mutate(year = lubridate::year(date)) %>%
  rename(country = name) %>% 
  group_by(year, country) %>% 
  summarise(fine = sum(price)) %>% 
  ungroup() %>% 
  filter(fine >= 1000000) %>% 
  mutate(country = reorder(country, fine))


world_map <- map_data("world") %>% 
  mutate(country = region) %>% 
  filter(long >= -12, 
         long <= 38,
         lat >=  32,
         lat <= 71)


map <- gdpr %>% 
  right_join(world_map, by = "country") %>% 
  ggplot(aes(long, lat, group = group, fill = fine)) +
  geom_polygon(color = "white") +
  scale_fill_viridis_c(option = "plasma", 
                       na.value = "lightgray") +
  coord_quickmap() +
  theme_void() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 10))
  
```
### Source[CARTO color scales] (https://nowosad.github.io/rcartocolor/reference/carto_scale.html)
### Source[tidytuesday by @sctyner] (https://twitter.com/hashtag/tidytuesday?f=live) using sf package for another way of map plot

```{r}
map1 <- gdpr %>% 
  right_join(world_map, by = "country") %>% 
  ggplot(aes(long, lat, group = group, fill = fine)) +
  geom_polygon(color = "white",
               size = .2) +
  rcartocolor::scale_fill_carto_c(
    palette = 7, "Vivid",
    direction = -1,
    trans = "log10",
    na.value = "#dccccd",
    guide = "colorbar"
  ) +
  coord_quickmap() +
  guides(fill = guide_colorbar(title = "Total fine",
                               title.position = "top",
                               title.hjust = .5,
                               barheight = unit(3, "mm"),
                               barwidth = unit(70, "mm"))) +
  labs(title = "General Data Protection Regulation(GDPR) Violations by European Countries",
       subtitle = "Total fines over one million euros between 2019 and 2020\nFrance has been most imposed followed by Italy, Germany and Austria",
       caption = "Source: Privacy Affairs   | Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "bottom", 
        legend.title = element_text(size = 9),
        plot.title = element_text(size = 13, 
                                  face = "bold",
                                  hjust = .5,
                                  margin = margin(t = 20, b = 10)),
        plot.subtitle = element_text(size = 11, 
                                         hjust = .5,
                                         margin = margin(b = 15)),
        plot.caption = element_text(size = 7,
                                    color = "#dccccd",
                                    margin = margin(t = 10, b = 10)))

ggsave(here("2020", "W17_GDPR-Violation.png"), width = 18, height = 16, units = "cm")
```

