---
title: "Broadway Musicals"
author: "Sung Inkyung"
date: '2020 6 7 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(showtext)
library(here)

font_add_google("Roboto Condensed", "Roboto Condensed")
showtext_auto()
```


```{r}
grosses <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/grosses.csv')
```

### Source[tidytuesday by @ysamano] (https://github.com/ysamano/TidyTuesday/blob/master/2020/week_17/week_17_gdpr_violations.R)
```{r}
set.seed(100)

axis_ <- tibble(axis_x = runif(82),
                axis_y = runif(82))

df_gross <- grosses %>% 
  mutate(year = year(week_ending)) %>% 
  filter(year == 2019) %>% 
  select(show, weekly_gross, year) %>% 
  group_by(show, year) %>% 
  summarise(total_gross = sum(weekly_gross)) %>% 
  ungroup() %>% 
  bind_cols(axis_) %>% 
  mutate(label = str_c(show, "\n",
                       scales::dollar(total_gross, prefix =  "$"), suffix = ""), "\n", show)

```

```{r}

ggplot() +
  geom_point(data = df_gross,
             aes(axis_x, axis_y, 
                 size = total_gross),
             color = "#a16526",
             alpha = .7) +
  scale_size(range = c(2, 80)) +
  geom_point(data = df_gross, aes(axis_x, axis_y),
             color = "#424f67", size = 3.5) +
  geom_text(data = df_gross %>% filter(total_gross > 5e7),
            aes(axis_x, axis_y,
                label = label),
            size = 4,
            fontface = "bold",
            family = "Roboto Condensed",
            color = "gray95") +
  xlim(-.02, 1) +
  labs(title = "Broadway Musicals with Top Gross in 2019",
       subtitle = "It is shown Broadway shows with above $50,000,000 in total gross in 2019",
       caption = "Source: Playbill | Graphic: Sung Inkyung") +
  theme_void(base_family = "Roboto Condensed") +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#252a32", 
                                       color = "#252a32"),
        plot.title = element_text(size = 30,
                                  face = "bold",
                                  color = "white",
                                  hjust = .5,
                                  margin = margin(t = 15, b = 10)),
        plot.subtitle = element_text(size = 18,
                                  face = "bold",
                                  color = "white",
                                  hjust = .5,
                                  margin = margin(t = 10, b = 15)),
        plot.caption = element_text(color = "gray45",
                                size = 10,
                                hjust = 1,
                                margin = margin(t = 20, b = 10)),
       plot.margin = margin(10, 20, 10, 20))

ggsave(here("2020", "W18_BroadwayMusicals_2.png"), width = 24, height = 30, units= "cm")
```

