---
title: "Untitled"
author: "Sung Inkyung"
date: '2020 5 19 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggforce)
library(here)
```


```{r}
grosses <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/grosses.csv', guess_max = 10000)

cpi <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/cpi.csv')

grosses %>% 
  filter(seats_sold == max(seats_sold))

grosses %>% 
  filter(avg_ticket_price == max(avg_ticket_price))

```
```{r}
binplot <- grosses %>% 
group_by(show) %>% 
  ggplot(aes(avg_ticket_price, seats_sold)) +
  geom_hex() +
  geom_mark_circle(aes(avg_ticket_price, seats_sold, 
                       label = show, 
                       description = "The most seats sold in January, 2017", 
                       filter = seats_sold > 23000),
                   label.fontsize = 11, 
                   label.fill = "#5b616b", 
                   label.colour = "#aeb0b5", 
                   label.margin = margin(1, 1, 1, 3, "mm"),
                   label.lineheight = 1.1, 
                   con.size = 0.25, size = 0, 
                   expand = unit(0, "mm"),  
                   con.cap = 0, con.colour = "grey45") +
  geom_mark_circle(aes(avg_ticket_price, seats_sold, 
                       label = show, 
                       description = "The most expensive ticket show", 
                       filter = avg_ticket_price > 500),
                   label.fontsize = 11, 
                   label.fill = "#5b616b", 
                   label.colour = "#aeb0b5", 
                   label.margin = margin(1, 1, 1, 3, "mm"),
                   label.lineheight = 1.1, 
                   con.size = 0.25, size = 0, 
                   expand = unit(0, "mm"),  
                   con.cap = 0, con.colour = "grey45") +
  scale_fill_gradientn(colors = c("#e6073a", "#ff6632", "#b98671", "#0094fb", "#b3e835")) +
  scale_y_continuous(labels = scales::comma_format()) +
  labs(x = "Average price of tickets sold",
       y = "Total seats sold",
       title = "Average Ticket Price and Seats of Broadway Musicals",
       caption = "Source: Playbill | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "black"),
        legend.title = element_text(color = "gray90", size = 11),
        plot.title = element_text(color = "gray90", size = 16),
        plot.caption = element_text(color = "gray90", size = 9),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(color = "gray90"),
        axis.title.y = element_text(color = "gray90"))

ggsave(here("2020", "W18_BroadwayMusicals.png"), width = 18, height = 18, units = "cm")
```

