---
title: "AnimalCrossing"
author: "Sung Inkyung"
date: '2020 5 20 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
```
### Source[color combo by DESIGN WIZARD] (https://www.designwizard.com/blog/design-trends/colour-combination)

```{r}
villagers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv') %>% 
  mutate(gender = str_to_title(gender),
         species = str_to_title(species),
         personality = str_to_title(personality))

```


```{r}
villagers %>% 
  count(species, sort = T)

villagers %>% 
  count(personality, sort = T)
```


```{r}
animals <- villagers %>% 
  group_by(gender, species) %>% 
  count(personality, sort = T) %>% 
  ungroup()
```

```{r}
pal <- c("#00539cff", "#76528bff", "#2bae66ff", "#f95700ff",
         "#fcf951ff", "#ffa177ff", "#4b878bff", "#df6589ff")

plot <- animals %>% 
  mutate(species = fct_rev(species),
         gender = fct_rev(gender)) %>% 
  ggplot(aes(personality, species, 
             size = n, color = personality)) +
  geom_point(show.legend = F) +
  scale_color_manual(values = pal) +
  facet_wrap(~gender, scales = "free_x") +
  labs(x = "Personality",
       y = "",
       title = "Personality of Animals in Animal Crossing: New Horizons by Nitendo",
       subtitle = "Among 391 villagers including 35 animals and 8 personalities in the 2020 life simulation video game,\nthe most frequent combo is a peppy rabbit and a lazy dog.",
       caption = "Source: Villager DB | Graphic: Sung Inkyung") +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "#1c1c1bff", 
                                        color = "#1c1c1bff"),
        plot.background = element_rect(fill = "#1c1c1bff", 
                                       color = "#1c1c1bff"),
        plot.margin = margin(10, 10, 10, 10, "mm"),
        plot.title = element_text(face = "bold",
                                  size = 16,
                                  margin = margin(b = 10)),
        plot.subtitle = element_text(size = 13,
                                     margin = margin(b = 15)),
        plot.caption = element_text(size = 9,
                                    margin = margin(t = 25)),
        strip.text = element_text(face = "bold",
                                  color = "#ffd662ff"),
        strip.background = element_rect(fill = "gray25"),
        text = element_text(color = "white"),
        axis.text = element_text(color = "white"),
        axis.title.x = element_text(margin = margin(t = 15),
                                    face = "bold"),
        panel.grid.major = element_line(color = "gray25", 
                                        size = rel(0.5)),
        panel.grid.minor = element_line(color = "gray25", 
                                        size = rel(0.25)))
  
  ggsave(here("2020", "W19_AnimalCrossing.png"), width = 25, height = 23, units = "cm")
```

