---
title: "AfricanAmericanCensus"
author: "Sung Inkyung"
date: '2020 6 27 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source: [tidytuesday by Yobanny Sámano]
(https://github.com/ysamano/TidyTuesday/blob/master/2020/week_25/week25_black_population.R)
```{r}
library(tidyverse)
library(ggtext)
library(here)

census <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/census.csv')

census %>% 
  count(region, sort = T)

census %>% 
  filter(region == "USA Total") 

```


```{r}
df <- census %>% 
  filter(region == "USA Total") %>% 
  pivot_longer(cols = c("black_free", "black_slaves"),
               names_to = "black_", values_to = "population")

df %>% 
  count(population, sort = T) ## 0 - 4880009

plot <- df %>% 
  ggplot(aes(year, population, fill = black_)) +
  geom_col(width = 5,
           show.legend = F) +
  scale_x_continuous(breaks = seq(1790, 1870, 10)) +
  scale_y_continuous(labels = scales::comma_format(),
                     limits = c(0, 5e6),
                     breaks = seq(0, 5e6, 1e6),
                     expand = c(0, 1)) +
  scale_fill_manual(values = c("#48A072", "#000000")) +
  labs(x = "",
       y = "Population",
       title = "African American Past Slave Voyages",
       subtitle = "In 1870, the 9th Decennial Census of the United States is the first census taken<br>since the Civil War brought an end tothe near-century of slavery. For the first time,<br>all African Americanswho had lived in slavery are counted,in the same manner<br>as their fellow citizens, and no longer classified as either <span style = 'color:#000000'>**SLAVE**</span> or <span style = 'color:#48A072'>**FREE**</span>.",
       caption = "Source: Black Past & Census & Slave Voyages | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.title = element_text(size = 20,
                                  face = "bold",
                                  hjust = .5,
                                  margin = margin(b = 15)),
        plot.subtitle = element_markdown(size = 15,
                                         lineheight = 1.1,
                                         hjust = .5,
                                         margin = margin(b = 40)), 
        plot.caption = element_text(size = 9,
                                    color = "gray75",
                                    hjust =.5,
                                    margin = margin(t = 25)),
        plot.margin = margin(40, 60, 20, 60))

ggsave(here("2020", "W25_AfricanAmericanCensus.png"), width = 27, height = 20, units = "cm")

```

