---
title: "Untitled"
author: "Sung Inkyung"
date: '2020 8 15 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggstream)
library(ggtext)
library(paletteer)
```


```{r}
avatar <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/avatar.csv')

scene_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/scene_description.csv')
```


```{r}


df <- avatar %>% 
  filter(character != "Scene Description") %>% 
  mutate(book = factor(book, levels = c("Water", "Earth","Fire")),
    imdb_rating = if_else(book == "Water" & chapter_num == 20, 9.7, imdb_rating)) %>% 
  distinct(book, book_num, chapter, chapter_num, imdb_rating)


pal <- c("#9a6642", "#e25822", "#73b6fe")

plot_tile <- df %>% 
  ggplot(aes(chapter_num, book, label = imdb_rating)) +
  geom_tile(aes(fill = imdb_rating),
            show.legend = F) +
  geom_text(aes(chapter_num, book, label = imdb_rating),
            alpha = .6, 
            size = 4,
            fontface = "bold",
            color = "black") +
  scale_y_discrete(
      labels = c(
        '<span style="font-size:11pt">Book 3:</span><br>**Fire**<br><br><br>', 
        '<span style="font-size:11pt">Book 2:</span><br>**Earth**<br><br><br>', 
        '<span style="font-size:11pt">Book 1:</span><br>**Water**<br><br><br>'
      ),
      expand = c(.05, .05)
    ) +
  scale_x_continuous(breaks = seq(1, 21, 1)) +
  scale_fill_paletteer_c("ggthemes::Classic Area Red-Green") +
  labs(x = "Chapter Numbers",
       y = "",
       title = "IMDB Ratings by Elements of Avatar: The Last Airbender",
       caption = "Source: appa by Avery Robbins | Graphics: Sung Inkyung") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(size = 28,
                                  margin = margin(b = 20)),
        axis.text.y = element_markdown(size = 20, 
                                       color = pal, 
                                       hjust = .12, 
                                       margin = margin(r = 10))) 
```

