---
title: "Extinct Plants"
author: "Sung Inkyung"
date: '2020 11 14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)

```


```{r}
plants <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv')

actions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv')

threats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv')

threats %>% 
  count(year_last_seen, sort = T)
```


```{r}
top_threats <- threats %>% 
  filter(threatened != 0,
         threat_type != "Unknown") %>% 
  group_by(continent) %>% 
  count(threat_type, name = "count_type", sort = T) %>% 
  mutate(rank = row_number(),
         threat_type = str_replace_all(threat_type, " ", "\n"),
         continent = str_replace(continent, " ", "\n"),
         total = sum(count_type)) %>% 
  ungroup() %>% 
  group_by(threat_type) %>% 
  mutate(total_type = sum(count_type)) %>% 
  ungroup()
  

plot_continent <- top_threats %>% 
  ggplot(aes(rank, 5)) +
  geom_point(aes(size = total_type), 
             color = "#8a9d79", 
             alpha = 0.6) +
  geom_text(aes(y = 3.5, 
                label = threat_type),
            size = 3.5,
            color = "#D198C5FF") + ## #708e9b
  scale_y_continuous(limits = c(3, 6)) +
  scale_size_continuous(range = c(6, 13),
                        name = "Extinct plant types") +
  facet_wrap(~ continent, 
             ncol = 1, 
             strip.position = "left") +
  labs(x = "",
       title = "Threaten Plant Types Across Continents upto 2020",
       caption = "**Source**: IUCN Red List | **Graphic**: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "top",
        legend.title = element_text(size = 11,
                                    color = "gray40"),
        legend.text = element_text(size = 9,
                                   color = "gray40"),
        plot.background = element_rect(fill = "black"),
        strip.text.y = element_text(size = 14,
                                    face = "bold",
                                    color = "#CBCE91FF",
                                    hjust = .5,
                                    vjust = .5,
                                    margin = margin(l = 10)),
        plot.title = element_text(size = 24,
                                  color = "#E0C568FF",
                                  face = "bold",
                                  hjust = .5,
                                  margin = margin(t = 30)),
        plot.caption = element_markdown(size = 9,
                                        color = "#ADEFD1FF",
                                        hjust = .5,
                                        margin = margin(t = 50,
                                                        b = 20)))

  ggsave(here::here("2020", "W34_ExtinctPlants.png"), width = 30, height = 24, units = "cm")

```
### Source[DESIGN WIZARD] (https://www.designwizard.com/blog/design-trends/colour-combination)
### Source[tidytuesday by MaiaPelletier] (https://github.com/MaiaPelletier/tidytuesday/blob/master/R/2020_Week34_ExtinctPlants.R)
```{r practice}
cols <- c("#669DB3FF", "#B3C7D6FF", "#A89C94FF", "#FF4F58FF")


plot_type <- top_threats %>% 
  ggplot(aes(x = fct_reorder(threat_type, -total_type),
             y = fct_reorder(continent, total))) +
  geom_point(size = 8, shape = 21, color = "gray55", 
                 fill = "white") +
  geom_point(aes(size = count_type, color = count_type))+
  scale_x_discrete(position = "top") +
  scale_size(range = c(1, 7),
             breaks = c(10, 50, 100),
             name = "Extinct plant types") +
  scale_color_gradientn(colors = cols,
                        breaks = c(10, 50, 100),
                        name = "Extinct plant types",
                        guide = guide_legend()) +
  labs(x = "",
       y = "",
       title = "Threaten Plant Types Across Continents upto 2020") +
  theme_minimal() +
  theme(legend.position = "top",
        legend.title = element_text(size = 8,
                                    color = "gray55"),
        legend.text = element_text(size = 6),
        plot.background = element_rect(fill = "#f5f6f4",
                                       color = NA),
        plot.title = element_text(size = 24, 
                                  hjust = .5,
                                  margin = margin(t = 30, 
                                                  b = 10)),
        plot.caption = element_text(size = 9,
                                    color = "gray70"),
        panel.grid.major.x = element_line(size = .3,
                                          color = "gray55"),
        
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 10,
                                   face = "bold",
                                   hjust = .5))
```

