---
title: "Passwords"
author: "Sung Inkyung"
date: '2020 1 14 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)
library(janitor)
library(here)
```
### Source[Lander Analytics:Ten Tremendous Tricks in the Tidyverse by David Robinson] (https://youtu.be/NDHSBUN_rVU)
```{r}
tuesdata <- tidytuesdayR::tt_load('2020-01-14') 
passwords <- tuesdata$passwords %>% 
  remove_empty("rows") %>% 
  arrange(category, password)


passwords %>% 
  na.omit() %>% 
  count(category, sort = TRUE) %>% 
  top_n(10) %>% 
  mutate(category = fct_reorder(category, n)) %>% 
  ggplot(aes(category, n)) +
  geom_col(show.legend = F) +
  coord_flip()

```
### Source[tidytuesday by Christian Hohenfeld @c_hoh] (https://gitlab.com/choh/tidy-tuesday/blob/master/R/2020_03_passwords.R)
```{r}
pw_type <- passwords %>% 
    mutate(n = nchar(password),
           len = str_length(password),
           type = case_when(
               str_detect(password, '^[0-9]+$') ~ 'numbers',
               str_detect(password, '^[a-z]+$') ~ 'lowercase',
               str_detect(password, '^[[a-z]|[0-9]]+$') ~ 'lowercase alphanumeric',
               str_detect(password, '^[A-Z]+$') ~ 'uppercase',
               str_detect(password, '^[[A-Z]|[0-9]]+$') ~ 'uppercase alphanumeric',
               T ~ 'other'
           )) %>% 
  select(password, type, offline_crack_sec, n) %>% 
  mutate(type = str_to_title(type)) %>% 
  group_by(type, n) %>% 
  summarise(crack_mean = mean(offline_crack_sec,
                              na.rm = T),
            example = first(password)) %>% 
  ungroup()
```


```{r}
pw_plot <- pw_type %>% 
  ggplot(aes(x = crack_mean, y = n, 
             color = type, 
             label = example)) +
  geom_point(size = 2, shape = 16) +
  geom_line(alpha = 0.5) +
  geom_text(nudge_x = 0.2,
            nudge_y = -0.15,
            size = 3,
            show.legend = FALSE) +
  scale_x_log10() +
  scale_y_continuous(breaks = seq(3, 10, 1)) +
  scale_color_manual(values = c("#004206", "#ff3844", "#5bb9e9")) +
  labs(x = "Mean of seconds to crack",
       y = "",
       title = "Passwords combined with lowercase and numbers are more robust",
       caption = "Source: Information is beautiful") +
  guides(color = guide_legend(reverse = TRUE)) +
  theme_minimal() +
  theme(plot.title = element_text(size = 14),
        plot.caption = element_text(size = 9))
  
```

```{r}
category_rank <- passwords %>% 
  add_count(category) %>% 
  filter(n > 20) %>% 
  ggplot(aes(x= fct_reorder(category, n), y = rank, 
             fill = category)) +
  geom_boxplot()+
  geom_jitter(width = 0.3,
              alpha = 0.2,
              show.legend = FALSE)+
  geom_hline(yintercept = 250.6,
             size = 1,
             lty = "dashed",
             color = "#004ea8") +
  scale_fill_brewer(palette = "Set2") +
  scale_y_continuous(limits = c(0, 500),
                     breaks = seq(0, 500, 50)) +
  coord_flip() +
  labs(x = "",
       y = "Rank",
       title = "Rank of top 7 categories in passwords") +
  theme_minimal()+
  theme(legend.position = "none")

category_strength <- passwords %>% 
  add_count(category) %>% 
  filter(n > 20) %>% 
  ggplot(aes(x= fct_reorder(category, n), y = strength, 
             fill = category)) +
  geom_boxplot()+
  geom_jitter(width = 0.3,
              alpha = 0.2,
              na.rm = T,
              show.legend = FALSE)+
  scale_fill_brewer(palette = "Set2") +
  scale_y_continuous(limits = c(0, 50),
                     breaks = seq(0, 50, 10)) +
  labs(x = "",
       y = "Strength",
       title = "Strength of top 7 categories in passwords") +
  theme_minimal()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 40, 
                               hjust = 1, 
                               margin = margin(t = -2, r = 0, b = 0, l = 0)))
```


```{r}
top7_category <- c("name", "cool-macho", 
                  "simple-alphanumeric", 
                  "fluffy", "sport", 
                  "nerdy-pop", "animal")

top_category <- passwords %>%
  filter(category %in% top7_category) %>%
  group_by(category) %>%
  summarise(
    avg_rank = mean(rank)
  ) %>% 
  mutate(avg_rank = round(avg_rank, 1))

top_category_selected <- top_category %>%
  mutate(avg_rank = round(avg_rank, 1)) %>% 
  arrange(category) %>%
  group_by(category) %>%
  slice(1:1) %>%
  ungroup() # average = 250.54
```

```{r}
library(tidybayes)

plot_theme <- 
  theme(title = element_text(size = 10),
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 11, 
                                     face = "plain"),
        axis.text = element_text(size = 9),
        legend.text = element_text(size = 9),
        legend.position = "none",
        legend.margin = margin(0,0,0,0, "cm"),
        plot.caption = element_text(hjust = 1)) +
  theme_minimal()

tol11qualitative=c("#332288", "#6699CC", "#88CCEE", "#44AA99", "#117733", 
                   "#999933", "#DDCC77")
 
p1 <- passwords %>% 
  na.omit() %>% 
  filter(category %in% top7_category) %>%
  filter(str_detect(password, "[a-z]")) %>% 
  ggplot(aes(rank, category)) +
  stat_intervalh(.width = c(.1, .25, .5, .75, 1),
                 height = 5, 
                 show.legend = FALSE) +
  rcartocolor::scale_colour_carto_d(palette = "Peach") +
    #geom_density_ridges(scale = 2, 
                     # aes(fill = country), 
                     # alpha = 0.5,
                     # color = "#0000001A",
                     # na.rm = TRUE,
                     # show.legend = FALSE) +
  geom_point(aes(rank, category), 
             color = "#4d3093", 
             size = 0.1, 
             alpha = 0.1)+
  geom_vline(lty =2, 
             xintercept = 250,
             alpha = 0.8) +
  scale_fill_manual(values = tol11qualitative) +
  labs(title = "Top 10 countries in ramen ratings",
       x = "rating",
       y = " ") +
  plot_theme

```


```{r}
library(ggbeeswarm)

p2 <- passwords %>% 
  na.omit() %>% 
  add_count(category) %>% 
  filter(n > 20) %>%
  ggplot(aes(category, rank, 
             size = rank)) +
  geom_quasirandom(alpha = 0.5,
                   width = 0.3,
                   color = "#ff3844",
                   na.rm = T) +
  stat_summary(fun.y = "median", 
               geom = "point", 
               size = 3,
               color = "#90c9c5",
               na.rm = T) +
  stat_summary(fun.y = "median", 
               geom = "line", 
               aes(group = 1),
               size = 1,
               color = "#90c9c5") +
  scale_y_continuous(limits = c(200, 500),
                     breaks = seq(200, 500, 50)) +
  labs(x = " ",
       y = " ",
       title = "Password category popularity") +
  theme_minimal() +
  theme(plot.title = element_text(size = 16,
                                  margin = margin(b = 10)),
        axis.text.x = element_text(angle = 70, 
                               hjust = 1, 
                               margin = margin(t = -2, r = 0, b = 0, l = 0)))
```

```{r}
library(tidytext)

p3 <- passwords %>%
  na.omit() %>% 
  add_count(category) %>% 
  filter(n > 20) %>%
  filter(str_detect(password, "[A-Za-z]")) %>% 
  bind_tf_idf(category, password, n) %>% 
  arrange(desc(tf_idf)) %>% 
  mutate(password = factor(password, levels = rev(unique(password)))) %>% 
  group_by(category) %>% 
  slice(1:10) %>% 
  ungroup() %>%
  mutate(password = fct_reorder(password, tf_idf)) %>% 
  ggplot(aes(password, tf_idf, fill = category)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~category, ncol = 2, scales = "free") +
  coord_flip()
```


```{r}
library(tidytext)

p4 <- passwords %>%
  na.omit() %>% 
  add_count(category) %>% 
  filter(n > 20) %>%
  filter(str_detect(password, "[A-Za-z]")) %>% 
  bind_tf_idf(category, password, n) %>% 
  arrange(desc(tf_idf)) %>% 
  mutate(password = factor(password, levels = rev(unique(password)))) %>% 
  group_by(category) %>% 
  slice(1:10) %>% 
  ungroup() %>%
  mutate(password = fct_reorder(password, tf_idf)) %>% 
  mutate(colour = case_when(
    category == "name" ~ "#1B9E77",
    category == "cool-macho" ~ "#666666",
    category == "simple-alphanumeric" ~ "#66A61E",
    category == "fluffy" ~ "#7570B3",
    category == "sport" ~ "#A6761D",
    category == "nerdy-pop" ~ "#D95F02",
    category == "animal" ~ "#E6AB02",
    T ~ "#808080"))%>%
  ggplot(aes(x = 0,
             y = fct_rev(factor(category)),
             xend = password,
             yend = 1, 
             colour= colour,
             alpha = (colour != "grey60")
             ))+
  geom_curve(aes(colour = colour), 
             curvature = -0.5, 
             arrow = arrow(length = unit(0.005, "npc")), 
             show.legend = F) +
  scale_x_discrete() +
  scale_y_discrete() +
  scale_color_identity() +
  scale_size_identity() +
  scale_alpha_manual(values = c(0.7, 0.9), guide = F) +
  labs(y = " ",
       x = " ",
       title = "Top 10 tf-idf passwords by cateogries",
       caption = "Source: Information is Beautiful") +
  theme_minimal () +
  theme(plot.title = element_text(size = 16,
                         margin = margin(b = 20)), 
        plot.caption = element_text(size = 9),
        panel.grid = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(angle = 60, 
                               size = 7,
                               hjust = 1 ,
                               margin=margin(t = -25, b = 10)))

ggsave(here("2020", "W3_Top10TF-IDFPasswords.png"), width = 20, height = 14, units = "cm")

```

```{r}
passwords_category <- passwords %>% 
  na.omit() %>% 
  add_count(category) %>% 
  filter(n > 20) %>%
  filter(str_detect(password, "[A-Za-z]")) %>% 
  bind_tf_idf(category, password, n) %>% 
  arrange(desc(tf_idf)) %>% 
  mutate(password = factor(password, levels = rev(unique(password)))) %>% 
  group_by(category, password) %>% 
  top_n(10) %>% 
  summarise(avg_rank = mean(na.omit(rank)),
            avg_strength = mean(na.omit(strength))) %>% 
  filter(avg_rank > 200) %>% 
  ggplot(aes(avg_rank, avg_strength)) +
  geom_point(color = "#fb2e01",
             aes(size = avg_strength),
             na.rm = TRUE) +
  ggrepel::geom_text_repel(aes(label = ifelse(avg_strength >= 20, category, "")),
                           size = 3.5,
                           box.padding = unit(0.7, "lines"),
                           na.rm = TRUE) +
 # geom_smooth(method = "lm", se = FALSE, show.legend = FALSE) +
  scale_x_continuous(breaks = seq(0, 500, 100)) +
  scale_y_continuous(breaks = seq(0, 50, 10)) +
  labs(x = "Average rank",
       y = "Average strength",
       title = "Top category by average rank and strength",
       subtitle = "Simple-alphanumeric in category is safer when creating a secure password.",
       caption = "Source: Information is Beautiful") +
  theme_minimal() +
  theme(legend.position = "top")
```
