---
title: "NCAA Women's Basketball"
author: "Sung Inkyung"
date: '2020 11 15 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggimage)
library(ggtext)
```


```{r}
tournament <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-10-06/tournament.csv')

tournament %>% 
  filter(tourney_finish == "Champ") %>% 
  count(conference, sort = T) %>% 
  summarise(total = sum(n))

tournament %>% 
  count(seed, sort = T)
```


```{r}
champs <- tournament %>% 
  filter(tourney_finish == "Champ") %>% 
  count(conference, sort = T) %>% 
  mutate(conference = glue::glue("{conference} ({n})"),
         conference = fct_reorder(conference, n))

num <- length(unique(champs$conference))

champs_ball <- tibble(conference = unique(champs$conference),
                      image = rep("C:/Users/inkyscope/Documents/projectR/datavizRscope/image/basketball.png"), 
                      length.out = num)

plot <- champs %>% 
  left_join(champs_ball) %>% 
  ggplot(aes(n, conference)) +
  geom_image(aes(image = image)) +
  scale_x_continuous(limits = c(0, 10),
                     breaks = seq(0, 10, 2),
                     expand = c(0, 0)) +
  labs(x = "",
       y = "",
       title = "Top Conferences of National Champions from 1982 to 2018",
       caption = "**Source**: FiveThirtyEight | **Graphic**: Sung Inkyung") +
    theme_minimal() +
    theme(plot.background = element_rect(fill = "#bb9c87ff"),
          panel.background = element_rect(fill = "#cdb6a0ff"),
          plot.title = element_text(color = "#00008b",
                                    size = 10),
          plot.caption = element_markdown(color = "#b54213",
                                          size = 4),
          axis.text.x = element_blank(),
          axis.text.y = element_text(color = "#161616",
                                     size = 5),
          panel.grid.major = element_blank())
  
  ggsave(here::here("2020", "W41_NCAA Women's Basketball.png"), width = 14, height = 8, units = "cm")
```
### Source[tidytuesday by long39ng] (https://github.com/long39ng/puig_orgaladhad/tree/main/2020_52_big_mac_index)
```{r}
library(ggtextures)

image_basketball <- "https://twemoji.maxcdn.com/v/13.0.1/72x72/1f3c0.png"

```


```{r}
plot_champs <- champs %>% 
  ggplot(aes(conference, n)) +
  geom_isotype_col(image = image_basketball,
                   img_width =  unit(1, "native"),
                   img_height = unit(1, "native"),
                   ncol = NA, 
                   nrow = 1, hjust = 0,
                   vjust = .5) +
  coord_flip() +
  labs(x = "",
       y = "",
       title = "The Number of NCAA Women's Champions by Conference",
       subtitle = "The **Big East** or **Southeastern** conferences are on the top position to produce the most champions<br>out of the 37 tournaments from 1982-2018",
       caption = "Source: FiveThirtyEight | Graphic: Sung Inkyung") +
  theme_minimal(base_size = 16) +
  theme(plot.background = element_rect(fill = "#dfbb85"),
        panel.grid = element_blank(),
        plot.title = element_markdown(size = rel(1.3),
                                      colour = "#981717"),
        plot.subtitle = element_markdown(colour = "#981717",
                                         lineheight = .7,
                                         margin = margin(b = 15)),
        plot.caption = element_markdown(size = 12,
                                        colour = "gray35",
                                        margin = margin(t = 20)),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 15),
        panel.grid.major.x = element_blank(),
        plot.margin = margin(20, 20, 20, 20))

 ggsave(here::here("2020", "W41_NCAA Women's Basketball Champions.png"), width = 33, height = 35, units = "cm")
```

