---
title: "Historical Phones"
author: "Sung Inkyung"
date: '2020 11 11 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(countrycode)
library(geofacet)
library(here)
```


```{r}
mobile <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/mobile.csv')

```


```{r}
mobile_africa <- mobile %>% 
  filter(continent == "Africa") %>% 
  filter(mobile_subs != "NA") %>%
  mutate(iso2 = countrycode(entity, 
                            origin = "country.name",
                            destination = "iso2c"))

 africa_grid <- africa_countries_grid1 %>% 
  mutate(name = case_when(name == "Central African Republic" ~ "CAR",
                          name == "Democratic Republic of the Congo" ~ "DRC",
                          TRUE ~ name))
```


```{r}
plot_africa <- mobile_africa %>% 
  ggplot() +
  geom_rect(aes(xmin = 2000, xmax = 2017,
            ymin = 0, ymax = 200),
            fill = "#3b2f31") +
  geom_area(aes(year, mobile_subs),
            fill = "#AE0E36FF") +
  facet_geo(~ iso2, 
            grid = africa_grid,
            label = "name") +
  scale_x_continuous(breaks = seq(2000, 2015, 5),
                     labels = c("'00", "'05", "'10", "'15")) +
  labs(title = "African Mobile Phone Subscriptions, 2000-2017",
       subtitle = "Mobile subscriptions are illustrated  per 100 people across countries in Africa\nAn abreviation of Central African Republic is CAR\nDRC is for Democratic Republic of the Congo",
       caption = "Source: ourworldindata.org | Graphic: Sung Inkyung") +
  theme_light() +
  theme(panel.background = element_rect(fill = "#3b2f31",
                                        color = NA),
        plot.title = element_text(size = 19,
                                  hjust = 0,
                                  color = "#3b2f31"),
        plot.subtitle = element_text(size = 15,
                                     hjust = 0,
                                     margin = margin(b = 45)),
        plot.caption = element_text(size = 11,
                                    hjust = .5,
                                    margin = margin(t = 45)),
        strip.text = element_text(size = 9,
                                  color = "#AE0E36FF"),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_text(color = "#D32E5EFF"),
        plot.margin = margin(t = 30, b = 30)) 

ggsave(filename = "W46_HistoricalPhones.png", 
       plot = plot_africa, 
       width = 22, 
       height = 29,
       units = "cm")
  
```

