---
title: "MeaslesVaccination"
author: "Sung Inkyung"
date: '2020 2 29 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggthemes)
library(ggtext)
library(here)
```

```{r}
measles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-25/measles.csv')

measles %>% 
  filter(!is.na(city)) %>% 
  count(mmr, sort = TRUE) 
```


```{r}
measles_vac <- measles %>% 
  filter(mmr > 0) %>% 
  drop_na(enroll) %>% 
  mutate(threshold = ifelse(mmr > 95, "pass", "fail")) %>% 
  group_by(city) %>% 
  mutate(avg = mean(mmr))

n_distinct(measles_vac$city)
```


```{r}
measles_vac %>% 
  ggplot(aes(enroll, mmr, color = threshold)) +
  geom_point(alpha = 0.2,
             show.legend = FALSE) +
  scale_color_manual(values = c("pass" = "#32a852", "fail" = "#d31a2c")) +
  geom_hline(yintercept = 95, linetype = 2, size = 0.75, color = "#5a175d") +
  labs(x = "School enrollment",
       y = "MMR immunisation rate(%)",
       title = "Average rates of Measles, Mumps, and Rubella (MMR)\nimmunisation across US schools in 3207 cities",
       subtitle = "Accoridng to the CDC, <span style = 'color:#5a175d'>**95%**</span>of a population needs to be vaccinated<br>to stop the spread of measles and preserve herd immunity.<br>Many cities appear to fall below this threshold.",
       caption = "Source: The Wall Stree Journal | Graphic: Sung Inkyung") +
  theme_minimal()+
  theme(plot.title = element_text(size = 16, 
                                  face = "bold"),
        plot.subtitle = element_markdown(size = 12),
        plot.caption = element_text(size = 9, color = "gray40"),
        plot.margin = margin(10, 10, 10, 10),
        axis.title.y = element_text(size = 9),
        axis.title.x = element_text(size = 9))

ggsave(here ("2020", "W9_MeaslesVaccination.png"), width = 19, height = 17, units = "cm")
```
