---
title: "W49 World Cup Cricket 1996"
author: "Sung Inkyung"
date: '2021 12 21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[gtExtras Package] (https://jthomasmock.github.io/gtExtras/)
### Source[tidytuesday by @tanya_shapiro] 9https://github.com/tashapiro/TidyTuesday/blob/master/2021/W49/cricket_world_cup.R
```{r}
library(tidyverse)
library(gt)
library(gtExtras) # remotes::install_github("jthomasmock/gtExtras")
library(ggflags)
library(paletteer)

```


```{r}
matches <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-11-30/matches.csv') %>% 
  mutate(match_year = parse_number(str_extract(match_date, "[0-9]{4}$")))

matches %>% 
  colnames()
```


```{r}
# team 1
team1 <- matches %>% 
  dplyr::select(team1, score_team1, wickets_team1, team2, winner, margin, series, match_year, match_id) %>% 
  rename(team = team1, score = score_team1, wickets = wickets_team1, rival = team2)

# team 2
team2 <- matches %>% 
  dplyr::select(team2, score_team2, wickets_team2, team1, winner, margin, series, match_year, match_id) %>% 
  rename(team = team2, score = score_team2, wickets = wickets_team2, rival = team1)

# combine team 1 and team 2
df <- rbind(team1, team2) %>% 
  mutate(win = ifelse(team == winner, 1, 0)) %>% 
  dplyr::select(match_id, team, rival, winner, series, match_year, score, wickets, win, margin)

df_1996 <- df %>% 
  filter(match_year == 1996) %>% 
  group_by(team) %>% 
  summarise(score = sum(score),
            wickets = sum(wickets),
            game = n(),
            avg_score = round(score /game, 0),
            wins = sum(win),
            losses = game - wins,
            win_prc = round(wins / game, 2)) %>% 
  arrange(desc(wins, win_prc)) %>% 
# flag images: https://www.flaticon.com/packs/countrys-flags
   mutate(
    flag = case_when(
      team == "South Africa" ~ 'https://cdn-icons-png.flaticon.com/512/197/197562.png',
      team == "Pakistan" ~ 'https://cdn-icons-png.flaticon.com/512/197/197606.png',
      team == "Sri Lanka" ~ 'https://cdn-icons-png.flaticon.com/512/197/197398.png',
      team == "India" ~ 'https://cdn-icons-png.flaticon.com/512/197/197419.png',
      team == "Australia" ~ 'https://cdn-icons-png.flaticon.com/512/197/197507.png',
      team == "West Indies" ~'https://s.ndtvimg.com/images/entities/300/west-indies-2119.png',
      team == "New Zealand" ~'https://cdn-icons-png.flaticon.com/512/197/197589.png',
      team == "England" ~'https://cdn-icons-png.flaticon.com/512/197/197485.png',
      team == "Zimbabwe" ~'https://cdn-icons-png.flaticon.com/512/197/197394.png',
      team == "Kenya" ~'https://cdn-icons-png.flaticon.com/512/197/197608.png',
      team == "Netherlands" ~'https://cdn-icons-png.flaticon.com/512/197/197441.png',
      team == "United Arab Emirates" ~'https://cdn-icons-png.flaticon.com/512/197/197569.png'
    )) %>%
  dplyr::select(flag, everything())

# create list of scores
scores <- df %>% 
  filter(match_year == 1996) %>% 
  group_by(team) %>% 
  summarise(scores_data = list(score), .groups = "drop")

win_losses <- df %>% 
  filter(match_year == 1996) %>% 
  group_by(team) %>% 
  summarise(outcome = list(win), .groups = "drop") %>% 
  dplyr::select(team, outcome)

# join datasets
df_1996 <- df_1996 %>% 
  left_join(scores) %>% 
  left_join(win_losses)
```
```{r}
# create table
table <- df_1996 %>% 
  dplyr::select(team, flag, score, wickets, game, wins, losses, avg_score, scores_data, outcome, win_prc) %>% 
  gt() %>% 
  gt_img_rows(flag) %>% 
  fmt_percent(columns = win_prc, decimals = 0) %>% 
  gt_color_rows(win_prc, palette = "ggsci::light_green_material") %>% 
  gt_sparkline(scores_data, line_color = "#505050") %>% 
  gt_plt_winloss(outcome, max_wins = 16) %>% 
  gt_theme_espn() %>% 
  cols_align(align = "center",
             columns = c(scores_data, flag, outcome)) %>% 
  tab_footnote("Outcome represents wins(blue) and losses(red)",
               locations = cells_column_labels(columns = outcome)) %>% 
  cols_label(flag = "",
             win_prc = "WIN %",
             score = "TOTAL PTS",
             scores_data = "PTS PER Game",
             avg_score = "AVG PTS") %>% 
  tab_options(heading.title.font.size = 20) %>% 
  tab_header(title = "CRICKET WORLD CUP 1996",
             subtitle = "Outcome summary by team from WILLS WORLD CUP") %>% 
  tab_source_note("Data: ESPN | Graphic: Sung inkyung | Credit: @tanya_shapiro")

table

# gtsave(table, file = file.path(tempdir(), "W49_WorldCupCricket1996.png"))
```

