---
title: "W29 Astronauts"
author: "Sung Inkyung"
date: '2020 7 19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(showtext)
font_add_google("Teko")
font_add_google("Inter")

showtext_opts(dpi = 320)
showtext_auto()
```


```{r}
astronauts <-
  readr::read_csv(
    "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv")
```

```{r}

df <- astronauts %>% 
  mutate(nationality_lump = fct_lump(nationality, 2)) %>% 
  filter(str_detect(selection, regex("nasa|tspk", ignore_case = T))) %>% 
  mutate(agency = case_when(
  str_detect(selection, fixed("nasa", ignore_case = T)) ~ "nasa",
  str_detect(selection, fixed("tspk", ignore_case = T)) ~"tspk",
  TRUE ~ selection
  ))

df_plot <- df %>% 
  count(year_of_mission, agency) %>% 
  group_by(agency) %>% 
  mutate(total = cumsum(n)) %>% 
  ungroup() %>% 
  arrange(agency, year_of_mission)


plot <- df_plot %>% 
  ggplot(aes(year_of_mission, total, color = agency)) +
  geom_line(size = 1.3,
            lineend = "round",
            show.legend = F) +
  geom_text(data = df_viz %>% filter(year_of_mission == last(year_of_mission)), 
            aes(label = agency, 
                x = year_of_mission + 2.7, 
                y = total,
                color = agency)) +
  labs(x = "",
       y = "Total number of Travels",
       title = "Space Travel by Agency",
       caption = "Source: Corlett, Stavnichuk & Komarova article | Graphic: Sung Inkyung") +
  scale_color_manual(values = c("nasa" = "#a6d81a", "tspk" = "#9b1cc7")) +
  theme_minimal()+
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#060e1a", 
                                       color = NA), 
        panel.grid = element_blank(),
        plot.title = element_text(color = "snow2",
                                  family = "Teko",
                                  size = 21,
                                  face = "bold",
                                  margin = margin(t = 20,
                                                  b = 10)),
        plot.caption = element_text(color = "snow3",
                                    family = "Inter",
                                    size = 7),
        axis.title.y = element_text(color = "#c5cedb",
                                    family = "Inter",
                                    size = 9,),
        axis.text = element_text(color = "#c5cedb",
                                 family = "Inter",
                                 size = 9))
ggsave("W29_Astronauts.png")
```

