---
title: "Bechel Test"
author: "Sung Inkyung"
date: '2021 3 16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by cnicault] (https://github.com/cnicault/tidytuesday/blob/master/2021/2021-11-Bechdel-test/bechdel_test.Rmd)
```{r}
library(tidyverse)
library(ggstream)
library(ggbeeswarm)
library(ggtext)
library(patchwork)
```


```{r}
raw_bechdel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/raw_bechdel.csv')
movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv')

```


```{r}
movies %>% 
  count(clean_test, sort = T)
```


```{r beeswarm plot}
df <- movies %>% 
  mutate(clean_test = case_when(
    clean_test == "ok"~ "Pass",
    clean_test == "dubious" ~ "Dubious",
    clean_test == "men" ~ "About men",
    clean_test == "notalk" ~ "No talk",
    clean_test == "nowomen" ~"No women"
  )) %>% 
  mutate(clean_test = as.factor(clean_test),
         clean_test = fct_relevel(clean_test, c("Pass", "Dubious", "About men", "No talk", "No women")))


pals <- c("Pass" = "#677eaa", 
          "Dubious" = "#d29958", 
          "No women" = "#ab9b91", 
          "No talk" = "#fff783", 
          "About men" = "#a7bd96")

plot_beeswarm <- df %>% 
  select(year, clean_test) %>% 
  group_by(year) %>% 
  arrange(clean_test) %>%
  mutate(position = row_number()) %>% 
  ggplot(aes(year, position, color = clean_test)) +
  geom_beeswarm(size = 1.2) +
  scale_color_manual(values = pals) +
  scale_x_continuous(breaks = seq(1970, 2010, 10),
                     expand = c(0.03, 0.01)) +
  #guides(color = guide_legend(override.aes = list(size = 3.5))) +
  labs(x = "",
       y = "") +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#304965",
                                       color = NA),
        #legend.position = "bottom",
        #legend.title = element_blank(),
        #legend.text = element_text(color = "#bbd3d5",
                                   #size = 9),
        axis.text.x = element_text(color = "#bcd0f0",
                                   size = 9,
                                   margin = margin(b = 10)),
        axis.ticks.x = element_line(color = "gray35"),
        plot.margin = margin(0, 0, 10, 0))
  
```

```{r stream plot}

rating <- df %>% 
  count(year, clean_test) %>% 
  group_by(year) %>% 
  mutate(prc = round(n / sum(n), 2))

plot_stream <- rating %>% 
  ggplot(aes(year, prc, fill = clean_test)) +
  geom_stream() +
  scale_fill_manual(values = pals) +
  scale_x_continuous(breaks = seq(1970, 2010, 10),
                     expand = c(0, 1.3)) +
  guides(fill = guide_legend(label.position = "top",
                             title.hjust = .5,
                             keywidth = unit(2.7, "line"),
                             keyheight = unit(.7, "line"),
                             nrow = 1)) +
  theme_void() +
  theme(plot.background = element_rect(fill = "#304965",
                                       color = NA),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(color = "#bbd3d5",
                                   size = 9),
        axis.text.x = element_text(color = "#bcd0f0",
                                   size = 9,
                                   margin = margin(b = 10)),
        axis.ticks.x = element_line(color = "gray35"),
        plot.margin = margin(0, 0, 10, 0))


final <- plot_beeswarm / plot_stream  +
  plot_layout(nrow = 2, heights = c(1, 0.5)) +
  plot_annotation(
    title = "Bechdel Test over Performance of Women in Films",
    caption = "Source: FiveThirtyEight | Graphic: Sung Inkyung",
    theme = theme(plot.title = element_text(size = 26, 
                                            color = "#304965",
                                            hjust = 0.5, 
                                            margin = margin(b = 15)),
                  plot.caption = element_text(size = 11, 
                                              color = "#304965",
                                              margin = margin(t = 20)),
                  plot.margin = margin(30, 20, 30, 20)))

ggsave(here::here("2021", "week11", "W11_BechelTest.png"), width = 30, height = 24, units = "cm")
```


