---
title: "W13 Alcohol Consumption"
author: "Sung Inkyung"
date: '2020 8 20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(showtext)

font_add_google("Bebas Neue")
font_add_google("Poppins")

showtext_opts(dpi = 320)
showtext_auto()
```


```{r}
alcohols <- read.csv("C:/Users/inkyscope/Documents/projectR/datavizRscope/2018/week13/data/AlcoholConsumption.csv")
```


```{r}
df <- alcohols %>% 
  pivot_longer(names_to = "alcohol", values_to = "value",
               -country) %>% 
  group_by(alcohol) %>% 
  slice_max(order_by = value, n = 100) %>% 
  mutate(axis_x = rep(1:10, length = n()),
         axis_y = rep(20:1, each = 10, length = n()),
         label = str_c(country, value, sep = "\n"))

```


```{r}
f1 = "Bebas Neue"
f2 = "Poppins"

plot_beer <- df %>% 
  filter(alcohol == "beer_servings") %>% 
  ggplot(aes(axis_x, axis_y)) +
  geom_point(aes(size = value),
             color = "darkgoldenrod2") +
  scale_size(range = c(0, 17)) +
  geom_text(aes(label = label),
            family = f2,
            size = 3.5, 
            nudge_y = -0.5) +
  labs(x = "",
       y = "",
       title = "Beer Consumption by Country",
       subtitle = "Top 100 countries with highest servings consumed per person, 2010",
       caption = "Source: FiveThirtyEight package | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        plot.title = element_text(family = f1, 
                                  size = 35, 
                                  face = "bold",
                                  hjust = .5),
        plot.subtitle = element_text(family = f2,
                                     size = 20,
                                     hjust = .5),
        plot.caption = element_text(family = f2,
                                    size = 12,
                                    color = "gray45"),
        axis.text = element_blank(),
        plot.margin = margin(20, 10, 10, 10))

ggsave("W13_BeerConsumption.png",  width = 30, height = 32, units = "cm", dpi = 300)
```

```{r}
plot_wine <- df %>% 
  filter(alcohol == "wine_servings") %>% 
  ggplot(aes(axis_x, axis_y)) +
  geom_point(aes(size = value),
             color = "deeppink4") +
  scale_size(range = c(0, 17)) +
  geom_text(aes(label = label),
            family = f2,
            size = 3.5, 
            nudge_y = -0.5) +
  labs(x = "",
       y = "",
       title = "Wine Consumption by Country",
       subtitle = "Top 100 countries with highest servings consumed per person, 2010",
       caption = "Source: FiveThirtyEight package | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        plot.title = element_text(family = f1,
                                  size = 35, 
                                  face = "bold",
                                  hjust = .5),
        plot.subtitle = element_text(family = f2,
                                     size = 20,
                                     hjust = .5),
        plot.caption = element_text(family = f2,
                                    size = 12,
                                    color = "gray45"),
        axis.text = element_blank(),
        plot.margin = margin(20, 10, 10, 10))

ggsave("W13_WineConsumption.png",  width = 40, height = 33, units = "cm")
```

```{r}
plot_spirit <- df %>% 
  filter(alcohol == "spirit_servings") %>% 
  ggplot(aes(axis_x, axis_y)) +
  geom_point(aes(size = value),
             color = "aquamarine3") +
  scale_size(range = c(0, 17)) +
  geom_text(aes(label = label),
            family = f2,
            size = 3.5, 
            nudge_y = -0.4) +
  labs(x = "",
       y = "",
       title = "Spirit Consumption by Country",
       subtitle = "Top 100 countries with highest servings consumed per person, 2010",
       caption = "Source: FiveThirtyEight package | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        plot.title = element_text(family = f1,
                                  size = 35, 
                                  face = "bold",
                                  hjust = .5),
        plot.subtitle = element_text(family = f2,
                                     size = 20,
                                     hjust = .5),
        plot.caption = element_text(family = f2,
                                    size = 12,
                                    color = "gray45"),
        axis.text = element_blank(),
        plot.margin = margin(20, 10, 10, 10))

ggsave("W13_SpiritConsumption.png",  width = 35, height = 32, units = "cm")
```

