---
title: "Untitled"
author: "Sung Inkyung"
date: '2021 3 1'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(ggtext)
library(glue)
```

### Source[tidytuesday by @jkaupp](https://github.com/jkaupp/tidytuesdays/blob/master/2021/week5/R/analysis.R)
```{r}
hs_students <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-02/hs_students.csv')
```


```{r}
df <- hs_students %>% 
  clean_names() %>% 
  rename(year = total) %>% 
  filter(!is.na(year)) %>%
  mutate(year = if_else(year > 10000, as.numeric(str_sub(year, 1, 4)), year)) %>% 
  select(year, white = white1, black = black1) %>% 
  mutate(across(-year, ~parse_number(as.character(.x))/100)) %>% 
  filter(!is.na(white) & !is.na(black))

df_line <- df %>% 
  pivot_longer(-year)

df_ribbon <- df 

dots <- df_line %>% 
  filter(year %in% range(year))

labels <- dots %>% 
  group_by(year) %>% 
  summarise(diff = max(value) - min(value),
            value = mean(value))

pal <- c("#00a260", "#b99f7b")

plot <- ggplot() +
  geom_ribbon(data = df_ribbon,
              aes(x = year,
                  ymin = black, ymax = white),
              fill = "gray70",
              alpha = .5) +
  geom_line(data = df_line,
            aes(x = year, y = value, color = name),
            size = 2) +
  geom_point(data = dots, 
             aes(x = year, y = value, color = name)) +
  geom_text(data = labels , 
            aes(x = year, y = value, 
                label = scales::percent(diff)),
            nudge_x = c(-2, 2),
            size = 5) +
  scale_x_continuous(limits = c(1935, 2020),
                     breaks = seq(1940, 2010, 10)) +
  scale_y_continuous(limits = c(0, 1),
                     labels = scales::percent) +
  scale_color_manual(values = pal) +
  labs(x = "",
       y = "",
       color = " ",
       title = "Highschool Completion Between <span style = 'color:#00a260'>**Black**</span> and <span style = 'color:#b99f7b'> **White**</span> in USA",
       subtitle = "Aged 25 and over who have graduated high school",
       caption = "Source: Data.World | Graphic: SungInkyung") +
  theme_light() +
  theme(legend.position = "none",
        plot.title = element_markdown(size = 16),
        panel.grid = element_blank())

ggsave(here::here("2021", "week6", "W6_HBCU Enrollment.png"))
  

```

