---
title: "W38 US Government Spending on Kids"
author: "Sung Inkyung"
date: '2020 11 10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source [tidytuesday by Kaustav sen] (https://github.com/kaustavSen/tidytuesday/blob/master/2020/week_38_govt_spending.Rmd)
### Source [tidytuesday by ysamano] (https://github.com/ysamano/TidyTuesday/blob/master/2020/week_46/week_46.R)
```{r}
library(tidyverse)
library(geofacet)
library(ggtext)
library(showtext)

font_add_google("Anton")
font_add_google("Antonio")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)
```


```{r}
kids <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-15/kids.csv')
```


```{r}
kids_pk12ed <- kids %>% 
  filter(variable == "PK12ed")

kids_years <- kids_pk12ed %>% 
  filter(year %in% c(2008, 2016)) %>% 
  select(state, year, inf_adj) %>% 
  pivot_wider(names_from = year, values_from = inf_adj) %>% 
  mutate(diff = if_else(`2008` < `2016`, "gain", "decline"))  

df <- kids_pk12ed %>% 
  left_join(kids_years)
```


```{r}
plot <- df %>% 
  ggplot(aes(year, inf_adj, color = diff, fill = diff)) +
  geom_line(size = .7) +
  geom_area(data = df %>% 
              filter(year <= 2008),
            alpha = .3) +
  geom_area(data = df %>% 
              filter(year >= 2008),
            alpha = .5) +
  scale_fill_manual(values = c("#FF7F41FF", "#79C000FF")) +
  scale_color_manual(values = c("#FF7F41FF", "#79C000FF")) +
  scale_x_continuous(limits = c(1996, 2018), 
                     breaks = c(2000, 2008, 2016)) +
  facet_geo(~state, 
            grid = "us_state_grid2",
            scales = "free_y",
            labeller = label_wrap_gen(width = 5)) +
  labs(x = "",
       y = "",
       title = "US Government Budget on PK12 between 1997 and 2016 by US States", 
       subtitle = "States are divided based on allocation <span style='color:#79C000FF'>gained</span> or <span style='color:#FF7F41FF'>declined</span> between 2008(recession) to 2016.",
       caption = "Data: Urban Institute | **Graphic**: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#EFEFE8FF",
                                       color = "#EFEFE8FF"),
        plot.title = element_text(family = "Anton",
                                  size = 21, 
                                  hjust = .5,
                                  margin = margin(b = 5)),
        plot.subtitle = element_markdown(family = "Antonio",
                                         size = 15,
                                         hjust = .5, 
                                         fill = NA, margin = margin(b = 20)),
        plot.caption = element_markdown(color = "gray65",
                                        family = "Antonio",
                                        size = 8,
                                        hjust = 1),
        strip.text = element_text(color = "gray40",
                                  family = "Antonio",
                                  size = 7),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        plot.margin =  margin(20, 20, 20, 20))

ggsave("W38_GovSpendingonKids.png", width = 25, height = 17, units = "cm")
```


