---
title: "W29 College Major Gender"
author: "sunginkyung"
date: '2019 7 6'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(scales)
library(cowplot)
library(showtext)

font_add_google("Anton")
font_add_google("Saira Condensed")

showtext_opts(dpi = 320)
showtext_auto()

```
### source[UC Business Analytics R Programming Guide](http://uc-r.github.io/cleveland-dot-plots)
```{r}
recent_grads <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-10-16/recent-grads.csv")
```


```{r}
majors_processed <-  recent_grads %>%
  arrange(desc(Total)) %>% 
  mutate(Major = str_to_lower(Major),
         Major = fct_reorder(Major, Median)) %>% 
  filter(Sample_size >= 100) %>% 
  head(20) %>% 
  arrange(desc(Sample_size)) %>% 
  gather(Gender, Number, Men, Women) %>% 
  arrange(Major) %>% 
  mutate(Major = fct_reorder(Major, Total))
  
```


```{r}
#create data frame that identifies number differences over 
num_diff <- majors_processed %>% 
  spread(Gender, Number) %>% 
  group_by(Major) %>% 
  mutate(Max = max(Women, Men),
         Min = min(Women, Men),
         Diff = Max / Min -1) %>% 
  arrange(desc(Diff)) %>% 
  filter(Diff > 1)

right_label <- majors_processed %>%
  group_by(Major) %>%
  arrange(desc(Number)) %>%
  top_n(1)

left_label <- majors_processed %>%
        group_by(Major) %>%
        arrange(desc(Number)) %>%
        slice(2)

right_label <- filter(right_label, Major %in% num_diff$Major)

left_label <- filter(left_label, Major %in% num_diff$Major)

highlight <- filter(majors_processed, 
                    Major%in% num_diff$Major)
```

```{r}
f1 = "Anton"
f2 = "Saira Condensed"


# create a new label data frame
plot_label <- num_diff %>%
        select(Major, Number = Max, Diff) %>%
        right_join(right_label, by = c("Major", "Number"))

p <- ggplot(majors_processed, aes(Number, Major)) +
  geom_line(aes(group = Major), alpha = .6) +
  geom_point(aes(color = Gender), 
                 size = 2, alpha = .6) +
  geom_line(data = highlight, 
            aes(group = Major)) +
  geom_point(data = highlight, 
             aes(color = Gender), size = 3.5) +
  geom_text(data = plot_label, 
            aes(color = Gender, 
               label = paste0("+", scales::percent(round(Diff, 1)))),
            family = f2,
            size = 5, hjust = -.2)+
  scale_color_manual(values = c( "#008080", "#ff73c1")) +
  theme_minimal() +
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.title.x = element_blank())
```

```{r}
p + 
  scale_x_continuous(expand = c(0.02, 0), 
                     limits = c(0, 350000),
                     breaks = seq(0, 350000, 100000),
                     labels = function(x){paste0(x/1000, 'K')}) +
  scale_color_manual(values = c("#008080", "#ff73c1")) +
  scale_y_discrete(expand = c(.02, 0)) +
  labs(x = "",
       y = "",
       title = "Number Difference by College Major and Gender",
       subtitle = "Out of 20 majors by total number with each major, 8 majors show a 100% or greater difference<br>in number generated by <span style = 'color:#008080'>**MEN**</span> versus <span style = 'color:#ff73c1'>**WOMEN**</span>.<br>In particular, majors in nursing and elementary education show a distinctive preferrence for women.",
       caption = "**Source** : 538 | **Graphic**: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none", 
        text = element_text(),
        plot.title = element_text(family = f1,
                                  size = 28,
                                  margin = margin(b = 10)),
        plot.subtitle = element_markdown(color = "darkslategrey",
                                         family = f2,
                                         size = 18,
                                         lineheight = 1.1,
                                        margin = margin(b = 15)),
        plot.caption = element_markdown(color = "#7d7d7d", 
                                        family = f2,
                                        size = 12,
                                        hjust = 0.5,
                                        margin = margin(t = 25)),
        axis.title = element_blank(),
        axis.text.y = element_text(family = f2,
                                    size = 15),
        axis.text.x = element_text(family = f2,
                                    size = 12),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank())

ggsave("W29_CollegeMajorGender.png", width = 32, height = 28, units = "cm")
```
