---
title: "Plastics"
author: "Sung Inkyung"
date: '2021 1 31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(ggalluvial)
library(pals)
```
### Source[Alluvial Plots in ggplot2 by Jason Cory Brunson] (https://cran.r-project.org/web/packages/ggalluvial/vignettes/ggalluvial.html)
### Source[Alluvia across strata] (https://corybrunson.github.io/ggalluvial/reference/geom_alluvium.html)

```{r}
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')

skimr::skim(plastics)

plastics %>% 
  count(parent_company, sort = T)
```


```{r}
df <- plastics %>% 
  filter(!parent_company %in% c("Grand Total", "Unbranded", "null", "Assorted"))%>% 
  mutate(parent_company = ifelse(parent_company == "Nestle", "Nestlé", 
                                 parent_company)) %>% 
  pivot_longer(cols = empty:grand_total,
               names_to = "type",
               values_to = "value",
               values_drop_na = T) %>% 
  filter(value != 0)
```


```{r}
df_company <- df %>% 
  group_by(year, parent_company, type) %>% 
  summarise(total = sum(value),
            n = n()) %>% 
  filter(n > 1) %>% 
  ungroup()

 df_company %>% 
  filter(type == "grand_total") %>% 
  arrange(-total) %>% 
  slice_head(n = 10, order_by = total) %>% 
  ggplot(aes(total, reorder(parent_company, total))) +
  geom_col() +
  facet_wrap(~ year)
 
 df_company %>% 
   filter(type != "grand_total") %>% 
   group_by(year, type) %>% 
   summarise(total = sum(total)) %>% 
   arrange(-total) %>% 
   ggplot(aes(total, reorder(type, total), fill = type)) +
   geom_col() +
   facet_wrap(~year)
 
 df_company %>% 
   filter(type == "pet") %>% 
   arrange(-total) %>% 
   slice_max(n = 10, order_by = total) %>% 
   ggplot(aes(total, reorder(parent_company, total), fill = parent_company)) +
   geom_col() +
   facet_wrap(~ year)
```


```{r}
df_plastic <- df_company %>% 
  mutate(parent_company = case_when(parent_company == "Pepsico" ~ "PepsiCo",
                                    parent_company == "Universal Robina Corporation" ~ "Universal Robina",
                                    TRUE ~ parent_company)) %>% 
  filter(type != "grand_total" & type != "empty") %>% 
  filter(year == 2020) %>% 
  filter(parent_company %in% c(
                              'The Coca-Cola Company',
                              'PepsiCo',
                              'Nestlé',
                              'Pure Water, Inc.',
                              'Universal Robina',
                              'Colgate-Palmolive',
                              'Unilever'
                              )) %>%
  mutate(type = str_to_upper(type))
  
```


```{r}
plot <- df_plastic %>% 
  ggplot(aes(y = total, 
             axis1 = fct_reorder(type, total),
             axis2 = fct_reorder(parent_company, total),
             fill = fct_reorder(type, total))) +
  geom_alluvium(curve_type = "sigmoid") + 
  geom_stratum(width = 1/8, 
               color = "gray45",
               alpha = .75) +
  geom_text(stat = "stratum",
            aes(label = fct_reorder(parent_company, total)),
            size = 5,
            fontface = "bold",
            nudge_x = .01) +
  scale_fill_manual(values = as.vector(cols25(7)),
                    limits = c("PP", "O", "PET",
                               "HDPE", "LDPE", "PS", "PVC"),
                    labels = c("PP", "Other", "PET",
                               "HDPE", "LDPE", "PS", "PVC")) +
  guides(fill = guide_legend(nrow = 1)) +
  labs(title = "Plastic Types by Comapnies With Most Collected in 2020",
       subtitle = "Top 6 companies are selected along with plsastic types collected by volunteers around world<br>in the **Break Free from Plastic** events in 2020",
       caption = "Source:Break Free from Plastic | Graphic: Sung Inkyung",
       fill = "Plastic type") +
  coord_flip() +
  theme_void() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 13),
        legend.key.size = unit(7, "mm"),
        legend.key = element_blank(),
        legend.margin = margin(t = 10),
        plot.title = element_text(size = 24, 
                                  hjust = .5,
                                  margin = margin(b = 5)),
        plot.subtitle = element_markdown(size = 18,
                                         hjust = .5,
                                         margin = margin(b = 15)),
        plot.caption = element_text(size = 13,
                                    color = "gray65",
                                    margin = margin(t = 25)))

ggsave(here::here("2021", "week5", "W5_Plastics.png"), width = 40, height= 30, units = "cm")
  
  
```


