---
title: "US Post Offices"
author: "Sung Inkyung"
date: '2021 4 27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by Charlie Gallagher] (https://github.com/charlie-gallagher/tidy-tuesday/blob/master/postal_service/postal_service.R)
```{r}
library(tidyverse)
library(ggtext)
```


```{r}
post_offices <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-13/post_offices.csv')
```


```{r}
est <- post_offices %>% 
  group_by(established) %>% 
  summarise(n = n()) %>% 
  filter(established > 1700, established < 2020)

discontinued <- post_offices %>% 
  group_by(discontinued) %>% 
  summarise(n = n()) %>% 
  filter(discontinued > 1700, discontinued < 2020)

pos <- full_join(est, discontinued, by = c('established' = 'discontinued'), suffix = c('_est', '_disc')) %>% 
  mutate(n_disc = -n_disc)

pos %>% 
  count(established, sort = T) #1764-2002

pos %>% 
  count(n_est, sort= T) %>% 
  arrange(-n_est) # 4022-1


pos %>% 
  count(-n_disc, sort= T) #4762

df_pos <- pos %>%  
  pivot_longer(cols = c(n_est, n_disc)) %>% 
  ggplot(aes(established, value, fill = name)) +
  geom_col() +
  labs(title = "OPENED AND CLOSED",
       subtitle = "post office per year 1764 2002") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .5),
        plot.subtitle = element_text(hjust = .5))


```


```{r}
pos_text <- tibble(
  text = c('**OPENED and** <span style="color: #efefef">**CLOSED**</span>',
           'US Post offices per year', '1764', '2002', '@inkyscope'),
  x = c(1883, 1883, 1765, 2000, 1995),
  y = c(7300, 6500, 250, 250, -6800),
  color = c('black', 'black', 'black', 'black', '#efefef'),
  size = c(9, 6, 4, 4, 3.5),
  hjust = c(0.5, 0.5, 0, 1, 1)
)
```


```{r}
p <- pos %>% 
  pivot_longer(cols = c(n_est, n_disc)) %>% 
  ggplot() +
  geom_rect(data = tibble(
    xmin = c(1760, 1899),
    xmax = c(2004, 1964.5),
    y = c(-7000, 7000),
    ymax = c(0, 7750)),
    aes(xmin = xmin, xmax = xmax, ymin = y, ymax = ymax),
    fill = "black",
    color = "black") +
  geom_richtext(data = pos_text,
                aes(x = x, y = y, label = text),
                color = pos_text$color, size = pos_text$size,
                hjust = pos_text$hjust,
                fill = NA, label.color = NA, 
                label.padding = grid::unit(rep(0, 4), "pt")) +
  geom_col(aes(x = established, y = value, group = name, fill = name)) +
  scale_fill_manual(values = c("#efefef", "black")) +
  scale_y_continuous(expand = c(0, 0, 0.05, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(1764, 2002)) +
  guides(fill = F) +
  theme_void() +
  theme(plot.background = element_rect(color = NA,
                                       fill = "#efefef"))
   
  ggsave(here::here("2021", "week16", "W16_USPostOffices.png"), width = 15, height = 30, units = "cm")
```
