---
title: "Water Access Points"
author: "Sung Inkyung"
date: '2021 5 17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Sources[tidytuesday live screencast by david robinson] (https://youtu.be/5ub92c-5xFQ)
```{r}
library(tidyverse)
library(lubridate)
library(ggmap)
library(scales)
library(countrycode)
library(ggthemes)
```


```{r}
water <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-04/water.csv')

water %>% 
  count(water_source, sort = T)

water %>% 
  count(install_year, sort = T)

water %>% 
  count(country_name, sort = T)

water %>% 
  count(water_tech, sort = T)

```


```{r}
water_africa <- water %>% 
  mutate(report_date = mdy(report_date)) %>% 
  rename(lat = lat_deg,
         lon = lon_deg,
         country = country_name) %>% 
  separate (water_tech, c("water_tech", "brand"),
            sep = " _ ", fill = "right") %>% 
  mutate(install_year = ifelse(install_year > 2021, NA_real_, install_year)) %>% 
filter(!country %in% c("Peru", "Dominican Republic", "Timor-Lester"),
       !is.na(country)) %>% 
  filter(between(lat, -35, 37),
         between(lon, -40, 60))
  

```


```{r}
water_africa %>% 
  filter(install_year > 1980) %>% 
  count(install_year) %>% 
  ggplot(aes(install_year, n)) +
  geom_col()
```
```{r}
water_africa %>% 
  group_by(country) %>% 
  summarise(lat = mean(lat),
            lon = mean(lon)) %>% 
  ggplot(aes(lon, lat)) +
  geom_point() +
  geom_text(aes(label = country),
            vjust = 1, hjust = 1)
```


```{r}
countries <- unique(water_africa$country) 

df_africa <- map_data("world") %>% 
  as_tibble() %>% 
  mutate(continent = countrycode(region, "country.name", "continent")) %>% 
  filter(continent == "Africa")

```


```{r}
water_africa %>% 
  sample_n(10000) %>% 
  ggplot(aes(lon, lat)) +
  geom_polygon(data = df_africa,
               aes(long, lat, group = group),
               color = "gray",
               fill = "white",
               size = .25) +
  geom_point(size = 1, alpha = .25,
             color = "steelblue") +
  theme_map()


water_uganda <- water_africa %>% 
  filter(country == "Uganda") %>% 
  sample_n(10000) %>% 
  ggplot(aes(lon, lat)) +
  geom_polygon(data = df_africa,
               aes(long, lat, group = group),
               color = "gray",
               fill = "white",
               size = .25) +
  geom_point(size = .7, alpha = .25,
             color = "#9cd3db") 

```


```{r}
df_uganda <- water_africa %>% 
  filter(country == "Uganda",
         between(lat, -3, 5),
         between(lon, 27, 40))
```


```{r}
map_uganda <- df_uganda %>% 
  ggplot(aes(lon, lat, color = status_id)) +
  geom_point(size = .1, alpha = .25) +
  borders("world", regions = "Uganda") +
  scale_color_discrete(guide = guide_legend(override.aes = list(size = 2, alpha = 1)))
```

```{r}
bbox <- c(left = 29.2, bottom = -2, right = 35, top = 4.2)

uganda_map <- get_stamenmap(bbox,
                            zoom = 7,
                            crop = T)
```


```{r}
ws_uganda <- df_uganda %>% 
  mutate(water_source = fct_lump(water_source, 5),
         water_source = fct_reorder(water_source, water_source, length, .desc = T)) %>% 
  replace_na(list(water_source = "Other"))

ws_uganda %>% 
  count(water_source, sort = T)

ggmap(uganda_map) +
  geom_point(data = ws_uganda,
             aes(lon, lat),
             size = .1, alpha = .1,
             color = "#9cd3db") +
  labs(title = "Water Sources in Uganda Since 1991",
       caption = "Source: WPDX | Graphic: Sung Inkyung") +
  facet_wrap(~water_source) +
  theme_map() +
  theme(strip.background = element_rect(fill = "#363b74",
                                        color = "#bbffff"),
        strip.text.x = element_text(size = 11,
                                    color = "#d3a625"),
        plot.title = element_text(size =  24,
                                  color ="#363b74",
                                  hjust = .5,
                                  margin = margin(b = 15)),
        plot.caption = element_text(size = 9,
                                    color = "#363b74",
                                    hjust = 1,
                                    margin = margin(t = 15)))

ggsave(here::here("2021", "week19", "W19_WaterAccessPoints.png"))
```
```{r}
library(gganimate)
```


```{r}
df_uganda %>% 
  filter(!is.na(install_year)) %>% 
  sample_n(10000) %>% 
  mutate(install_year = pmax(1990, install_year)) %>% 
  mutate(year = map(install_year, ~seq(., 2021))) %>% 
  unnest(year) %>% 
  ggplot(aes(lon, lat)) +
  borders("world", regions = "Uganda") +
  geom_point(size = .1, alpha = .25,
             "#9cd3db") +
  theme_map() +
  transition_manual(year) +
  labs(title = "Water Sources in Uganda by year: { current_frame }")
```
```{r}
yr_uganda <- df_uganda %>% 
  filter(!is.na(install_year)) %>% 
  mutate(install_year = pmax(1990, install_year)) %>% 
  mutate(year = map(install_year, ~seq(., 2021))) %>% 
  unnest(year)

ggmap(uganda_map)+
  geom_point(data = yr_uganda,
             aes(lon, lat),
             size = .1, alpha = .25,
             color = "#9cd3db") +
  transition_manual(year) +
  labs(title = "Water Sources in Uganda by Year: { current_frame }")
```

