---
title: "IKEA"
author: "Sung Inkyung"
date: '2020 11 6'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
library(ggtext)
library(showtext)

font_add_google("Anton")
font_add_google("Fira Sans Condensed")
font_add_google("JetBrains Mono")


showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)

```
### Source[tidytuesday by henrywrover] (https://github.com/henrywrover/tidytuesday/blob/master/R/ikea.R)

```{r}
ikea <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-03/ikea.csv')

```

```{r}
ikea_size <- ikea %>% 
  select(-X1) %>%
  filter(!is.na(width),
         !is.na(height)) %>% 
  add_count(category, name = "category_total") %>% 
  mutate(category = fct_reorder(category, category_total))


plot_size <- ikea_size %>% 
  ggplot(aes(x = width, y = height)) +
  geom_rect(aes(xmin = 0, xmax = width, 
                ymin = 0, ymax = height), 
            alpha = 0.1, 
            fill = "#ffda1a",
            color = "#0051ba",
            size = .5) +
  facet_wrap(~category, ncol = 4) +
  #scale_x_continuous(limits = c(0,300)) +
  #scale_y_continuous(limits = c(0,300)) +
  labs(x = "Width (cm)",
       y = "Height (cm)",
       title = "Size Diversity by IKEA Furniture Category",
       caption = "**Source**: Kaggle | **Graphic**: Sung Inkyung") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(family = "Anton",
                                  size = 31,
                                  hjust = 0.5,
                                  margin = margin(b = 20)),
        plot.caption = element_markdown(family = "Fira Sans Condensed",
                                        size = 10),
        strip.text = element_text(family = "JetBrains Mono",
                                  size = 12),
        axis.text = element_text(family = "Fira Sans Condensed",
                                 size = 9),
        axis.title.y = element_text(family = "Fira Sans Condensed",
                                    size = 11,
                                    margin = margin(r = 10)))

ggsave("W45_IKEA.png", width = 38, height = 24, units = "cm")

```

```{r do not run}
ikea_volume <- ikea %>% 
  mutate(volume_m3 = depth * height * width,
         price_usd = price * .27) %>% # price in Saudi Riyals
  filter(!is.na(volume_m3),
         volume_m3 >= 1000000) %>% 
  arrange(desc(volume_m3)) %>% 
  add_count(category, name = "category_total") %>% 
  mutate(category = fct_reorder(category, volume_m3))

plot_volume <- ikea_volume %>% 
  ggplot(aes(x = volume_m3, y = price_usd)) +
  geom_rect(aes(xmin = 0, xmax = volume_m3, ymin = 0, ymax = price_usd), 
            alpha = 0.1, 
            fill = "#ffda1a",
            color = "#0051ba",
            size = .7) +
  facet_wrap(~category, ncol = 4) +
  scale_x_log10() +
  scale_y_continuous(labels = scales::dollar,
                     limits = c(0, 2500),
                     breaks = seq(0, 2500, 500)) +
  labs(x = "Volume (m3)",
       y = "Price",
       title = "Price per Cubic Meter of IKEA Furniture Category",
       caption = "Source: Kaggle | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(family = "Anton",
                                  size = 31),
        plot.caption = element_text(family = "Fira Sans Condensed",
                                    size = 8),
        strip.text = element_text(family = "JetBrains Mono",
                                  size = 12, 
                                  face = "bold"),
        axis.text = element_text(family = "Fira Sans Condensed",
                                 size = 9))
```

