---
title: "Avatar: The Last Airbender"
author: "Sung Inkyung"
date: '2020 8 16 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(paletteer)
library(showtext)
# Avartar Typeface: "Papyrus"

font_add_google("Paprika")
font_add_google("Merriweather")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)

```

### Source[tidytuesday by @ysamano28] (https://github.com/ysamano/TidyTuesday/blob/master/2018/week_12/week_12.R)
```{r}
avatar <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/avatar.csv')
```

```{r}

avatar_character <- avatar %>% 
  filter(character != "Scene Description") %>% 
  mutate(imdb_rating = if_else(book_num == 1 & chapter_num == 20, 9.7, imdb_rating)) %>% 
  select(book, chapter, chapter_num, character, character_words, imdb_rating) %>% 
  group_by(book) %>% 
  mutate(line_num = row_number()) %>% 
  ungroup() %>% 
  unnest_tokens(word, character_words) %>% 
  anti_join(stop_words)

main_character <-  c("Aang", "Katara", "Sokka", "Zuko", "Toph", "Iroh", "Azula")

avatar_words <- avatar_character %>% 
  filter(character %in% main_character) %>% 
  count(book, chapter, chapter_num, character, imdb_rating) %>% 
  add_count(character, wt = n, name = "count") 

```


```{r}
plot_character <- avatar_words %>% 
  mutate(character = factor(character,
                           levels = c("Aang", "Katara", "Sokka", "Zuko", "Toph", "Iroh", "Azula"))) %>% 
  ggplot(aes(chapter_num, character, color = character)) +
  geom_point(aes(size = count), alpha = .7) +
  scale_size_area(max_size = 10) +
  guides(color = F,
         size = guide_legend(title = "Lines \nper Chapter")) +
  scale_color_paletteer_d("khroma::bright") +
 # scale_color_paletteer_d("ggsci::default_jama") +
 # scale_color_paletteer_d("nord::baie_mouton") +
  scale_x_continuous(breaks = seq(1, 21, 1)) +
  labs(title = "Number of Lines Mentioning in Each Chapter by Book Elements",
       subtitle = "Word counts tell that Sokka, Aang and Katara are main characters through all the episodes", 
       caption = "Source: appa | Graphic: Sung Inkyung") +
  facet_wrap(~ book, ncol = 1, scales = "free_y") +
  ggthemes::theme_fivethirtyeight(base_size = 10) +
  theme(legend.title = element_text(size = 8), 
        strip.text.x = element_text(family = "Paprika",
                                    size = 13,
                                    hjust = 0,
                                    face = "bold"),
        plot.title = element_text(family = "Paprika",
                                  size = 18,
                                  hjust = 0.5,
                                  margin = margin(b = 9)),
        plot.subtitle = element_text(family = "Merriweather",
                                  size = 14,
                                  hjust = 0.5,
                                  margin = margin(b = 20)),
        plot.caption = element_text(family = "Merriweather",
                                    size = 8),
        panel.grid.minor = element_blank(), 
        panel.grid.major.y = element_line(colour = "gray60"),
        axis.title = element_blank(), 
        axis.text.y = element_text(family = "Merriweather",
                                   size = 9))

ggsave("W33_Avatar-TheLastAirbender_1.png", width = 28, height = 28, units = "cm")
  
```

