---
title: "W7 DuBois Challenge_Conjugal
author: "Sung Inkyung"
date: '2022 2 25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggforce)
library(ggtext)
library(cowplot)
library(showtext)


font_add_google("Arapey")
font_add_google("Saira Condensed")

showtext_opts(dpi = 300)
showtext_auto()

#plot for conjugal condition
f1 = "Arapey"
f2 = "Saira Condensed"
```


```{r}
# challenge 07
conjugal = read_csv("https://raw.githubusercontent.com/ajstarks/dubois-data-portraits/master/challenge/2022/challenge07/data.csv")

df <- conjugal %>% 
  mutate(Group = case_when(Group == "Over 65" ~ "  Ages. \nOver 65", 
                           TRUE ~ Group),
         Group = fct_inorder(Group)) %>% 
  pivot_longer(!Gender:Group) %>% 
  mutate(value = case_when(Gender == "Male" ~ -1 * value,
                           TRUE ~ value))

df_labs1 <- levels(df$Group)
df_labs2 <- levels(df$Group)

```


```{r}
plot <- df %>% 
  ggplot(aes(x = as.numeric(Group), y = value)) +
  geom_col(aes(fill = factor(name, 
                             levels = c("Widowed", "Married", "Single"))), show.legend = FALSE, width = 1, alpha = 0.95) +
  geom_hline(yintercept = seq(-100, 100, 2), alpha = .1, size = .3) +
  geom_hline(yintercept = seq(-100, 100, 10), alpha = .2, size = .4) + 
  geom_hline(yintercept = 0, alpha = .5, size = .4) +
  geom_vline(xintercept = seq(0.5, 9.5, 1), alpha = .2, size = .4) +
  scale_x_continuous(breaks = 1:length(df_labs1),
                     labels = str_to_upper(df_labs1),
                     sec.axis = dup_axis()) +
  scale_y_continuous(breaks = seq(-100, 100, 10),
                     labels = abs(seq(-100, 100, 10))) +
  scale_fill_manual(values = c("#3D8861", "#CF1A42", "#0058AC")) +
  coord_flip(expand = FALSE, clip = "off") +
  labs(y = "PER CENTS.",
       title = "<span style = 'font-size:17pt'>Conjugal condition of American Negroes according to age periods.</sapn><br><span style = 'font-size: 14pt'>Condition conjugale des Negres Americains au point de vue de l'age.</span><br><span style = 'font-size: 12pt'>Done by Atlanta University.</span><br>",
       caption = "Source: @ajstarks | Graphic: Sung Inkyung | Credit: @leeolney3") +
  annotate(geom = "rect", 
           ymin = -100.2, ymax = 100.2, xmin = 9.5, xmax = 9.7, fill = "#DFD3C2", color = NA) +
  annotate(geom = "text",
         y = c(-50, 50), x = c(9.62, 9.62), label = c("MALES.", "FEMALES."), family = f2, fontface = "bold", size = 5.5) +
  annotate(geom = "text",
           y = c(-38, -55, -93), x = c(1.8, 5.5, 8.5),
           label = c("SINGLE", "MARRIED", "WIDOWED"), angle = c(52, 52, 65), family = f2, fontface = "bold", size = c(7.3, 7.3, 5.3)) +
  annotate(geom = "text",
           y = c(38, 55, 89), x = c(1.8, 5.5, 7.5),
           label = c("SINGLE", "MARRIED", "WIDOWED"), angle = c(-52, -52, -65), family = f2, fontface = "bold", size = c(7.3, 7.3, 5.3)) +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "#DFD3C2", color = NA), 
        plot.title = element_markdown(family = f1,
                                      face = "bold",
                                      hjust = 0.5,
                                      lineheight = 2.7),
        plot.caption = element_text(family = f1,
                                    size = 11,
                                    hjust = 0.5,
                                    margin = margin(t = 20)),
        axis.text.y.left = element_text(family = f2, 
                                            size = 11, 
                                            face = "bold",
                                            vjust = -.97),
        axis.text.y.right = element_text(family = f2, 
                                            size = 11, 
                                            face = "bold",
                                            vjust = -.87),
        axis.text.x = element_text(family = f2, 
                                   size = 11,
                                   face = "bold",
                                   margin = margin(t = 3)),
        axis.title.y = element_blank(),
        axis.title.x = element_text(family = f2, 
                                    size = 11.5,
                                    face = "bold",
                                    margin = margin(t = 5)),
        plot.margin = margin(15, 10, 25, 10))

plot_final <- plot_grid(plot) +
  #add lines between titles
  draw_line(x = c(0.42, 0.58), y = c(0.9, 0.9), size = 0.3, color = "gray60") +
  draw_line(x = c(0.42, 0.58), y = c(0.945, 0.945), size = 0.3, color = "gray60")

ggsave("W7_DuBoisCahllenge_ConjugalConditions.png", width = 25, height = 29, units = "cm")
```

```{r}
#challenge 5
data5 = read_csv("https://raw.githubusercontent.com/ajstarks/dubois-data-portraits/master/challenge/2022/challenge05/data.csv") %>% 
  add_row(Year = 1863, Slave = 97, Free = 3)

df_data5 <- data5 %>% 
  mutate(Free = ifelse( Free == 100.0, "100%", Free),
         Free = ifelse(Free == 1.3, "1.3%", Free)) %>% 
  filter(Year != 1863)
  

plot_data5 <- data5 %>% 
  pivot_longer(Slave:Free) %>% 
  ggplot(aes(Year, value)) +
  geom_area(aes(fill = name), show.legend = FALSE, color = "#DFD3C2") +
  geom_vline(xintercept = df_data5$Year, color = "#DFD3C2") +
  scale_x_reverse(breaks = df_data5$Year,
                  expand = c(0, 0),
                  sec.axis = sec_axis(~. * 1, 
                                      breaks = df_data5$Year, 
                                      labels = df_data5$Free)) +
  scale_y_continuous(position = "right",
                     breaks = c(97, 98, 99, 100),
                     labels = c("3%", "2%", "1%", ""),
                     expand = c(0, 0)) +
  scale_fill_manual(values = c("#D41735", 'black')) +
  labs(title = "SLAVES AND FREE NEGROES.",
       caption = "Source: @ajstarks | Graphic: Sung Inkyung | Credit: @leeolney3") +
  coord_flip(ylim = c(97, 100)) +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "#DFD3C2", color = NA), 
        plot.title = element_markdown(family = f2, size = 34, face = "bold", hjust = 0.5,
                                      margin = margin(b = 68)),
        plot.caption = element_text(family = 2, size = 12, hjust = 0.5,
                                    margin = margin(t = 30)),
        axis.text.y.left = element_text(family = f2, size = 16,
                                        margin = margin(r = 17)),
        axis.text.y.right = element_text(family = f2, size = 16,
                                         margin = margin(l = 17)),
        axis.text.x.top =  element_text(family = f2, size = 14),
        axis.ticks.x.top = element_line(size = .4),
        axis.text.x.bottom = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(20, 60, 20, 60))

p <- plot_grid(plot_data5) +
  draw_text("PERCENT\nOF\nFREE NEGROES", x = .86, y = .895, size = 10, family = f2, lineheight = .8)

ggsave("W7_DuBoisChallenge_FreeNegroes.png", width = 20, height = 31, units = "cm")
```
