---
title: "W30 AustralianPets"
author: "Sung Inkyung"
date: '2020 7 26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(geofacet)
library(showtext)

font_add_google("Prata")
font_add_google("Fira Sans")
font_add_google("Saira")


showtext_opts(dpi = 320)
showtext_auto()
```
### Source:[geofacet package] (https://github.com/hafen/geofacet)

```{r}
animal_outcomes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-21/animal_outcomes.csv')

```


```{r}
df <- animal_outcomes %>% 
  filter(animal_type == "Dogs") %>% 
  select(-Total) %>% 
  pivot_longer(cols = c(ACT, NSW, NT, QLD, SA, TAS, VIC, WA), names_to = "Province", values_to = "Total") %>% 
  filter(between(year, 2000, 2018)) %>% 
  mutate(outcome =fct_collapse(outcome,
                               Euthanized = c("Euthanized"),
                               Reclaimed = c("Reclaimed"),
                               Rehomed = c("Rehomed"),
                               Transferred = c("Transferred"),
                               Others = c("Other", "Currently In Care", "In Stock", "Released"))) %>% 
  group_by(year, Province) %>%
  mutate(pct = Total/sum(Total),
         pct = round(pct, 2)) %>% 
  ungroup() %>% 
  mutate(Province = case_when(
    Province == "ACT" ~ "Australian Capital Territory",
    Province == "NSW" ~ "New South Wales",
    Province == "QLD" ~ "Queensland",
    Province == "WA" ~ "Western Australia",
    Province == "SA" ~ "South Australia",
    Province == "VIC" ~ "Victoria",
    Province == "TAS" ~ "Tasmania",
    TRUE ~ "Western Territory"
  ),
  outcome = factor(outcome,
                   levels = c("Euthanized","Transferred", "Rehomed", "Reclaimed",  "Others")))
```


```{r}
plot <- df %>% 
  ggplot(aes(year, pct, fill = outcome)) +
  geom_col(width = .5) +
  geofacet::facet_geo(~Province, 
                      grid = "aus_grid1",
                      scales = "free_x") +
  scale_x_continuous(breaks = seq(2000, 2018, 3)) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = c("#5a27c1", "#b1c844", "#9b3920", "#e70052", "#d2ab67")) +
  guides(fill = guide_legend(title = "Outcome",
                             title.position = "top",
                             title.hjust = .5,
                             keywidth = 3,
                             keyheight = .5, label.position = "bottom",
                             nrow = 1, 
                             override.aes = list(shape = c(19)))) +
  labs(x = " ",
       y = "",
       title = "Distribution of Dog's Outcome in Australia since 2000",
       subtitle = "Major Outcome category is selected based on cases above 100.\n'Others' outcome include 'Currently In Care', 'In Stock', 'Released' and 'Other'.",
       caption = "Source: RSPCA | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title = element_text(family = "Fira Sans Condensed",
                                    size = 10,
                                    face = "bold"),
        legend.text = element_text(family = "Fira Sans Condensed",
                                   size = 7),
        strip.text = element_text(family = "Saira",
                                  size = 12),
        plot.background = element_rect(fill = "#91a6b4",
                                       colour = NA),
        plot.title = element_text(family = "Prata",
                                  size = 20,
                                  face = "bold"),
        plot.subtitle = element_text(family = "Fira Sans Condensed",
                                     size = 15,
                                     margin = margin(b = 25)),
        panel.grid.major = element_line(color = "#636466",
                                        size = .3),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(family = "Fira Sans Condensed", size = 7),
        axis.text.y = element_text(family = "Fira Sans Condensed", size = 7),
        axis.ticks = element_blank(),
        plot.margin = margin(20, 20, 20, 20))

ggsave("W30_AustralianPets.png", width = 30, height = 24, units = "cm")
  
```

