---
title: "Global Mortality"
author: "Sung Inkyung"
date: '2020 8 17 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggbump)
library(paletteer)
library(showtext)

font_add_google("Roboto Condensed", "Roboto Condensed")
showtext_auto()

extrafont::loadfonts(device = "win")

```


```{r}
global_mort <- read_csv("2018/week_03/global_mortality.csv")

```


```{r}
global_mort_tidy <- global_mort %>% 
  pivot_longer(cols = 4:35, 
               names_to = "cause",
               values_to = "percent") %>% 
  filter(country == "World") %>% 
  group_by(year) %>% 
  mutate(rank = min_rank(desc(percent))) %>% 
  ungroup() %>% 
  mutate(cause = str_remove(cause, "[[:space:]]\\(%\\)"),
         pal = case_when(cause == "HIV/AIDS" ~ "HIV/AIDS",
                         cause == "Parkinson disease" ~ "Parkinson disease",
                         cause == "Dementia" ~ "Dementia",
                         cause == "Diabetes" ~ "Diabetes", 
                         cause == "Conflict"~ "Conflict",
                         cause == "Kidney disease"~ "Kidney disease",
                         cause == "Natural disasters"~ "Natural disasters",
                         TRUE ~ "other")) 

global_mort_tidy_wide <- global_mort_tidy %>%  
  select(year, cause, rank) %>% 
  pivot_wider(names_from = "year", values_from = "rank")
View(global_mort_tidy_wide)
# HIV/AIDS(-8), Parkinson disease(-6), Dimentia(-5), Diabetes(-4), Homicide(-4), Kidney disease(-3), Liver disease(-2), Alcohol disorders(-2)


group_1 <- global_mort_tidy %>% 
  filter(pal == "other")

group_2 <- global_mort_tidy %>% 
  filter(pal != "other")

```

```{r}
plot <- group_1 %>% 
  ggplot(aes(year, rank, group = cause)) +
  geom_bump(size = 1.1,
            alpha = .7,
            color = "gray") +
  geom_point(size = 2, 
             color = "gray") +
  geom_text(data = group_1 %>% 
              filter(year == 1990),
            aes(x = 1989, 
                y = rank,
                label = rank),
            size = 4, 
            hjust = 1, 
            family = "Roboto Condensed") +
  geom_text(data = group_1 %>% 
              filter(year == 2016),
            aes(x = 2016.5, 
                y = rank, 
                label = cause),
            size = 4, 
            hjust = 0,
            family = "Roboto Condensed") +
  geom_bump(data = group_2,
            na.rm = T,
            aes(year, rank, 
                group = cause, 
                color = pal),
            size = 1.3) +
  geom_point(data = group_2,
             na.rm = T,
            aes(year, rank, 
                group = cause, 
                color = pal),
            size = 3) +
  geom_text(data = group_2 %>% 
              filter(year == 1990),
            aes(x = 1989, 
                y = rank,
                label = rank),
            size = 5.5, 
            hjust = 1, 
            family = "Roboto Condensed",
            fontface = "bold") +
  geom_text(data = group_2 %>% 
              filter(year == 2016),
            aes(x = 2016.5, 
                y = rank, 
                label = cause),
            size = 5.5, 
            hjust = 0,
            family = "Roboto Condensed",
            fontface = "bold") +
  paletteer::scale_color_paletteer_d("ghibli::KikiMedium") +
  scale_y_reverse(breaks = 1:32,
                  expand = c(0.01, 0.01)) +
  scale_x_continuous(limits = c( 1989, 2026),
                        breaks = seq(1990, 2016, 2)) +
  labs(x = "",
       y = "",
       title = "Motality Causes by Year",
       subtitle = "Highlighted causes of motatlity shows comparatively fluctuations over years",
       caption = "Source: ourworldindata.org | Graphic: Sung Inkyung") +
  theme_minimal(base_size = 9) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        plot.title = element_text(size = 26,
                                  family = "Roboto Condensed",
                                  face = "bold",
                                  margin = margin(b = 5)),
        plot.subtitle = element_text(size = 18,
                                  family = "Roboto Condensed",
                                  margin = margin(b = 10)),
        plot.caption = element_text(size = 13,
                                    margin = margin(t = 5,
                                                    b = 10)),
        axis.text.y = element_blank())
  
ggsave(here::here("2018", "week_03", "W3_GlobalMortality.png"), width = 20, height = 13, units = "cm")
```

