---
title: "W8 Food Carbon Footprint"
author: "Sung Inkyung"
date: '2020 2 29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggraph)
library(ggforce)
library(glue)
library(colorspace)
library(paletteer)
library(showtext)

font_add_google("Staatliches")
font_add_google("Oxygen")

showtext_opts(dpi = 320)
showtext_auto()
```


```{r}
tuesdata <- tidytuesdayR::tt_load('2020-02-18') 
food_consumption <- tuesdata[[1]]

```


```{r}
category <- food_consumption %>% 
  group_by(food_category) %>% 
  summarise(sum = sum(co2_emmission))
  
pos <- pack_circles(category$sum) %>% 
  as_tibble()

layout <- tibble(x = pos$V1,
                 y = pos$V2,
                 r = sqrt(category$sum/pi))

plot_data <- bind_cols(category, layout)

fill_pal <- colorRampPalette(palettes_d$rcartocolor$TealRose)(571)
color_pal <- darken(colorRampPalette(palettes_d$rcartocolor$ag_Sunset)(571))
```


```{r}
top <- plot_data %>% 
  ungroup() %>% 
  top_n(5) %>% 
  arrange(desc(sum)) 
```


```{r}
set.seed(123)

plot <- ggplot(plot_data) +
  geom_circle(aes(x0 = x, y0 = y, r = r,
                  fill = food_category, color = food_category),
              show.legend = FALSE,
              inherit.aes = FALSE) +
  geom_text(data = top, 
            aes(x = x, y = y,
                label = glue("{str_wrap(food_category, 10)}\n{sum}")), color = "black", size = 3) +
  scale_fill_manual(values = sample(fill_pal, 571))+
  scale_color_manual(values = sample(color_pal, 571)) +
  coord_equal() +
  labs(x = " ", 
       y = " ",
       title = "Top 5 food category Responsible for CO2 Emmission",
       caption = "Source: nu3 | Graphic: Sung Inkyung") +
  theme_void() +
  theme(plot.title = element_text(family = "Staatliches",
                                  size = 20,
                                  hjust = 0.5,
                                  margin = margin(b = 15)),
        plot.caption = element_text(family = "Oxygen",
                                    size = 9,
                                    hjust = 0.5,
                                    margin = margin(t = 25)),
        axis.text = element_blank())

ggsave("W8_FoodCarbonFootprint.png", width = 20, height = 20, units = "cm")
```
