---
title: "FoodCarbonFootprint"
author: "Sung Inkyung"
date: '2020 2 29 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggraph)
library(ggforce)
library(colorspace)
library(paletteer)
library(here)
```


```{r}
tuesdata <- tidytuesdayR::tt_load('2020-02-18') 
food_consumption <- tuesdata[[1]]

food_consumption %>% 
  count(co2_emmission)
```


```{r}
category <- food_consumption %>% 
  group_by(food_category) %>% 
  summarise(sum = sum(co2_emmission))
  

pos <- pack_circles(category$sum) %>% 
  as_tibble()

layout <- tibble(x =  pos$V1,
                 y = pos$V2,
                 r = sqrt(category$sum/pi))

plot_data <- bind_cols(category, layout)

fill_pal <- colorRampPalette(palettes_d$rcartocolor$TealRose)(571)
color_pal <- darken(colorRampPalette(palettes_d$rcartocolor$ag_Sunset)(571))
```


```{r}
top <- plot_data %>% 
  ungroup() %>% 
  top_n(5) %>% 
  arrange(desc(sum)) 
```


```{r}
library(glue)

food <- ggplot(plot_data) +
  geom_circle(aes(x0 = x, y0 = y, r = r,
                  fill = food_category, color = food_category),
              show.legend = FALSE,
              inherit.aes = FALSE) +
  geom_text(data = top, 
            aes(x = x, y = y,
                label = glue("{str_wrap(food_category, 10)}\n{sum}")), color = "black", size = 3) +
  scale_fill_manual(values = sample(fill_pal, 571))+
  scale_color_manual(values = sample(color_pal, 571)) +
  coord_equal() +
  labs(x = " ", 
       y = " ",
       title = "Top 5 food category of CO2 emmission",
       caption = "Source: nu3 | Graphic: Sung Inkyung") +
  theme_void() +
  theme(axis.text = element_blank())

ggsave(here("2020", "W8_FoodCarbonFootprint.png"), width = 11, height = 15, units = "cm")
```

```{r ternary plot}
library(tricolore)
library(ggtern)
```


```{r}
diet <- food_consumption %>% 
  mutate(continent = countrycode::countrycode(country, 
                                              origin = "country.name", 
                                              destination = "continent"),
         category = case_when(food_category %in% c("Wheat and Wheat Products",
                                                   "Soybeans", "Rice", 
                                                   "Nuts inc. Peanut Butter")
                              ~ "Grains",
                              food_category %in% c("Milk - inc. cheese",
                                                   "Eggs") ~ "Dairy_and_Eggs",
                              TRUE ~ "Meat_and_Fish")) %>% 
  group_by(continent, country, category) %>% 
  summarize(co2 = sum(co2_emmission)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = category, values_from = co2)
```


```{r}
tern_plot <- Tricolore(diet, "Dairy_and_Eggs", "Meat_and_Fish",
                       "Grains", breaks = 5, show_data = FALSE)

diet_plot <- diet %>% 
  drop_na() %>% 
  mutate(color = tern_plot$rgb) %>% 
  ggtern(aes(x = Dairy_and_Eggs,
             y = Meat_and_Fish, 
             z = Grains,
             color = color)) +
  geom_point(size = 3) +
  scale_color_identity() +
  facet_wrap(~continent, nrow = 1, scales = "free") +
  labs(x = "Dairy\nEggs",
       y = "Meat and Fish",
       z = "Grains",
    title = "CO2 footprints by food category",
       subtitle = "Discrepancy of each food category is noticeable between continents ",
       caption = "Source: nu3 | Graphic: Sung Inkyung") +
  theme(plot.title = element_text(margin = margin(b = 10),
                                  size = 30,
                                  face = "bold"),
        plot.subtitle = element_text(margin = margin(b = 30),
                                     size = 21),
        plot.caption = element_text(margin = margin(t = 70), size = 14),
        plot.margin = margin(2, 2, 2, 2, "cm"),
        panel.spacing = unit(2, "lines"),
        strip.text = element_text(size = 16),
        axis.title = element_text(size = 5),
        axis.text = element_text(size = rel(1.5))) +
  theme_linedraw()

ggsave(here("2020", "W8_ContinentsFoodCo2.png"), width = 44, height = 16, units = "cm")
```

