---
title: "W16 Best Rap Artists"
author: "Sung Inkyung"
date: '2020 4 19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(packcircles)
library(ggtext)
library(patchwork)
library(showtext)

font_add_google("Rambla")
font_add_google("Playfair Display")

showtext_opts(dpi = 320)
showtext_auto()
```

```{r}
polls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-14/polls.csv')

rankings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-14/rankings.csv')

rankings %>% 
  filter(!is.na(gender),
    gender == "mixed") #m:268, f:23, m:20, total:311
```

```{r}
df <- rankings %>% 
  select(ID, title, artist, year, points, gender) %>% 
  mutate(color = case_when(gender == "male" ~ "#000000",
                           gender == "female" ~ "#b00000", 
                           TRUE ~ "#ebff9a"))

df_circles <- df %>% 
  arrange(year) %>% 
  circleProgressiveLayout(sizecol = "points", 
                          sizetype = "area") %>% 
  mutate(radius = radius * .85)

df_plot <- circleLayoutVertices(df_circles, npoints = 120, 
                                xysizecols = 1:3, 
                                sizetype = c("radius", "area"), 
                                idcol = NULL)

labels_circle <- df %>% 
  arrange(year) %>% 
  select(ID, points) %>% 
  bind_cols(df_circles)

## Source[tidytuesday by @ysamano28] (https://github.com/ysamano/TidyTuesday/blob/master/2020/week_16/week_16_hip_hop.R)
songs <- df %>% 
  mutate(note = str_c(ID, ". ", title, " - ", artist),
         axis_x = rep(1:4, each = 79, length = n()),
         axis_y = rep(79:1, length = n()))

```

```{r}
plot_circles <- ggplot() +
  geom_polygon(data = df_plot,
               aes(x, y, group = id, 
                   fill = factor(id)),
               color = NA) +
  geom_text(data = labels_circle,
            aes(x, y, size = points, label = ID),
            color = "#767cbf",
            family = "Playfair Display",
            fontface = "bold") +
  scale_size_continuous(range = c(1, 6)) +
  scale_fill_manual(values = df$color) +
  coord_equal() +
  theme_void() +
  theme(legend.position = "none")
```

```{r}
plot_songs <- songs[1:20, ] %>% 
  ggplot(aes(axis_x, axis_y)) +
  geom_text(aes(label = note),
            color = "#767c6f",
            family = "Rambla",
            size = 2.5, hjust = 0,
            lineheight = 1.1) +
  xlim(1, 5) +
  scale_y_continuous() +
  theme_void()
```
### Source[patchwork package] (https://patchwork.data-imaginist.com/articles/guides/annotation.html)
```{r}
plot_final <- (plot_circles | plot_songs) +
  plot_layout(widths = c(1, .7)) +
  plot_annotation(title = "The Best Hip-Hop Songs for 40 Years",
       subtitle = "<span style = 'color:#000000'>**Man** rappers: 268 songs</span><br>
       <span style = 'color:#b00000'>**Woman** rappers: 23 songs</span><br>
       <span style = 'color:#ebff9a'>**Mixed bands** rappers: 20 songs</span>",
       caption = "Source: BBC Music | Graphic: Sung Inkyung") &
  theme(plot.background = element_rect(fill = "#d8cdbe",
                                       color = NA),
        plot.title = element_text(color = "#420420",
                                  family = "Rambla",
                                  size = 22, 
                                  face = "bold",
                                  hjust = .5,
                                  margin = margin(t = 20, b = 10)),
        plot.subtitle = element_markdown(color = "white",
                                         family = "Playfair Display",
                                         size = 16, 
                                         lineheight = 1.1,
                                         hjust = .5,
                                         margin = margin(b = 15)),
        plot.caption = element_text(color = "gray45",
                                    family = "Rambla",
                                    size = 7,
                                    hjust = 0.5,
                                    margin = margin(t = 10, b = 10)))

ggsave("W16_BestRapArtists.png", width = 21, height = 16, units = "cm")
```

