---
title: "Untitled"
author: "Sung Inkyung"
date: '2020 8 17 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(countrycode)
```


```{r}
life_expectancy <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-07-03/week14_global_life_expectancy.csv")

life_expectancy <- life_expectancy %>% 
  mutate(continent = countrycode(sourcevar = country,
                                 origin = "country.name",
                                 destination = "continent")) %>% 
  filter(!is.na(continent))

life_expectancy %>% 
  count(year, sort = T) %>% 
  arrange(year)


```
```{r}
library(viridis)

plot_life <- life_expectancy %>% 
  filter(year > 1950) %>% 
  ggplot(aes(code, year, fill = life_expectancy)) +
  geom_tile() +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(1950, 2015, 10),
                     expand = c(0, 0)) +
  scale_fill_viridis(option = "viridis") +
  facet_wrap(~ continent,
             ncol = 1, 
             scales = "free") +
  guides(fill = guide_colorbar(title = "Years",
                               title.position = "top")) +
  labs(x = "",
       y = "",
       title = "Global Life Expectancy from 1950 to 2015",
       caption = "Source: oneworldindata.org | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key.width = unit(3.5, "line"),
        legend.key.height = unit(.7, "line"),
        plot.title = element_text(size = 22,
                                  face = "bold",
                                  margin = margin(b = 18)),
        axis.text.x = element_text(angle = 90, 
                                   vjust = .5, 
                                   size = 6),
        axis.text.y = element_text(size = 7),
        axis.ticks = element_line(color = "gray60"),
        strip.text.x = element_text(size = 12, 
                                    hjust = 0, 
                                    face = "bold"))
  
  ggsave(here::here("2018", "week_14", "W14_GlobalLifeExpectancy.png"), width = 21, height = 27, units = "cm")
```

