---
title: "US dairy consumption"
author: "sung inkyung"
date: '2019 7 19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stars)
library(cowplot)
```

```{r}
milk_products_facts <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/milk_products_facts.csv")
```

```{r}
palette(rainbow(12, s = 0.5, v =0.95))

stars(milk_products_facts[, 2:7],
      labels = milk_products_facts[[1]],
      len = .6, 
      key.loc = c(23, -.5),
      main = "Dairy consumption by year", 
      full = FALSE,
      draw.segments = TRUE,
      frame.plot = TRUE, 
      nrow = 4, 
      cex = 0.7, 
      lwd = 0.25, 
      lty = par("lty"), 
      xpd = FALSE)
```

```{r}
milk_products_gathered <- milk_products_facts %>% 
   gather(product, lbs_per_person, -year) %>% 
   separate(product, c("category", "product"), 
            sep = "_",
            extra = "merge",
            fill = "right") %>% 
   mutate(product = coalesce(product, category),
          product = str_to_title(str_replace_all(product, "_", " ")),
          product = str_replace(product, "American", "American_Cheese"),
          category = str_to_title(category),
          product = ifelse(product == "Other", paste(product, category), product)) 
```

```{r}
product_sorted <- milk_products_gathered %>% 
   filter(product %in% c("Milk", "Yogurt", "Butter", "American_Cheese"),
          lbs_per_person > 0) %>% 
   mutate(product = factor(product, 
                           levels = c("Milk", "Yogurt", "Butter", "American_Cheese")))


p <- product_sorted %>% 
   ggplot(aes(year, lbs_per_person, 
              color = product, 
              fill = product,
              shape = product)) +
   geom_line(size = 0.75) +
   # geom_point(color = "white", size = 2) +
   scale_shape_manual(values = c(21, 22, 23, 24),
                      name = NULL) +
   scale_y_continuous(limits = c(0, 300), 
                      expand = c(0, 0),
                      name = "lbs_per_person") +
   scale_x_continuous(name = "year",
                limits = c(1975, 2017),
                breaks = c(1975, 1985, 1995, 2005, 2015),
                expand = expand_scale(mult = c(0.02, 0))) +
   scale_color_manual(values =  c("#3b5998", "#8d1673", "#088da5", "#ee7b68"),
                      name = NULL) +
   scale_fill_manual(values = c("#3b5998", "#8d1673", "#088da5", "#ee7b68"),
                     name = NULL) + 
   coord_cartesian(clip = "off") +
   theme(legend.title.align = 0.5,
        legend.position = c(0.1, .9),
        legend.just = c(0, 1),
        plot.margin = margin(14, 7, 3, 1.5)) +
   theme_half_open()

p
   
```

```{r}
cheese <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/clean_cheese.csv")
```

```{r}
palette(rainbow(5, s = 0.5, v =0.75))

stars(cheese[, 2:7],
      labels = cheese[[1]],
      len = .6, 
      key.loc = c(23, -.5),
      main = "Cheese consumption in USA between 1970 and 2017", 
      draw.segments = TRUE,
      frame.plot = TRUE, 
      nrow = 4, 
      cex = 0.7, 
      lwd = 0.25, 
      lty = par("lty"), 
      xpd = FALSE)

ggsave("C:/Users/inkyscope/Documents/projectR/dvscope/figures/Cheese consumption in USA.png")

```

```{r}
cheese_gathered <- cheese %>% 
   gather(type, lbs_per_person, -Year) %>% 
   rename(year = Year) %>% 
   mutate(type = str_to_title(type),
          type = fct_recode(type, "Total American Cheese" = "Total American Chese"))


cheese_sorted <- cheese_gathered %>% 
   filter(type %in% c("Cheddar", "Mozzarella", "American Other", "Italian Other", "Swiss", "Brick"),
          lbs_per_person > 0) %>% 
   mutate(type = factor(type,
                        levels = c("Cheddar", "Mozzarella", "American Other", "Italian Other", "Swiss", "Brick")))


p <- cheese_sorted %>% 
   ggplot(aes(year, lbs_per_person, 
              color = type, 
              fill = type,
              shape = type)) +
   geom_line(size = 0.75) +
   # geom_point(color = "white", size = 2) +
   # scale_shape_manual(values = c(21, 22, 23, 24, 25, 26),name = NULL) +
   scale_y_continuous(limits = c(0, 20), 
                      expand = c(0, 0),
                      name = "lbs_per_person") +
   scale_x_continuous(name = "year",
                limits = c(1970, 2017),
                breaks = c(1970, 1980, 1990, 2000, 2010, 2017)) +
   scale_color_manual(values =  c("#3b5998", "#8d1673", "#088da5", "#ee7b68", "#27c96d", "#cc9500"),
                      name = NULL) +
   scale_fill_manual(values = c("#3b5998", "#8d1673", "#088da5", "#ee7b68", "#27c96d", "#cc9500"),
                     name = NULL) + 
   coord_cartesian(clip = "off") +
   theme(
      axis.line.y.right = element_blank(),
      axis.ticks.y.right = element_blank(),
      axis.text.y.right = element_text(margin = margin(0, 0, 0, 0)),
      plot.margin = margin(14, 7, 3, 1.5))+
   theme_half_open()

p

```