---
title: "W5 ACS Census Data(2015)"
author: "Sung Inkyung"
date: '2020 8 20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
library(showtext)

font_add_google("Oswald")
font_add_google("Poppins")

showtext_opts(dpi = 320)
showtext_auto()

```


```{r}
census <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-04-30/week5_acs2015_county_data.csv")
```


```{r}
plot <- census %>% 
  ggplot() +
  geom_density_ridges(aes(IncomePerCap, State),
                      scale = 2,
                      alpha = .9,
                      size = .3,
                      color = "#033f40",
                      fill = "#006766") +
  scale_x_continuous(labels = scales::dollar,
                     n.breaks = 7,
                     expand = c(0.01, 0.01)) +
  labs(x = "",
       y = "",
       title = "US Census 2015",
       subtitle = "Income per Capita by State",
       caption = "Source: cnesus.gov, Kaggle | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "#ebe6d9",
                                       color = NA),
        plot.title = element_text(family = "Oswald",
                                  size = 30,
                                  hjust = .5),
        plot.subtitle = element_text (family = "Poppins",
                                      size = 20,
                                      hjust = .5,
                                      margin = margin(b = 15)),
        plot.caption =  element_text (family = "Poppins",
                                      size = 9,
                                      hjust = .5),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text = element_text(family = "Poppins",
                                 size = 11),
        plot.margin = margin(20, 35, 20, 20))

ggsave("W5_ACS Census Data 2015.png", width = 24, height = 30, units = "cm")
```

