---
title: "Untitled"
author: "Sung Inkyung"
date: '2020 4 12 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
```


```{r}
dog_descriptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-17/dog_descriptions.csv')

```


```{r}
order <- c("Extra Large",
           "Large",
           "Medium",
           "Small")
```


```{r}
dog <- dog_descriptions %>% 
  group_by(age, sex, size) %>% 
  add_count(size) %>% 
  rename(total = n) %>% 
  select(age, sex, size, total)


plot <- dog %>% 
  ggplot(aes(size, total), group = interaction(age, size),
         fill = age, color = age) +
  geom_polygon(aes(group = sex),
               alpha = .01, size = .2, 
               fill = NA)+
  scale_x_discrete(limits = order,
                   labels = c("Extra Large", "Large",
                              "Medium", "Small")) +
  scale_y_continuous(limits = c(0, 7500),
                     breaks = seq(0, 7500, 1500)) +
  scale_color_manual(values = c("#b50aba", "#005180", "#00b903", "#8d5524"),
                     labels = c("Baby", "Young", "Adult", "Senior")) +
  scale_fill_manual(values = c("#b50aba", "#005180", "#00b903", "#8d5524"),
                    labels = c("Baby", "Young", "Adult", "Senior")) +
  coord_polar(clip = "off") +
  theme_minimal() +
  labs(x = "",
       y = "",
       title = "Age and Size of Dog") +
  ylim(0, 7500) +
  geom_polygon(data = . %>%  
               group_by(age, sex, size) %>% 
               summarise_at(c("total"),mean) %>%
               arrange(factor(size, levels = order)) %>%
               ungroup(),
               aes(x = size, y = total, group = sex,
                   fill = age, color = age),
               alpha =.4,
               size = .7
  )

```

```{r}
facet <- dog %>%
  ggplot(aes(size, total,
             group = interaction(age, size),
             fill = age, color = age)) +
  geom_polygon(aes(group = sex),
               size = .2,
               alpha = .03)+ 
  scale_x_discrete(limits = order,
                   labels = c("Extra Large", "Large",
                              "Medium", "Small")) +
  scale_color_manual(values = pal,
                     labels = c("Baby", "Young", "Adult", "Senior")) +
  scale_fill_manual(values = pal,
                    labels = c("Baby", "Young", "Adult", "Senior")) +
  coord_polar(clip="off") +
  theme_minimal() +
  labs(caption = "Source: Petfinder.com via The Pudding  | Graphic: Sung Inkyung")+
  theme(legend.title = element_blank(),
        strip.text = element_blank(),
        axis.title = element_blank(),
        plot.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.caption = element_text(size = 9)) +
  ylim(0, 7500) +
  facet_grid(~age)
```

