---
title: "AmusementParkInjuries"
author: "Tidy Tuesday"
date: '2019 9 16 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(UpSetR)
library(lubridate)
library(cowplot)
```

```{r}
safer_parks <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-10/saferparks.csv")
```
### source[UpSetR package] (https://github.com/hms-dbmi/UpSetR)
### source[tidy tuesday by Christian Burkhart] (https://github.com/ch-bu)
```{r explore UpSetR package}
device <- safer_parks %>% 
  mutate(manufacturer = manufacturer %>% 
      fct_lump(15) %>% 
      fct_infreq) %>% 
  select(acc_id,device_type, manufacturer, mechanical, op_error, employee, num_injured) %>% 
  as.data.frame(device) %>% 
  mutate_all(~replace(., is.na(.), 0))


device  %>% 
 upset(sets = c("mechanical", "op_error", "employee"),
      sets.bar.color = "#56B4E9",
      order.by = "freq", 
      empty.intersections = "on",
      set_size.show = FALSE)
  
```
```{r}
upset(device, attribute.plots = list(gridrows = 100, ncol =1,
                                     plots = list(list(plot = histogram, x = "num_injured", queries = T))),
      sets = c("mechanical", "op_error", "employee"),
      queries = list(list(query = intersects, 
                          params = list("mechanical"),
                          active = T),
                     list(query = intersects, 
                          params = list("op_error"))))
```

```{r root causes of accidents per top 15 device types}
safer_parks_cleaned <- safer_parks %>% 
  mutate(
    date =  mdy(acc_date) %>% as.character,
    year = year(date),
    quarter = quarter(date),
    device_type = device_type %>% 
      fct_lump(15) %>% 
      fct_infreq)
```

```{r}
# Reorder factors levels by first appearance, frequency, or numeric order.
safer_parks_cleaned %>% 
  count(device_type, sort = TRUE) %>% 
  mutate(
    device_type = device_type %>% 
      fct_lump(15) %>% 
      fct_infreq
  ) %>% 
  filter(!is.na(device_type)) %>% 
  ggplot(aes(reorder(device_type, n),n)) +
  geom_col() +
  coord_flip() +
  theme_minimal()

#safer_parks_cleaned %>% 
#  count(device_type, sort = TRUE) %>% 
#  head(20) %>% 
#  ggplot(aes(reorder(device_type, n),n)) +
#  geom_col() +
#  coord_flip()

```

```{r}
safer_parks_cleaned %>% 
  mutate(
    device_type = device_type %>% 
      fct_lump(9) %>% 
      fct_infreq
  ) %>% 
  drop_na(year, device_type) %>% 
  count(year, device_type, sort = TRUE) %>% 
  ggplot(aes(year, n, group = 1)) +
  geom_line() +
  facet_wrap(~ (device_type)) +
  theme_minimal()
```

```{r}
safer_parks_cleaned  %>% 
  count(year, quarter) %>% 
  filter(!is.na(year),
         !year %in% c(2010, 2017)) %>% 
  ggplot(aes(quarter, n)) +
  geom_col()+
  facet_wrap(~ year) +
  theme_minimal()
```

```{r}
nested <- safer_parks_cleaned %>% 
  nest(-device_type) %>% 
  mutate(
  mean_age = data %>% map_dbl(~ mean(.$age_youngest, na.rm = TRUE)),
  injuries = data %>% map_dbl(~ nrow(.)),
  mean_age = round(mean_age, 1)
  ) %>% 
  arrange(desc(injuries))
  
```

```{r}
worst_device <- safer_parks_cleaned %>% 
  count(device_type, sort = TRUE) %>% 
  slice(1:15) %>% 
  {.$device_type}
```

```{r}
device_var <- safer_parks_cleaned %>% 
  select(acc_id, device_type, mechanical, op_error, employee) %>% 
  gather(type, value, -acc_id, -device_type) %>% 
  filter(!is.na(value)) %>% 
  separate_rows(value, sep = " , ") %>% 
  arrange(device_type) %>% 
  count(device_type, type, value, sort = TRUE) %>% 
  mutate(
    device_type = fct_infreq(device_type) %>%
      fct_rev) %>% 
  drop_na(type)
  
```

```{r heatmap}
heatmap <- device_var %>% 
  filter(device_type %in% worst_device) %>% 
  ggplot(aes(x = type, y = device_type)) +
  geom_tile(aes(fill = n), color = "#003366") +
  geom_text(aes(label = n), color = "#490d2f") +
  # coord_flip() +
  theme_minimal() +
  scale_fill_gradient(low = "#f9dfe5", high = "#f53c55") +
  labs(y = "", x = "Root causes of injuries") +
  scale_x_discrete(position = "top") +
  guides(fill = NULL) +
  theme(
    plot.margin = unit(c(1, 0, 0, 1), "cm"),
    axis.title.x = element_text(color = "#003366", 
                                size = 12,
                                hjust = 0),
    axis.text.y = element_text(color = "#0b0816",
                               margin = margin(r = 10)),
    axis.text.x = element_text(color = "#0b0816",
                               margin = margin(b = 10)),
    axis.ticks.x = element_line(color = "#AFAFAF"),
    axis.ticks.y = element_line(color = "#AFAFAF"),
    legend.position = "none"
  ) 

heatmap
```

```{r}
barplot <- safer_parks_cleaned %>% 
  count(device_type, sort = TRUE) %>% 
  slice(1:15) %>% 
  ggplot(aes(reorder(device_type, n), n)) +
  geom_col(aes(fill = n), 
           color = NA,
           show.legend = FALSE) + 
  scale_fill_gradient(low = "#f9dfe5", high = "#f53c55") +
  coord_flip() +
  scale_y_continuous(position = "right")  +
  labs(
    x = "",
    y = "Number of injuries"
  ) +
  guides(
    fill = NULL
  ) +
  theme(
    plot.margin = unit(c(1,1, 1, 0), "cm"),
    axis.text.y = element_blank(),
    axis.title.x = element_text(color = "#003366", 
                                size = 12,
                                hjust = 0),
    axis.text.x = element_text(margin = margin(b = 20),
                               color = "#0b0816"),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_line(color = "#B8C2CC"),
    legend.position = "none",
    legend.box = "horizontal"
  ) +
  theme_minimal()
```

```{r}
title <- ggdraw() +
  draw_label("Root causes of accidents based on the most dangerous device types",
             y = 0.4,
             x = 0.05,
             hjust = 0,
             size = 14,
             color = "#0b0816") 

p <- plot_grid(heatmap, barplot,
               ncol = 2,
               align = "h",
               rel_widths = c(1.5, .7))


plot_grid(title, p, ncol = 1, 
          rel_heights = c(0.2, 1, 0.5)) +
  labs(
    caption = paste0("Source: https://saferparksdata.org/downloads")
  ) +
  theme(
    plot.margin = unit(c(1, 1, 1, 1), "cm"),
    plot.caption = element_text(color = "#808080", 
                                hjust = 1,
                                size = 9)
  )
```

```{r coord diagram}
safer_parks_coord <- safer_parks %>% 
  mutate(
    device_type = device_type %>% 
      fct_lump(9) %>% 
      fct_infreq
  ) %>% 
  drop_na(device_type) %>% 
  group_by(device_type) %>% 
  summarise(n = sum(num_injured)) %>% 
  arrange(desc(n))
```

```{r}

safer_parks_coord <- safer_parks %>% 
  select(acc_date, device_type, num_injured)

safer_parks_coord <- safer_parks_coord %>% 
  separate(acc_date, into = c("month", "day", "year"), sep = "/")

```

```{r}
safer_parks_coord <- safer_parks_coord %>% 
  mutate(month = case_when(
    month == "1" ~ "Jan",
    month == "2" ~ "Feb",
    month == "3" ~ "Mar",
    month == "4" ~ "Apr",
    month == "5" ~ "May",
    month == "6" ~ "Jun",
    month == "7" ~ "Jul",
    month == "8" ~ "Aug",
    month == "9" ~ "Sep",
    month == "10" ~ "Oct",
    month == "11" ~ "Nov",
    month == "12" ~ "Dec"
  )) %>% 
  select(-day)

safer_parks_coord$month <- as.factor(safer_parks_coord$month)
safer_parks_coord$year <- as.numeric(safer_parks_coord$year)

safer_parks_coord <- safer_parks_coord %>% 
  mutate(month = factor(month, 
                        levels = month.abb))


safer_parks_coord %>% 
  filter(!(year %in% c(2010, 2017))) %>% 
  group_by(month, year) %>% 
  summarize(n = sum(num_injured)) %>%
  filter(!is.na(month)) %>% 
  ggplot()+
  geom_col(aes(month, n, fill = n)) +
  coord_polar() +
  facet_wrap(~ year) +
  scale_fill_gradient2() +
  theme_minimal() +
  labs(x = "",
       y = "",
       title = "Monthly park accidents (2010 - 2016)") +
  theme(axis.text.y = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "#fff4b6"),
        axis.text.x = element_text(color = "#490d2f",
                                   size = 7),
        strip.text = element_text(size = 9))
```
