---
title: "CarFuelContributors"
author: "Sung Inkyung"
date: '2019 10 18 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### source[data in detail](https://www.fueleconomy.gov/feg/ws/index.shtml#fuelType1)
```{r}
library(tidyverse)
library(ggrepel)
library(ggtext)
library(ggalt)
library(janitor)
library(scales)
library(here)
```

```{r}
big_epa_cars <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-15/big_epa_cars.csv")
```

```{r}
big_epa_cars %>% 
  clean_names() %>% 
  count(fuel_type1)
```

```{r}
electric_car <- big_epa_cars %>% 
  clean_names() %>% 
  filter(fuel_type1 == "Electricity") %>% 
  group_by(make) %>% 
  select(make, city_e, highway_e) %>% 
  summarise(avg_city = round(mean(city_e, na.rm = TRUE), 1),
            avg_highway = round(mean(highway_e, na.rm = TRUE), 1)) %>% 
  drop_na()

electric_car %>% 
  filter(avg_city == max(avg_city))

electric_car %>% 
  filter(avg_city == min(avg_city))



plot <- electric_car %>% 
  ggplot(aes(avg_city, avg_highway, group= 1,
             label = make)) + 
  geom_text_repel(
    data = filter(electric_car, avg_highway > 47),
    size = 3.5,
    nudge_y = 5.5 ,
    segment.size = 0.2,
    segment.color = "gray50",
    direction = "y"
  ) +
  geom_point(data = electric_car,
             color = ifelse(electric_car$avg_highway >= 47, "red", "black"),
             na.rm = TRUE,
              show.legend = FALSE) +
  geom_hline(yintercept = 46.5, 
             lty = 2, size = 0.7,
             color = "#c0c0c0", 
             na.rm = FALSE,
             show.legend = FALSE) +
  geom_vline(xintercept = 41.9,
             lty = 2, size = 0.7,
             color = "#c0c0c0", 
             na.rm = TRUE,
             show.legend = FALSE) +
  scale_x_continuous(breaks = seq(0, 100, 20)) +
  scale_y_continuous(breaks = seq(0, 100, 20)) +
  labs(x = "City",
       y = "Highway",
       title = "Consumption of Electricity Car",
       subtitle = "Average electricity consumption in kw-hrs/100miles") +
  theme_minimal() +
  theme(panel.grid = element_blank())
  
  plot
```

```{r dumbell plot}
electric_car %>% 
  ggplot(aes(x = avg_city, 
             xend = avg_highway,
             y = reorder(make, avg_city))) +
  geom_dumbbell(color = "#c0c0c0",
               size = 1.5,
               colour_x =  "#800080",
               colour_xend = "#007481") +
  labs(x = "Consumption in kw-hrs/100 miles",
       y = "",
       title = "Electric vehicles in <span style = 'color: #800080'>**city**</span> and <span style = 'color:#007481'>**highway**</span>", 
       subtitle = "GMC electric car is more efficient on <span style = 'color:#007481'>highway</span>, <br>which is different from other electric car makers.",
       caption = "source : fueleconomy.gov") +
  theme_minimal() +
  theme(plot.title = element_markdown(size = 16),
        plot.subtitle = element_markdown(size = 13),
        panel.grid = element_blank(),
        panel.grid.major.y = element_line(size = 0.2, color = "#fff3d9"),
        legend.position = "none") 
 
```

```{r}
top_make <- big_epa_cars %>%
  clean_names() %>% 
  count(make, year) %>% 
  count(make) %>% 
  filter(n == max(n))
 
```

```{r}
library(gghighlight)

top_save <- big_epa_cars %>% 
  clean_names() %>% 
  select(make, year, save = you_save_spend) %>% 
  semi_join(top_make) %>% 
  group_by(year, make) %>% 
  summarise(total_save = mean(save)) %>% 
  group_by(year) %>% 
  mutate(rank = min_rank(desc(total_save))) %>% 
  ungroup()

tol22rainbow= c("#771155", "#AA4488", "#CC99BB", "#114477", "#4477AA", "#77AADD", "#117777", "#44AAAA", "#77CCCC", "#117744", "#008000", "#88CCAA", "#777711", "#AAAA44", "#244C96", "#774411", "#AA7744", "#FFA500", "#771122", "#AA4455", "#DD7788", "#525252")

top_save_plot <- top_save %>%
  sample_frac(1) %>% 
  ggplot() +
  geom_line(aes(year, rank, color = make),
            show.legend = FALSE) +
  gghighlight(unhighlighted_colour = alpha("#b8b8b8"),
              use_direct_label = FALSE) +
  facet_wrap(~make) +
  scale_y_continuous(trans = "reverse", breaks = NULL) +
  scale_color_manual(values = tol22rainbow) +
  expand_limits(x = 2020) +
  labs(x = "",
       y = "",
       title = "Cost saving journey of major automakers",
       subtitle = "Suggesting headwinds and tailwinds against moving upward are displayed among automakers<br>since 1984. <span style='color:#008000'>**Jaguar**</span>, <span style = 'color:#244C96'>**Mercedez-Benz**</span> and <span style='color:#FFA500'>**Porsche**</span> need a bold plan to shift.",
       caption = "source | fueleconomy.gov") +
  theme(panel.background = element_rect(fill = "#c4e2f3"),
        panel.grid.major = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text = element_text(color = "#1c1c39"),
        axis.ticks = element_blank(),
        plot.title = element_markdown(color = "#1c1c39",
                                      size = 20,
                                      margin = margin(b = 5)),
        plot.subtitle = element_markdown(color = "#1c1c39",
                                         size = 15,
                                         margin = margin(b = 15)),
        plot.caption = element_text(color = "#132048",
                                    size = 9,
                                    hjust = 1),
        strip.text = element_text(color = "#132048",
                                  size = 10),
        strip.background = element_rect(fill = "#c4e2f3", color = NA),
        panel.spacing.x = unit(10, "pt"),
        panel.spacing.y = unit(10, "pt"),
        plot.margin = margin(10, 10, 10, 10),
        legend.position = "none")

top_save_plot

ggsave(here("figures", "TopSavingCarJourney.png"), width = 11, height = 9, units = "in")

```
### source[tidy tuesday by jake kaupp](https://github.com/jkaupp/tidytuesdays/blob/master/2019/week42/R/analysis.R)
```{r}
colors <- set_names(grey.colors(22), pull(top_make, make))
colors[["Dodge"]] <- "#390071"
colors[["Porsche"]] <- "#a95292"
colors[["BMW"]] <- "#ea3b52"
colors[["Mazda"]] <- "#39ff14"
colors[["Honda"]] <- "#98f898"
colors[["Volkswagen"]] <- "#c7ea46"
colors[["Ford"]] <- "#ffdb00"
colors[["Lincoln"]] <- "#79f6fc"


rank_plot <-  
  ggplot(top_save, aes(year, rank, color = make)) +
  geom_segment(aes(x =1983,
                   xend = 2021,
                   y = rank, yend = rank),
               color = "#cccccc", alpha = 0.5, size = 0.1) +
  geom_xspline(aes(color = make),
               show.legend = FALSE)+
  geom_point(aes(fill = make), 
             shape = 21, 
             color = "#b9bbb6",
             show.legend = FALSE) +
  geom_richtext(data = filter(top_save, year == 2020), 
                aes(label = make, 
                    x = 2021, color = make), 
                hjust = 0, size = 4, 
                show.legend = FALSE,  
                fill = NA, 
                label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt")) +
  geom_text(data = filter(top_save, year == 1984),
            aes(label = rank, x = 1983),
            hjust = 1,
            size = 3) +
  scale_color_manual(values = colors) +
  scale_fill_manual(values = colors) +
  scale_size_identity() +
  scale_x_continuous(breaks = 1984:2020) +
  scale_y_continuous(trans = "reverse", breaks = NULL) +
  expand_limits(x = 2025)+
  labs(x = "",
       y = "",
       title = "Fuel cost savings journey of major automakers since 1984",
       subtitle = "It appears to be hard to set a default value for the pereference or purpose of car buyers despite of cost saving advantage \nsince it is a challenging task to pull off a desired result.",
       caption = "source | fueleconomy.gov") +
  theme(panel.background = element_rect(fill = "#b9bbb6"),
        panel.grid = element_blank(),
        axis.text = element_text(color = "#1c1c39"),
        plot.title = element_text(color = "#1c1c39",
                                  size = 20,
                                  margin = margin(b = 5)),
        plot.subtitle = element_text(color = "#1c1c39",
                                         size = 15,
                                         margin = margin(b = 15)),
        plot.caption = element_text(color = "#132048",
                                    size = 9,
                                    hjust = 1),
        plot.margin = margin(10, 10, 10, 10),
        legend.position = "none")

rank_plot

ggsave(here("figures", "TopSavingRank.png"), width = 13, height = 10, units = "in")

```
