---
title: "BikeWalkCommutes"
author: "Sung Inkyung"
date: '2020 4 12 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Source[tidytuesday by spren9er] (https://github.com/spren9er/tidytuesday/blob/master/tidytuesday_201945_bike_and_walk_commutes.r)
```{r}
library(tidyverse)
library(geofacet)
library(xkcd) # new package
```

```{r}
commute <-read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-11-05/commute.csv")
```

```{r}
totals <- commute %>% 
  mutate(state_abb = ifelse(state == "District of Columbia", "DC", state_abb)) %>% # count(state_abb, sort = T)
  filter(!is.na(state_abb)) %>% 
  group_by(mode, state, state_abb, city_size) %>% 
  summarise(total = sum(n)) %>% 
  ungroup() %>% 
  mutate(mode = str_to_lower(mode),
         city_size = str_to_lower(city_size))

prop <- totals %>% 
  group_by(state, state_abb, city_size) %>% 
  mutate(total_city_size = sum(total)) %>% 
  group_by(state, state_abb) %>% 
  mutate(total_state = sum(total),
         prc_city_size = total_city_size / total_state,
         prc = total / total_city_size) %>% 
  pivot_wider(names_from = mode, values_from = c(prc, total)) %>% 
  select(state, state_abb, city_size, prc_city_size, prc_walk, prc_bike) %>% 
  arrange(state, state_abb, city_size)

cum_prc <- prop %>% 
  group_by(state, state_abb) %>% 
  mutate(cum_size = cumsum(prc_city_size),
         lag_cum_size = lag(cum_size, default = 0))

cum_prc %>% 
  select(state_abb, city_size) %>% 
  count(city_size, sort = T)
  
```


```{r}
bw_plot <- cum_prc %>% 
  ggplot() +
  xkcdrect(
    data = cum_prc,
    aes(
      xmin = 0, xmax = prc_walk,
      ymin = lag_cum_size, ymax = cum_size,
      fill = paste('walk', city_size, sep = ' | ')
    ), 
    size = 0.1) +
  xkcdrect(
    data = cum_prc,
    aes(
      xmin = prc_walk, xmax = 1,
      ymin = lag_cum_size, ymax = cum_size,
      fill = paste('bike', city_size, sep = ' | ')
    ), 
    size = 0.1) +
  coord_fixed() +
  scale_fill_manual(values = c("#d2c531", "#797e83", "#6250a1",
                               "#663300", "#005180", "#e490a8")) +
  facet_geo(~ state_abb) +
  labs(title = "Walk and Bike Ratios of Commutes in U.S 2008 - 2012",
       caption = "Source: ACS | Graphic: Sung Inkyung") +
  theme_void() +
  theme(
    legend.title = element_blank(),
    strip.background = element_blank(),
    plot.title = element_text( size = 16,
                               hjust = .5,
                               margin = margin(t = 15)),
    plot.subtitle = element_text(size = 11,
                                 hjust = .5,
                                 margin = margin(t = 10, b = 11)),
    plot.caption = element_text(size = 7, 
                                color = "#797e83",
                                margin = margin(t = 5, b = 6)))
```

