---
title: "ChristmasSongs"
author: "Sung Inkyung"
date: '2019 12 26 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Sourse[tidytuesday by julia watzek](https://github.com/jwatzek/tidytuesday/blob/master/scripts/2019-52_xmas_songs.R)
```{r}
library(tidyverse)
library(cowplot)
library(ggimage) # new package
library(here)
```

```{r}
christmas_songs <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-24/christmas_songs.csv")

```

```{r}
songs_2000 <- christmas_songs %>% 
  filter(year >=2000) %>% 
  count(song, year) %>% 
  mutate(song = str_to_title(song)) %>% 
  group_by(song) %>% 
  mutate(n = n_distinct(year)) %>% 
  arrange(desc(year), desc(n))

color_bells <- tibble(
  song = unique(songs_2000$song),
  image = rep(c("C:/Users/inkyscope/Documents/projects/tidytuesday/image/gold_ball.png", "C:/Users/inkyscope/Documents/projects/tidytuesday/image/silver_ball.png"), length.out = length(unique(songs_2000$song)))
)
  
plot_data <- left_join(songs_2000, color_bells) %>% 
  ungroup %>% 
  mutate(song = factor(song, levels = rev(color_bells$song)))

plot_data %>%
  filter(song == "All I Want For Christmas Is You")
```


```{r}
plot <- plot_data %>% 
  ggplot(aes(year, song)) +
  geom_image(aes(image = image), size = 0.03) +
  annotate("text", x = 2001.2, y = 32,
           size = 4,
           hjust = 0,
           color = "#00b32c",
           label= "Song by Mariah Carey made the Top 100 8 times from 2000 - 2017.") +
  annotate("text", x = 2011.7, y = 10,
           size = 4,
           hjust = 0, 
           color = "#b3000c",
           label = "9 Xmas songs made \nthe Billboard Top 100\nin 2011.") +
  geom_curve(x = 2001, xend = 2000.4, y = 32, yend = 32, 
             arrow = arrow(length = unit(0.1, "cm"))) +
  geom_curve(x = 2010, xend = 2010.7, y = 31.7, yend = 31.7, 
             arrow = arrow(length = unit(0.1, "cm"))) +
  geom_curve(x = 2011.5, xend = 2011, y = 11, yend = 13, 
             arrow = arrow(length = unit(0.2, "cm")),
             curvature = -0.3) +
  labs(x = "",
       y = "",
       title = "Christmas Songs in Billboard Top 100",
       subtitle = "Christmas ornaments(green and red) indicate that a song made the Billboard Top 100 in the corresponding year.",
       caption = "Source: Billboard Top 100") +
  theme(
    plot.title = element_text(size = 16,
                              margin = margin(b = 10)),
    plot.subtitle = element_text(size = 13,
                                 margin = margin(b = 25)),
    axis.ticks = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line = element_blank()
    ) +
  theme_minimal_vgrid()


ggsave(here("figures", "ChristmasSongsTop100.png"), width = 35, height =35, units = "cm")
  
```
`

