---
title: "college_majors_cleveland_dot_plot"
author: "sunginkyung"
date: '2019 7 6 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
library(cowplot)
library(here)
```
### source[UC Business Analytics R Programming Guide](http://uc-r.github.io/cleveland-dot-plots)
```{r}
recent_grads <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-10-16/recent-grads.csv")

View(recent_grads)
```

```{r}
skimr::skim(recent_grads)
```

```{r}
majors_processed <-  recent_grads %>%
  arrange(desc(Total)) %>% 
  mutate(Major = str_to_lower(Major),
         Major = fct_reorder(Major, Median)) %>% 
  filter(Sample_size >= 100) %>% 
  head(20) %>% 
  arrange(desc(Sample_size)) %>% 
  gather(Gender, Number, Men, Women) %>% 
  arrange(Major) %>% 
  mutate(Major = fct_reorder(Major, Total))
  
```

```{r}
majors_processed %>% 
  ggplot(aes(Major, Total)) +
  geom_col() +
  expand_limits(y = 0) +
  coord_flip() +
  theme_minimal_vgrid() +
  theme(legend.position = "none") +
  theme_minimal()

majors_processed %>%
 ggplot(aes(Major, Total))+
  geom_point()+
  expand_limits(y = 0)+
  coord_flip()+
  theme(legend.position = "none")

```

```{r}
ggplot(majors_processed, aes(Major, Number, 
                             fill = Gender))+
  geom_bar(stat = "identity")+
  coord_flip()+
  scale_fill_manual(values = c("#008080", "#ff73c1")) +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank()
  )

ggplot(majors_processed, aes(Major, Number, 
                             fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()+
  scale_fill_manual(values = c("#008080", "#ff73c1")) +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank()
  )

ggplot(majors_processed, aes(Major, Number, 
                             fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  facet_wrap(~ Gender)+
  scale_fill_manual(values = c( "#008080", "#ff73c1")) +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank()
  )

ggplot(majors_processed, aes(Number, Major))+
  geom_line(aes(group = Major),
            color = "#d3d3d3",
            size = 1.5) +
  geom_point(aes(color = Gender),
             size = 1.5) +
  scale_x_log10() +
  scale_color_manual(values = c( "#008080", "#ff73c1")) +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    legend.position = "top",
    legend.title = element_blank()
  )

```

```{r}
right_label <- majors_processed %>%
  group_by(Major) %>%
  arrange(desc(Number)) %>%
  top_n(1)

left_label <- majors_processed %>%
        group_by(Major) %>%
        arrange(desc(Number)) %>%
        slice(2)

ggplot(data = majors_processed, 
       aes(Number, Major)) +
  geom_line(aes(group = Major),
            na.rm = TRUE) +
  geom_point(aes(color = Gender), size = 1.5,
             na.rm = TRUE) +
  geom_text(data = right_label, 
            aes(color = Gender, 
                label = round(Number, 0)),
            size = 3, 
            hjust = -.5,
            na.rm = TRUE) +
  geom_text(data = left_label, 
            aes(color = Gender, 
                label = round(Number, 0)),
            size = 3, 
            hjust = 1.5,
            na.rm = TRUE) +
  scale_x_continuous(limits = c(0, 250000),
                     breaks = seq(0, 250000, 50000),
                     labels = function(x){paste0(x/1000, 'K')}) +
  scale_color_manual(values = c( "#008080", "#ff73c1")) +
theme_minimal_vgrid() +
  theme(
    axis.title.y = element_text(size = 4),
    axis.title.x = element_blank(),
    legend.position = "top",
    legend.title = element_blank()
  )

```

```{r}
#create data frame that identifies number differences over 
num_diff <- majors_processed %>% 
  spread(Gender, Number) %>% 
  group_by(Major) %>% 
  mutate(Max = max(Women, Men),
         Min = min(Women, Men),
         Diff = Max / Min -1) %>% 
  arrange(desc(Diff)) %>% 
  filter(Diff > 1)

right_label <- filter(right_label, Major %in% num_diff$Major)
left_label <- filter(left_label, Major %in% num_diff$Major)

highlight <- filter(majors_processed, 
                    Major%in% num_diff$Major)

ggplot(majors_processed, 
       aes(Number, Major)) +
  geom_line(aes(group = Major), 
            alpha = .3,
            na.rm = TRUE) +
  geom_point(aes(color = Gender), 
             size = 1.5, 
             alpha = .3,
             na.rm = TRUE)+
  geom_line(data = highlight, 
            aes(group = Major),
            na.rm = TRUE)+
  geom_point(data = highlight, 
             aes(color = Gender), 
             size = 2,
             na.rm = TRUE)+
  geom_text(data = right_label, 
            aes(color = Gender, label = round(Median, 0)), 
            size = 3, 
            hjust = -.2,
            na.rm = TRUE) +
  geom_text(data = left_label, aes(color = Gender, 
                                   label = round(Median, 0)), 
            size = 3, 
            hjust = 1.2,
            na.rm = TRUE) +
  scale_color_manual(values = c( "#008080", "#ff73c1")) +
  scale_x_continuous(limits = c(1000, 300000))+
  expand_limits(y = 0) +
  theme_minimal_vgrid() +
  theme(
    axis.title.y = element_text(size = 4),
    axis.title.x = element_blank(),
    legend.position = "top",
    legend.title = element_blank(),
  )
```

```{r}
# create a new label data frame
plot_label <- num_diff %>%
        select(Major, Number = Max, Diff) %>%
        right_join(right_label, by = c("Major", "Number"))

p <- ggplot(majors_processed, aes(Number, Major)) +
        geom_line(aes(group = Major), alpha = .3) +
        geom_point(aes(color = Gender), 
                   size = 1.5, alpha = .3) +
        geom_line(data = highlight, 
                  aes(group = Major)) +
        geom_point(data = highlight, 
                   aes(color = Gender), size = 2) +
        geom_text(data = plot_label, 
                  aes(color = Gender, 
                      label = paste0("+", scales::percent(round(Diff, 2)))),
                  size = 3, hjust = -.2)+
  scale_color_manual(values = c( "#008080", "#ff73c1")) +
  theme_minimal() +
  theme(
    axis.title.y = element_text(size = 4),
    axis.title.x = element_blank(),
    legend.position = "top",
    legend.title = element_blank(),
  )

p
```

```{r}
p + 
  scale_x_continuous(
                     expand = c(0.02, 0), 
                     limits = c(0, 350000),
                     breaks = seq(0, 350000, 100000),
                     labels = function(x){paste0(x/1000, 'K')}
                     ) +
  scale_color_manual(values = c( "#008080", "#ff73c1")) +
  scale_y_discrete(expand = c(.02, 0)) +
  labs(title = "Number Difference by College Major and Gender",
       subtitle = "Out of 20 majors by total number with each major, 8 majors show \na 100% or greater difference in number generated by men versus \nwomen.In particular, majors in nursing and elementary education \nshow a distinctive preferrence.",
       caption = "source : 538") +
        theme_minimal() +
        theme(
          axis.title = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor = element_blank(),
          legend.title = element_blank(),
          legend.justification = c(0, 1), 
          legend.position = c(.1, 1.09),
          legend.background = element_blank(),
          legend.direction="horizontal", 
          text = element_text(),
          plot.title = element_text(size = 14, 
                                    margin = margin(b = 10)),
          plot.subtitle = element_text(size = 11,
                                       color = "darkslategrey", 
                                       margin = margin(b = 25)),
          plot.caption = element_text(size = 8,
                                      margin = margin(t = 10),
                                      color = "#7d7d7d", 
                                      hjust = 1))
```
