---
title: "dearabby_word_pairs"
author: "sung inkyung"
date: '2019 7 16 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(cowplot)
library(widyr)
library(ggraph)
library(igraph)
```
### sources: https://pudding.cool/2018/11/dearabby/,                                                     https://github.com/the-pudding/data/tree/master/dearabby
```{r}
dearabby <- readr::read_csv("https://raw.githubusercontent.com/the-pudding/data/master/dearabby/raw_da_qs.csv") 
```
### source: https://www.tidytextmining.com/ngrams.html
```{r}
dearabby_bigrams <- dearabby %>% 
  mutate(wordid = row_number(),
         question = question_only) %>% 
  select(letterId, question) %>% 
  unnest_tokens(bigram, "question", token = "ngrams", n= 2) 

dearabby_bigrams
```

```{r}
dearabby_bigrams %>% 
  count(bigram, sort = TRUE)
```

```{r}
bigrams_separated <- dearabby_bigrams %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts
bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)

bigram_counts
```

```{r}
bigrams_united <- bigrams_filtered %>%
  unite(bigram, word1, word2, sep = " ")

bigrams_united
```

```{r}
# trigram
dearabby_triigrams <- dearabby %>% 
  mutate(question = question_only) %>% 
  select(letterId, question) %>%
  unnest_tokens(trigram, "question", token = "ngrams", n = 3) %>%
  separate(trigram, c("word1", "word2", "word3"), sep = " ") %>%
  filter(!word1 %in% stop_words$word,
         !word2 %in% stop_words$word,
         !word3 %in% stop_words$word) %>%
  count(word1, word2, word3, sort = TRUE)

dearabby_triigrams
```

```{r}
bigrams_filtered %>%
  filter(word2 == "bad") %>%
  count(word2, word1, sort = TRUE)
```

```{r}
bigram_tf_idf <- bigrams_united %>%
  mutate(id = row_number()) %>% 
  count(id, bigram) %>%
  bind_tf_idf(bigram, id, n) %>%
  arrange(desc(tf_idf))

bigram_tf_idf 
```

```{r}
bigram_tf_idf %>% 
  filter(tf_idf > 10) %>% 
  head(20) 
```

```{r}
# Sentiment analysis

bigrams_separated %>%
  filter(word1 == "not") %>%
  count(word1, word2, sort = TRUE)
```

```{r}
AFINN <- get_sentiments("afinn")

AFINN
```

```{r}
not_words <- bigrams_separated %>%
  filter(word1 == "not") %>%
  inner_join(AFINN, by = c(word2 = "word")) %>%
  count(word2, score, sort = TRUE)

not_words
```

```{r}
not_words %>%
  mutate(contribution = n * score) %>%
  arrange(desc(abs(contribution))) %>%
  head(25) %>%
  mutate(word2 = reorder(word2, contribution)) %>% 
  ggplot(aes(word2, n * score, fill = n * score > 0)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c("#f15e75", "#27c96d")) +
  xlab("Words preceded by \"not\"") +
  ylab("Sentiment score * number of occurrences") +
  coord_flip() +
  theme_minimal()
```

```{r}
negation_words <- c("not", "no", "never", "without")

negated_words <- bigrams_separated %>%
  filter(word1 %in% negation_words) %>%
  inner_join(AFINN, by = c(word2 = "word")) %>%
  count(word1, word2, score, sort = TRUE)
```

```{r}
no_words <- bigrams_separated %>%
  filter(word1 == "no") %>%
  inner_join(AFINN, by = c(word2 = "word")) %>%
  count(word2, score, sort = TRUE)

no_words
```

```{r}
no_words %>%
  mutate(contribution = n * score) %>%
  arrange(desc(abs(contribution))) %>%
  head(25) %>%
  mutate(word2 = reorder(word2, contribution)) %>% 
  ggplot(aes(word2, n * score, fill = n * score > 0)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c("#f15e75", "#27c96d")) +
  xlab("Words preceded by \"no\"") +
  ylab("Sentiment score * number of occurrences") +
  coord_flip()+
  theme_minimal()
```

```{r}
never_words <- bigrams_separated %>%
  filter(word1 == "never") %>%
  inner_join(AFINN, by = c(word2 = "word")) %>%
  count(word2, score, sort = TRUE)

never_words
```

```{r}
never_words %>%
  mutate(contribution = n * score) %>%
  arrange(desc(abs(contribution))) %>%
  head(25) %>%
  mutate(word2 = reorder(word2, contribution)) %>% 
  ggplot(aes(word2, n * score, fill = n * score > 0)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c("#f15e75", "#27c96d")) +
  xlab("Words preceded by \"never\"") +
  ylab("Sentiment score * number of occurrences") +
  coord_flip() +
  theme_minimal()
```

```{r}
without_words <- bigrams_separated %>%
  filter(word1 == "without") %>%
  inner_join(AFINN, by = c(word2 = "word")) %>%
  count(word2, score, sort = TRUE)

without_words
```

```{r}
without_words %>%
  mutate(contribution = n * score) %>%
  arrange(desc(abs(contribution))) %>%
  head(20) %>%
  mutate(word2 = reorder(word2, contribution)) %>% 
  ggplot(aes(word2, n * score, fill = n * score > 0)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c("#f15e75", "#27c96d")) +
  xlab("Words preceded by \"without\"") +
  ylab("Sentiment score * number of occurrences") +
  coord_flip()+
  theme_minimal()
```

```{r}
# Visualizing a network of bigrams with ggraph
# original counts

bigram_counts       
```

```{r}
# filter for only relatively common combinations

bigram_graph <- bigram_counts %>%
  filter(n > 50) %>%
  graph_from_data_frame() %>% 
  ggraph()+
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), 
                 check_overlap = TRUE,
                 vjust = 1, 
                 hjust = 1) +
  theme_void()+ 
  labs(title = "Common bigrams in questions of Dear Abby")

bigram_graph
```

```{r}
set.seed(2019)

a <- grid::arrow(type = "closed", 
                 length = unit(.05, "inches"))

bigram_graph <- bigram_counts %>%
  filter(n > 50) %>%
  graph_from_data_frame() %>% 
  ggraph() +
  geom_edge_link(aes(edge_alpha = n), 
                 show.legend = FALSE,
                 arrow = a, 
                 end_cap = circle(.09, 'inches')) +
  geom_node_point(color = "#6297E770", size = 3) +
  geom_node_text(aes(label = name), 
                 check_overlap = TRUE,
                 vjust = 1, 
                 hjust = 1) +
  theme_void()
  
bigram_graph
```

```{r}
# Counting and correlating pairs of words
dearabby_words <- dearabby %>%
  mutate(id = row_number()) %>% 
  select(id, question_only) %>% 
  unnest_tokens(word, question_only) %>%
  filter(!word %in% stop_words$word) 

dearabby_words
```

```{r}
# count words co-occuring within sections

dearabby_wordpairs <- dearabby_words %>% 
  pairwise_count(word, id, sort = TRUE) %>% 
  head(20)
```

```{r}
dearabby_wordpairs %>% 
  filter(item1 == "time")
```

```{r}
# Pairwise correlation

dearabby_wordcors <-  dearabby_words %>%
  group_by(word) %>%
  filter(n() >= 1000) %>%
  pairwise_cor(word,id, sort = TRUE)

dearabby_wordcors
```

```{r}
dearabby_wordcors %>%
  filter(item1 == "love")
```

```{r}
dearabby_wordcors %>%
  filter(item1 %in% c("love", "time", "money", "relationship")) %>%
  group_by(item1) %>%
  top_n(8) %>%
  ungroup() %>%
  mutate(item2 = reorder(item2, correlation)) %>%
  ggplot(aes(item2, correlation)) +
  geom_bar(stat = "identity", fill = "#6297E770") +
  facet_wrap(~ item1, scales = "free") +
  coord_flip() +
  theme_minimal_vgrid()
```

```{r}
set.seed (2019)         

dearabby_wordcors %>%
  filter(correlation > .15) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), show.legend = FALSE) +
  geom_node_point(color = "#6297E770", size = 5) +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void()
```
