---
title: "Economist Remake"
author: "Sung Inkyung"
date: '2019 6 26 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(scales)
library(ggrepel)
library(cowplot)
```

```{r}
brexit <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-16/brexit.csv")

```
### source[original article] (https://medium.economist.com/mistakes-weve-drawn-a-few-8cdd8a42d368)
### source[tidy tuesday by Anastasia Kuprina] (https://github.com/kuprinaga/tidytuesday-economist-remakes/blob/master/brexit_remake.R)

```{r}
brexit_processed <- brexit %>% 
  rename(right = percent_responding_right,
         wrong = percent_responding_wrong) %>% 
  gather(response, prc, -date) %>% 
  mutate(date = dmy(date)) %>% 
  select(date, response, prc) %>% 
  arrange(date) %>% 
  group_by(response) %>% 
  mutate(rank = rank(desc(date), ties.method = "first"),
         vote = if_else(rank == 10, response, NA_character_))

brexit_plot <- brexit_processed %>% 
  ggplot(aes(date, prc, color = response)) +
  geom_smooth(method = "loess",
              fill = "#F1E0B6") +
  geom_point(alpha = 0.3) +
  geom_jitter(stat = "identity",
              alpha = 0.3) +
  geom_label_repel(data = brexit_processed,
                   aes(label = vote), 
                   nudge_x = 1,
                   na.rm = TRUE) +
  coord_cartesian(ylim = c(38, max(brexit_processed$prc))) +
  scale_x_date(date_breaks = "4 months",
               date_labels = "%b '%y") +
  scale_y_continuous(position = "right",
                     breaks = c(seq(38, 48, 2)),
                     labels = number_format(accuracy = 1,
                                            suffix = "%")) +
  scale_color_manual(values = c("#BAB6B2", "#CA3433")) +
  labs(title = "Bremorse",
       subtitle = "In hindsight, do you think Britain was right or wrong to vote to leave the EU?",
       x = " ",
       y = "responded") +
  theme(axis.text = element_text(size = 9),
        axis.text.y = element_text(hjust = 1),
        axis.title.x = element_blank(),
        axis.ticks.length = unit(5, "pt"),
        legend.position = "none",
        panel.grid.major.y = element_line(color = "grey70",
                                          size = 0.4)) +
  theme_classic()

brexit_plot <- 
  add_sub(brexit_plot,
        "Source: NatCen Social Research", 
        x = 0.8, hjust = 0,
        size = 10)
  
ggdraw(brexit_plot)

```

