---
title: "GlaobalPlasticWastes"
author: "Sung inkyung"
date: '2019 6 25 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(skimr)
library(countrycode)
library(plotly)
library(scales)
library(sf)
library(maptools)
library(cartogram)
library(ggthemes)
library(cowplot)
library(patchwork)
library(here)
```
### sources:[Tidy Tuesday by David Robinson_ Screencast](https://youtu.be/BRdLOYtJk9o)
### source;[tidy tuesday by carsten stann](https://github.com/carstenstann/TidyTuesday/blob/master/2019/2019_21_PlasticWaste.R)
```{r}
plastic_coast <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv") 

mismanaged_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv") 

waste_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-plastic-waste-vs-gdp-per-capita.csv")
```

```{r}
plastic_coast <-  
  clean_names(plastic_coast)
mismanaged_gdp <- 
  clean_names(mismanaged_gdp)
waste_gdp <- 
  clean_names(waste_gdp)


plastic_coast %>% 
  filter(!is.na(coastal_population)) %>% 
  skim()

mismanaged_gdp %>% 
  filter(!is.na(per_capita_mismanaged_plastic_waste_kilograms_per_person_per_day)) %>% 
   skim()

waste_gdp %>% 
  filter(!is.na(per_capita_plastic_waste_kilograms_per_person_per_day)) %>% 
  skim()


plastic_coast %>% 
  clean_names() %>% 
  summarize_all(~mean(is.na(.)))

plastic_coast %>% 
  clean_names() %>% 
  filter(!is.na(coastal_population)) %>% 
  count(year)
 
plastic_coast_2010 <- plastic_coast %>% 
   clean_names() %>% 
   filter(!is.na(coastal_population)) %>% 
   select(-year)
 

mismanaged_gdp %>% 
   clean_names() %>% 
   colnames()

waste_gdp %>% 
  clean_names() %>% 
  colnames()
```

```{r join data}

clean_dataset <-  function(tbl) {
  tbl %>%
    clean_names() %>% 
    rename(country = entity,
           code = code,
           year = year) %>% 
    filter(year == 2010) %>% 
    select(-year)
}

plastic_waste <- plastic_coast %>% 
  clean_dataset() %>% 
  select(-total_population_gapminder) %>% 
  inner_join(clean_dataset(mismanaged_gdp) %>% 
             select(-total_population_gapminder),
             by = c("country", "code")) %>% 
  inner_join(clean_dataset(waste_gdp), 
             by = c("country", "code")) %>%   
  select(country,
         code,
         mismanaged_waste = mismanaged_plastic_waste_tonnes,
         coastal_pop = coastal_population,
         total_pop = total_population_gapminder,
         mismanaged_pc = per_capita_mismanaged_plastic_waste_kilograms_per_person_per_day,
         gdp_pc = gdp_per_capita_ppp_constant_2011_international_rate,
         waste_pc = per_capita_plastic_waste_kilograms_per_person_per_day) %>% 
  drop_na()
```

```{r}
View(plastic_waste)
```

```{r add continent}
waste <- plastic_waste %>%
   mutate(
      gdp = gdp_pc * total_pop,
      continent1 = countrycode(country, 
                               origin = "country.name", 
                               destination = "continent", 
                               warn = FALSE),
      continent2 = countrycode(code, 
                               origin = "iso3c", 
                               destination = "continent", 
                               warn = FALSE),
      Continent = coalesce(continent1, continent2),
      continent1 = NULL,
      continent2 = NULL,
      total_plastic_waste = waste_pc  * total_pop, # kg/per day
      total_mismanaged_plastic = mismanaged_pc * total_pop # kg/per day
      )

glimpse(waste)
```

```{r}
p <- plastic_waste %>% 
     filter(total_pop >= 1e6) %>% 
     arrange(-total_pop) %>% 
     ggplot(aes(gdp_pc, mismanaged_pc)) +
     geom_point(aes(size = total_pop,
                    color = total_pop),
                show.legend = FALSE,
                na.rm = TRUE) +
     geom_text(aes(label = country), 
               vjust = 1, 
               check_overlap = TRUE,
               na.rm = TRUE)+
     scale_x_log10(labels = dollar_format()) +
     scale_y_log10() +
     labs(x = "GDP per capita",
          y = "Mismanaged plastic waste\nkg per person per day")

# p <- ggplotly(p)

p
```

```{r bar plots}

p1 <- plastic_waste %>% 
   top_n(20, mismanaged_pc) %>% 
   ggplot(aes(fct_reorder(country, mismanaged_pc), mismanaged_pc)) + 
   geom_col(color = "white",
            fill = "#413413",
            width = 1) + 
   geom_text(aes(label = round(mismanaged_pc, 2)), 
             nudge_y = -.01, 
             nudge_x = .09,
             color = "white",
             size = 2.5,
             na.rm = TRUE) +
   coord_flip() +
   scale_y_continuous(expand = c(0, 0), 
                      limits = c(0, 0.3), 
                      breaks = seq(0, 0.3, by = 0.1)) +
   theme(axis.ticks = element_blank(),
         axis.text.x = element_text(size = 7),
         axis.text.y = element_text(size = 7),
         axis.title.x = element_text(size = 7),
         plot.background = element_rect(fill = NA),
         plot.margin = margin(12, 12, 12, 12)) +
   theme_half_open(12) +
   labs(x = NULL, 
        y = "Mismanaged plastic waste per capita (kg)")

p2 <-  plastic_waste %>% 
  top_n(20, waste_pc) %>% 
  ggplot(aes(fct_reorder(country, waste_pc), waste_pc)) + 
  geom_col(color = "white",
           fill = "#413413",
           width = 1) +
  geom_text(aes(label = round(waste_pc, 2)), 
             nudge_y = .15, 
             size = 2.5,
             color = "#0f4d6f",
             na.rm = TRUE) +
  coord_flip() +
  scale_y_continuous(expand = c(0, 0), 
                     limits = c(0, 4), 
                     breaks = seq(0, 4, by = 1)) +
  theme(axis.ticks = element_blank(),
        axis.text.x = element_text(size = 7),
        axis.text.y = element_text(size = 7),
        axis.title.x = element_text(size = 7),
        plot.background = element_rect(fill = NA),
        plot.margin = margin(12, 12, 12, 12)) +
  theme_half_open(12) +
  labs(x = NULL, 
       y = "Plastic waste per capita (kg)")

cowplot::plot_grid(p1, p2, nrow = 1)
```

```{r lollipop plot}

p <- plastic_waste %>% 
   top_n(20, mismanaged_pc) %>% 
   mutate(country = fct_reorder(country, mismanaged_pc)) %>% 
   ggplot(aes(mismanaged_pc, country, 
              label = round(mismanaged_pc, 2))) + 
   geom_segment(aes(x= 0, y = country,
                    xend = mismanaged_pc,
                    yend = country),
                color = "grey50") + 
   geom_point(size = 7,
              color = "#413413")+
   geom_text(size = 2.5,
             color = "white",
             na.rm = TRUE) +
   scale_x_continuous(expand = c(0, 0), 
                      limits = c(0, 0.35), 
                      breaks = seq(0, 0.35, by = 0.1)) +
   theme(axis.ticks = element_blank(),
         axis.text.x = element_text(size = 7),
         axis.text.y = element_text(size = 7),
         axis.title.x = element_text(size = 7)) +
   theme_minimal_vgrid() +
   labs(x = "Mismanaged plastic waste per capita(kg/day)", 
        y = NULL)
p

```
```{r}
waste %>% 
  colnames()

view(waste)
```

```{r}
waste %>% 
  filter(Continent == "Asia") %>% 
  summarize(med = median(gdp_pc))

waste %>% 
  filter(Continent == "Americas") %>% 
  summarize(med = median(gdp_pc))

waste %>% 
  filter(Continent == "Europe") %>% 
  summarize(med = median(gdp_pc))

waste %>% 
  filter(Continent == "Oceania") %>% 
  summarize(med = median(gdp_pc))

waste %>% 
  filter(Continent == "Africa") %>% 
  summarize(med = median(gdp_pc))

```

```{r}
gdp_plot <- waste %>% 
  mutate(prop_mis = mismanaged_pc / waste_pc,
                prop_mis = round(prop_mis, 2),
         gdp_cut = cut(gdp_pc, 
                       breaks = c(17942.83, 13605.93, 28678.37, 4984.194, 2994.61))) %>% 
  drop_na()%>% 
  ggplot(aes(Continent, prop_mis, color = gdp_cut)) +
  geom_boxplot(fill = "white") +
  geom_point(na.rm = TRUE) +
  geom_jitter(width = 0.3, 
              alpha = 0.3,
              na.rm = TRUE) +
  labs(
    x = NULL,
    y = "Percent of mismanaged plastic waste per capita",
    title = "Correlation of gdp per capita and\nmismanaged plastic wastes by continents",
    color = "GDP per captia (percentile)"
  ) +
  scale_color_calc(labels = c("25th",
                              "50th",
                              "75th",
                              "100th")) +
  theme_half_open(12) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 13))

gdp_plot 

```

```{r joint plots}

p1 <- waste %>% 
  arrange(-total_pop) %>% 
  ggplot(aes(gdp_pc, waste_pc * 365,
             label = country)) +
  geom_point(aes(size = mismanaged_waste,
                 color = Continent),
             show.legend = FALSE) +
  stat_smooth(geom = "line",
              color = "dodgerblue",
              alpha =0.9,
              method = "lm",
              show.legend = FALSE) +
  geom_smooth(method = "lm", 
              color = NA,
              alpha = 0.3,
              show.legend = FALSE) +
  geom_text(size = 2.5,
            vjust = 1, 
            check_overlap = TRUE,
            na.rm = TRUE)+
  scale_x_log10(labels = dollar_format())+
  scale_y_log10() +
  theme_half_open(12) +
  guides(col = guide_legend(override.aes = list(size = 2.5)),
          size = guide_legend(override.aes = list())) +
  labs(x = "GDP per capita",
       y = "Total plastic waste per capita \n(kg/year)",
       title = "Total plastic waste per capita in 2010",
       subtitle = "Size represents mismanaged plastic waste(tons)")

p1


p2 <- waste %>% 
  arrange(-total_pop) %>% 
  ggplot(aes(gdp_pc, mismanaged_pc * 365,
             label = country)) +
  geom_point(aes(size = mismanaged_waste,
                 color = Continent)) +
  stat_smooth(geom = "line",
              color = "dodgerblue",
              alpha = 0.9,
              method = "loess",
              show.legend = FALSE) +
  geom_smooth(method = "loess", 
              color = NA,
              alpha = 0.3,
              show.legend = FALSE) +
  geom_text(size = 2.5,
            vjust = 1, 
            check_overlap = TRUE,
            na.rm = TRUE)+
  scale_x_log10(labels = dollar_format())+
  scale_y_log10() +
  theme_half_open(12) +
  guides(col = guide_legend(override.aes = list(size = 2.5)),
          size = guide_legend(override.aes = list())) +
  labs(x = "GDP per capita",
       y = "Mismanaged plastic waste per capita \n(kg/year)",
       title = "Mismanaged plastic waste in 2010",
       subtitle = "Size represents mismanaged plastic waste(tons)") +
  theme(legend.position = "bottom") +
  guides(col = guide_legend(override.aes = list(size = 2.5)),
         size = guide_legend(override.aes = list()))

p2

```


```{r}
p1 <- waste %>% 
  arrange(-total_pop) %>% 
  ggplot(aes(gdp_pc, mismanaged_pc)) +
  geom_point(aes(size = total_pop,
                 color = Continent),
            show.legend = FALSE,
            na.rm = TRUE) +
  stat_smooth(geom = "line",
              color = "dodgerblue",
              alpha = 0.9,
              method = "loess",
              show.legend = FALSE) +
  geom_smooth(method = "loess", 
              color = NA,
              alpha = 0.3,
              show.legend = FALSE) +
  geom_text(aes(label = country), 
            vjust = 1, 
            check_overlap = TRUE,
            na.rm = TRUE)+
  scale_x_continuous(labels = comma_format()) +
  theme_half_open(12) +
  theme(axis.ticks = element_blank(),
        axis.text.x = element_text(size = 9),
        axis.text.y = element_text(size = 9),
        axis.title.x = element_text(size = 9)) +
  labs(x = "GDP per capita",
       y = "Mismanaged plastic waste\n(kg per person per day)",
       title = "GDP correlates with mismanaged plastic waste",
       subtitle = "Size represents total population")

p1

p2 <- waste %>% 
  mutate(prc_pop_coastal = pmin(1, coastal_pop / total_pop)) %>% 
  arrange(-total_pop) %>% 
  ggplot(aes(gdp_pc, mismanaged_pc)) +
  geom_point(aes(size = coastal_pop,
                 color = Continent),
                 show.legend = FALSE,
                 na.rm = TRUE) +
  stat_smooth(geom = "line",
              color = "dodgerblue",
              alpha = 0.9,
              method = "loess",
              show.legend = FALSE) +
  geom_smooth(method = "loess", 
              color = NA,
              alpha = 0.3,
              show.legend = FALSE) +
  geom_text(aes(label = country), 
            vjust = 1, 
            check_overlap = TRUE,
            na.rm = TRUE)+
  scale_x_log10(labels = dollar_format()) +
  scale_y_log10() +
  theme_half_open(12) +
  labs(x = "GDP per capita",
       y = "Mismanaged plastic waste\n(kg per person per day)",
       title = "GDP correlates with mismanaged plastic waste",
       subtitle = "Size & color represent a coastal population")
p2


p3 <- waste %>% 
  mutate(prc_pop_coastal = pmin(1, coastal_pop / total_pop)) %>% 
  arrange(-total_pop) %>% 
  ggplot(aes(gdp_pc, mismanaged_pc)) +
  geom_point(aes(size = mismanaged_waste,
                 color = coastal_pop),
             show.legend = FALSE,
             na.rm = TRUE) +
  stat_smooth(geom = "line",
              color = "dodgerblue",
              alpha = 0.9,
              method = "loess",
              show.legend = FALSE) +
  geom_smooth(method = "loess", 
              color = NA,
              alpha = 0.3,
              show.legend = FALSE) +
  geom_text(aes(label = country), 
            vjust = 1, 
            check_overlap = TRUE,
            na.rm = TRUE)+
  scale_x_log10(labels = dollar_format()) +
  scale_y_log10() +
  scale_color_distiller(palette = 1 )+
  theme_half_open(12) +
  labs(x = "GDP per capita",
       y = "Mismanaged plastic waste\n(kg per person per day)",
       title = "GDP correlates with mismanaged plastic waste",
       subtitle = "Size represents a mismanage waste(ton), \ncolor represents a coastal population")
p3
```

```{r joint plots}

p1 <- waste %>% 
  mutate(prc_pop_coastal = pmin(1, coastal_pop / total_pop)) %>% 
  arrange(-total_pop) %>% 
  ggplot(aes(gdp_pc, mismanaged_pc *365)) +
  geom_point(aes(size = mismanaged_waste,
                 color = Continent),
             na.rm = TRUE) +
  stat_smooth(geom = "line",
              color = "dodgerblue",
              alpha = 0.9,
              method = "loess",
              show.legend = FALSE) +
  geom_smooth(method = "loess", 
              color = NA,
              alpha = 0.3,
              show.legend = FALSE) +
  geom_text(aes(label = country), 
            vjust = 1, 
            check_overlap = TRUE,
            na.rm = TRUE)+
  scale_x_log10(labels = dollar_format()) +
  scale_y_log10() +
  theme_half_open(12) +
  labs(x = "GDP per capita",
       y = "Mismanaged plastic waste per capita(kg/year)",
       title = "Global mismanaged plastic waste(2010)") +
  theme(legend.position = "right",
        plot.title = element_text(size = 24),
        axis.ticks = element_blank(),
        axis.text.x = element_text(size = 9),
        axis.text.y = element_text(size = 9),
        axis.title.x = element_text(size = 9))

# bar plot
p2 <- plastic_waste %>% 
   top_n(20, mismanaged_pc) %>% 
   ggplot(aes(fct_reorder(country, mismanaged_pc), mismanaged_pc)) + 
   geom_col(color = "white",
            fill = "#413413",
            width = 1) + 
   geom_text(aes(label = round(mismanaged_pc, 2)), 
             nudge_y = -.01, 
             nudge_x = .09,
             color = "white",
             size = 3,
             na.rm = TRUE) +
   coord_flip() +
   scale_y_continuous(expand = c(0, 0), 
                      limits = c(0, 0.35), 
                      breaks = seq(0, 0.3, by = 0.1)) +
   theme(plot.title = element_text(size = 24),
         axis.ticks = element_blank(),
         axis.text.x = element_text(size = 9),
         axis.text.y = element_text(size = 9),
         axis.title.x = element_text(size = 9)) +
  theme_half_open(12) +
  labs(x = NULL, 
       y = "Mismanaged plastic waste per capita (kg/day)",
       title = "Top 20 countries of mismanaged plastic waste")


 plot_grid(p1, p2,
           nrow = 1,
           rel_widths = c(1.2, 1),
           rel_heights = c(.6, 1))
 

ggsave(here("figures", "GDP vs plastic wastes.png"), width = 13, height = 5.5)
```
### source:[Z3tt/TidyTuesday](https://github.com/Z3tt/TidyTuesday/blob/master/R/2019_21_PlasticWaste.Rmd)
```{r data-spatial}

data("wrld_simpl")

waste_gdp_map <- wrld_simpl %>% 
  st_as_sf() %>% 
  st_transform(crs = "+proj=robin") %>% 
  mutate(ISO3 = as.character(ISO3)) %>% 
  left_join(waste_gdp, 
            by = c("ISO3" = "code")) %>% 
  filter(year == 2010)
```

```{r data-proportion}

plastic_prop <- plastic_waste %>% 
  select(country, code, waste_pc, mismanaged_pc) %>% 
  mutate(prop_mis = mismanaged_pc / waste_pc,
         prop_mis = round(prop_mis, 2))

plastic_prop %>% 
  count(prop_mis, sort = TRUE) %>% 
  filter(!is.na(prop_mis))
```

```{r map}
# R color palettes exploration
plastic_map <- waste_gdp_map %>% 
  left_join(plastic_prop, 
            by = c("ISO3" = "code")) %>% 
  mutate(prop_mis_cut = cut(prop_mis, 
                            breaks = seq(0, 0.9, by = 0.1))) %>% 
  ggplot() +
  geom_sf(aes(geometry = geometry, 
              fill = as.numeric(prop_mis_cut)), 
          color = "white", 
          size = 0.03) +
  scale_fill_gradientn(colors = terrain.colors(10),
                       name = "Share of mismanaged plastic wastes",
                       na.value = "grey50") +   
    labs(
    x = NULL, y = NULL,
    title = "Correlation of GDP and mismanaged plastic waste across the globe",    
    caption = "Source: Our World in Data | sunginkyung",
    fill = " ") +
  theme_void() +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 9),
    legend.title = element_text(face = "bold", 
                                color = "grey20", 
                                size = 11),
    plot.title = element_text(size = 13),
    plot.subtitle = element_text(),
    plot.background = element_rect(fill = "aliceblue")) +
  guides(fill = guide_legend(title.position = "top", 
                             title.hjust = 0.5, nrow = 1,
                             label.position = "bottom")) 

plastic_map 
```

```{r corrplot }
corrplot <- plastic_waste %>% 
  mutate(mis_prc = mismanaged_pc / waste_pc,
          mis_prc = round(mis_prc, 2)) %>% 
  select(waste_pc, mismanaged_pc, gdp_pc, total_pop, coastal_pop, mis_prc) %>% 
  drop_na() %>% 
  cor() %>%
  corrplot::corrplot(method = "circle")
```

```{r grayscale map}

plastic_map <- waste_gdp_map %>% 
  left_join(plastic_prop, 
            by = c("ISO3" = "code")) %>% 
  mutate(prop_mis_cut = cut(prop_mis, 
                            breaks = seq(0, 0.9, by = 0.1))) %>% 
  ggplot() +
  geom_sf(aes(geometry = geometry, 
              fill = prop_mis_cut), 
          color = "white", 
          size = 0.01) +
  scale_fill_grey(start = 0.8, end = 0.2,
                  name = "Share of mismanaged plastic wastes(%)",
                  na.value = "#fde6b6",
                  labels = c("0–10", "10–20", "20–30", 
                             "30–40", "40–50", "50–60", 
                             "60–70", "70–80", "80–90", 
                             "No data")) +   
    labs(
    x = NULL, y = NULL,
    title = "Mismanaged plastic waste distribution across countries",    
    fill = " ") +
  theme_void() +
  theme(
    legend.position = "bottom",
    legend.key.height = unit(0.5, "lines"), 
    legend.key.width = unit(2, "lines"),
    legend.text = element_text(size = 7),
    legend.title = element_text(size = 9),
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(size = 9,
                               color = "grey30"),
    plot.title = element_text(size = 24,
                              hjust = 0.5),
    plot.subtitle = element_text(),
    plot.background = element_rect(fill = "aliceblue",
                                   colour = "aliceblue",
                                   size = 0.5, 
                                   linetype = "solid")) +
  guides(fill = guide_legend(title.position = "top", 
                             title.hjust = 0.5, nrow = 1,
                             label.position = "bottom")) 

plastic_map

ggsave(here("figures", "mismanaged plastic wastes_worldmap.png"), width = 14, height = 7.5)

```

```{r}
## left-alligned title
title <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(x = NULL, y = NULL,
       title = "Correlation of GDP and mismanaged plastic waste across countries") +
  theme(line = element_blank(),
        panel.background = element_rect(fill = NA),
        plot.background = element_rect(fill = NA, color = NA),
        panel.border = element_rect(color = NA),
        axis.text = element_blank())
```

```{r}
plastic_map <- waste_gdp_map %>% 
  left_join(plastic_prop, 
            by = c("ISO3" = "code")) %>% 
  mutate(prop_mis_cut = cut(prop_mis, 
                            breaks = seq(0, 0.9, by = 0.1))) %>% 
  ggplot() +
  geom_sf(aes(geometry = geometry, 
              fill = prop_mis_cut), 
          color = "white", 
          size = 0.03) +
  scale_fill_tableau(name = "Share of mismanaged plastic wastes",
                     na.value = "gray40",
                     labels = c("0–10", "10–20", "20–30", 
                             "30–40", "40–50", "50–60", 
                             "60–70", "70–80", "80–90", 
                             "No data")) +   
    labs(
    x = NULL, y = NULL,
    title = "Correlation of GDP and mismanaged plastic waste across the globe",    
    caption = "Source: Our World in Data | sunginkyung",
    fill = " ") +
  theme_void() +
  theme(
    legend.position = "bottom",
    legend.key.height = unit(0.5, "lines"), 
    legend.key.width = unit(3, "lines"),
    legend.text = element_text(size = 9),
    legend.title = element_text(face = "bold", 
                                color = "grey20", 
                                size = 11),
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(size = 9,
                               color = "grey50"),
    plot.title = element_text(size = 15),
    plot.subtitle = element_text(),
    plot.background = element_rect(fill = "aliceblue")) +
  guides(fill = guide_legend(title.position = "top", 
                             title.hjust = 0.5, nrow = 1,
                             label.position = "bottom")) 

plastic_map 
```

