---
title: "happy_moment"
author: "sung inkyung"
date: '2019 7 27')
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cowplot)
```
### sources: https://github.com/rit-public/HappyDB
```{r}
happy_moment <- readr::read_csv("https://raw.githubusercontent.com/rit-public/HappyDB/master/happydb/data/cleaned_hm.csv")
view(happy_moment)
demographic <- readr::read_csv("https://raw.githubusercontent.com/rit-public/HappyDB/master/happydb/data/demographic.csv") %>% 
  mutate(age_lbls = factor(case_when(
  .$age <  20 ~ "0",
  .$age >= 20 & .$age <= 29 ~ "1",
  .$age >= 30 & .$age <= 39 ~ "2",
  .$age >= 40 & .$age <= 49 ~ "3",
  .$age >= 50 & .$age <= 59 ~ "4",
  .$age >= 60 & .$age <= 69 ~ "5",
  .$age >= 70 & .$age <= 79 ~ "6",
    TRUE  ~"7")))

## mutate(age_group=cut(age,seq(0,100,10)))
## scale_x_discrete(labels=c('10','20','30','40','50','60','70','80','90','100'))
```
  
```{r}
hm <- happy_moment %>% 
  left_join(demographic, by = "wid") %>% 
  select(wid, 
         cleaned_hm,
         predicted_category,
         age,
         country,
         gender,
         marital,
         parenthood,
         ground_truth_category,
         age_lbls) %>% 
  rename(text = cleaned_hm,
         category = predicted_category) %>% 
  filter(gender %in% c("m", "f"),
         marital %in% c("single", "married"),
         parenthood %in% c("n", "y"),
         !is.na(country)) %>% 
  distinct(wid, .keep_all = TRUE)
  
View(hm)
  
```
## source: Visualizing Multivariate Categorical Data (http://www.sthda.com/english/articles/32-r-graphics-essentials/129-visualizing-multivariate-categorical-data/)
```{r}
library(ggpubr)
theme_set(theme_pubr())

hm %>% 
  count(category, gender) %>% 
  mutate(category = reorder(category, n)) %>% 
ggplot(aes(x = category, n))+
  geom_bar(
    aes(fill = category), stat = "identity", color = "white",
    position = position_dodge(0.9)
    )+
  facet_wrap(~gender) + 
  coord_flip() + 
  fill_palette("jco")
```
```{r}
library(viridis)

hm %>% 
  count(category, gender, parenthood, marital) %>% 
  mutate(category = reorder(category, n)) %>%
ggballoonplot(x = "marital", y = "category", size = "n",
              fill = "n", facet.by = "gender",
              ggtheme = theme_bw()) +
  scale_fill_viridis_c(option = "C")
```
## source:Alluvial Diagrams in ggplot2 by Jason Cory Brunson (https://cran.r-project.org/web/packages/ggalluvial/vignettes/ggalluvial.html)

```{r}
library(ggalluvial)

hm %>% 
  count(category, gender, parenthood, marital) %>% 
  mutate(category = reorder(category, n)) %>%
ggplot(aes(y = n,
           axis1 = category, axis2 = gender, axis3 = marital, axis4 = parenthood)) +
  geom_alluvium(aes(fill = gender),
                width = 0, 
                knot.pos = 0, 
                reverse = FALSE) +
  geom_stratum(width = 1/8, 
               reverse = FALSE) +
  geom_text(stat = "stratum", 
            label.strata = TRUE,
            check_overlap = TRUE) +
  scale_x_continuous(breaks = 1:4, 
                     labels = c("Category", "Gender", "Marital", "Parenthood")) +
  scale_fill_manual(values = c("#f15e75", "#27c96d")) +
  coord_flip() +
  ggtitle("Happy Moment by gender, marital and parenthood") +
  theme(legend.position = "right")

```

```{r}
hm %>%
  count(country, sort = TRUE)%>% 
  filter(!is.na(country)) %>% 
  mutate(country = reorder(country, n)) %>% 
  top_n(10) %>% 
  ggplot(aes(country, n)) +
  geom_col()+
  scale_y_log10() +
  coord_flip() +
  theme_minimal_vgrid()
```

```{r}
hm %>%
  count(age_lbls, country, sort = TRUE)%>% 
  filter(country > 200,
         !is.na(age_lbls)) %>% 
  ggplot(aes(age_lbls, n)) +
  geom_col()+
  scale_x_discrete(name = "age group",
                   labels = c("<20", "20-29", "30-39", "40-49",
                              "50-59", "60-69", "70-79", "80+")) +
  scale_y_continuous(labels = scales::comma)+
  theme_minimal_hgrid()

hm %>%
  count(age_lbls, gender, sort = TRUE) %>% 
  arrange(desc(age_lbls)) %>% 
  ggplot(aes(age_lbls, n, fill = gender))+
  geom_col(position = "dodge", 
           color = "white", 
           size = 1, 
           width = 1) +
  scale_x_discrete(name = "age years",
                   labels = c("<20", "20-29", "30-39", "40-49", "50-59",
                              "60-69", "70-79", "80+")) +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_manual(values = c("#f15e75", "#27c96d"))+
  theme_minimal_hgrid()

```

```{r}
hm %>% count(category, sort = TRUE) %>%
  mutate(category = fct_reorder(category, n)) %>%
  ggplot(aes(category, n)) +
  geom_col(aes(fill = category))+
  guides(fill = guide_legend(reverse = TRUE)) +
  coord_flip() +
  theme_minimal_vgrid()


hm %>%
  count(category, gender, sort = TRUE) %>% 
  arrange(desc(category))%>% 
  mutate(category = fct_reorder(category, n)) %>% 
  ggplot(aes(category, n, fill = gender))+
  geom_col(position = "dodge", 
           color = "white", 
           size = 1, 
           width = 1)+
  scale_fill_manual(values = c("#f15e75", "#27c96d"))+
  coord_flip() +
  theme(axis.text.x = element_text(size = 7))+
  theme_minimal_vgrid()

```

```{r}
hm %>%
  count(category, marital, sort = TRUE) %>% 
  arrange(desc(category))%>% 
    mutate(category = fct_reorder(category, n)) %>% 
  ggplot(aes(category, n, fill = marital))+
  geom_col(position = "dodge", 
           color = "white", 
           size = 1, 
           width = 1)+
  scale_fill_manual(values = c("#f15e75", "#27c96d"))+
  coord_flip()+
  theme(axis.text.x = element_text(size = 7))+
  theme_minimal_vgrid()
```

```{r}
hm %>% 
  count(country, category) %>% 
  mutate(category = reorder(category, n)) %>% 
  filter(country %in% c("USA", "IND", "GBR", "PHL", "AUS", "NGA"))%>% 
ggplot(aes(category, n)) +
  geom_line (aes(group = country), color = "#ff1493", size = .7) +
  coord_flip() +
  facet_wrap(~country) +
  theme_light()

````

```{r}
library(tidytext)

hm_words <- hm %>%
  unnest_tokens(word, text) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(str_detect(word, "[a-z]"))

hm_words
```

```{r}
hm_words %>% 
  count(word, sort = TRUE) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  filter(!(word %in% c("happy", "time", "day", "months", "month", "week")),
         str_detect(word, "[a-z]")) %>% 
  head(20) %>% 
  ggplot(aes(word, n))+
  geom_col()+
  scale_y_continuous(labels = scales::comma) +
  coord_flip()+
  labs(title = "Common words in happy moment") +
  theme_minimal_vgrid()
```

```{r}
hm_bigrams <- hm %>% 
  unnest_tokens(bigram, text, token = "ngrams", n= 2)

hm_bigrams %>% 
  count(bigram, sort = TRUE)

hm_separated <- hm_bigrams %>% 
  separate(bigram, c("word1", "word2"), sep = " ")

hm_filtered <- hm_separated %>% 
  filter(!word1 %in% stop_words$word) %>% 
  filter(!word2 %in% stop_words$word) %>% 
  filter(
    !str_detect(word1, pattern = "[[:digit:]]"), 
    !str_detect(word1, pattern = "[[:punct:]]"), 
    !str_detect(word1, pattern = "(.)\\1{2,}"),  
    !str_detect(word1, pattern = "\\b(.)\\b")) %>% 
  filter(
    !str_detect(word2, pattern = "[[:digit:]]"), 
    !str_detect(word2, pattern = "[[:punct:]]"), 
    !str_detect(word2, pattern = "(.)\\1{2,}"),  
    !str_detect(word2, pattern = "\\b(.)\\b"))

# new bigram counts:
bigram_counts <- hm_filtered %>% 
  count(word1, word2, sort = TRUE)

bigram_counts
```

```{r}
hm_bigrams_united <- hm_filtered %>% 
  unite(bigram, word1, word2, sep = " ")


hm_bigrams_united
```


```{r}
hm_filtered %>% 
  filter(word2 == "moment") %>% 
  count(category, word1, sort = TRUE) 
```

```{r}
hm_tf_idf <- hm_bigrams_united  %>%
  count(category, bigram) %>%
  bind_tf_idf(bigram, category, n) %>%
  arrange(desc(tf_idf))

hm_tf_idf
```
```{r}
hm_tf_idf %>% 
  filter(category == "exercise") %>% 
  group_by(category) %>% 
  top_n(5, tf_idf) %>%
  ungroup() %>% 
  mutate(bigram = reorder(bigram, tf_idf)) %>% 
  ggplot(aes(bigram, tf_idf, fill = factor(bigram))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~category, scales = "free") +
  coord_flip()

```

```{r}
hm_tf_idf %>%
  arrange(desc(tf_idf)) %>%
  group_by(category) %>%
  top_n(8, tf_idf) %>%
  ungroup() %>%
  mutate(bigram = reorder(bigram, tf_idf)) %>%
  ggplot(aes(bigram, tf_idf, fill = category)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ category, ncol = 2, scales = "free") +
  coord_flip() +
  labs(y = "tf-idf of bigram to category of happy moments",
       x = "")
```

```{r}
# sentiment analysis by using bigrams

sentiments_hm_words <- hm_separated %>% 
  inner_join(get_sentiments("afinn"), by = c(word2 = "word")) %>% 
  group_by(gender, parenthood, marital) %>% 
  summarize(sent_score = mean(score)) %>% 
  mutate(method = "AFINN") 

sentiments_hm_words %>% 
ggplot(aes(gender, sent_score))+
  geom_boxplot(aes(fill = gender))+
  geom_point(size = 2)+
  geom_jitter(size = .7)+
  scale_fill_manual(values = c("#f15e75", "#27c96d")) +
  theme(text = element_text(size=11)) +
  theme_light()

sentiments_hm_words %>% 
ggplot(aes(parenthood, sent_score))+
  geom_boxplot(aes(fill = parenthood))+
  geom_point(size = 2)+
  geom_jitter(size = .7)+
  scale_fill_manual(values = c("#088da5", "#ee7b68")) +
  theme(text = element_text(size=11)) +
  theme_light()

sentiments_hm_words %>% 
ggplot(aes(marital, sent_score))+
  geom_boxplot(aes(fill = marital))+
  geom_point(size = 2)+
  geom_jitter(size = .7)+
  scale_fill_manual(values = c("#008000", "#8d1673")) +
  theme(text = element_text(size=11)) +
  theme_light()
```

```{r}
sentiments_hm_words <- hm_separated %>% 
  inner_join(get_sentiments("afinn"), by = c(word2 = "word")) %>% 
  group_by(category) %>% 
  summarize(sent_score = mean(score)) %>% 
  mutate(method = "AFINN") 


sentiments_hm_words %>% 
ggplot(aes(category, sent_score))+
  geom_col(aes(fill = category))+
  scale_fill_manual(values = c("#f15e75", "#27c96d", "#3b5998", "#8d1673", "#088da5", "#ee7b68", "#27c96d")) +
  theme(text = element_text(size=11)) +
  theme_light()
```

```{r}
sentiments_hm_words <- hm_separated %>% 
  inner_join(get_sentiments("afinn"), by = c(word2 = "word")) %>% 
  group_by(age_lbls, gender) %>% 
  summarize(sent_score = mean(score)) %>% 
  mutate(method = "AFINN") %>% 
  na.omit()


sentiments_hm_words %>% 
ggplot(aes(sent_score))+
  geom_col(aes(age_lbls, sent_score, fill = gender))+
  scale_fill_manual(values = c("#f15e75", "#27c96d")) +
  scale_x_discrete(labels=c('10','20','30','40','50','60','70','80','90','100'))+
  facet_wrap(~gender)+
  labs(title = "Average happiness sentiment scor by age",
       xlab = "e group",
       ylab = "average sentiment score")+
  theme_light()

```

```{r}
hm_separated %>% 
  filter(word1 == "no") %>% 
  count(word1, word2, sort = TRUE)

```

```{r}
sentiments_hm_words <- hm_separated %>%
  filter(word1 == "not") %>%
  inner_join(get_sentiments("afinn"), by = c(word2 = "word")) %>%
  count(word2, score, sort = TRUE)

sentiments_hm_words
```

```{r}
not_words <- sentiments_hm_words %>% 
  mutate(contribution = n * score) %>%
  arrange(desc(abs(contribution))) %>%
  head(20) %>%
  mutate(word2 = reorder(word2, contribution)) %>%
  ggplot(aes(word2, n * score, fill = n * score > 0)) +
  geom_col(show.legend = FALSE) +
  xlab("Words preceded by \"not\"") +
  ylab("Sentiment score * number of occurrences") +
  coord_flip()
```


```{r}
negation_words <- c("not", "no", "never", "without")

negated_words <- hm_separated %>%
  filter(word1 %in% negation_words) %>%
  inner_join(get_sentiments("afinn"), by = c(word2 = "word")) %>%
  count(word1, word2, score, sort = TRUE)
  
```


```{r}
negated_words %>%
  mutate(contribution = n * score,
         word2 = reorder(paste(word2, word1, sep = "__"),
                         contribution)) %>%
  group_by(word1) %>%
  top_n(12, abs(contribution)) %>%
  ggplot(aes(word2, contribution, 
             fill = n * score > 0)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ word1, scales = "free") +
  scale_x_discrete(labels = function(x) gsub("__.+$", "", x)) +
  xlab("Words preceded by negation term") +
  ylab("Sentiment score * # of occurrences") +
  coord_flip()+
  theme_light()
```

```{r}
library(tidytext)
library(igraph)
library(ggraph)

count_bigrams <- function(dataset) {
  dataset %>%
    unnest_tokens(bigram, text, token = "ngrams", n = 2) %>%
    separate(bigram, c("word1", "word2"), sep = " ") %>%
    filter(!word1 %in% stop_words$word,
           !word2 %in% stop_words$word) %>%
    count(word1, word2, sort = TRUE)
}

vis_bigrams <- function(bigrams) {
  
  set.seed(2019)
  a <- grid::arrow(type = "closed", 
                   length = unit(.05, "inches"))

  bigrams %>%
    graph_from_data_frame() %>%
    ggraph(layout = "fr") +
    geom_edge_link(aes(edge_alpha = log(n)), 
                   show.legend = FALSE,
                   arrow = a) +
    geom_node_point(color = "#ff1493", size = 2.5) +
    geom_node_text(aes(label = name), 
                   vjust = 1, 
                   hjust = 1,
                   show.legend = FALSE,
                   repel = TRUE) +
    theme_void()
}

```


```{r}
hm_bigrams <- hm %>% 
  count_bigrams()

hm_bigrams %>% 
  filter(n > 10,
         !str_detect(word1, "\\d"),
         !str_detect(word2, "\\d")) %>%
  
  vis_bigrams()
```

```{r}
# Counting and crrelating among categories

hm_category_words <- hm %>%
  filter(category == "affection") %>%
  mutate(category = row_number() %/% 10) %>% 
  filter(category > 0) %>% 
  unnest_tokens(word, text) %>%
  anti_join(stop_words, by = "word")  # filter(!word %in% stop_words$word)

hm_category_words
```

```{r}
library(widyr)
hm_word_pairs <- hm_category_words %>% 
  pairwise_count(word, category, sort = TRUE)


hm_word_pairs %>% 
  filter(item1 == "daughter")
```


```{r}
# pairwise correlation
hm_word_cors <-  hm_category_words %>% 
  group_by(word) %>% 
  pairwise_cor(word, category, sort=TRUE)

hm_word_cors
```


```{r}
hm_word_cors %>% 
  filter(item1 == "happy",
         str_detect(item1, "[a-z]"),
         str_detect(item2, "[a-z]"))
```

```{r}
hm_word_cors %>% 
  filter(item1 %in% c("happy", "lucky", "hungry", "bad")) %>% 
  group_by(item1) %>% 
  top_n(8) %>% 
  ungroup() %>% 
  mutate(item2 = reorder (item2, correlation)) %>% 
  ggplot(aes(item2, correlation)) +
  geom_col()+
  facet_wrap(~item1, scales = "free") +
  coord_flip()
```

```{r}
set.seed(2019)

hm_word_cors %>%
  filter(correlation > .6) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), show.legend = FALSE) +
  geom_node_point(color = "#ff1493", size = 3.5) +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void()
```

