---
title: "HorrorMovies"
Author: "Sung Inkyung"
date: '2019 10 23 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### source[Tidy Tuesday screencast: predicting horror movie ratings by david robinson] (https://youtu.be/yFRSTlk3kRQ)
```{r}
library(tidyverse)
library(tidytext)
library(lubridate)
library(scales)
library(cowplot)
library(paletteer)
library(here)
```

```{r}
horror_movies_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-22/horror_movies.csv")

```

```{r}
horror_movies <- horror_movies_raw %>% 
  rename(country = release_country) %>%
  select(title, genres, release_date, country, review_rating) %>% 
  mutate(month = month(dmy(release_date)),
         year = year(dmy(release_date))) %>% 
  filter(!is.na(month),
         !is.na(year))

country <- horror_movies%>% 
  group_by(country) %>% 
  summarise(total_country = sum(n())) %>% 
  arrange(desc(total_country)) %>% 
  ungroup() 

p <- country %>% 
  filter(total_country >= 35) %>% 
  mutate(country = fct_reorder(country, total_country)) %>% 
  ggplot(aes(country, total_country)) +
  geom_col() +
  coord_flip() +
  theme_minimal()

```


```{r}
top_released_month <- horror_movies %>% 
  group_by(country, month) %>% 
  summarise(total_month = sum(n())) %>% 
  left_join(country, by = "country") %>% 
  mutate(prc = total_month / total_country,
         prc = round(prc,  2)) %>% 
  ungroup() %>% 
   mutate(month = factor(month, 
                         levels = 1:12, 
                   labels = month.abb))

p1 <- top_released_month %>% 
  filter(total_country >= 35) %>% 
  mutate(month = reorder(month, total_country)) %>% 
  ggplot(aes(x= month, prc, fill = month)) +
  geom_col(show.legend = FALSE)+
  scale_y_continuous( breaks = seq(0, 50, 5)) +
  expand_limits(y = c(0, 0)) +
  facet_wrap(~ country, scales = "free") +
  labs(x = "",
       y = "",
       title = "Monthly release of horror movies",
       subtitle = "Mostly October stands out to release horror movies. India and Philippines show \nnot as distinctive as other countries.") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, 
                                   size = 4.5))
p1

p2 <- top_released_month %>% 
  filter(total_country >= 35,
         month == "Oct") %>% 
  top_n(7) %>% 
  mutate(country = fct_reorder(country, prc)) %>% 
  ggplot(aes(country, prc, fill = country)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = prc),
            color = "black",
            nudge_y = 0.02,
            size = 3.5) +
  scale_y_continuous(breaks = seq(0, 50, 10),
                     labels = percent_format()) +
  scale_fill_paletteer_d(ghibli, MarnieDark1) +
  expand_limits(y = c(0, 0)) +
  coord_flip() +
  labs(x = "",
       y = "",
       title = "Percentage of released horror movies in October since 2012") +
  theme_minimal()
p2


top <- top_released_month %>% 
  filter(total_country >= 10) %>% 
  select(country, month, prc) %>% 
   filter(prc >= 0.30)

```

```{r}
library(ggforce)

back_col <- paletteer_d(ghibli, KikiMedium)[3]

tol12qualitative=c("#332288", "#6699CC", "#88CCEE", "#44AA99", "#117733", "#999933", "#DDCC77", "#661100", "#CC6677", "#AA4466", "#882255", "#AA4499")

annotation_spain <- top %>% 
  group_by(country, prc) %>% 
  filter(country == "Spain",
         month == "Oct") 

annotation_malaysia <- top %>% 
  group_by(country, prc) %>% 
  filter(country == "Malaysia",
         month == "Feb")

annotation_belgium <- top %>% 
  group_by(country, prc) %>% 
  filter(country == "Belgium",
         month == "Apr")

annotation_korea <- top %>% 
  group_by(country, prc) %>% 
  filter(country == "South Korea",
         month == "Jul") 

p3 <- top_released_month %>% 
  filter(total_country >= 10) %>% 
  mutate(month = fct_reorder(month, total_country)) %>% 
  ggplot(aes(x = month, y = prc, fill = month)) +
  geom_jitter(aes(size = total_month, 
                  fill = month), 
              width = 0.1, 
              alpha = 0.4, 
              shape = 21,
              colour = "#85e21f") +
  geom_boxplot(aes(fill = month), 
               colour = "white", 
               width = 0.4,
               show.legend = FALSE, 
               outlier.shape = NA, 
               alpha = 0.4) +
  geom_mark_circle(data = annotation_spain,
                   aes(label = country,
                   description = "42%"),
                   expand = unit(2, "mm"),
                   label.fontsize = 11,
                   label.fill = back_col) +
  geom_mark_circle(data = annotation_malaysia,
                   aes(label = country,
                       description = "38%"),
                   expand = unit(2, "mm"),
                   label.fontsize = 11,
                   label.fill = back_col) +
  geom_mark_circle(data = annotation_belgium,
                   aes(label = country,
                       description = "36%"),
                   expand = unit(2, "mm"),
                   label.fontsize = 11,
                   label.fill = back_col) +
  geom_mark_circle(data = annotation_korea,
                   aes(label = country,
                       description = "34%"),
                   expand = unit(2, "mm"),
                   label.fontsize = 11,
                   label.fill = back_col) +
  geom_hline(yintercept = 0, 
             size = 0.7,
             color =  "#85e21f") +
  scale_fill_manual(values = tol12qualitative) +
  scale_x_discrete(limits = month.abb)  +
  scale_y_continuous(breaks = seq(0, 50, 10),
                     labels = scales::percent) +
  labs(x = "", 
       y = "", 
       title = "Monthly distribution of released horror movies since 2012 across countries",
       subtitle = "Each point represents a country and shows the percentage of horror films is released in a given country.\nOctober is known for the release of horror films year-round. However, while many in the West celebrate \nthe horrors of Halloween in October as below, South Korea has a strong horror film trend in the summer.\nBecause nothing beats a spooky movie that cools you down in the hot summer.\n",
       caption = "source : IMDB") +
  theme(legend.position = "none",
        plot.title = element_text(size = rel(1.5),
                                  color = "gray80"),
        plot.subtitle = element_text(size = rel(1.2),
                                     color = "gray80",
                                     margin = margin(b = 10)),
        plot.caption = element_text(size = rel(0.7),
                                    color = "#e5e6e0"),
        plot.background = element_rect(fill = back_col),
        panel.background = element_rect(fill = back_col),
        panel.grid = element_blank(),
        axis.text = element_text(colour = "white"),
        #axis.text.x = element_text(margin = margin(t = .05, unit = "cm")),
        axis.title.y.left = element_text(size = 7),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        plot.margin = margin(10, 10, 10, 10)) 

p3

ggsave(here("figures", "HorrorMovies.png"), width = 11, height = 7, units = "in")

```
            
  