---
title: "IMDB TV Rating"
author: "Sung Inkyung"
date: '2020 3 20 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```
### Source[ggplot2 3.3.0] (https://www.tidyverse.org/blog/2020/03/ggplot2-3-3-0/)

```{r}
tv_data <- read_csv("https://github.com/rfordatascience/tidytuesday/raw/master/data/2019/2019-01-08/IMDb_Economist_tv_ratings.csv") %>% 
  rename(title_id = titleId,
         season_number = seasonNumber) %>% 
  mutate(year = year(date))

tv_genres <- tv_data %>% 
  mutate(genres = fct_lump(genres, 10), "Others") %>% 
  filter(genres != "Other") %>% 
  select(genres, av_rating, year) %>% 
  filter(!is.na(genres))
  

plot <- tv_genres %>% 
  ggplot() +
  geom_tile(aes(genres, year, fill = av_rating)) +
  scale_fill_viridis_c(direction = -1) +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) + #new label feature
  scale_y_continuous(trans = "reverse") +
  labs(x = "",
       y = "",
       title = "IMDB TV Shows Average Ratings fo Genres by year",
       subtitle = "Drama ratings have been recovering since 2010 but romance dramas have poor ratings.") +
  guides(fill = guide_legend(nrow = 1),
         alpha = .9) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


```

