---
title: "Incarceration Trends"
author: "Sung Inkyung"
date: '2020 4 19 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[tidytuesday by @othom] (https://otho.netlify.app/post/2-04-prison/)
```{r}
library(tidyverse)
library(paletteer)
library(ggtext)
library(here)
```


```{r}
prison_population<- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-22/prison_population.csv")
```


```{r}
prison_population %>% 
  count(pop_category, sort = T)

prison_population %>% 
  count(year, sort = T)

prison_population %>% 
  count(prison_population, sort = T)


```


```{r}
prison <- prison_population %>% 
  filter(pop_category == "Total") %>% 
  group_by(year, state) %>% 
  summarise(prison_population = prison_population %>% sum(na.rm = TRUE),
            population = population %>% sum(na.rm = TRUE)) 
```


```{r}
state_prison <- prison_population %>% 
  filter(pop_category == "Total",
         !is.na(pop_category)) %>% 
  filter(year >= 1990,
         year != 2016) %>% 
  group_by(year, state) %>% 
  summarise(prison_population = sum(prison_population,
                                    na.rm = TRUE),
            population = sum(population,
                             na.rm = TRUE)) %>% 
  ungroup()

plot <- state_prison %>% 
  ggplot(aes(x = year,
             y = state,
             fill = prison_population)) +
  geom_raster() +
  scale_fill_paletteer_c("grDevices::Turku",
                         name = "Prison\nPopulation") +
  scale_x_continuous(expand = expansion(c(0, 0)))
```
```{r}
category <- prison_population %>% 
  filter(!is.na(prison_population),
         !is.na(population)) %>%
  filter(pop_category != "Other") %>%
  filter(year >= 1990,
         year != 2016) %>%
  mutate(ratio = prison_population / population) 

plot1 <- category %>% 
  ggplot(aes(year, state,
             fill = prison_population)) +
  geom_raster() +
  facet_grid(. ~ pop_category) +
  scale_fill_paletteer_c("grDevices::Turku",
                         trans = "log10",
                         breaks = 10^c(1:5)) +
  labs(x = "",
       y = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = .5)) 

plot2 <- category %>% 
  ggplot(aes(year, ratio, group = year)) +
  geom_boxplot(width = .5, alpha = .7,
               color = "#838691",
               show.legend = F) +
  scale_y_log10() +
  facet_grid(pop_category ~.,
             scales = "free",
             labeller = label_wrap_gen(width = 10)) +
  theme_minimal()
  
  
```

```{r}
by_cat <- prison_population %>% 
  na.omit() %>% 
  filter(!is.na(prison_population),
         pop_category != "Other") %>%
  filter(year >= 1990,
         year != 2016) %>%
  mutate(decade = year - (year %% 10)) %>% 
  group_by(decade, state, pop_category) %>% 
  summarise(prison_population = mean(prison_population)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = decade, values_from = prison_population)


year_plot <- by_cat %>% 
  ggplot(aes(pop_category, prison_population)) +
  geom_bar(aes(y = `2010`, fill = '2010'), 
           stat = 'identity', 
           width = .2,
           na.rm = T) +
  geom_bar(aes(y = `2000`, fill = '2000'), 
            stat = 'identity',
           width = .4,
           na.rm = T) +
  geom_bar(aes(y = `1990`, 
               fill = '1990'), 
           stat = 'identity', 
           width = .6,
           na.rm = T) +
    scale_fill_manual('', values = c('darkslategray', 'slategray', 'lightgray')) +
    scale_y_continuous(expand = expansion(c(0, .05))) +
    expand_limits(y = 0) +
  labs(x = " ",
       y = "Average of Prison Population",
       title = "Prison Population by Category",
       subtitle = "Average of prison population increased in **White, Latino, and Male** from 1990 to 2015 in USA",
       caption = "Source: Vera Institute | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 16,
                                  face = "bold",
                                  margin = margin(b = 10)),
        plot.subtitle = element_markdown(size = 13,
                                         margin = margin(b = 5),
                                         lineheight = 1.1),
        plot.caption = element_text(size = 9,
                                    color = "darkslategray",
                                    margin = margin(t = 10,
                                                    b = 5)),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size = .5,
                                          color = "gainsboro"),
        panel.grid.minor = element_blank(),
        plot.margin = unit(c(.5, .5, .5, .5), "cm"))

ggsave(here("figures", "IncarcerationTrends.png"), width = 21, height = 17, units = "cm")
```

