---
title: "Measles"
author: "Sung Inkyung"
date: '2019 12 12 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
library(lubridate)
```


```{r}
diseases <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-10/diseases.csv")

diseases %>% 
  count(disease, sort = TRUE)

diseases %>% 
  filter(disease == "Measles") %>% 
  group_by(disease, year) %>% 
  summarise(total = sum(count)) %>% 
  top_n(3)

```
#https://simplystatistics.org/2019/08/28/you-can-replicate-almost-any-plot-with-ggplot2/
```{r}
# Wrangle data
diseases_processed <- diseases %>% 
  select(-state) %>% 
  filter(disease == "Measles") %>% 
  group_by(disease, year) %>% 
  mutate(rate = count / population * 10000 *52 / weeks_reporting) %>%
  filter(!is.na(rate))


plot <- diseases_processed %>% 
  ggplot(aes(x = year, y = 0, color = disease)) +
  geom_point(aes(y = 0, size = rate), color = "#f7c59f") +
  geom_hline(yintercept = 0, color = "#dedede", size = 0.9)+
  geom_segment(aes(y = 0.47, x = 1963, yend = 0.001, xend = 1963),
               color = "#e1e5ee", size = 0.2) +
  geom_segment(aes(y = 0.27, x = 1934, yend = 0.001, xend = 1936),
               color = "#e1e5ee", size = 0.2) +
  geom_segment(aes(y = 0.37, x = 1997, yend = 0.001, xend = 1997),
               color = "#e1e5ee", size = 0.2) +
  annotate(geom = "text",
           x = 1963,
           y = 0.5,
           label = "The measles vaccine was first introduced in 1963", size = 3, hjust = 0.2, color = "#e1e5ee") +
  annotate(geom = "text",
           x = 1934, 
           y = 0.3,
           label = "The highest rate of measles broke out in 1934",
           size = 3, hjust = 0.2, color = "#e1e5ee") +
  annotate(geom = "text",
           x = 1997,
           y = 0.4,
           label = "Abnormal outbreak rise is detected in 1997",
           size = 3, hjust = 0.2, color = "#e1e5ee") +
  guides(color = guide_legend(title = "Outbreak rate")) +
  labs(x = "",
       y = "",
       title = "Measles rates in the United States:1928-2002",
       caption = "Source: Simply Statistics") + 
  theme(plot.background = element_rect(fill = "#2a324b"),
        plot.title = element_text(color = "#e1e5ee"),
        plot.caption = element_text(color = "#e1e5ee"),
        panel.background = element_rect(fill = "#2a324b", 
                                        color = NA),
        panel.grid = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(size = 12, color = "#e1e5ee"),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 7, 
                                   color = "#e1e5ee"),
        legend.title = element_text(size = 9,
                                    color = "#e1e5ee"),
        legend.background = element_rect(fill = "transparent"),
        legend.key = element_rect(fill = "transparent",
                                  color = "transparent"),
        legend.position = "left")

```

