---
title: "MediumDataScienceArticles"
author: "sung inkyung"
date: '2020 4 5 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### source [tidytuesday by david robinson] (https://github.com/dgrtwo/data-screencasts/blob/master/medium-datasci.Rmd)
```{r}
library(tidyverse)
library(GGally)
library(ggrepel)
library(tidytext)
library(ggtext)
library(widyr)
library(ggraph)
library(igraph)
library(here)
```


```{r}
medium_datasci <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-12-04/medium_datasci.csv")

View(medium_datasci)
```

```{r}
medium_gathered <- medium_datasci %>% 
  select(-x1) %>% 
  mutate(post_id = row_number()) %>% 
  gather(tag, value, starts_with("tag")) %>% 
  mutate(tag = str_remove(tag, "tag_")) %>% 
  filter(value == 1)
```

```{r}
variables <- c("year", "tag", "reading_time", "claps")

medium_gathered %>% 
  select(variables) %>% 
  mutate(above_median = claps > median(claps)) %>% 
  sample_n(100) %>% 
  ggparcoord(
    groupColumn = "above_median",
    showPoints = TRUE, 
    alphaLine = 1,
    scale = "center",
    title = "Medium_features")+
  theme_minimal()+
  theme(plot.title = element_text(size = 10))
```

```{r}
# highlighting

variables <- c("year", "tag", "reading_time", "claps")

medium_gathered %>% 
  select(variables) %>% 
  mutate(above_median = claps >median(claps)) %>% 
  sample_n(100) %>% 
  ggparcoord(
    groupColumn = "above_median",
    showPoints = TRUE, 
    alphaLine = 1,
    scale = "std",
    title = "Medium features") +
  scale_color_manual(values=c("#b8b8b8", "#8d1673")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 10))
```

```{r}
medium_gathered %>% 
  group_by(tag) %>% 
  summarise(median_claps = median(claps),
            reading_time = mean(reading_time)) %>% 
  ggplot(aes(reading_time, median_claps)) +
  geom_point(size = 3, color = "#8d1673") +
  geom_text_repel(aes(label = tag)) +
  expand_limits(y= 0) +
  theme_minimal()

medium_gathered %>% 
  group_by(tag) %>% 
  summarize(reading_time = mean(reading_time)) %>% 
  arrange(desc(reading_time)) 

medium_gathered %>% 
  count(tag, sort = T)

medium_gathered %>% 
  group_by(tag) %>% 
  summarise(median_claps = median(claps)) %>% 
  arrange(desc(median_claps))

medium_gathered %>% 
  group_by(tag) %>% 
  summarize(reading_time = mean(reading_time)) %>% 
  arrange(desc(reading_time)) 
```

```{r}
medium_processed <- medium_datasci %>% 
  select(-x1) %>% 
  mutate(post_id = row_number())

medium_processed %>% 
  summarize_at(vars(starts_with("tag_")), sum)


medium_words <- medium_processed %>% 
  filter(!is.na(title)) %>% 
  select(post_id,
         title, 
         subtitle, 
         year, 
         reading_time, 
         claps) %>% 
  unnest_tokens(word, title) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(!(word %in% c("de", "la", "para")),
         str_detect(word, "[a-z]"))

```

```{r}
set.seed(123)

medium_words %>%
  count(word, sort = TRUE) %>%
  mutate(word = fct_reorder(word, n)) %>%
  head(20) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  coord_flip() +
  labs(title = "Common words in Medium post titles") +
  theme_minimal()

```
```{r}
medium_words_count <- medium_words %>%
  add_count(word) %>%
  filter(n >= 500)  

tag_claps <- medium_words_count %>% 
  group_by(word) %>% 
  summarize(median_claps = median(claps),
            occurrences = n()) %>% 
  arrange(desc(median_claps))  
```


```{r}
medium_words_count %>% 
  select(post_id, word) %>% 
  pairwise_cor(word, post_id, sort = TRUE)

set.seed(123)
top_word_cors %>% 
  graph_from_data_frame() %>% 
  ggraph()+
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void()

vertices <- tag_claps %>% 
  filter(word %in% top_word_cors$item1 | word %in%top_word_cors$item2)

set.seed(123)
word_plot <- top_word_cors %>% 
  graph_from_data_frame(vertices = vertices) %>% 
  ggraph()+
  geom_edge_link()+
  geom_node_point(aes(size= occurrences, color = median_claps)) +
  geom_node_text(aes(label = name), repel = TRUE) +
  scale_color_gradient(low = "#104e8b",
                       high = "#ffce00") +
  labs(title = "Pairwise Correlation of Words in the Titles of Medium Data Science Articles",
       subtitle = "Plot below shows that **artificial intelligence** is closely related to **human** and **business**",
       caption = "Source: kaggle.com | Graphic: Sung Inkyung",
       size = "Occurrences",
       color = "Median of Claps") +
  theme_void() +
  theme(plot.title = element_markdown(size = 16),
        plot.subtitle = element_markdown(size = 12,
                                         margin(margin(b = 15)))) 
ggsave(here("figures", "MediumDataScienceArticles.png"), width = 21, height = 15, units = "cm")
```
