---
title: "Nobel Prize Winners"
author: "sung inkyung"
date: "2019 5 27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### source: datascreencast by david robinson:https://github.com/dgrtwo/data-screencasts/blob/master/nobel-prize.Rmd         
```{r}
library(tidyverse)
library(lubridate)
library(LaCroixColoR)
library(patchwork)
library(here)
```

```{r}
nobel_winners <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv") %>% 
  distinct(full_name, prize_year, category, .keep_all = TRUE) %>% 
  mutate(decade = 10 * (prize_year %/% 10),
         age = prize_year - year(birth_date))

nobel_winner_all_pubs <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winner_all_pubs.csv") %>% 
  mutate(prize_decade = 10 * (prize_year %/% 10))
```

```{r}
glimpse(nobel_winners)
glimpse(nobel_winner_all_pubs)
skimr::skim(nobel_winners)
skimr::skim(nobel_winner_all_pubs)
nobel_winners %>% 
  count(category, sort = TRUE)
```

```{r}
nobel_winners %>% 
  mutate(category = fct_reorder(category, age, median, na.rm = TRUE)) %>% 
  ggplot(aes(category, age)) +
  geom_boxplot() +
  geom_jitter(size = .7, alpha =.5) +
  geom_hline(yintercept =  59.5, color = "#8d1673", linetype = "dashed", size = .9) +
  coord_flip()

nobel_winners %>% 
  mutate(category = fct_reorder(category, age, median, na.rm = TRUE)) %>% 
  ggplot(aes(x = fct_rev(category), age, fill = category, alpha = .7)) +
  geom_violin(show.legend = FALSE) +
  geom_jitter(size = .7, alpha =.5,
              show.legend = FALSE) +
  geom_hline(yintercept =  59.5, color = "#8d1673", lty = "dashed", size = .9) +
  scale_fill_manual(values = lacroix_palette("PeachPear", n = 6, type = "discrete")) +
  coord_flip()+
  theme_half_open()

nobel_winners %>% 
  distinct(full_name, prize_year, category, .keep_all = TRUE) %>% 
  mutate(decade = 10 * (prize_year %/% 10),
         age = prize_year - year(birth_date),
         year = prize_year) %>% 
  ggplot(aes(year, age))+ 
  geom_point(size = 3, alpha = .5, color = "black",
             na.rm = TRUE)+
  geom_smooth(aes(fill = "#8d1673"),
              method = "loess",
              na.rm = TRUE) +
  scale_x_continuous() +
  scale_y_continuous() +
  theme(legend.position = "none") +
  labs(title = "Nobel Prize age distribution over time")

```
### source: plotly package by Carson Sievert (https://plotly-r.com/overview.html)
```{r}
library(plotly)

p <- nobel_winners %>% 
  distinct(full_name, prize_year, category, .keep_all = TRUE) %>% 
  mutate(decade = 10 * (prize_year %/% 10),
         age = prize_year - year(birth_date),
         year = prize_year) %>% 
  ggplot(aes(year, age)) + 
  geom_point(alpha = .7,
             na.rm = TRUE,
             show.legend = FALSE) +
  geom_smooth(aes(color = category),
              method = "loess",
              na.rm = TRUE) +
  geom_hline(yintercept = 59.45, 
             lty = "dotted", 
             size = .7, 
             color = "#8d1673") +
  scale_x_continuous(limits = c(1900, 2016),
                     breaks = seq(1900, 2016, 20)) +
  scale_fill_manual(values = lacroix_palette("PeachPear", n = 6, 
                                             type = "discrete")) +
  facet_wrap(~category) +
  theme(legend.position = "none") +
  theme_minimal()

p

# ggplotly(p)
```
### source: gghighlight (https://yutani.rbind.io/post/2017-10-06-gghighlight/)
```{r}
library(gghighlight)

p <- nobel_winners %>% 
  group_by(decade, category) %>% 
  count(decade,
        category) %>% 
  mutate(percent = n / sum(n)) %>% 
  ungroup() %>% 
  ggplot(aes(decade, n)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  gghighlight(category == "Economics") +
  theme_half_open()
p
```

```{r}
p1 <- nobel_winners %>% 
  group_by(decade, category) %>% 
  count(decade,
        category) %>% 
  mutate(percent = n / sum(n)) %>% 
  ungroup() %>% 
  ggplot(aes(decade, n, fill = category)) +
  geom_col() + 
  scale_fill_manual(values = lacroix_palette("PeachPear", n = 6, type = "discrete")) +
  gghighlight() +
  facet_wrap(~category) +
  labs(title = "Category distribution\nin Nobel prize since 1901",
       x = " ",
       y = " ") +
  theme(line = element_blank(),
        panel.border = element_rect(colour = "transparent"),
        plot.background = element_blank(),
        axis.text = element_blank(),
        axis.text.x = element_text(size = 7,
                                   color = "gray40"),
        axis.text.y = element_text(size = 7,
                                   color = "gray40")) +
   theme_half_open() 

p2 <- nobel_winners %>% 
  group_by(decade, category) %>% 
  count(decade,
        category,
        gender= coalesce(gender, laureate_type)) %>% 
  mutate(percent = n / sum(n)) %>% 
  ungroup() %>% 
  ggplot(aes(decade, n, fill = gender)) +
  geom_col() + 
  scale_fill_manual(values = c("#ff73c1", "#0096b7", "#f7c56e")) +
  gghighlight() +
  facet_wrap(~category) +
  theme(line = element_blank(),
        panel.border = element_rect(colour = "transparent"),
        plot.background = element_blank(),
        axis.text = element_blank(),
        axis.text.x = element_text(size = 7,
                                   color = "gray40"),
        axis.text.y = element_text(size = 7,
                                   color = "gray40")) +
      labs(title = "Gender distribution\nin nobel prize since 1901",
       x = " ",
       y = " ") +
  theme_half_open()


caption <- 
  ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(x = "",
       y = "",     
       caption = "Source: Kaggle") +
  theme(plot.caption = element_text(size = 9, 
                                    color = "grey45"),
        line = element_blank(),
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", 
                                       color = "transparent"),
        panel.border = element_rect(colour = "transparent"),
        axis.text = element_blank())
  

p1 + p2 + caption +
  plot_layout(widths = c(1, 1, 0), nrow = 1)


ggsave(here("figures", "category_gender distribution.png"), width = 16, height = 5.7)

```
### sources:[DATA VISUALIZATION BY KIERAN HEALY](https://socviz.co/refineplots.html#use-theme-elements-in-a-substantive-way),                [UC Business Analytics R Programming Guide](http://uc-r.github.io/gda)
```{r}
library(ggridges)

nobel_winners %>% 
    count(decade,
          category,
          gender = coalesce(gender, laureate_type)) %>% 
  group_by(decade, category) %>% 
  mutate(percent = n / sum(n)) %>%
  ggplot(aes(decade, category, 
             color = gender, 
             fill = gender,
             alpha = .7)) +
  ggridges::geom_density_ridges(scale = .95, 
                                rel_min_height = 0.01, 
                                gradient_lwd = 1) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_fill_manual(values = c("#ff73c1", "#0096b7", "#f7c56e"), 
                    labels = c("female", "male", "orgranization")) +
  scale_color_manual(values = c("#ff73c1", "#0096b7", "#f7c56e"), 
                     guide = "none") +
  theme_ridges(font_size = 13, 
               grid = TRUE)+
  theme(axis.title.y = element_blank()) +
  guides(fill = guide_legend(
    override.aes = list(
    fill = c("#ff73c1", "#0096b7", "#f7c56e"),
    color = NA, point_color = NA)))+
  ggtitle("Nobel prize gender distribution per category since 1900") +
  theme_ridges(center = TRUE) 
```

```{r}
nobel_winners %>% 
  count(decade,
        category,
        gender = coalesce(gender, laureate_type)) %>%  
  mutate(percent = n / sum(n)) %>% 
  ggplot(aes(decade, n, fill = category)) +
  geom_col() +
  facet_grid(gender~category) +
  scale_fill_manual(values = lacroix_palette("PeachPear", n = 6, type = "discrete")) +
  theme_half_open() +
  labs(x = "decade",
       Y = "# of Nobel prize winners",
       title = "Nobel prize categroy and gender distribution over time")
    
```

```{r}
nobel_winners %>% 
  filter(!is.na(birth_country)) %>% 
  count(birth_country = fct_lump(birth_country, 9), 
        category, sort = TRUE) %>% 
  mutate(birth_country = fct_reorder(birth_country, n)) %>% 
  ggplot(aes(birth_country, n, fill = category)) +
  geom_col() +
  guides(fill = guide_legend(reverse = TRUE)) +
  coord_flip() +
  scale_fill_manual(values = lacroix_palette("PeachPear", n = 6, type = "discrete")) +
  theme_half_open()
```

```{r}
nobel_winners %>% 
  filter(!is.na(birth_country)) %>% 
  count(birth_country = fct_lump(birth_country, 9), 
        category, sort = TRUE) %>% 
  mutate(birth_country = fct_reorder(birth_country, n)) %>% 
  ggplot(aes(birth_country, n, fill = category)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~category) +
  coord_flip() +
  scale_fill_manual(values = lacroix_palette("PeachPear", n = 6, type = "discrete")) +
  theme_half_open() +
  labs(title = "Category distribution in Nobel prize per country",
       x = " ",
       y =" ")
```
