---
title: "NYC_PizzaRating"
date: '2019 10 9 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggbeeswarm)
library(scales)
library(glue)
library(here)
library(cowplot)
```
### source [Tidy Tuesday screecast: analyzing pizza ratings by david robinson] (https://youtu.be/Mkac8DHScps)
```{r}
pizza_jared <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_jared.csv") %>% 
  mutate(time = as.POSIXct(time, origin = "1970-01-01"),
         date = as.Date(time))


pizza_barstool <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_barstool.csv") 
```

```{r different scale!}
answer_levels =  c("Never Again", "Poor", "Average", "Good", "Excellent")

jared <- pizza_jared %>% 
  mutate(answer = fct_relevel(answer, answer_levels),
         answer_num = as.numeric(answer)) %>% 
  group_by(place, answer) %>% 
  summarise(votes = sum(votes)) %>% 
  mutate(answer_num = as.numeric(answer),
         total = sum(votes),
         percent = votes / total,
         jared_avg = sum(answer_num * percent),
         jared_avg = round(jared_avg, 2)) %>% 
  ungroup()

jared_plot <- jared %>% 
  filter(total > 15) %>% 
  mutate(place = fct_reorder(place, jared_avg)) %>% 
  ggplot(aes(jared_avg, place)) +
  geom_point(aes(size = total)) +
  labs(x = "Average ratign",
       y = "",
       size = "# of reviews",
       title = "NYOSPM ratings of pizza place") +
  theme_minimal()
 
pizza_barstool %>% 
  filter(review_stats_all_count >= 70) %>% 
  mutate(name = fct_reorder(name, review_stats_all_average_score)) %>% 
  ggplot(aes(review_stats_all_average_score, name)) +
  geom_point(aes(size = review_stats_all_count)) +
  labs(x = "Average rating",
       y = "",
       size = "# of reviews",
       title = "Bastool Sports ratings of pizza places",
       subtitle = "Places with at least 70 reviews") +
  theme_minimal()
```

```{r ggbeeswarm plot}

pizza_barstool %>% 
  filter(review_stats_all_count > 20) %>% 
  mutate(city = fct_lump(city, 5)) %>% 
  add_count(city) %>% 
  mutate(city = glue::glue("{ city } ({ n })")) %>% 
  ggplot(aes(city, review_stats_all_average_score, 
             size = review_stats_all_count)) +
  geom_quasirandom(alpha = 0.5,
                   width = 0.3,
                   color = "#fb2e01") +
  stat_summary(fun.y = "median", 
               geom = "point", 
               size = 2.5,
               color = "#abdcf1") +
  stat_summary(fun.y = "median", 
               geom = "line", 
               aes(group = 1),
               size = 1,
               color = "#abdcf1") +
  scale_y_continuous(limits = c(5, 10),
                     expand = c(0, 0)) +
  labs(x = "",
       y = "average score",
       title = "Pizza ratings across cities",
       subtitle = "Pizza places with at least 20 reviews\nMedian of review_all_average_score is on the line") +
  theme_minimal() +
  guides(size = guide_legend(title = "Review count"))
```

```{r}
pizza_reviewers <- pizza_barstool %>% 
  select(place = name,
         price_level,
         contains("review")) %>% 
  rename_all(~str_remove(., "review_stats_")) %>% 
  select(-contains("provider")) %>% 
  pivot_longer(cols = ends_with("average_score"),
               names_to = "reviewers",
               values_to = "score",
               values_drop_na = TRUE) %>% 
  mutate(reviewers = factor(reviewers, 
                            labels = c("Community", "Critics", "Dave", "All"))) %>% 
  mutate(price_level = factor(price_level,
                              labels = c("Very cheep", "Cheep", "Expensive", "Very expensive"))) %>% 
  mutate(score = round(score, 2))
```


```{r}
plot <- pizza_reviewers %>% 
  filter(!reviewers == "All") %>% 
  ggplot() +
  geom_density(aes(x= score, fill = reviewers),
               alpha = 0.5) +
  scale_fill_brewer(palette = "Dark2") +
  scale_y_continuous(labels = scales::percent_format()) +
  facet_grid(~ price_level) +
  labs(x = "Scores",
       y = "",
       title = "Pizza place rating by reviewers",
       subtitle = "Price range from very cheap to expensive appears to be aligned among \nviewers but very expensive price. Reviewrs from community are more aggressive \non price rating comparing to reviewers from other sources.") +
  theme_bw() +
  theme(plot.title = element_text(size = 16),
        legend.position = "bottom", 
        legend.direction = "horizontal",
        strip.text = element_text(size = 9)) +
  guides(fill = guide_legend(nrow = 1))

plot
```
```{r NYOSPM vs Barstool Sports}
barstool <- pizza_barstool %>% 
  select(place = name,
         city,
         price_level,
         contains("review")) %>% 
  rename_all(~str_remove(., "review_stats_")) %>% 
  select(-contains("provider")) %>% 
  filter(place %in% jared$place,
        !city %in% c("Brooklyn", "Miami", "Santa Monica"))

jb <- jared %>% 
  select(place, answer, answer_num, votes, total, jared_avg) %>% 
  left_join(barstool, by = "place") %>%  
  mutate(scale_jared = unlist(as.list(scale(jared_avg))), 
         scale_barstool= unlist(as.list(scale(all_average_score)))) %>% 
  unnest() %>% 
  mutate(price_level = factor(price_level,
                              labels = c("Very cheep", "Cheep", "Expensive"))) %>% 
  filter(!is.na(price_level))

pizza_combo <- jb %>% 
  distinct(place, answer, answer_num, price_level, scale_jared, scale_barstool) %>% 
  pivot_longer(cols = c("scale_jared", "scale_barstool"),
               names_to = "reviewer",
               values_to = "scale",
               values_drop_na = TRUE) %>% 
  mutate(average = round(scale, 2))
```

```{r}
pizza_place <- pizza_combo %>% 
  ggplot() +
  geom_density(aes(scale,  fill = reviewer), 
               alpha = 0.5,
               show.legend = FALSE) +
  scale_fill_manual(values = c("#bbbc1d", "#003363"),
                    labels = c("New York Open\nData Science Meetup",
                               "Barstool Sports")) +
  labs(x = "", 
       y = " ",
       title = "Pizza place ratings from two groups",
       subtitle = "NYODSM members stand slightly \nstronger on rating pizza places \nin New York city than Barstool \nsports reviewers") +
  theme(panel.background = element_blank(),
        legend.position = "none") +
  theme_minimal()


pizza_price <- pizza_combo %>% 
  ggplot()+
  geom_density(aes(scale,  fill = reviewer), 
               alpha = 0.5) +
  scale_fill_manual(values = c("#bbbc1d", "#003363"),
                    labels = c("New York Open\nData Science Meetup",
                               "Barstool Sports")) +
  facet_wrap(~price_level) + 
  labs(x = " ",
       y = " ",
       title = "Pizza price ratings from two groups",
       subtitle = "NYODSM members takes on rating pizza price \nmore aggressively in New York City than \nBarstool sports reviewers.") +
  theme(panel.background = element_blank(),
        legend.position = "top") 

```
### http://rpubs.com/thewiremonkey/534934
### http://docs.statwing.com/interpreting-residual-plots-to-improve-your-regression/ 
```{r}
jb_aov <- aov(scale_barstool ~scale_jared, jb)
jb_stdres <- rstandard(jb_aov)
order(abs(jb_stdres), decreasing = TRUE)[1:6]
```

```{r}
labels <- jb[order(abs(jb_stdres), decreasing = TRUE)[1:30], ]

aov_plot <- jb %>% 
  ggplot(aes(scale_jared, scale_barstool)) +
  geom_point(aes(color = "#tomato",
                 size = abs(jb_stdres))) +
  geom_abline(slope = 1, color = "#7daba1",
              size = 1) +
  geom_smooth(method = "lm",
              size = 0.7,
              color = "#b30417") +
  scale_x_continuous(limits = c(-2, 2)) +
  scale_y_continuous(limits = c(-2, 2)) +
  geom_text(data = labels,
            aes(scale_jared, scale_barstool,
                label = place),
            nudge_y = 0.35) +
  labs(title = "Pizza places with the highest variance in rating", 
       subtitle = "Corresponding pizza places with distinguishable rating difference by NYODSM and \nthe average Barstool Sports reviewer # of size is absolute value of the standardized residuals",
       x = "New York Open Data Science Meetup", 
       y = "Barstool Sports Reviewers",
       caption="source | Jared Lander / Barstool Sports") +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        legend.position = "none") 


ggdraw() +
  draw_plot(pizza_place, x = 0, y = 0.5, width = .5, height = .5) +
  draw_plot(pizza_price, x = 0.5, y = 0.5, width = .5, height = .5) +
  draw_plot(aov_plot, x = 0, y = 0, width = 1, height = 0.5) +
  draw_plot_label(label = c("A", "B", "C"), 
                  size = 14, 
                  x = c(0, 0.5, 0),
                  y = c(1, 1, 0.5))

ggsave(here ("figures", "NYC-PizzaPlaceRatings.png"), width = 7, height = 7, units = "in")
    
```