---
title: "NYC_Squirrel_ChordDiagrams"
author: "Sung Inkyung"
date: '2019 11 4'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(lubridate)
library(scales)
library(circlize)
```

```{r}
nyc_squirrels <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-29/nyc_squirrels.csv")
```

```{r}
shift <- nyc_squirrels %>% 
  group_by(shift) %>% 
  summarize(
    Running = sum(running, na.rm = T),
    Chasing = sum(chasing, na.rm = T),
    Climbing = sum(climbing, na.rm = T),
    Eating = sum(eating, na.rm = T),
    Foraging = sum(foraging, na.rm = T))
  

shift_long <- shift %>% 
  pivot_longer(names_to = "behavior", values_to = "count", -shift)

shift_long$count <- as.numeric(shift_long$count)
shift_long$behavior <- factor(shift_long$behavior, ordered = T,
                              levels = c("Running", "Chasing", "Climbing", "Eating", "Foraging"))
```


```{r Chord Diagram}

circos.clear()
circos.par(start.degree = 90, gap.degree = 1, 
           track.margin = c(-0.2, 0.2),
           points.overflow.warning = F)
par(mar = rep(1, 4))

# Color palette
shift_color <- c(AM = "#fcba03", PM = "#7256ff",
             Running = "#ff5065", Eating = "#ff5065",  
             Climbing = "#ff5065", Chasing = "#ff5065", 
             Foraging = "#ff5065")

# Base plot
chordDiagram(x = shift_long,
             grid.col = chord_color,
             transparency = 0.7,
             link.sort = TRUE,
             link.decreasing = TRUE,
             annotationTrack = "grid",
             annotationTrackHeight = c(0.05, 0.1))

# Add text and axis
circos.trackPlotRegion(
  track.index = 1,
  bg.border = NA,
  panel.fun = function(x, y){
    xlim = get.cell.meta.data("xlim")
    sector.index = get.cell.meta.data("sector.index")
    
    # Add names to the sector
    circos.text(
      x = mean(xlim),
      y = 4.5,
      labels = sector.index,
      facing = "bending",
      cex = .75
    )
    # Add graduation on axis
    circos.axis(
      h = "top",
      major.at = seq(from = 0, to = xlim[2], by = 250)
    )
  }
)
title(main = "The behavior of squirrels by time in New York Central Park")

```

```{r}
color <- nyc_squirrels %>% 
  filter(!is.na(primary_fur_color)) %>% 
  group_by(color = primary_fur_color) %>% 
  summarize(
    Running = sum(running, na.rm = T),
    Chasing = sum(chasing, na.rm = T),
    Climbing = sum(climbing, na.rm = T),
    Eating = sum(eating, na.rm = T),
    Foraging = sum(foraging, na.rm = T)
  )

color_long <- color %>% 
  pivot_longer(names_to = "behavior", values_to = "count", -color)

color_long$count <- as.numeric(color_long$count)

color_long2 <- color_long %>% 
  arrange(desc(color))
```

```{r}
circos.clear()
circos.par(gap.degree = 2, 
           track.margin = c(-0.2, 0.2),
           points.overflow.warning = F)
par(mar = rep(1, 4))

# Color palette
chord_color <- c(Gray = "grey60", Black = "black", Cinnamon = "#d2691e",
             Running = "#ff5065", Eating = "#ff5065",  
             Climbing = "#ff5065", Chasing = "#ff5065", 
             Foraging = "#ff5065")


# Base plot
chordDiagram(x = color_long2,
             grid.col = chord_color,
             transparency = 0.25,
             link.sort = TRUE,
             link.decreasing = TRUE,
             annotationTrack = "grid",
             annotationTrackHeight = c(0.05, 0.1))

# Add text and axis
circos.trackPlotRegion(
  track.index = 1,
  bg.border = NA,
  panel.fun = function(x, y){
    xlim = get.cell.meta.data("xlim")
    sector.index = get.cell.meta.data("sector.index")
    
    # Add names to the sector
    circos.text(
      x = mean(xlim),
      y = 5,
      labels = sector.index,
      facing = "bending",
      cex = 1
    )
    # Change the scaling for the sectors
    circos.axis(
      h = "top",
      major.at = seq(from = 0, to = xlim[2], by = 250),
      minor.ticks = 1,
      major.tick.percentage = 0.5, labels.cex = 0.9,
      labels.niceFacing = FALSE
    )
  }
)
title(main = "The behavior of squirrels by squirrels type in New York Central Park")
```
