---
title: "NYCPizzaRating"
date: '2019 10 9 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggbeeswarm)
library(scales)
library(glue)
```
### [Tidy Tuesday screecast: analyzing pizza ratings by david robinson] (https://youtu.be/Mkac8DHScps)
```{r}
pizza_jared <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_jared.csv") %>% 
  mutate(time = as.POSIXct(time, origin = "1970-01-01"),
         date = as.Date(time))


pizza_barstool <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_barstool.csv") 
```

```{r}
pizza_barstool %>% 
  filter(review_stats_all_count >= 70) %>% 
  mutate(name = fct_reorder(name, review_stats_all_average_score)) %>% 
  ggplot(aes(review_stats_all_average_score, name)) +
  geom_point(aes(size = review_stats_all_count)) +
  labs(x = "Average rating",
       y = "",
       size = "# of reviews",
       title = "Bastool Sports ratings of pizza places",
       subtitle = "Places with at least 50 reviews") +
  theme_minimal()
```

```{r ggbeeswarm plot}

pizza_barstool %>% 
  filter(review_stats_all_count > 20) %>% 
  mutate(city = fct_lump(city, 5)) %>% 
  add_count(city) %>% 
  mutate(city = glue::glue("{ city } ({ n })")) %>% 
  ggplot(aes(city, review_stats_all_average_score, 
             size = review_stats_all_count)) +
  geom_quasirandom(alpha = 0.5,
                   width = 0.3,
                   color = "#fb2e01")+
  stat_summary(fun.y = "median", 
               geom = "point", 
               size = 2.5,
               color = "#abdcf1") +
  stat_summary(fun.y = "median", 
               geom = "line", 
               aes(group = 1),
               size = 1,
               color = "#abdcf1") +
  scale_y_continuous(limits = c(5, 10),
                     expand = c(0, 0)) +
  labs(x = "",
       y = "average score",
       title = "Pizza ratings across cities",
       subtitle = "Pizza places with at least 20 reviews\nMedian of review_all_average_score is on the line") +
  theme_minimal() +
  guides(size = guide_legend(title = "Review count"))
```

```{r}
pizza_reviewers <- pizza_barstool %>% 
  select(place = name,
         price_level,
         contains("review")) %>% 
  rename_all(~str_remove(., "review_stats_")) %>% 
  select(-contains("provider")) %>% 
  pivot_longer(cols = ends_with("average_score"),
               names_to = "reviewers",
               values_to = "score",
               values_drop_na = TRUE) %>% 
  mutate(reviewers = factor(reviewers, 
                            labels = c("Community", "Critics", "Dave", "All"))) %>% 
  mutate(price_level = factor(price_level,
                              labels = c("Very cheep", "Cheep", "Expensive", "Very expensive"))) %>% 
  mutate(score = round(score, 2))
```


```{r}
plot <- pizza_reviewers %>% 
  filter(!reviewers == "All") %>% 
  ggplot()+
  geom_density(aes(x= score, fill = reviewers),
               alpha = 0.5) +
  scale_fill_brewer(palette = "Dark2") +
  scale_y_continuous(labels = scales::percent_format())+
  facet_grid(~ price_level) +
  labs(x = "Scores",
       y = "",
       title = "Pizza place rating by reviewers",
       subtitle = "Price range from very cheap to expensive appears to be aligned among \nviewers but very expensive price. Reviewrs from community are more aggressive \non price rating comparing to reviewers from other sources.") +
  theme_bw() +
  theme(plot.title = element_text(size = 16),
        legend.position = "bottom", 
        legend.direction = "horizontal",
        strip.text = element_text(size = 9)) +
  guides(fill = guide_legend(nrow = 1))

plot
```
```{r}
answer_levels =  c("Never Again", "Poor", "Average", "Good", "Excellent")

pizza_j <- pizza_jared %>% 
  mutate(answer = fct_relevel(answer, answer_levels)) %>% 
  group_by(place, answer) %>% 
  summarise(votes = sum(votes)) %>% 
  mutate(total = sum(votes),
         percent = votes / total,
         answer_num = as.numeric(answer),
         jared_avg = sum(answer_num * percent),
         jared_avg = round(jared_avg, 2)) %>% 
  ungroup()

pizza_b <- pizza_barstool %>% 
  select(place = name,
         city,
         price_level,
         contains("review")) %>% 
  rename_all(~str_remove(., "review_stats_")) %>% 
  select(-contains("provider")) %>% 
  filter(place %in% pizza_j$place,
        !city %in% c("Brooklyn", "Miami", "Santa Monica"))

pizza_jb <- pizza_j %>% 
  select(place, answer, answer_num, votes, total, jared_avg) %>% 
  left_join(pizza_b, by = "place") %>%  
  mutate(scale_jared = unlist(as.list(scale(jared_avg))), 
         scale_barstool= unlist(as.list(scale(all_average_score)))) %>% 
  unnest() %>% 
  mutate(price_level = factor(price_level,
                              labels = c("Very cheep", "Cheep", "Expensive"))) %>% 
  filter(!is.na(price_level))


pizza_combo <- pizza_jb %>% 
  distinct(place, answer, answer_num, price_level, scale_jared, scale_barstool) %>% 
  pivot_longer(cols = c("scale_jared", "scale_barstool"),
                names_to = "reviewer",
                values_to = "scale",
                values_drop_na = TRUE) %>% 
  mutate(average = round(scale, 2))
```


```{r}
pizza_combo %>% 
  ggplot() +
  geom_density(aes(scale,  fill = reviewer), 
               alpha = 0.5)+
  scale_fill_manual(values = c("#bbbc1d", "#003363"),
                    labels = c("New York Open\nData Science Meetup",
                               "Barstool Sports")) +
  labs(x = "scale",
       y = "density",
       title = "Pizza place ratings from two groups",
       subtitle = "NYODSM members stand slightly stronger on rating pizza places \nin New York citythan Barstool sports raters  ",
       caption="source | Jared Lander / Barstool Sports") +
  theme(panel.background = element_blank(),
        legend.position = "bottom") +
  theme_minimal()


pizza_price <- pizza_combo %>% 
  ggplot()+
  geom_density(aes(scale,  fill = reviewer), 
               alpha = 0.5)+
  scale_fill_manual(values = c("#bbbc1d", "#003363"),
                    labels = c("New York Open\nData Science Meetup",
                               "Barstool Sports")) +
  facet_wrap(~price_level) + 
  labs(x = "scale",
       y = "density",
    title = "Pizza price from two groups",
    subtitle = "NYODSM members takes on rating pizza price more aggressively \nin New York City than Barstool sports raters.",
    caption="source | Jared Lander / Barstool Sports") +
  theme(panel.background = element_blank(),
        legend.position = "bottom") 
```

