---
title: "selected books from bible"
author: "sung inkyung"
date: '2019 8 7'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## sources: http://uc-r.github.io/tidy_text
### Tidying Text & Word Frquency
```{r}
library(tidyverse)
library(tidytext)
library(cowplot)
```

```{r}
bible <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/bible_kjv_new.csv") %>% 
  view()
```

```{r}
bible_text <- bible %>% 
  unnest_tokens(word, text) %>% 
  count(word, sort = TRUE)
```

```{r}
bible_text %>% 
  anti_join(stop_words) %>% 
  count(word, sort = TRUE)
```

```{r}
bible %>% 
  count(book)
```

```{r}

books_filtered <- bible %>% 
  filter(book %in% c("Job", "Psalms", "Proverbs", "Ecclesiastes")) %>% 
  select(-c(citation, verse)) %>% 
  unnest_tokens(word, text) 
```

```{r}
books_filtered %>% 
  count(word, sort = TRUE)
```

```{r}
books_filtered %>% 
  anti_join(stop_words) %>% 
  filter(!(word %in% c("thy", "thou", "thine", "thee", "hast", "hath", "lord", "god", "ye")),
         str_detect(word, "[a-z]")) %>%
  count(word, sort = TRUE)
```

```{r}
books_filtered %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(!(word %in% c("thy", "thou", "thine", "thee", "hast", "hath", "lord", "god", "ye")),
         str_detect(word, "[a-z]")) %>%
  group_by(book) %>%
  count(word, sort = TRUE) %>%
  top_n(10)
```

```{r}
# top 10 most common words in each book

books_filtered %>% 
  anti_join(stop_words) %>% 
  filter(!(word %in% c("thy", "thou", "thine", "thee", "hast", "hath", "lord", "god", "ye")),
         str_detect(word, "[a-z]")) %>% 
  group_by(book) %>% 
  count(word, sort = TRUE) %>% 
  top_n(10) %>% 
  ungroup() %>% 
  mutate(book = factor(book),
         text_order = nrow(.) :1) %>% 
  ggplot(aes(reorder(word, text_order), n, fill = book)) +
  geom_bar(stat = "identity") +
  facet_wrap(~book, scales = "free_y") +
  labs(x = "", 
       y = "Frequency") +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none")
  
```


```{r}
# calculate percent of word use across the selected books

books_pct <- books_filtered %>% 
  anti_join(stop_words) %>% 
  filter(!(word %in% c("thy", "thou", "thine", "thee", "hast", "hath", "lord", "god", "ye")),
         str_detect(word, "[a-z]")) %>%
  count(word) %>% 
  transmute(word, all_words = n / sum(n))

# calculate percent of word use within each book
frequency <- books_filtered %>% 
  anti_join(stop_words) %>% 
  filter(!(word %in% c("thy", "thou", "thine", "thee", "hast", "hath", "lord", "god", "ye")),
         str_detect(word, "[a-z]")) %>%
  count(book, word) %>% 
  mutate(book_words = n/ sum(n)) %>% 
  left_join(books_pct, by = "word") %>% 
  arrange(desc(book_words)) %>% 
  ungroup()

frequency
```

```{r}
ggplot(frequency, 
       aes(book_words, all_words, 
           color = abs(all_words - book_words))) +
  geom_abline(color = "gray40", lty = 2) +
  geom_jitter(alpha = .3, 
              size = 1.7, 
              width = .3,
              height = .3) +
  geom_text(aes(label = word),
            check_overlap = TRUE,
            vjust = 1.5) +
  scale_x_log10(labels = scales::percent_format()) +
  scale_y_log10(labels = scales::percent_format()) +
  scale_color_gradient(limits = c(0, 0.001),
                       low = "darkslategray4", 
                       high = "gray75") +
  facet_wrap(~book, ncol = 2) +
  theme(legend.position = "none") +
  labs(y = "Selected books from bible",
       x = " ")
```

```{r}
frequency %>% 
  group_by(book) %>% 
  summarise(coorelation = cor(book_words, all_words),
            p_value = cor.test(book_words, all_words)$p.value)
```

```{r Sentiment Analysis}
# to see the individual lexicons try
get_sentiments("afinn")
get_sentiments("bing")
get_sentiments("nrc")
```

```{r}
books_filtered %>% 
  right_join(get_sentiments("nrc")) %>% 
  filter(!is.na(sentiment)) %>% 
  count(sentiment, sort = TRUE)
```
```{r}
books_filtered %>% 
  group_by(book) %>% 
  mutate(word_count = 1:n(),
         index = word_count %/% 500 + 1) %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(book, index = index, sentiment) %>% 
  ungroup() %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative,
         book = factor(book)) %>% 
  ggplot(aes(index, sentiment, fill = book))+
  geom_bar(alpha = .7, stat = "identity", show.legend = FALSE) +
  facet_wrap(~book, ncol = 2, scales = "free_x") +
  labs(title = "Sentiment of Ecclesiates, Job, Proverbs, and Psalms") +
  theme(plot.background = element_rect()) +
  theme_minimal()

ggsave("C:/Users/inkyscope/Documents/projectR/dvRscope/figures/sentimentPlot.png")
```

```{r comparing sentiments}

afinn <-  books_filtered %>% 
  group_by(book) %>% 
  mutate(word_count = 1:n(),
         index = word_count %/% 500 + 1) %>% 
  inner_join(get_sentiments("afinn")) %>% 
  group_by(book, index) %>% 
  summarise(sentiment = sum(score)) %>% 
  mutate(method = "AFINN")

bing_and_nrc <- bind_rows(books_filtered %>%
                  group_by(book) %>% 
                  mutate(word_count = 1:n(),
                         index = word_count %/% 500 + 1) %>% 
                  inner_join(get_sentiments("bing")) %>%
                  mutate(method = "BING"),
          books_filtered %>%
                  group_by(book) %>% 
                  mutate(word_count = 1:n(),
                         index = word_count %/% 500 + 1) %>%
                  inner_join(get_sentiments("nrc") %>%
                                     filter(sentiment %in% c("positive", "negative"))) %>%
                  mutate(method = "NRC")) %>%
        count(book, method, index = index , sentiment) %>%
        ungroup() %>%
        spread(sentiment, n, fill = 0) %>%
        mutate(sentiment = positive - negative) %>%
        select(book, index, method, sentiment)
```

```{r}
library(wesanderson)

bind_rows(afinn, 
          bing_and_nrc) %>% 
  ungroup() %>% 
  mutate(book = factor(book, levels = titles)) %>% 
  ggplot(aes(index, sentiment, fill = method)) +
  geom_bar(stat = "identity",
           show.legend = FALSE) +
  scale_fill_manual(values = wes_palette (n=3,                                       name="Moonrise2")) +
  facet_grid(book ~ method) +
  theme_minimal()
```

```{r Common Sentiment Words}
bing_word_counts <- books_filtered %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(word, sentiment, sort = TRUE) %>% 
  ungroup()
```

```{r}
bing_word_counts %>% 
  group_by(sentiment) %>% 
  top_n(10) %>% 
  ggplot(aes(reorder(word, n), n, fill = sentiment)) +
  geom_bar(alpha = 0.8, stat = "identity", 
           show.legend = FALSE) +
  scale_fill_manual(values = c("#869c98", "#00fa9a")) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Word category by sentiment",
       x = "") +
  coord_flip() +
  theme_minimal()
```

```{r Sentiment Analysis with Larger Units}
psalms_sentences <- bible %>% 
  filter(book %in% "Psalms") %>% 
  select(-c(citation, verse)) %>% 
  unnest_tokens(sentence, text, token = "sentences")
```

```{r}
psalms_sent<- psalms_sentences %>%
        group_by(chapter) %>%
        mutate(sentence_num = 1:n(),
               index = round(sentence_num / n(), 2)) %>%
        unnest_tokens(word, sentence) %>%
        inner_join(get_sentiments("afinn")) %>%
        group_by(chapter, index) %>%
        summarise(sentiment = sum(score, na.rm = TRUE)) %>%
        arrange(desc(sentiment))

psalms_sent
```

```{r}
ggplot(psalms_sent, aes(index, 
                        factor(chapter, 
                               levels = sort(unique(chapter),
                                             decreasing = TRUE)),
                        fill = sentiment)) +
        geom_tile() +
        scale_fill_distiller(type = "div", palette = "Spectral") +
        scale_x_continuous(labels = scales::percent, 
                           expand = c(0, 0)) +
        scale_y_discrete(expand = c(0, 0)) +
        labs(x = "Chapter Progression", y = "Chapter") +
        ggtitle("Sentiment of Bible and Psalms",
                subtitle = "Summary of the net sentiment score through each chapter") +
        theme_minimal() +
        theme(panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              legend.position = "top")
```

```{r Term vs Document Frequency}
books_words <-  books_filtered %>% 
  count(book, word, sort = TRUE) %>% 
  ungroup()

books_filtered_words <- books_words %>% 
  group_by(book) %>% 
  summarise(total = sum(n))

books_words <- left_join(books_words, books_filtered_words, by = "book")
```

```{r}
books_words %>% 
  mutate(ratio = n / total) %>% 
  ggplot(aes(ratio, fill = book)) +
  geom_histogram(show.legend = FALSE) +
  scale_x_log10() +
  facet_wrap(~book, ncol = 2)
```

```{r Zipf's Law}
freq_by_rank <- books_words %>% 
  group_by(book) %>% 
  mutate(rank = row_number(),
         term_freq = n / total)

freq_by_rank %>% 
  ggplot(aes(rank, term_freq,
             color = book)) +
  geom_line() +
  scale_x_log10() +
  scale_y_log10() +
  theme_minimal()
```

```{r}
lower_rank <- freq_by_rank %>%
        filter(rank < 500)

lm(log10(term_freq) ~ log10(rank), data = lower_rank)
```

```{r}
freq_by_rank %>% 
        ggplot(aes(rank, term_freq, color = book)) +
        geom_abline(intercept = -0.6945, slope = -1.0783, 
                    color = "gray50", linetype = 2) +
        geom_line(size = 1.2, alpha = 0.8) +
        scale_x_log10() +
        scale_y_log10() +
  theme_minimal()
```

```{r}
books_words <-  books_words %>% 
  bind_tf_idf(word, book, n) %>% 
  arrange(desc(tf_idf))
```

```{r}
books_words %>% 
  arrange(desc(tf_idf)) %>% 
  mutate(word = factor(word, levels = rev(unique(word))),
         book = factor(book, levels = titles)) %>% 
  group_by(book) %>% 
  top_n(15, wt = tf_idf) %>% 
  ungroup() %>% 
  ggplot(aes(word, tf_idf, fill = book)) +
  geom_bar(stat = "identity", alpha = .7, 
           show.legend = FALSE) +
  labs(title = "Highest tf-idf word in the selected bible books",
       x = NULL,
       y = "tf-idf") +
  facet_wrap(~book, ncol = 2, scales = "free") +
  coord_flip() +
  theme_minimal()
```
