---
title: "PA-ParkingTickets"
author: "Sung Inkyung"
date: '2019 12 5 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(osmdata)
library(scales)
library(lubridate)
library(ggpointdensity)
library(paletteer)
```

```{r}
tickets <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-03/tickets.csv") 
```

```{r}
p1 <- tickets %>% 
  mutate(violation_desc = fct_lump(violation_desc, n = 22, 
                                   other_level = "Others")) %>% 
  group_by(violation_desc) %>% 
  summarise(total = sum(fine)) %>% 
  ungroup() %>% 
  mutate(violation_desc = fct_reorder(violation_desc, total)) %>% 
  ggplot(aes(violation_desc, total, fill = violation_desc)) +
  geom_col(show.legend = FALSE) +
  coord_flip()+
  scale_y_continuous(label = dollar_format()) +
  scale_fill_paletteer_d(pals, stepped) +
  labs(x = "",
       y = "Total fine amount",
       title = "Total amount of fine for 10 violation types") +
  theme_minimal()

p1
```
```{r}
library(gghighlight)
library(ggtext)

agency <- tickets %>% 
  mutate(day = as.factor(wday(issue_datetime, label = TRUE, abbr = TRUE)),
         month = month(issue_datetime, label = TRUE, abbr = TRUE),
         hour = as.factor(hour(issue_datetime)),
         date = date(issue_datetime)) 
  
housing <- agency %>% 
  filter(issuing_agency == "HOUSING")

p2 <- agency %>% 
  group_by(issuing_agency, month) %>% 
  summarise(total = sum(fine),
            n = n()) %>% 
  mutate(avg = round(total / n, 2)) %>% 
  ungroup() %>% 
  ggplot(aes(month, avg, group = issuing_agency, color = issuing_agency)) +
  geom_line(color = "#ff0000") +
  gghighlight(issuing_agency == "HOUSING",
             unhighlighted_colour = alpha("#dedede", 0.7),
             use_direct_label = TRUE,
             label_key = issuing_agency) +
  scale_x_discrete(labels = month.abb) +
  scale_y_continuous(limits = c(0, 120),
                     breaks = seq(0, 120, 20),
                     expand = c(0.01, 0)) +
  scale_color_paletteer_d(pals, stepped) +
  labs(x = "",
       y = "Average of fines",
       title = "Parking violation tickets in Philadelphia",
       subtitle = "In 2017, the highest fine share of parking ticket was issued from <span style = 'color: #ff0000'>**housing agency**.</span>",
       caption = "Source: Open Data Philly") +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_markdown(size = 16),
        plot.subtitle = element_markdown(size = 11))
  
  p2
```

```{r}
wday <- agency %>% 
  group_by(day, hour) %>% 
  summarise(total = sum(fine, 
                        na.rm = TRUE),
            n = n(),
            avg = total / n) %>% 
  ungroup() %>% 
  mutate(day = case_when(
    day == "일" ~ "Sunday",
    day == "월" ~ "Monday",
    day == "화" ~ "Tueday",
    day == "수" ~ "Wednesday",
    day == "목" ~ "Thursday",
    day == "금" ~ "Friday",
    day == "토" ~ "Saturday"
  )) 

p3 <- wday %>% 
  ggplot(aes(hour, day, fill = avg)) +
  geom_tile(color = "white", size = 0.1) +
  coord_equal() +
  scale_fill_paletteer_c(gameofthrones, targaryen2,
                         name = "Fine avg") +
  labs(x = "",
       y = "",
       title = "Parking ticket fines over day",
       subtitle = "Saturday morning is idle on issuing parking ticket") +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 16),
        plot.subtitle = element_text(size = 11))
  
p3
  
p4 <- wday %>% 
  ggplot(aes(hour, day, fill = n)) +
  geom_tile(color = "white", size = 0.1) +
  scale_fill_paletteer_c(gameofthrones, targaryen2,
                         name = "Frequency") +
  labs(x = "Hour of day",
       y = "",
       title = "Parking ticket frequency over day",
       subtitle = "Daily activities are peaked right before lunch time \nduring weekdays according to the number of parking tickets",
       caption = "Source: Open Data Philly") +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 16),
        plot.subtitle = element_text(size = 11))
p4

##  need to figure out how to order weekdays; i tried as follwos but not worked. I got NA as well.
## mutate(day = ordered(day, levels=c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")))
```
### Source[osmdata package] (https://ggplot2tutor.com/streetmaps/streetmaps/)
```{r osmdata features}
available_features()
available_tags("highway")
```

```{r}

philly <- getbb("Philadelphia")

street1 <- 
  opq(philly) %>% 
  add_osm_feature(key = "highway",
                  value = c("primary", "secondary", "motorway", "tertiary")) %>%
  osmdata_sf()

street2 <- 
  opq(philly) %>% 
  add_osm_feature(key = "highway",
                  value = c("residential", "living street", "unclassified", "services", "footway")) %>% 
  osmdata_sf()


violation <- tickets %>% 
  filter(between(lon, philly[1,1], philly[1,2]), 
         between(lat, philly[2,1], philly[2,2])) %>% 
  mutate_at(c("lat", "lon"), ~round(.x, 3)) %>% 
  filter(issuing_agency == "HOUSING")

map <- violation %>% 
  ggplot() +
  geom_sf(data = street1$osm_lines, color = "black", size = 0.4) +
  geom_sf(data = street2$osm_lines, color = "gray50", size = 0.1) +
  geom_pointdensity(aes(lon, lat), size = 1, alpha = 0.7,
                    show.legend = FALSE) +
  scale_color_paletteer_c(gameofthrones, targaryen2) +
  coord_sf(xlim = philly[1,],
           ylim = philly[2,],
           expand = FALSE) +
  labs(x = "",
       y = "",
       title = "Parking violations issued by housing agency in Philadelphia",
       caption = "Open Data Philly") +
  theme(legend.position = "none") +
  theme_void()
  
  
```
