---
title: "NationalParkVisits"
author: "Tidy Tuesday"
date: '2019 9 17 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(forcats)
library(tidybayes)
library(here)
library(scales)
```

```{r}
park_visits <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/national_parks.csv")

state_pop <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/state_pop.csv")

gas_price <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/gas_price.csv")
```
### source[tidy tuesday by Georgios Karamanis](https://github.com/gkaramanis/tidytuesday/tree/master/week-38)
```{r}
pv <-  park_visits %>% 
  distinct(year, unit_name, unit_type, visitors) %>% 
  filter(unit_type == "National Park" & year != "Total") %>% 
  mutate(year = as.numeric(year)) %>% 
  group_by(unit_name) %>% 
  filter(unit_name != "Denaili National Preserve") %>% 
  mutate(mean = mean(visitors),
         mean = round(mean, 2),
         pct = log10(visitors / mean),
         pct = round(pct, 2),
         pct_cut = cut_interval(pct, 10)) %>% 
  add_tally()

```


```{r}
pv %>% 
  ggplot(aes(year, n), color = pct_cut) +
  stat_intervalh(.width = c(.1, .25, .5, .75, 1), 
                   height = 5, show.legend = F)  +
  scale_x_continuous(breaks = seq(1910, 2010, 20)) +
  scale_y_continuous(breaks = seq(0, 120, 20)) +
  facet_wrap(vars(fct_reorder(unit_name, -n)), ncol = 3) +
  rcartocolor::scale_color_carto_d(palette = "Azure") +
  labs(
    title = "National Park Visits, 1904–2016",
    caption = "Source: dataisplural/data.world" 
  ) +
  guides(color = guide_colorbar(
    title.position = "top",
    label.position = "top",
    title = NULL,
    ticks = FALSE,
    barwidth = 20,
    barheight = 0.5
  )) +
  theme_void() +
  theme(
    legend.position = "none",
    legend.title = element_text(size = 9, color = "grey20"),
    strip.text = element_text(color = "grey30",
                              hjust = 1, 
                              vjust = 1),
    plot.title = element_text(size = 14),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_text(size = 7, color = "grey40"),
    axis.text.x = element_text(size = 7, color = "grey40"),
    panel.grid.major.x = element_line(color = "grey75"))

```
### source[tidy tuesday by Joshua Feldman](https://github.com/joshua-feldman/tidy-tuesday/blob/master/2019-09-17-national-park-visits/script.R)
```{r}
pv_year <- park_visits %>% 
  filter(year != "Total") %>% 
  mutate(year = as.numeric(year)) %>% 
  group_by(year) %>% 
  summarise(visitors = sum(visitors))

sp_year <- state_pop %>% 
  group_by(year) %>% 
  summarise(pop = sum(pop))

full <- pv_year %>% 
  left_join(sp_year) %>% 
  left_join(gas_price) %>% 
  select(-gas_current)

full <- full[complete.cases(full),]

```


```{r}
main_plot <- full %>% 
  mutate(pop = pop / 1000000) %>% 
  mutate(visitors = visitors / 1000000) %>% 
  ggplot()+
  geom_line(aes(year, pop), lwd = 0.7,
            col = "goldenrod") +
  geom_line(aes(year, visitors), lwd = 1,
            col = "ForestGreen") +
  annotate("text",
           label = "Population",
           x = 1960, y = 200,
           col = "goldenrod",
           size = 5) +
  annotate("text",
           label = "Visitors",
           x = 1960, y = 100,
           col = "mediumorchid",
           size = 5) +
  labs(title = "Visits to US national parks have stalled – despite a rising population",
       subtitle = "In the 1980s and 1990s, national park visitors outnumbered the US population. However, increasing petrol prices\nhave deterred home travellers, as the number of visitors has levelled off.",
       x = NULL,
       y = NULL,
       caption = "Source: dataisplural/data.world") +
  scale_y_continuous(labels = scales::unit_format(unit = "m"))

main_plot
```

```{r}
sub_plot <- full %>% 
  ggplot(aes(year, gas_constant)) +
  labs(title = "Gas price",
       x = "",
       y = "") +
  geom_line(lwd = 0.7,
            col = "coral") +
  theme(plot.background = element_rect(color = "#CCCDC6", 
                                       fill = "#CCCDC6"),
        panel.background = element_rect(color = "#CCCDC6", 
                                        fill = "#CCCDC6"),
        panel.grid.major = element_line(color = "#808080", 
                                        size = rel(0.5)),
        panel.grid.minor = element_line(color = "#808080", 
                                        size = rel(0.25)),
        title = element_text(size = 9),
        plot.title = element_text(size = 9),
        axis.text.x = element_text(size = 7),
        axis.text.y = element_text(size = 7),
        ) +
  theme_half_open()
    
sub_plot
```
```{r}
sub_plot <- ggplotGrob(sub_plot)
```

```{r}
main_plot +
  annotation_custom(
    grob = sub_plot,
    xmin = 1990,
    xmax = 2015,
    ymin = 25,
    ymax = 150
  )
```

