---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(streamgraph)
```


```{r}
r4ds_members <-
        readr::read_csv(
                "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-16/r4ds_members.csv"
        )

```
 

```{r}
inds <- grep("messages_in", names(r4ds_members))
r4ds_members <- r4ds_members[, c(inds, 1)]
```


```{r}
type <- r4ds_members %>% 
  select(date, messages_in_public_channels, messages_in_private_channels, messages_in_shared_channels, messages_in_d_ms) %>% 
  #rename(c("Public channel" = "messages_in_public_channels",
        # "Private channel" = "messages_in_private_channels",
        # "Shared channel" = "messages_in_shared_channels",
        # "Direct channel" = "messages_in_d_ms")) %>%  # Error: All arguments must be named
  pivot_longer(
               names_to = "type",
               values_to = "total",
               -date) 

plot <- type %>% 
  group_by(date, type) %>% 
  tally(wt = total) %>% 
  streamgraph("type", "n", "date", offset = "zero", interpolate = "step") %>%
  sg_axis_x(1, "month", "%d/%Y") %>% 
  sg_fill_brewer(palette = "Paired") %>% 
  sg_legend(show=TRUE, label="Message Type: ")

plot <- type %>% 
  group_by(date, type) %>% 
  tally(wt = total) %>% 
  streamgraph("type", "n", "date") %>%
  sg_axis_x(1, "month", "%d/%Y") %>% 
  sg_fill_tableau(palette = "colorblind10") %>% 
  sg_legend(show=TRUE, label="Message Type: ")
```

