---
title: "RamenRatings"
author: "Sung Inkyung"
date: '2019 6 5 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
library(skimr)
library(broom)
library(tidybayes)
library(cowplot)
library(here)
```
### source[tidy tuesday by david robinson](https://github.com/dgrtwo/data-screencasts/blob/master/ramen-ratings.Rmd)
### source[tidy tuesday by carsten stann](https://github.com/carstenstann/TidyTuesday/blob/master/2019/2019_23_RamenRatings.Rmd)
```{r}
ramen_ratings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-04/ramen_ratings.csv")
```

```{r}
library(drlib)

ramen_ratings_gathered <- ramen_ratings %>%  
  mutate(style = fct_relevel(fct_lump(style, 4), "Other"),
         country = fct_relevel(fct_lump(country, 12), "Other"),
         brand = fct_relevel(fct_lump(brand, 12), "Other"))%>%
  replace_na(list(style = "Other")) %>%  
  drop_na()

skim(ramen_ratings_gathered) 


ramen_ratings_gathered %>% 
  gather(category, value, -review_number, -stars) %>% 
  count(category, value) %>% 
  group_by(category) %>% 
  top_n(20, n) %>%
  ungroup() %>% 
  mutate(value = drlib::reorder_within(value, n, category)) %>% 
  ggplot(aes(value, n, fill = category)) +
  geom_col(show.legend = FALSE)+
  facet_wrap(~category, scales = "free_y") +
  scale_x_reordered()+ # package(drlib)
  coord_flip()+
  labs(title = "Categories relating to ramen rating",
  x = "category",
  y = " ") +
  theme_minimal()
```

```{r plot}
plot_theme <- 
  theme(title = element_text(size = 10),
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 11, 
                                     face = "plain"),
        axis.text = element_text(size = 9),
        legend.text = element_text(size = 9),
        legend.position = "none",
        legend.margin = margin(0,0,0,0, "cm"),
        plot.caption = element_text(hjust = 1)) +
  theme_minimal()
```

```{r joint plots}
p1 <- lm(stars ~brand + country + style, ramen_ratings_gathered) %>%   
  tidy(conf.int = TRUE) %>% # for coefficient plot
  filter(term != "(Inercept)") %>%
  arrange(desc(estimate)) %>% 
  extract(term, c("category", "term"), "^([a-z]+)([A-Z].*)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  drop_na() %>% 
  ggplot(aes(estimate, term, color = category)) +
  geom_point(na.rm = TRUE,
             show.legend = FALSE) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high),
                 show.legend = FALSE) +
  geom_vline(lty =2, 
             color = "#9a2543",
             xintercept = 0) +
  facet_wrap(~ category, ncol = 1, 
             scales = "free_y") +
  scale_color_brewer(palette = "Set2") +
  labs(x = "Coefficient",
       y =" ",
       title = "Categories relating to ramen ratings") +
  theme_minimal() +
  theme(axis.title = element_blank(),
              panel.grid.major.x = element_blank(),
              panel.grid.minor = element_blank(),
              plot.title = element_text(size = 16, margin = margin(b = 10)),
              plot.subtitle = element_text(size = 11, color = "darkslategrey", margin = margin(b = 25)),
              plot.caption = element_text(size = 9, margin = margin(t = 10), color = "#757575", hjust = 1))


tol11qualitative=c("#332288", "#6699CC", "#88CCEE", "#44AA99", "#117733", 
                   "#999933", "#DDCC77", "#661100", "#CC6677", "#882255",
                   "#AA4499")
 
p2 <- ramen_ratings_gathered  %>% 
  mutate(country = fct_lump(country, 10),
         country = fct_relevel(country, "Other")) %>% 
  ggplot(aes(stars, country)) +
  stat_intervalh(.width = c(.1, .25, .5, .75, 1),
                 height = 5, 
                 show.legend = FALSE) +
  rcartocolor::scale_colour_carto_d(palette = "Peach") +
    #geom_density_ridges(scale = 2, 
                     # aes(fill = country), 
                     # alpha = 0.5,
                     # color = "#0000001A",
                     # na.rm = TRUE,
                     # show.legend = FALSE) +
  geom_point(aes(stars, country), 
             color = "#4d3093", 
             size = 0.1, 
             alpha = 0.1)+
  geom_vline(lty =2, 
             xintercept = 3.69,
             alpha = 0.8) +
  scale_fill_manual(values = tol11qualitative) +
  labs(title = "Top 10 countries in ramen ratings",
       x = "rating",
       y = " ") +
  plot_theme


p3 <- ramen_ratings%>%
  count(country = fct_lump(country, 12), 
        brand = fct_lump(brand, 20), sort=TRUE)%>%
  mutate(colour = case_when(
    country == "United States" ~ "#1B9E77",
    country == "South Korea" ~ "#666666",
    country == "Malaysia" ~ "#66A61E",
    country == "Indonesia" ~ "#7570B3",
    country == "Taiwan" ~ "#A6761D",
    country == "China" ~ "#D95F02",
    country == "Thailand" ~ "#E6AB02",
    country == "Japan" ~ "#E7298A",
    T ~ "#808080"))%>%
  ggplot(aes(x = 0,
             y = fct_rev(factor(country)),
             xend = brand,
             yend = 1, 
             colour= colour,
             alpha = (colour != "grey60")
             ))+
  geom_curve(aes(colour = colour), 
             curvature = -0.5, 
             arrow = arrow(length = unit(0.005, "npc")), 
             show.legend = F) +
  scale_x_discrete() +
  scale_y_discrete() +
  scale_color_identity() +
  scale_size_identity() +
  scale_alpha_manual(values = c(0.1, 0.2), guide = F) +
  scale_size_manual(values = c(0.1, 0.4), guide = F) +
  labs(y = " ",
       x = "Brand",
       title = "Top 20 Ramen brands from their origin countries",
       caption = "Source: The Ramen Rater") +
  theme_minimal () +
  theme(
    title = element_text(size = 10), 
    panel.grid = element_blank(),
    legend.position = "none",
    axis.text.x = element_text(angle = 40, 
                               hjust = 1, 
                               margin = margin(t = -2, r = 0, b = 0, l = 0))
  )
  
```

```{r Layout plots in grid}
plot_grid(p1, plot_grid(p2, p3), 
          ncol = 1, 
          rel_heights = c(1.2, 1))

ggsave(here("figures", "categories for ramen rating.png"), width = 10, height = 10, units = "in")
```
