---
title: "SeattleCatDogNames"
author: "Sung Inkyung"
date: '2019 10 4 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(lubridate)
library(scales)
library(broom)
library(ggrepel)
library(cowplot)
```

```{r}
seattle_pets <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-26/seattle_pets.csv") %>% 
  mutate( year = year(mdy(license_issue_date)),
          animal_name = str_to_title(animals_name)) 

```

```{r}
pet_names <- seattle_pets %>% 
  select(animal_name, year, species) %>% 
  filter(species %in% c('Cat', 'Dog'), 
          !is.na(animal_name), 
          year >= 2015) %>%
  count(species, animal_name) %>%
  mutate(name_number = row_number()) %>% 
  unnest_tokens(word, animal_name) %>% 
  anti_join(stop_words, by = "word") %>% 
  distinct(species, name_number, word) 

p <- pet_names %>% 
  count(species, word, sort = TRUE) %>% 
  head(30) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n, fill = species)) +
  geom_col(show.legend = FALSE)+
  scale_fill_manual(values = c("#f8c1c4", "#88cfc8")) +
  coord_flip() +
  facet_wrap(~species) +
  labs(x = "",
       y = "Frequency of word",
       title = "Most common words in Seattle pet names") +
  theme_half_open(12)
```

```{r tf-idf}
top_names <- seattle_pets %>% 
  filter(!is.na(animal_name),
         !is.na(species)) %>% 
  mutate(id = row_number()) %>% 
  unnest_tokens(word, animal_name) %>% 
  anti_join(stop_words, by = "word") %>% 
  distinct(species, id, word) %>% 
  count(species, word, sort = TRUE)
  
top_names_tf_idf <- top_names %>% 
  group_by(species) %>% 
  mutate(total_names = sum(n)) %>% 
  ungroup() %>% 
  filter(str_detect(word, "[a-z]")) %>% 
  bind_tf_idf(word, species, n) %>% 
  arrange(desc(tf_idf)) %>% 
  filter(species %in% c ("Cat", "Dog")) 

top_names_tf_idf %>% 
  mutate(popular_name = paste0(species, ": ", word)) %>% 
  head(30) %>% 
  mutate(popular_name = fct_reorder(popular_name, tf_idf)) %>% 
  ggplot(aes(popular_name, tf_idf)) +
  geom_col()+
  coord_flip()+
  labs(x = "",
       y = "TF-IDF",
       title = "Using TF-IDF as Seattle pet names(Dog and Cat)")

p <- top_names_tf_idf %>% 
  top_n(50, tf_idf) %>% 
  ggplot(aes(n, tf_idf, label = word, color = species)) +
  geom_point(show.legend = FALSE) +
  geom_text_repel(point.padding = 0.3) +
  scale_color_manual(values = c("#f8c1c4", "#88cfc8")) +
  facet_wrap(~species) +
  theme_half_open(12) +
  labs(x = "",
       y = "tf_idf",
       title = "Comparison of pet names with the highest tf-idf in Seatle 2015-2018",
    caption = "source | seattle.gov") +
  theme(legend.position = "none")

pp <- top_names_tf_idf %>% 
  top_n(50, tf_idf) %>% 
  ggplot(aes(n, tf_idf, label = word, color = species)) +
  geom_point(show.legend = FALSE) +
  geom_text_repel(point.padding = 0.3) +
  scale_color_manual(values = c("#f8c1c4", "#88cfc8")) +
  theme_half_open(12) +
  labs(x = "",
       y = "tf_idf",
       title = "Comparison of pet names with the highest tf-idf in Seatle 2015-2018",
    caption = "source | seattle.gov") +
  theme(legend.position = "none")

```
### source [tidy tuesday by torsten sprenger] (https://github.com/spren9er/tidytuesday/blob/master/tidytuesday_201913_seattle_pets.r)
### source [pivot_wider: Pivot data from long to wide by hadley wickham] (https://rdrr.io/github/hadley/tidyr/man/pivot_wider.html)
```{r}
pets <- seattle_pets %>% 
   filter(species %in% c('Cat', 'Dog'), 
          !is.na(animal_name), 
          year >= 2015) %>%
  count(species, animal_name) %>% 
   pivot_wider(
    names_from = species, 
    values_from = n, 
    values_fill = list(n = 0)
  ) %>%
  transmute(animal_name,
            dog = Dog, 
            cat = Cat)
```

```{r}
model <- lm(cat ~ dog, pets)

intercept <- model$coefficients[1]

slope <- model$coefficients[2]

pets_popular <- augment(model, pets) %>%
  mutate(
    total = dog + cat,
    most_popular = total >= 230,
    popular = total >= 70,
    sign = factor(-sign(.resid))
  )
```
### source [How to Change GGPlot Facet Labels] (https://www.datanovia.com/en/blog/how-to-change-ggplot-facet-labels/)
```{r facet_share plot}

library(ggpol)

sign_labs <- c("cat", "dog")
names(sign_labs) <- c(-1, 1)

p1 <- pets_popular %>%
  filter(total >= 170) %>% 
  mutate(animal_name = fct_rev(fct_reorder(animal_name, total))) %>% 
  ggplot(aes(x = reorder(animal_name, desc(animal_name)),
             y = total,
             fill = sign)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c("#f8c1c4", "#88cfc8")) +
  facet_wrap(~sign, 
             dir = "h", 
             scales = "free",
             labeller = labeller(sign = sign_labs)) +
  coord_flip()+
  labs(x = "",
       y = "",
       title = "Comparison of the most popular pet names in Seatle 2015-2018",
       caption = "source | seattle.gov") + 
   theme_half_open(12) 

p1

p2 <-  pets_popular %>% 
  filter(total >= 200) %>% 
  mutate(animal_name = fct_reorder(animal_name, total),
         total = ifelse(sign == "-1", -total, total)) %>% 
  ungroup () %>% 
  ggplot(aes(x = animal_name,
             y = total,
             fill = sign)) +
  geom_col(show.legend = FALSE)+
  scale_fill_manual(values = c("#f8c1c4", "#88cfc8")) +
  facet_share(~sign, 
             dir = "h", 
             scales = "free",
             reverse_num = TRUE,
             labeller = labeller(sign = sign_labs)) +
  coord_flip()+
  labs(x = "",
       y = "",
       title = "Comparison of the most popular pet names in Seatle 2015-2018",
       caption = "source | seattle.gov"
       ) +
  theme(legend.position = "none",
        panel.border = element_rect(size=0.5, 
                                    color="#A9A9A9", 
                                    fill = NA)) +
  theme_half_open(12) 
  
p2

p3 <- pets_popular %>% 
  select(animal_name, dog, cat, total) %>% 
  filter(total >= 200) %>% 
  pivot_longer(-c("animal_name", "total"),
                 names_to = "species", 
                 values_to = "number",
                 values_drop_na = TRUE) %>%   
  select(-total) %>% 
  mutate(number = ifelse(species == "cat", -number, number),
         animal_name = reorder(animal_name, number)) %>% 
  ggplot(aes(x= animal_name,
             y= number, 
         fill = species)) +
  geom_col(show.legend = FALSE) + 
  scale_fill_manual(values = c("#f8c1c4", "#88cfc8")) +
  facet_share(~species, 
             dir = "h", 
             scales = "free",
             reverse_num = TRUE) +
  coord_flip() +
  labs(x = "",
       y = "",
       title = "Comparison of the most popular pet names in Seatle 2015-2018",
    caption = "source | seattle.gov"
    ) +
  theme(legend.position = "none",
        panel.border = element_rect(size=0.5, 
                                    color="#A9A9A9", 
                                    fill = NA)) +
  theme_half_open(12) 

p3
```

```{r}
p4 <- pets_popular %>%
  filter(total >= 400) %>% 
  ggplot(aes(x = dog, y = cat)) +
  geom_text_repel(
    data = filter(pets_popular, 
                  popular & !most_popular),
    aes(label = animal_name, 
        size = total, 
        color = sign),
    fontface = 'bold', 
   # segment.size = 0.25, 
   # segment.alpha = 0.35, 
   # seed = 6,
    show.legend = FALSE
    ) +
  geom_text(
    data = filter(pets_popular, most_popular),
    aes(label = animal_name, 
        size = total, 
        color = sign),
    fontface = 'bold', 
    show.legend = FALSE,
    na.rm = TRUE)+
  facet_wrap(~sign, 
             nrow = 1,
             scales = "free",
             labeller = labeller(sign = sign_labs)) +
  expand_limits(x = 0, y = 0) +
  scale_color_manual(values = c("#f8c1c4", "#88cfc8")) +
  scale_y_continuous(limits = c(0, 80),
                     breaks = seq(0, 80, 20),
                     expand = c(0, 0)) +
  labs(
    x = "",
    y = "",
    title = "Comparison of the most popular pet names in Seatle 2015-2018",
    caption = "source | seattle.gov"
    ) +
  theme_half_open(12) 

p4

p5 <- pets_popular %>%
  ggplot(aes(x = dog, y = cat)) +
  geom_abline(
    intercept = intercept, 
    slope = slope, 
    size = 0.25, 
    color = "#1b2c47",
    linetype = 2
    ) +
  geom_text_repel(
    data = filter(pets_popular, 
                  popular & !most_popular),
    aes(label = animal_name, 
        size = total, 
        color = sign),
    fontface = 'bold', 
    segment.size = 0.25, 
    segment.alpha = 0.35, 
    seed = 6,
    show.legend = FALSE
    ) +
  geom_text(
    data = filter(pets_popular, most_popular),
    aes(label = animal_name, 
        size = total, 
        color = sign),
    fontface = 'bold', 
    show.legend = FALSE
    ) +
  expand_limits(x = 0, y = 0) +
  scale_y_continuous(breaks = c(0, 25, 50, 75, 100)) +
  scale_size_continuous(range = c(1.5, 4.25)) +
  scale_color_manual(values = c("#f8c1c4", "#88cfc8")) +
  labs(
    x = 'Number of Dogs',
    y = 'Number of Cats',
    title = "Comparison of the most popular pet names in Seatle 2015-2018",
    caption = "source | seattle.gov"
    ) +
  theme(axis.text.x = element_text(color = "#1b2c47"),
        axis.text.y = element_text(color = "#1b2c47"),
        plot.caption = element_text(color = "#9a9a9a")) +
 theme_half_open(12) 

p5
```
