---
title: "Untitled"
author: "Sung Inkyung"
date: '2020 4 12 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

simpsons <- readr::read_delim("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-27/simpsons-guests.csv", delim = "|", quote = "")

```
```{r}
simpsons %>% 
  filter(season != "Movie") %>% 
  group_by(season) %>% 
  summarise(n = n()) %>% 
  ungroup() %>% 
  mutate(season = as.numeric(season)) %>% 
  ggplot(aes(season, n)) +
  geom_line(color = "#fed90f",
            size = 3) +
  scale_x_continuous(breaks = seq(1, 30, 10)) +
  labs(x = "Season",
       y = "# of guest stars",
       title = " # of Guuest Stars Appearance per Season") +
  theme_minimal() +
  theme(
        plot.background = element_rect(fill = "black"),
        text = element_text(color = "#ffffff"),
        plot.title = element_text(size = 16,
                                  face = "bold",
                                  hjust = .5,
                                  color = "#ffffff"),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_line(size = .003),
        panel.grid.minor.x = element_blank(),
        axis.text = element_text(color = "#ffffff"),
        plot.margin = margin(0, 1, 0, .5, unit = "cm"))
```



```{r}
self <- simpsons %>% 
  filter(season != "Movie") %>% 
  filter(role == "Himself" | role == "Herself" | role == "Themselves") %>% 
  group_by(season, guest_star, role) %>% 
  summarize(total = sum(n))

plot <- self %>% 
  ggplot(aes(x = role, y = total,  fill = role)) +
  geom_col(show.legend = F) +
  scale_fill_manual(values = c("#ffd90f", "#70d1f3", "#424f46")) +
  theme_minimal() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "black"),
        text = element_text(color = "#ffffff"),
        plot.title = element_text(size = 16,
                                  face = "bold",
                                  hjust = .5,
                                  color = "#ffffff"),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_line(size = .003),
        panel.grid.minor.x = element_blank(),
        axis.text = element_text(color = "#ffffff"),
        plot.margin = margin(0, 1, 0, .5, unit = "cm"))
  
```
```{r}
simpsons_tidy <- simpsons %>% 
  filter(season != "Movie") %>% 
  filter(role == "Himself" | role == "Herself" | role == "Themselves") %>% 
  mutate(role = as.factor(role),
         guest_star = as.factor(guest_star),
         season_group = case_when( season %in% 1:10 ~ "Seasons 1-10",
                                   season %in% 11:20 ~ "Seasons 11-20",
                                   season %in% 21:30 ~ "Seasons 21-30"), 
         season = as.numeric(season)
         )

```


```{r}
plot <- simpsons_tidy %>% 
  group_by(season_group, season, role) %>% 
  summarise(total = sum(n)) %>% 
  ggplot(aes(season, total, fill = role)) +
  geom_bar(stat = "identity", width = .6) +
  scale_fill_manual(values = c("#fed90f", "#70d1f3", "#d1b271")) +
  scale_x_continuous(breaks = seq(1, 30, 1)) +
  labs(x = "",
       y = "",
       title = "Number of guest stars in the The Simpson by Season") +
  facet_wrap(~ season_group, ncol = 1, scales = "free_y") +
  theme_minimal() +
  theme(legend.position = "top",
        plot.background = element_rect(fill = "black"),
        text = element_text(color = "#ffffff"),
        plot.title = element_text(size = 16,
                                  face = "bold",
                                  hjust = .5,
                                  color = "#ffffff"),
        strip.text = element_text(color = "#fed90f",
                                  face = "bold",
                                  size = 10),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_line(size = .003),
        panel.grid.minor.x = element_blank(),
        axis.text = element_text(color = "#ffffff"),
        plot.margin = margin(0, 1, 0, .5, unit = "cm")
        )
```

### Source[tidytuesday by @aaumaitre]  (https://github.com/aaumaitre/tidytuesday)
```{r}
guests_plot <- simpsons %>% 
  filter(season != "Movie") %>% 
  group_by(guest_star) %>% 
  summarise(n = n()) %>% 
  filter(n >= 10) %>% 
  ggplot(aes(x = 1.15, y = reorder(guest_star, n))) + # x = 1.15 ? to be learned
  geom_point(aes(size = n), color = "#ffd90f") +
  geom_text(aes(label = reorder(guest_star, n), x = 1.2), #label = ifelse(n > 150, paste0(n, "\ntimes"), n),
            hjust = 0, 
            color = "#70d1fe",
            size = 4) +
  geom_text(aes(label = n,
                x = 1.15),
            color = "black", 
            size = 4) +
  scale_size(range = c(6, 16), # ? to be learned
             guide = F) +
  xlim(c(1, 1.5)) +
  labs(title = "Most frequent guest stars over Season 1 - 30",
       caption = "Source: Wikipedia | Graphic: Sung Inkyung") +
  theme(plot.background = element_rect(fill = "black"),
        panel.background = element_rect(fill = "black"),
        panel.grid = element_blank(),
        plot.margin = unit(c(1.2,0.2,0,0), "cm"),
        text = element_text(color = "#ffffff"),
        axis.text = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(face = "bold" ,
                                  hjust = 0.5,
                                  color = "#ffd90f",
                                  size = 16,
                                  vjust = 4),
        plot.caption = element_text(color = "#d1b271",
                                    size = 9,
                                    margin = margin(b = 10, r = 15)))
  
```

