---
title: "SpaceLaunches"
author: "Sung Inkyung"
date: '2020 3 21 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggtext)
library(here)
```


```{r}
launches <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-15/launches.csv")

agencies <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-15/agencies.csv")

launches %>% 
  count(category, sort = T)

```
### Source[tidytuesday by @perspectivalean] (https://github.com/JoseEchave/tidy-tuesdays/blob/master/2020/week_7_hotels/hotel%20bookings%20github.Rmd)
### Source[tidytuesday by @RichyyL] (https://github.com/Richyyl/Tidy-Tuesday/blob/master/2019/Space%20Race_14_01_19/Space_race-14-01-19.Rmd)
```{r}
agencies_processed <- agencies %>% 
  mutate(tstart = str_trim(word(tstart, 1), side = "both"),
         tstart = str_replace(tstart, "\\-|\\*|\\?|s", ""),
         tstop = str_trim(word(tstop, 1), side = "both"),
         tstop = str_replace(tstop, "\\-|\\*", as.character(year(now()))),
         tstop = str_replace(tstop, "\\?", "")) %>% 
  select(tstart, tstop, agency_type, count) %>% 
  replace_na(list(tstart = " ")) %>% 
  filter(tstart != "na")

## about to give up on this approach to the plot becasue I had (dxxx)hard time to grrapple with this to extract year from as.character date. gave up getting help from Stackoverflow, moved on to #tidytuesday contributors on twitter!!! so lucky to come across @RichyyL, thanks a ton*value
```

```{r}
agency_life <- agencies_processed %>% 
  ggplot() +
  geom_curve(aes(x = tstart, xend = tstop, color = agency_type,
                 y = 0, yend = 1),
             curvature = -.4, alpha = .7, size = .5) +
  ylim(0, 1550) +
  scale_color_manual(values = c("#b4005b", "#18d667", "#383b39" ),
                     labels = c("<span style = 'color: #b4005b'>Private</span>", 
                                "<span style = 'color: #18d667'>StartUp</span>",
                                "<span style = 'color: #383b39'>State</span>")) + 
  # values = set_names(c("#b4005b", "#18d667", "#383b39"), c( "Private", "StartUp", "State)
  labs(x = "",
       y = "",
       title = "Life span of Space Agencies Run by State, Private and Start up",
       subtitle = "Each line represents start and stop of operation",
       caption = "Source: JSR laumnch Vehicle Database | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_markdown(size = 7.5),
        legend.text.align = 0,
        plot.title = element_markdown(size = 20, hjust = .5),
        plot.subtitle = element_text(size = 13, hjust = .5, vjust = 1),
        panel.background = element_blank(),
        strip.text = element_text(size = 10),
        plot.caption = element_text(size = 7.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 7.5),
        axis.text.x = element_text(angle = 45),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ggsave(here("figures", "SpaceAgencies.png"), width = 9, height = 7)
  
```


```{r}
library(countrycode)

launches_processed <- launches %>% 
  #mutate(state_code = fct_lump(state_code, 6), "Others") %>% 
  #count(state_code, sort = T)
  mutate(state_code_cleaned = fct_collapse(
    state_code,
    "RU" = c("SU", "RU"),
    "FR" = "F",
    "JP" = "J",
    "IT" = "I"
  )) %>% 
  mutate(state_name = countrycode(state_code_cleaned, "iso2c", "country.name"),
         state_name = fct_lump(state_name, 6)) %>% 
  replace_na(list(state_name = "Other"))

launches_processed %>% 
  count(state_name)

launches_count <- launches_processed %>% 
  filter(state_name != "Other") %>% 
  group_by(state_name, launch_year) %>% 
  add_tally(name = "n")%>% 
  add_count(category, name = "nn") %>% 
  distinct(state_name, launch_year, category, n, nn) %>% 
  mutate(prc = nn / n *100) %>% 
  ungroup() 

launch_life <- launches_count %>% 
  mutate(state_name = fct_reorder(state_name, prc)) %>% 
  ggplot(aes(launch_year, prc,
             fill = category)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("#b4005b", "#6897bb"),
                    labels = c("<span style = 'color: #b4005b'>Failure</span>", 
                                "<span style = 'color: #6897bb'>Success</span>")) +
  scale_x_continuous(breaks = seq(1960, 2020, 10)) +
  facet_wrap(~ state_name, nrow = 6) +
  labs(x = " Launch year",
       y = "Percentage of Launches",
       title = "Status of Space Launches over Time",
       subtitle = "Back to Back trials and errors to success have been  building up persistently",
       caption = "Source: JSR Launch Vehicle Database | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        legend.position = "bottom",
        legend.text = element_markdown(size = 9),
        legend.title = element_blank())

ggsave(here ("figures", "SpaceLaunches.png"), width = 9, height = 7.5)

```

