---
title: "Stanford Open Policing Project"
author: "Sung Inkyung"
date: '2020 4 26 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
openpolicing <- readr::read_csv("https://raw.githubusercontent.com/5harad/openpolicing/master/results/data_for_figures/combined_data.csv") %>%   mutate(location = str_to_title(location)) %>% 
  rename(county = location)

stops <- openpolicing %>% 
  group_by(state, county, driver_race) %>% 
  summarise(avg = mean(stop_rate,
                       na.rm = T))

plot <- stops %>% 
  ggplot(aes(county, avg)) +
  geom_point(aes(color = factor(driver_race)),
             size = 1, 
             alpha = .6,
             na.rm = T) +
  coord_cartesian(ylim = c(0, 1),
                    expand = T) +
  scale_color_manual(values = c("black", "#f2147d", "white"), 
                     name = "Driver race") + #Hispanic: "#cd025c
  facet_grid(.~state, scales = "free") +
  labs(x = "",
       y = "Average of stop rate",
       title = "Total Stops Average Rate of Speeding Violatons across States",
       caption = "Source: SOPP - arXiv:1706.05678 | Graphic: Sung Inkyung") +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  theme_dark() +
  theme(legend.position = "bottom",
        legend.key = element_blank(),
        legend.text = element_text(size = 9),
        legend.background = element_rect(fill = "#a9a9a9"),
        panel.background = element_rect(fill = "#a9a9a9"),
        panel.border = element_blank(),
        panel.grid = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank())
  


```

