---
title: "Untitled"
author: "Sung Inkyung"
date: '2020 3 17 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
```


```{r}
ufo_sightings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-25/ufo_sightings.csv")
```
```{r}
## UFO color code: #7fff00, #ff1693, #9a2be2

shapes <- ufo_sightings %>% 
  group_by(ufo_shape) %>% 
  summarise(total = n()) %>% 
  filter(ufo_shape != "NA") %>% 
  ungroup()
 
set.seed(2020)
  
library(treemapify)

shape_tree <- shapes %>% 
  ggplot(aes(area = total, label = ufo_shape, fill = total)) +
  geom_treemap(color = "#ff1693", start = "topleft") +
  geom_treemap_text(min.size = 3, place = "center", 
                    color = "#7fff00", start = "topleft") +
  scale_fill_gradient(low = "#301934", high = "#05210c") +
  labs(title = "Common UFO Shapes")+
  theme(legend.position = "none",
        plot.title = element_text(size = 20,
                                  hjust = .5,
                                  vjust = .5,
                                  face = "bold",
                                  color = "#301934",
                                  margin = margin(b = 20)),
        plot.margin = margin(1, 1, 1, 1, unit = "cm"))
```


```{r}
shapes <- c("light", "triangle", "circle", "fireball", "shpere", "disk", "oval", "formation", "cigar", "changing", "cylinder", "rectangle", "flash", "diamond") # n > 10000
  
ufo <- ufo_sightings %>% 
  filter(ufo_shape %in% shapes) %>% 
  select(ufo_shape, description) %>% 
  unnest_tokens(word, description) %>% 
  anti_join(stop_words) %>% 
  filter(!str_detect(word, "[0-9]")) %>% 
  count(ufo_shape, word) %>% 
  filter(n > 200) %>% 
  ungroup() %>% 
  mutate(word = fct_reorder(word, n)) 

ufo %>% 
  count(ufo_shape, sort = T)

```
```{r}
library(igraph)
library(ggraph)



set.seed(2020)


ufo_graph <- 
  graph_from_data_frame(ufo)


ufo_plot <- ufo_graph %>% 
  ggraph(layout = "kk") +
  geom_edge_link(aes(edge_alpha = .7), 
                 color = "#7fff00",
                 show.legend = FALSE) +
  geom_node_point(aes(size = n),
                  color = "#ff1693") +
  geom_node_text(aes(label = name),
                 size = 4,
                 color = "#cdcdcd",
                 check_overlap = TRUE) +
  labs(title = "Words Describing Common UFO-Shapes",
       caption = "Source:nuforc.org | Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#301934"),
        plot.title = element_text(size = 20,
                                  hjust = .5,
                                  vjust = .5,
                                  face = "bold",
                                  color = "#7fff00",
                                  margin = margin(b = 20)),
        plot.caption = element_text(color = "#c0c0c0",
                                    size = 9),
        plot.margin = margin(1, 1, 1, 1, unit = "cm"))
```

```{r}
library(patchwork)

shape_tree + ufo_plot

ggsave(here("figures", "UFO-Shapes.png"), width = 34, height = 14, unit = "cm")

```

