---
title: "HousePriceIndex"
author: "Sung Inkyung"
date: '2020 4 11 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(knitr)
library(GGally)
library(paletteer)
library(superheat)
```


```{r}
state_hpi <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-05/state_hpi.csv")

```


```{r}
hpi <- state_hpi %>% 
  group_by(year, state) %>% 
  summarise_all(mean, na.rm = T) %>% 
  ungroup()

p <- hpi %>%
  filter(state == c("HI", "DC")) %>% 
  ggplot(aes(year, price_index, color = state)) +
  geom_line() 
```


```{r}
plot <- hpi %>% 
  mutate(state = fct_reorder(state, price_index)) %>% 
  ggplot(aes(year, state, fill = price_index)) +
  geom_tile(color = "white", size = 0.05) +
  scale_x_continuous(breaks = c(1975, seq(1980, 2010, 10), 2018)) +
  scale_fill_paletteer_c("oompaBase::cyanyellow",
                         direction = 1,
                         breaks = pretty(5)) +
  scale_color_identity() +
  labs(x = " ", y = " ", 
       title = "The Yearly Average Housing Price in USA since 1975",
       subtitle = "Increase in US house price stands out in Washington DC and Hawaii over last 43years",
       caption = "Data: FRED | Graphic: Sung InKyung") +
  theme_minimal()+
  theme(legend.position = "bottom",
        legend.key.width = unit(.7, "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.margin = margin(0, 1, 0, .5, unit = "cm"),
        panel.spacing.y = unit(.2, "cm"))

plot
```


```{r}
hpi_state <- hpi %>% 
  select(state, year, price_index) %>% 
  spread(key = state, value = price_index)

hpi_state %>% 
  column_to_rownames("year") %>% 
  cor() %>% 
  round(2) %>% 
  kable()


hpi_state %>% 
  ggcorr(
       label = T,
       nbreaks = 7,
       palette = "BrBG")

# Scale each variable between 0 and 1
hpi_state_scale <- hpi_state %>% 
  mutate_at(vars(-contains("year")),
            ~scales::rescale(., to = c(0, 1),
                             from = c(0, max(.))))

hpi_state_scale %>% 
  head() %>% 
  round(2) %>% 
  kable()

hpi_state_clust <- hpi_state_scale %>% 
  column_to_rownames("year") %>% 
  t()

hpi_hclust <- hpi_state_clust %>% 
  dist() %>% 
  hclust() %>% 
  plot()





```
### Source[Superheat Vignette] (https://rlbarter.github.io/superheat/basic-usage.html#heatmap-scale)

```{r}
set.seed(123)

hpi_state_clust %>% 
  superheat::superheat(scale = T,
                     heat.pal = c("#137a63", "#d0ad8d", "#3b0056"),
                     heat.pal.values = c(0, .5, 1),
                     heat.lim = c(-1, 2),
                     row.dendrogram = T,
                     left.label.size = 5,
                     left.label.text.alignment = "center",
                     bottom.label.text.angle = 90,
                     bottom.label.text.size = 5,
                     grid.hline.col = "gray40",
                     grid.vline.col = "gray40",
                     title = "The USA Yearly Average Housing Price since 1975",
                     title.size = 16,
                     column.title.size = 9)
  
png("HousePriceIndex.png", height = 900, width = 800)
superheat(X = hpi_state_clust, scale = T)
dev.off()
```
