---
title: "VideoGames"
author: "Sung Inkyung"
date: '2020 4 18 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```


```{r}
video_games <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-30/video_games.csv") %>% 
  janitor::clean_names()


```
```{r}
```



```{r}
top_publishers <- video_games %>% 
  na.omit() %>% 
  count(publisher) %>% 
  top_n(7)
```
```{r}

video <- video_games %>% 
  mutate(year = year(mdy(release_date))) %>% 
  group_by(publisher, year) %>% 
  summarise(avg_score = mean(metascore, na.rm = T)) %>% 
  ungroup() %>% 
  dplyr::filter(publisher %in% top_publishers$publisher) 

plot <- video %>% 
  dplyr::filter(year >= 2010) %>% 
  ggplot(aes(year, publisher, fill = avg_score)) + 
  geom_tile() + 
  scale_fill_continuous(low = "#cd8f89",
                        high = "#89cdb1",
                        name = "Avg Score") +
  scale_x_continuous(breaks = seq(2010, 2018, 2)) +
  labs(x = "",
       y = "publisher",
       title = "Mean Score of Top 7 Publisher from 2010 to 2018") +
  theme_minimal()
  
  
```

