---
title: "wine reviews"
author: "sung inkyung"
date: '2019 8 17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
theme_set(theme_minimal())
```


```{r}
wine_reviews <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/winemag-data-130k-v2.csv") %>% 
  select(-X1) %>% 
  filter(!is.na(variety))
```

```{r Exploring Data}
wine_reviews %>% 
  count(country, sort = TRUE)

wine_reviews %>% 
  count(variety, sort = TRUE) %>% 
  top_n(15) %>% 
  filter(!variety == "Bordeaux-style Red Blend") %>% 
  mutate(variety = reorder(variety, n)) %>% 
  ggplot(aes(variety, n)) +
  geom_col()+
  coord_flip()

wine_reviews %>% 
  summarise(mean(points))

wine_reviews %>% 
  summarise(mean(price))

wine_reviews %>% 
  ggplot(aes(points))+
  geom_histogram(binwidth = 1) +
   geom_vline(xintercept = 88.4,
             lty = "longdash",
             size = 1,
             color = "firebrick3",
             !is.na(points))

wine_reviews %>% 
  ggplot(aes(price)) +
  geom_histogram()+
  geom_vline(xintercept = 35.4,
             lty = "longdash",
             size = 1,
             color = "firebrick3",
             !is.na(price))+
  scale_x_log10()

wine_reviews %>% 
  mutate(variety = fct_relevel(fct_lump(variety, 15))) %>% 
  mutate(variety = fct_reorder(variety, points)) %>% 
  filter(!is.na(variety),
         !variety == "Bordeaux-style Red Blend") %>% 
  ggplot(aes(variety, points)) +
  geom_boxplot() +
  coord_flip()

wine_reviews %>% 
  group_by(variety) %>% 
  filter(!is.na(variety)) %>% 
  summarise(avg_points = mean(points), n()) %>% 
  filter(avg_points >= 92.5) %>% 
  arrange(desc(avg_points))

wine_reviews %>% 
  mutate(id = row_number()) %>% 
  arrange(points) %>% 
  head(1) %>% 
  select(id, description) %>% 
  pull(description)

```

```{r}
wine_reviews %>% 
  ggplot(aes(price, points)) +
  geom_point(alpha = .1) +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = 88.4,
             color = "firebrick3",
             lty = "longdash") +
  scale_x_log10()
```

```{r}
wine_reviews_words <- wine_reviews %>% 
  count(variety, description, sort = TRUE) %>% 
  top_n(15) %>% 
  filter(!variety == "Bordeaux-style Red Blend") %>% 
  unnest_tokens(word, description) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(!word %in% c("wine", "drink"),
         str_detect(word, "[a-z]"))

wine_reviews_words %>% 
  count(variety, word, sort = TRUE) %>% 
  filter(!word == "flavors") %>% 
  head(50) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(word, n, fill = variety)) +
  geom_col() +
  coord_flip()
  
```

```{r}
wine_reviews_words %>% 
  right_join(get_sentiments("nrc")) %>% 
  filter(!is.na(sentiment)) %>% 
  count(sentiment, sort = TRUE)
```

```{r}
 wine_reviews_words %>% 
  group_by(variety) %>% 
  mutate(word_count = 1:n(),
         index = word_count %/% 500+1) %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(variety, index = index, sentiment) %>% 
  ungroup() %>% 
  filter(variety %in% c("Syrah", "Pinot Noir", "Nebbiolo", "Resling", "Zinfandel", "Sangiovese", "Red Blend", "Portugese Red", "Malbec", "Chardonnay", "Cabernet Sauvignon", "Sauvignon Blanc", "Rose", "Merlot")) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative,
         variety = factor(variety)) %>%
  ggplot(aes(index, sentiment, fill = variety)) +
  geom_bar(alpha = 0.5,
           stat = "identity",
           show.legend = FALSE) +
  facet_wrap(~variety,
             ncol=2,
             scales = "free")
```

```{r Common sentiment words}
bing_word_counts <- wine_reviews_words %>% 
  inner_join(get_sentiments("bing"), by = "word") %>% 
  count(word, sentiment, sort = TRUE) %>% 
  ungroup()

bing_word_counts 
```

```{r}
bing_word_counts %>% 
  group_by(sentiment) %>% 
  top_n(15) %>% 
  ggplot(aes(reorder(word, n), n, fill = sentiment))+
  geom_bar(alpha = .7,
           stat = "identity",
           show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y")+
  labs(x = NULL,
       y = "Contribution to sentiment") +
  coord_flip()
```

```{r}
wine_tf_idf <- wine_reviews_words %>% 
  count(variety, word, sort = TRUE) %>% 
  ungroup() %>% 
  bind_tf_idf(word, variety, n)

wine_tf_idf %>% 
  arrange(-tf_idf)
```

```{r}
wine_tf_idf %>% 
  filter(variety %in% c("Pinot Noir", "Chardonnay", "Cabernet Sauvignon","Red Blend", "Resling", "Sauvignon Blanc", "Syrah", "Rose", "Merlot", "Zinfandel", "Malbec", "Sangiovese", "Nebbiolo","Portugese Red")) %>% 
  arrange(desc(tf_idf)) %>% 
  group_by(variety) %>% 
  distinct(word, .keep_all = TRUE) %>% 
  top_n(10, tf_idf) %>% 
  ungroup() %>% 
  mutate(variety = factor(variety) %>% 
           forcats::fct_rev()) %>% 
  ggplot(aes(drlib::reorder_within(word, tf_idf, variety), n, 
             fill = variety)) +
  geom_col(stat = "identity",
           alpha = .7,
           show.legend = FALSE) +
  drlib::scale_x_reordered() +
  facet_wrap(~variety, 
             ncol = 3,
             scales = "free")+
  coord_flip()+
  labs(title = "Highest tf_idf word in the wine description per variety",
       x = NULL,
       y = "tf-idf")
```

```{r Topic modeling}
word_counts <- wine_reviews %>% 
  unnest_tokens(word, description) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(!word %in% c("wine", "drink"),
         str_detect(word, "[a-z]")) %>% 
  count(variety, word, sort = TRUE) %>% 
  ungroup()

word_counts
```

```{r}
word_dtm <- word_counts %>% 
  cast_dtm(variety, word, n)

word_dtm
```

```{r}
library(topicmodels)

wine_lda <- LDA(word_dtm, k = 6,
                control = list(seed = 1234))

wine_lda 
```

```{r}
lda_tidied <- tidy(wine_lda)

lda_tidied
```

```{r}
top_terms <- lda_tidied %>% 
  group_by(topic) %>% 
  top_n(10, beta) %>% 
  ungroup() %>% 
  arrange(topic, -beta)

top_terms
  
```

```{r}
top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  group_by(topic, term) %>%    
  arrange(desc(beta)) %>%  
  ungroup() %>%
  mutate(term = factor(paste(term, topic, sep = "__"), 
                       levels = rev(paste(term, topic, sep = "__")))) %>%
  ggplot(aes(term, beta, 
             fill = as.factor(topic))) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  scale_x_discrete(labels = function(x) gsub("__.+$", "", x)) +
  labs(title = "Top 10 terms in each topic of wine variety descriptions",
       x = NULL, 
       y = expression(beta)) +
  facet_wrap(~ topic, 
             ncol = 2,
             scales = "free")
```

```{r}
lda_gamma <- tidy(wine_lda, matrix = "gamma")

lda_gamma
```

```{r}
lda_gamma %>% 
ggplot(aes(gamma)) +
  geom_histogram() +
  scale_y_log10() +
  labs(title = "Distribution of probabilities for all topics",
       y = "Number of varieties", 
       x = expression(gamma))
```

```{r}
ggplot(lda_gamma, aes(gamma, fill = as.factor(topic))) +
  geom_histogram(show.legend = FALSE) +
  facet_wrap(~ topic, ncol = 2) +
  scale_y_log10() +
  labs(title = "Distribution of probability for each topic",
       y = "Number of variety", 
       x = expression(gamma))
```

```{r}
library(LDAvis)

topicmodels2LDAvis <- function(x, ...){
  post <- topicmodels::posterior(x)
  if (ncol(post[["topics"]]) < 3) stop("The model must contain > 2 topics")
  mat <- x@wordassignments
  LDAvis::createJSON(
    phi = post[["terms"]], 
    theta = post[["topics"]],
    vocab = colnames(post[["terms"]]),
    doc.length = slam::row_sums(mat, na.rm = TRUE),
    term.frequency = slam::col_sums(mat, na.rm = TRUE)
  )
}

serVis(topicmodels2LDAvis(wine_lda))
```

```{r Word Relationships}
library(widyr)

wine_words_pairs <- wine_reviews_words %>% 
  pairwise_count(word, variety, sort = TRUE)

wine_words_pairs
```

```{r}
wine_words_pairs %>% 
  filter(item1 == "aromas")

wine_words_pairs %>% 
  filter(item1 == "palate")
```

```{r}
library(ggraph)
library(igraph)

set.seed(2019)

wine_words_pairs %>%
  filter(n > 70) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = n, edge_width = n),
                 edge_colour = "#5b0136") +
  geom_node_point(size = 3) +
  geom_node_text(aes(label = name), 
                 repel = TRUE, 
                 point.padding = unit(0.2, "lines")) +
  theme_void() +
  theme(legend.position = "none")
```

```{r word correlations}
wine_words_cors <- wine_reviews_words %>% 
  group_by(word) %>% 
  filter(n() >= 70) %>% 
  pairwise_cor(word, variety, sort = TRUE) 
```

```{r}
wine_words_cors %>% 
  filter(item1 == "elements")
```

```{r}
library(ggsci)

wine_words_cors %>%
  filter(item1 %in% c("elements", "firm", "silky", "dry")) %>%
  group_by(item1) %>%
  top_n(6) %>%
  ungroup() %>%
  mutate(item2 = reorder(item2, correlation)) %>%
  ggplot(aes(item2, correlation, fill = item1)) +
  geom_bar(stat = "identity",
           alpha = .7,
           show.legend = FALSE) +
  scale_fill_npg() +
  facet_wrap(~ item1, scales = "free") +
  coord_flip()
```

```{r}
set.seed(2019)

wine_words_cors %>%
  filter(correlation > .65) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), 
                 show.legend = FALSE) +
  geom_node_point(color = "#5b0136", 
                  size = 3) +
  geom_node_text(aes(label = name), 
                 repel = TRUE) +
  theme_void()
```

```{r bigram network}

wine_bigrams <- wine_reviews %>% 
  select(variety, description) %>% 
  unnest_tokens(bigram, description, token = "ngrams", n=2) %>% 
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  filter(!word1 %in% stop_words$word,
         !word2 %in% stop_words$word) %>% 
  count(word1, word2, sort = TRUE)

```

```{r}
wine_bigram_network <- wine_bigrams %>% 
  filter(n > 700) %>% 
  graph_from_data_frame()
  
  wine_bigram_network
```

```{r}
set.seed(2019)

a <- grid::arrow(type = "closed",
                 length = unit(.09, "inches"))

ggraph(wine_bigram_network, 
       layout = "fr") +
  geom_edge_link(aes(edge_alpha = n),
                 show.legend = FALSE,
                 arrow = a,
                 end_cap = circle(.07, "inches")) +
  geom_node_point(color = "#5b0136", 
                  size = 3)+
  geom_node_text(aes(label = name),
                 repel = TRUE) +
  labs(title = "Common bigrams network in wine reviews",
       subtitle = "Bigrams that occurred more than 700 times in varieties") +
  theme(plot.background = element_rect(fill = NA)) +
  theme_void()

ggsave("C:/Users/inkyscope/Documents/projectR/dvscope/figures/wine_bigrams_network.png")
```

