---
title: "WineReviews_vizPCA"
author: "sung inkyung"
date: '2019 8 19 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
theme_set(theme_minimal())
```

```{r}
wine_reviews <- readr::read_csv("C:/Users/inkyscope/Documents/projects/data/winemag-data-130k-v2.csv") %>% 
  select(-X1) %>% 
  filter(!is.na(variety))
```

```{r}
wine_review_words <- wine_reviews %>% 
  filter(points > 92) %>% 
  select(description) %>% 
  unnest_tokens(word, description) %>% 
  anti_join(stop_words) %>%
  filter(str_detect(word, "[a-z]"),
    !str_detect(word, pattern = "[[:digit:]]"), 
    !str_detect(word, pattern = "[[:punct:]]"), 
    !str_detect(word, pattern = "(.)\\1{2,}"),  
    !str_detect(word, pattern = "\\b(.)\\b"),
    !word %in% c("wine", "flavors", "drink")) %>% 
  group_by(word) %>%
  count(sort = TRUE) %>% 
  ungroup()
```

```{r}
wine_word <- wine_review_words %>% 
  mutate(id = row_number(),
  word = str_replace_all(word, " ?(f|ht)tp(s?)://(.*)[.][a-z]+", "")) %>%
  filter(n >= 50)
```

```{r}
wine_word  %>% 
  top_n(15, n) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n, 
             label = word, 
             fill = word)) +
  geom_col(alpha = .7,
           show.legend = FALSE) +
  geom_text(aes(word, 0.001),
            hjust = 0,
            color = "white", size = 4) +
  coord_flip()+
  labs(x = NULL,
       y = "word frequency of wine word") +
  scale_y_continuous(labels = scales:: percent_format(),
                     expand = c(0.015, 0)) +
  theme(axis.text.y = element_blank())
```

```{r}
# Implementing PCA
sparse_wine_matrix <- wine_word  %>% 
  tidytext::cast_sparse(id, word, n)

dim(sparse_wine_matrix)

wine_scaled <- scale(sparse_wine_matrix)

wine_pca <- irlba::prcomp_irlba(wine_scaled,
                                   n= 6, scale. = TRUE)
```

```{r}
library(broom)

wine_tidy <- bind_cols(word = colnames(wine_scaled),
                        tibble::as_tibble(wine_pca$rotation)) %>%
    gather(PC, contribution, PC1:PC6)

wine_tidy 
```

```{r}
wine_tidy %>% 
    filter(PC %in% paste0("PC", 1:6)) %>%
    ggplot(aes(word, contribution, fill = word)) +
    geom_col(show.legend = FALSE, 
             alpha = 0.8) +
    theme(axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank()) + 
    labs(x = "wine words",
         y = "Relative importance in each principal component") +
    facet_wrap(~ PC, ncol = 2)
```

```{r}
wine_tidy  %>%
    filter(PC == "PC4") %>%
    top_n(40, abs(contribution)) %>%
    mutate(word = reorder(word, contribution)) %>%
    ggplot(aes(word, contribution, 
               fill = word)) +
    geom_col(show.legend = FALSE, 
             alpha = 0.8) +
    theme(axis.text.x = element_text(angle = 65,
                                     hjust = 1, 
                                     vjust = 1), 
          axis.ticks.x = element_blank()) + 
    labs(x = "wine words",
         y = "Relative importance in each principal component")
```

```{r}
wine_tidy %>% 
  filter(PC == c("PC1", "PC2", "PC3", "PC4", "PC5", "PC6")) %>% 
  group_by(PC) %>% 
  top_n(16, abs(contribution)) %>% 
  ungroup() %>% 
  mutate(word = drlib::reorder_within(word, contribution, PC)) %>% 
  ggplot(aes(word, contribution, fill = factor(PC))) +
  geom_col(alpha = .7,
           show.legend = FALSE) +
  facet_wrap(~ PC, 
             scales = "free") +
  drlib::scale_x_reordered() +
  coord_flip()+
  labs(title = "Six principle components of words in wine reviews")
```

```{r}
percent_variation <- wine_pca$sdev^2 / sum(wine_pca$sdev^2)

augmented_pca <- bind_cols(id = rownames(wine_scaled),
                           tidy(wine_pca$x))

augmented_pca
```
```{r}
augmented_pca %>%
    mutate(id = as.integer(id)) %>%
    ggplot(aes(PC3, PC4)) +
    geom_point(alpha = 0.5,
               size = 1.5, 
               color = "#780303") +
   labs(title = "Projection of wine words on to the two principal components of PC3 and PC4",
        subtitle = "The very high dimensional space can be projected down onto components we have explored")
```
