---
title: "wine_ratings"
author: "sunginkyung"
date: '2019 7 4 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggthemes)
library(treemapify)
library(ggridges)
library(cowplot)
```
### source: https://github.com/dgrtwo/data-screencasts/blob/master/medium-datasci.Rmd
```{r}
wine_ratings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv") %>% 
  select(-1) %>% 
  extract(title, "year", "(20\\d\\d)", convert = TRUE, remove = FALSE) %>%
  mutate(year = ifelse(year < 1900, NA, year)) %>%
  filter(!is.na(price))
```

```{r}
wine_ratings %>% 
  select(price, points) %>% 
  skimr::skim()

wine_ratings %>% 
  select(points, country) %>% 
  skimr::skim()
```
### source: Graphical Data Analysis with R by Antony Unwin
### http://www.gradaanwr.net/content/ch06/
```{r}
library(GGally)

variables <- c("country", "year", "variety", "price","points")

wine_ratings %>% 
  select(variables) %>% 
  mutate(above_avg = points >mean(points)) %>% 
  sample_n(30) %>% 
  ggparcoord(
    groupColumn = "above_avg",
    showPoints = TRUE, 
    alphaLine = 1,
    scale = "center",
    title = "Wine features")+
  theme_minimal()+
  theme(plot.title = element_text(size = 10))

```

```{r}
#highlighting

variables <- c("country", "year", "variety", "price", "points")

p1 <- wine_ratings %>% 
  select(variables) %>% 
  mutate(above_avg = points >mean(points)) %>% 
  sample_n(30) %>% 
  ggparcoord(
    groupColumn = "above_avg",
    showPoints = TRUE, 
    alphaLine = 1,
    scale = "std")+
  scale_color_manual(values=c("#b8b8b8", "#780303"),
                     name = "above_avg\n(88.4)") +
  theme(plot.title = element_text(size = 10)) +
  theme_half_open(12) + 
  background_grid(minor = 'none')


n_wines <- wine_ratings %>% 
  group_by(country) %>% 
  summarise(n_wines = n()) %>% 
  arrange(desc(n_wines)) %>% 
  drop_na()


p2 <- wine_ratings %>% 
  filter(country %in% n_wines$country[1:10]) %>% 
  left_join(n_wines, by = "country") %>% 
  arrange(desc(n_wines)) %>% 
  mutate(country = reorder(as.factor(country), n_wines)) %>% 
  ggplot(aes(points, country)) +
  geom_density_ridges(alpha = .25) +
  geom_vline(xintercept = median(wine_ratings$points), 
             color = "#780303",
             lty = "dashed") +
  scale_y_discrete(expand = c(.01, 0)) +
  scale_x_continuous(expand = c(0.01,0)) +
  scale_fill_brewer(palette = 4) +
  theme_ridges() +
  labs(x = "points",
       y = NULL) +
  theme(legend.position = "none")+
  background_grid(minor = 'none')


plot_row <- plot_grid(p1, p2)


title <- ggdraw() + 
  draw_label("Features relating to Wine rating",
             fontface = 'bold',
             x = 0,
             hjust = 0) +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title, plot_row,
          ncol = 1,
          rel_heights = c(0.1, 1),
          rel_widths = c(1.5, 1))

ggsave("C:/Users/inkyscope/Documents/projectR/datavizRscope/figures/wine_rating_features.png")

```

```{r}
n_wines <- wine_ratings %>% 
  group_by(country) %>% 
  summarise(n_wines = n()) %>% 
  arrange(desc(n_wines)) %>% 
  drop_na()


wine_ratings %>% 
  filter(country %in% n_wines$country[1:10]) %>% 
  left_join(n_wines, by = "country") %>% 
  arrange(desc(n_wines)) %>% 
  mutate(country = reorder(as.factor(country), n_wines)) %>% 
  ggplot(aes(points, country))+
  geom_density_ridges(alpha = 0.6, 
                      fill = "#780303", 
                      scale = 1.5)+
  geom_vline(xintercept = median(wine_ratings$points), 
             lty = "dashed", 
             color = "#f9ebde", 
             size = .9)+
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_x_continuous(expand = c(0.01, 0)) +
  theme_ridges()+
  theme(legend.position = "none") +
  labs(x = "Points", 
       y = NULL,
       title = "Country by wine points",
       subtitle = "Austria, Australia and Germany shows points above average.") +
    theme_ridges() +
    theme(title = element_text(size = 11),
          axis.text.x = element_text(size = 7),
          plot.title = element_text(size = 14))
```

```{r}
wine_top_country <- wine_ratings %>% 
  group_by(country) %>% 
  summarize(n_wines = n()) %>% 
  drop_na() %>% 
  ggplot(aes(area = n_wines, 
             fill = n_wines, 
             label = country))+
  treemapify::geom_treemap()+
  geom_treemap_text(color = "white",
                    place = "center",
                    grow = TRUE)+
  scale_fill_gradient2(midpoint = 250000) 
```

```{r}
wine_top_rating_country <- wine_ratings %>%
  group_by(country) %>% 
  summarize(
    rating = mean(points, na.rm = TRUE),
    n= n()) %>% 
  filter(!is.na(country),
         n > 100) %>% 
  top_n(10)
```

```{r}
wine_top_rating_country  %>% 
  ggplot(aes(area = rating, 
             fill = rating, 
             label = country))+
  treemapify::geom_treemap()+
  geom_treemap_text(color = "white",
                    place = "center",
                    grow = TRUE)+
  scale_fill_gradient2(midpoint = 85)
```

```{r}
wine_ratings %>%
  group_by(variety) %>% 
  summarize(n_wines = n()) %>% 
  drop_na() %>% 
  top_n(10) %>% 
  ggplot(aes(area = n_wines, fill = n_wines, label = variety))+
  treemapify::geom_treemap()+
  geom_treemap_text(color = "white",
                    place = "center",
                    grow = TRUE)+
  scale_fill_distiller(palette = "Dark2")+
  labs(fill = "Number of wines",
       title = "Wine Variety Proportion") +
  theme(plot.title = element_text(size= 14, face = "bold"))
```

```{r}
library(tidytext)

wine_rating_words <- wine_ratings %>%
  mutate(wine_id = row_number()) %>%
  unnest_tokens(word, description) %>%
  anti_join(stop_words, by = "word") %>%
  filter(!word %in% c("wine", "drink"),
         str_detect(word, "[a-z]"))
```

```{r}
wine_rating_words %>% 
  count(word, sort = TRUE) %>% 
  head(20) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(word, n))+
  geom_col(fill = "#780303") +
  coord_flip()+
  theme_minimal_vgrid()
```

```{r}
library(widyr)

wine_words_count <- wine_rating_words %>% 
  pairwise_count(word, wine_id, sort = TRUE) %>% 
  filter(n > 5000)

wine_words_count
```

```{r}
wine_words_count %>% 
  filter(item1 == "aromas")

wine_words_count %>% 
  filter(item1 == "palate")
```

```{r}
library(ggraph)

set.seed(2019)

wine_words_count %>%
  filter(n > 500) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = n, edge_width = n),
                 edge_colour = "#780303") +
  geom_node_point(size = 3) +
  geom_node_text(aes(label = name), 
                 repel = TRUE, 
                 point.padding = unit(0.2, "lines")) +
  theme_void() +
  theme(legend.position = "none")
```

```{r}
# word correlations
wine_words_cors <- wine_rating_words %>% 
  group_by(word) %>% 
  filter(n() >= 1000) %>% 
  pairwise_cor(word, wine_id, sort = TRUE) 
```

```{r}
wine_words_cors %>% 
  filter(item1 == "bodied")
```

```{r}
wine_words_cors %>%
  filter(item1 %in% c("bodied", "firm", "silky", "dry")) %>%
  group_by(item1) %>%
  top_n(6) %>%
  ungroup() %>%
  mutate(item2 = reorder(item2, correlation)) %>%
  ggplot(aes(item2, correlation, fill = item1)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ item1, scales = "free") +
  coord_flip() +
  theme_minimal_vgrid() +
  theme(legend.position = "none")
```

```{r}
library(ggraph)
library(igraph)
```

```{r}
set.seed(2019)

wine_words_cors %>%
  filter(correlation > .3) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), 
                 show.legend = FALSE) +
  geom_node_point(color = "#780303", size = 3) +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void()
```
