---
title: "W24 African-American Achievements"
author: "Sung Inkyung"
date: '2020 6 10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(showtext)

font_add_google("Roboto")
font_add_google("Roboto Condensed")
showtext_opts(dpi = 320)
showtext_auto()
```


```{r}
firsts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/firsts.csv')

```


```{r}
firsts_decade <- firsts %>% 
  mutate(decade = year - year %% 10) %>% ## 1730 - 2010
  group_by(decade) %>% 
  arrange(category) %>% 
  mutate(index = row_number()) %>% 
  ungroup()

```


```{r}
col <-  c("#e3c81c", "#ddccbb", "#bbccdd", "#91aa8d", "#f15664", "#c3bc12", "#a991c3", "#3a453e")

bar_plot <- firsts_decade %>% 
  ggplot(aes(decade, 1, group = index, fill = category)) +
  geom_bar(stat = "identity",
           width = 8,
           color = "#1b1f2b",
           size = .7) +
  annotate("text",
           x = 1820, y= 63,
           label = "The First Achievements by African Americans",
           size = 11,
           color = "white",
           fontface = "bold",
           family = "Roboto") +
  annotate("text",
           x = 1743,
           y = 17,
           label = "1738 - First free African-American\ncommunity: Gracia Real de Santa Teresa de Mose\n(later named Fort Mose) in Florida", 
           color = "gray80",
           family = "Roboto Condensed",
           hjust = 0,
           size = 4.5,
           lineheight = 1.1) +
  annotate(geom = "curve",
           x = 1728,
           y = 1.5,
           xend = 1740,
           yend = 16.5,
           curvature = -.35,
           color = "gray80",
           arrow = arrow(length = unit(1, "mm"), type = "closed")) +
  annotate("text",
           x = 1872,
           y = 33,
           label = "1865 - First African-American attorney:\nJohn Stewart Rock admitted to\nthe bar of the U.S. Supreme Court", 
           color = "gray80",
           family = "Roboto Condensed",
           hjust = 0,
           size = 4.5,
           lineheight = 1.1) +
  annotate(geom = "curve",
           x = 1858,
           y = 19,
           xend = 1870,
           yend = 33,
           curvature = -.35,
           color = "gray80",
           arrow = arrow(length = unit(1, "mm"), type = "closed")) +
  scale_x_continuous(breaks = seq(1730, 2010, by = 10),
                     labels = paste0(seq(1730, 2010, by = 10), "s"),
                     expand = c(0, 1)) +
  scale_fill_manual(values = col,
                    guide =  guide_legend(nrow = 1,
                             direction = "horizontal")) +
  labs(x = "",
       y = "Number of Achievements",
       caption = "Source: Wikipedia & Wikipedia | Graphic: Sung Inkyung") +
  theme(legend.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 13, 
                                   color = "white",
                                   family = "Roboto Condensed"),
        legend.key.size = unit(.1, "cm"),
        legend.key.width = unit(0.5,"cm"),
        legend.position = c(0.325, 0.88),
        panel.background = element_rect(fill = "black", 
                                        color = NA),
        plot.background = element_rect(fill = "black",
                                       color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.caption = element_text(color = "gray65",
                                    family = "Roboto Condensed",
                                    size = 10),
        axis.text.x = element_text(color = "gray95",
                                   family = "Roboto Condensed",
                                   size = 13),
        axis.text.y = element_text(color = "gray95",
                                   family = "Roboto Condensed",
                                   size = 13),
        axis.title.y = element_text(color = "gray95",
                                    family = "Roboto",
                                    size = 12,
                                    margin = margin(r = 10)),
        axis.ticks = element_blank(),
        plot.margin = margin(10, 20, 15, 20))

ggsave("W24_African-AmeriacanAchievements.png", width = 47, height = 24, units = "cm")
  
```

